### ISSUE TITLE
[Bug] All Hotkeys not working anymore!, all broken!

### ISSUE THREAD

**Issue by ShadowMaster85** [darkreader/darkreader#6838] opened 2021-09-21 15:57 UTC
## Bug Description
All the Hotkeys are not working at all, i suspect this is caused by the latest version of Dark Reader since they worked normally until yesterday.

## Website Address
This problem happen on any website

## Steps To Reproduce
Try to use any of the Dark reader keyboard shortcuts

## Expected Behavior
The keyboard shortcuts working, as usual until yesterday

## Actual Behavior
After pressing any of the keyboard shortcut nothing happen

## System Information
- OS: Windows 10 64 bit, version 1709
- Browser: Firefox 92.0 64 bit
- Dark Reader Version: 4.9.35

**Comment by infinitewarp** [comment] 2021-09-21 16:42
This also just started affecting me today, and I'm using:

- OS: macOS 10.15.7
- Browser: Firefox 92.0 (64-bit)
- Dark Reader Version: 4.9.35

I've tried disabling/enabling/uninstalling/reinstalling the Dark Reader extension with no luck.

**Comment by infinitewarp** [comment] 2021-09-21 16:49
When I checked `about:debugging` I also found this warning from the Dark Reader extension. Not sure it it's relevant, but it's my only extension with a warning, and it says:

```
Reading manifest: Warning processing optional_permissions: Error processing optional_permissions.0: Value "contextMenus" must either: must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["browserSettings"], be one of ["topSites"], be one of ["tabs", "tabHide"], be one of ["management"], be one of ["downloads", "downloads.open"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
```

**Comment by Gusted** [comment] 2021-09-21 16:55
Duplicate of #6832

**Closed by Gusted** 2021-09-21 16:55 UTC
Labels: bug

**Comment by aimi617** [comment] 2021-09-22 00:51
The same situation is here, Dark Reader stopped reacting on the keyboard in FF browser of any version though it does work in Google Chrome.
