### ISSUE TITLE
[Bug] All the images gets "filtered" since the latest update

### ISSUE THREAD

**Issue by SixelAlexiS90** [darkreader/darkreader#8154] opened 2022-02-06 12:13 UTC
# Bug Report

All the images gets "filtered" since the latest update and it's awful to browse like this.
I'm on "dynamic" mode but I never changed that, it should be the default mode from what I know but yeah, everything worked fine yesterday but now when I browse on MANY sites all the images, video thumbnails, avatars or emote get filtered with my Dark Reader settings, which are supposed to work only for backgrounds.

Please, is there any way to fix this or roll back to previous update? This extension is very important for me so I could even use an old offline version if I have to.

Thank you very much for your work and for this fantastic extension <3

## Bug Description

The Dark Reader filters get applied on images, video thumbnails, avatars or emote too.

## Steps To Reproduce

- Go to https://www.amazon.com/, https://www.twitch.tv/, https://web.telegram.org/, https://multiplayer.it/, or many other sites out there (like https://github.com/ itself).
- Look at every image, video thumbnails, avatars or emote
- All of them will look filtered

## Expected Behavior

The images shouldn't be altered by Dark Reader filters.

## Actual Behavior

All the images are altered by Dark Reader filters.

## Screenshots

BEFORE

![1-Before](https://user-images.githubusercontent.com/63536218/152679544-5d606c6e-4017-4d83-aa88-5577b08e575d.PNG)

AFTER

![1-After](https://user-images.githubusercontent.com/63536218/152679543-bf3c5fde-ba33-4cc5-9e33-a98335d39395.PNG)

BEFORE (don't mind the firewall stuff at the center)

![2-Before](https://user-images.githubusercontent.com/63536218/152679548-16a5dbdb-f758-4c1a-a052-0d132c7ee84f.png)

AFTER

![2-After](https://user-images.githubusercontent.com/63536218/152679545-072a72b2-6a7d-4708-b04a-9d4c86000c49.png)

p.s. the attached images looks all filtered now on my browser due to the bug being present on GitHub too. The images have to be saved on PC to see them properly since even by opening them on a new them they will still be filtered (the "AFTER" images are double filtered in this case).

## System Information

- OS:  Windows 10 Pro
- Browser:  Chrome 97.0.4692.99
- Dark Reader Version:  4.9.44

**Comment by Gusted** [comment] 2022-02-06 12:15
Duplicate of #8145

**Closed by Gusted** 2022-02-06 12:15 UTC
Labels: bug
