### ISSUE TITLE
[Bug] site list does not work with urls with square brackets

### ISSUE THREAD

**Issue by peter-moran** [darkreader/darkreader#8165] opened 2022-02-07 15:57 UTC
# Bug Report

## Website Address
✅ https://example.com/test/foo.html
✅ https://example.com/test/(bar).html
❌ https://example.com/test/[foobar].html

## Bug Description
If I add `example.com/test/` to my "not inverted list", I expect all urls starting with that to be disabled. However, this does not work for URLs /w brackets in them, as shown with the URLs above.

## Steps To Reproduce
1. Open all 3 websites above
2. Add `example.com/test/` to your "not inverted list"

## Expected Behavior
Dark Reader should be disabled on all 3 pages.

## Actual Behavior
Dark Reader is not disabled on `https://example.com/test/[foobar].html`.

## System Information

- OS: macOS
- Browser: Chrome 98
- Dark Reader Version: 4.9.44

**Comment by Gusted** [comment] 2022-02-07 21:31
Duplicate of https://github.com/darkreader/darkreader/issues/2660

**Closed by Gusted** 2022-02-07 21:31 UTC
Labels: bug
