### ISSUE TITLE
[Feature Request] Toggle Icon also if current site is toggled

### ISSUE THREAD

**Issue by Primajin** [darkreader/darkreader#9647] opened 2022-08-22 12:50 UTC
# Feature Request

## Is this feature request related to a problem?

I am often not sure if `darkreader` is active for a given page or not.
It would be great if the icon would switch not only based on if the entire plugin is set active or not but also if the current site was toggled or not.

## Screenshots

Icon state when active and set to ON:
![Screenshot 2022-08-22 at 14 41 35](https://user-images.githubusercontent.com/1742115/185923808-90d50511-677a-42b1-928e-79f5bcd02271.png)

Icon when set to OFF:
![Screenshot 2022-08-22 at 14 41 21](https://user-images.githubusercontent.com/1742115/185923960-627e24f6-099d-4f1e-b2f7-bd09de3459ce.png)

Icon when set to ON _but_ site was exempted:
![Screenshot 2022-08-22 at 14 41 10](https://user-images.githubusercontent.com/1742115/185924045-480cf919-6926-4539-8b6b-7c4c91bc8129.png)

-------

Photoshop of how I'd like it to be:
![mockup](https://user-images.githubusercontent.com/1742115/185924783-2d8d1206-18dc-4e25-8fc3-2e264591a6b3.png)

So that you can see: `darkreader` is not active for the current site

## Additional Context

This way one can see directly if the current page was altered or not just by looking at the icon, without the need to extra click it and check if the page is amongst the exempted ones or not.

**Comment by Gusted** [comment] 2022-08-22 12:54
Duplicate of #1671

**Comment by Primajin** [comment] 2022-08-22 12:55
Ahh thanks I was looking for duplicates but didn't spot that one 👍🏻

**Closed by Gusted** 2022-08-22 12:55 UTC
Labels: enhancement

**Comment by Gusted** [comment] 2022-08-22 12:57
Github issues and searching duplicate is quite a PITA, don't worry about it. I only happen to know the duplicate as I tried to fix it myself a while ago.
