### ISSUE TITLE
[Bug] "Dark Reader is slowing down FireFox" on new.reddit.com

### ISSUE THREAD

**Issue by privacyguy123** [darkreader/darkreader#13588] opened 2024-12-05 12:13 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Title says it all - not sure what is causing this. For the record I have "detect dark theme" off and use Dark Readers theme for everything.

### Website Address

https://new.reddit.com

### Steps To Reproduce

1. Browse website
2. Browser freezes and reports above error

### Expected Behavior

No lag/error

### Actual Behavior

Lag/error - have to wait long or click "stop" to continue browsing.

### Screenshots

![image](https://github.com/user-attachments/assets/5c3cafe1-a402-4223-b240-feefc0de856f)

### Operating System

Windows 10

### Web Browser name and version

FireFox 133.0

### Dark Reader version

4.9.96

**Comment by 0x25CBFC4F** [comment] 2024-12-05 14:22
Same behavior.

Profiler: https://share.firefox.dev/4f63xGq

**Comment by alexanderby** [comment] 2024-12-05 15:15
It seems like Reddit moved their styles to adopted style sheets. The problem is Firefox doesn't provide direct access to adopted style sheets, so I had to implement a huge workaround some time ago. It seems like it is what causes a problem.

Until this is fixed, please disable Dark Reader for Reddit, or use dark theme detection, and activate Reddit's built-in dark theme.

**Comment by tvcat** [comment] 2024-12-05 23:38
I'm on the same version of operating system, Firefox and Dark Reader. I cannot reproduce this.

**Comment by vulns-are-features-too** [comment] 2024-12-06 02:59
I'm on Arch Linux using Mozilla Firefox 133.0 and am having this issue. Dark reader has been deactivated by "dark theme detected" but it still slows things down.

**Comment by codysjordan** [comment] 2024-12-06 03:56
> I'm on Arch Linux using Mozilla Firefox 133.0 with Dark Reader 4.9.96 and am having this issue. Dark reader has been deactivated by "dark theme detected" but it still slows things down.

Same as @vulns-are-features-too except I'm on W11

**Comment by Patrick-Poitras** [comment] 2024-12-06 09:19
OpenSUSE with 133. Same issue.

**Comment by Iey4iej3** [comment] 2024-12-06 11:42
I encounter the same issue both on Desktop (128.5.0-esr) and on Android (133.0.0).

**Comment by Hitu1197** [comment] 2024-12-07 03:56
As a workaround you might want to use filter mode on reddit. Works well on my android. The only weird thing is that the images are inverted too (in thumbnails or embeds only), idk if there is an option to disable that.

**Comment by alexanderby** [comment] 2024-12-09 14:52
Thank you for the additional information.

We are currently testing the fix for the issue and will release the patch soon.

**Comment by UreshiiPanda** [comment] 2024-12-09 17:11
same issue here. 
On MacOS 14.5, Firefox Developer Edition 134.0b2 (aarch64)

**Comment by mmBesar** [comment] 2024-12-09 23:43
Same problem!

**Comment by kimsey0** [comment] 2024-12-10 13:12
> The problem is Firefox doesn't provide direct access to adopted style sheets, so I had to implement a huge workaround some time ago.

https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets#browser_compatibility says Firefox has support since version 101. @alexanderby, was there something specific missing about the Firefox support or did you just implement the workaround before 101 was released in 2022?

**Comment by alexanderby** [comment] 2024-12-10 14:23
I meant, browser extensions have no direct access to these style sheets. Please be patient, as there was another big performance optimisation on the way, and they all should be tested thoroughly.

**Comment by kimsey0** [comment] 2024-12-10 17:12
Thanks. I was not trying to rush you, just seeking to understand the underlying technical limitations. Do Chrome extensions have a different access to adopted style sheets?

**Comment by alexanderby** [comment] 2024-12-10 17:23
Yes, Chrome extensions have such access. You can see more info about this Firefox bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1751346

The fix is under review. The last time it took 1 week.

**Comment by alexanderby** [comment] 2024-12-13 15:20
It took 3 days for an expedited review, please check out the version 4.9.97/

**Closed** 2024-12-13 15:20 UTC
Labels: bug
