### ISSUE TITLE
Apply dark mode only to a subdomain

### ISSUE THREAD

**Issue by MindSwipe** [darkreader/darkreader#8381] opened 2022-03-07 07:18 UTC
# Feature Request
I'd like to request that I can selectively apply Dark Reader to subdomains, for example apply to `meta.stackoverflow.com` while not applying to `stackoverflow.com`

## Is this feature request related to a problem?
Yes. StackOverflow has added an official dark mode and I prefer it over the dark mode of Dark Reader, but the dark mode is only available on stackoverflow.com while it's not available on meta.stackoverflow.com. Now the problem is that if I add `stackoverflow.com` to the Site List in Not Invert Listed mode then stackoverflow.com uses its own dark mode theme, great, but now if I navigate over to meta.stackoverflow.com my Retinas are seared like Tuna Steaks as it doesn't have a dark mode and Dark Reader does not apply its dark mode

**Comment by Gusted** [comment] 2022-03-07 21:41
Duplicate of #4508

**Closed by Gusted** 2022-03-07 21:41 UTC
Labels: enhancement
