### ISSUE TITLE
Wikipedia SVG Images don't invert

### ISSUE THREAD

**Issue by andre-fu** [darkreader/darkreader#1283] opened 2019-04-29 16:32 UTC
SVG images used in formulas etc on Wiki (or all SVGs? Haven't tested fully) don't invert properly

https://imgur.com/a/ijzDO7v

Earlier it did though, so I assume some prod push made this bug

**Comment by or-toledano** [comment] 2019-04-29 19:09
![dark_reader_bug](https://user-images.githubusercontent.com/49984106/56920127-f1ccd780-6ab1-11e9-8fe8-822b1910a2be.png)

Weird different behaviour for .svg, . .svg.png?? and .png (as shown in the screenshot, ordered up-bottom)
Taken from en.wikipedia.org/wiki/Commutative_diagram

**Comment by krupenja** [comment] 2019-05-04 21:36
This is a duplicate of https://github.com/darkreader/darkreader/issues/59

**Closed** 2020-03-19 21:28 UTC
