### ISSUE TITLE
Is there a practical way to globally disable Dark Reader except for some specific sites?

### ISSUE THREAD

**Issue by zetapulse** [darkreader/darkreader#2093] opened 2020-03-08 11:24 UTC
Clicking it OFF disables all the options in the box so I can't, say, click it ON "Only for this site".

**Comment by Gusted** [comment] 2020-03-08 15:22
Duplicate of #2017

**Comment by Xerus2000** [comment] 2020-04-09 10:16
Yep, exists: Site List > Invert listed only

**Comment by Gusted** [comment] 2020-04-17 21:51
#2017 and https://github.com/darkreader/darkreader/issues/2093#issuecomment-611449556

**Closed by Gusted** 2020-04-17 21:51 UTC
