### ISSUE TITLE
[Broken Website] g1.com.br (again)

### ISSUE THREAD

**Issue by sampaiodias** [darkreader/darkreader#7850] opened 2022-01-04 15:50 UTC
# Broken Website Report

## Website Address

Any news page within g1.globo.com
For example: https://g1.globo.com/mundo/noticia/2022/01/04/centenas-de-motoristas-ficam-presos-em-rodovia-nos-eua-apos-acidente-e-acumulo-de-neve.ghtml

## Steps To Reproduce

Go to g1.globo.com
Click on any news link.

## Expected Behavior

The news text should be readable

## Actual Behavior

The text is almost unreadable, aside from the title and links.

## Screenshots

![image](https://user-images.githubusercontent.com/14952766/148085363-a7550275-28ca-4712-b832-e07b516c3293.png)

## System Information

- OS: Windows
- Browser: Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
- Dark Reader Version: 4.9.43

## Additional Context

I think there was an attempt to fix this on issue #7511

**Comment by isaec** [comment] 2022-01-04 18:38
I can't reproduce this on chrome 96:
![image](https://user-images.githubusercontent.com/72410860/148107377-67b166b4-1708-448e-a0e1-9f2188dfb711.png)

**Comment by Gusted** [comment] 2022-01-04 18:47
It's fixed by #7631 which isn't in the latest version yet.
See https://github.com/darkreader/darkreader#site-fixes on how the get the fix early.

**Closed by Gusted** 2022-01-04 18:47 UTC
Labels: Broken Website
