### ISSUE TITLE
[Broken Website] Stripe Dashboard

### ISSUE THREAD

**Issue by unknowncoder05** [darkreader/darkreader#8996] opened 2022-06-02 14:05 UTC
# Broken Website Report

## Website Address
https://dashboard.stripe.com/dashboard

## Steps To Reproduce
- Create a basic test account in stripe
- Set Dark Reader on 

## Problematic Observation
The whole web browser will start to slow down and eventually crash (and in cases, even freeze my whole system)

## System Information

- OS: Linux/Ubuntu 22.04
- Browser: Brave V1.39.111
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment] 2022-06-04 18:05
Duplicate of #6799

**Closed by Gusted** 2022-06-04 18:05 UTC
Labels: Broken Website
