### ISSUE TITLE
ngrok.com: SVG font remain dark on a dark background

### ISSUE THREAD

**Issue by GauthierPLM** [darkreader/darkreader#1963] opened 2020-02-06 01:51 UTC
The SVG element on [ngrok.com](https://www.ngrok.com/) main page uses a dark background and a dark font, making the text unreadable.

I attached an image to illustate this.

I use Firefox Nightly and Dark Reader version 4.8.8 with default settings (Dynamique style and default font and color settings).

<img width="670" alt="Capture d’écran 2020-02-06 à 10 49 00 AM" src="https://user-images.githubusercontent.com/2579741/73898916-4b2e2680-48ce-11ea-85f5-8de37e9429e7.png">

**Comment by Myshor** [comment] 2020-02-08 19:06
Made some fixes which ends with:
![image](https://i.ibb.co/sK3Fj41/ngrok.png)

Fix is waiting for acceptance. ;)

**Comment by MariusCC** [comment] 2020-04-18 10:51
Wikipedia is using svg and many are rendered unreadable when maximized.
Looks like this in the page: 
![image](https://user-images.githubusercontent.com/1683264/79635727-5083d900-817b-11ea-8448-4cb51ca23dbf.png)
but unreadable when zoomed in:
![image](https://user-images.githubusercontent.com/1683264/79635762-75784c00-817b-11ea-9a11-5db1a6f66f26.png)

Maybe a good solution will be to render them as intended by the author - ie black text on white background - as trying to invert the colors in the image will lead to strange results.

**Comment by Myshor** [comment] 2020-04-18 11:07
First of all... Not nice to ressurect something that was already burried and fixed. 😄 
Second thing. As you show some examples in screen. Can you give exact URL? It will be easier to analyse what and how can be fixed. 😉

**Comment by MariusCC** [comment] 2020-04-18 12:48
Sorry - I saw the issue still open.
That's the page: 
`https://en.wikipedia.org/wiki/HIV`
and the image:
`https://en.wikipedia.org/wiki/HIV#/media/File:HI-virion-structure_en.svg`

I'm using Chromium Version 81.0.4044.92 (Official Build) Arch Linux (64-bit) if that makes a difference.

**Comment by Myshor** [comment] 2020-04-18 13:11
Will be fixed with #2321 ;)
You can check how the fix will look like - I shared screens after fixes in Pull Request.

**Comment by MariusCC** [comment] 2020-04-18 13:17
Tried your fix using the dev tools in the extension.
I think 0.40 for transparency is still not readable. 0.75  is much better even if probably at night will be a little discomfort.
`background-color: rgba(255, 255, 255, 0.75) !important;`

**Comment by MariusCC** [comment] 2020-04-18 13:49
Oh, and thanks a lot for the quick fix.

**Comment by Myshor** [comment] 2020-04-18 13:50
I'll check some more SVGs from wiki and maybe I will do that .75 until it's not merged yet. ;)

**Comment by Myshor** [comment] 2020-04-18 13:55
Ok... Your logic seems legit. I made change transparency to .75

**Comment by Gusted** [comment] 2020-04-18 14:07
Suggested a more globaly fix that will help a lot more in more cases probably as of classes with wikipedia that have a lot of sub domains isn't reliable
![](https://i.imgur.com/ONplVNy.png)
https://github.com/darkreader/darkreader/pull/2321#pullrequestreview-395916322

**Closed** 2020-04-20 18:02 UTC
