### ISSUE TITLE
[Bug] Works incorrectly on PDF files in Chrome

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6611] opened 2021-08-26 09:36 UTC
# Bug Report

## Steps To Reproduce

 - Install Dark Reader from `master`
 - Give it local file access permission, enable for PDF
 - Open local PDF

## Expected Behavior
Document is dark, as well as the background and UI around it.

## Actual Behavior
Document is dark, but UI around it looks inverted into lighter gray than normal.

## System Information

- OS: Windows 10
- Browser: Chrome 92
- Dark Reader Version: `master`

**Comment by Akhil132-dev** [comment] 2021-08-30 05:03
can please share screen shot with me so i can see that what a problem and i can work on it .

**Comment by Gusted** [comment] 2021-08-30 11:28
@bershanskiy I think we can close this issue as we've discussed it that it's working as intended.

**Closed** 2021-08-30 11:41 UTC
Labels: bug

**Comment by bershanskiy** [comment] 2021-08-30 11:44
> @bershanskiy I think we can close this issue as we've discussed it that it's working as intended.

Done!

@Akhil132-dev If you would like to contribute and just looking for something to work on, I recommend looking into any issue labeled ["help wanted"](https://github.com/darkreader/darkreader/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) or ["Broken Website"](https://github.com/darkreader/darkreader/issues?q=is%3Aissue+is%3Aopen+label%3A%22Broken+Website%22).

**Comment by luo-chuan** [comment] 2024-04-15 18:49
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
