### ISSUE TITLE
[Bug] Use System Color Scheme not following 

### ISSUE THREAD

**Issue by bagnaram** [darkreader/darkreader#10302] opened 2022-11-14 22:36 UTC
# Bug Report

## Website Address
N/A

## Bug Description
Setting the "Use System Color Scheme" does not follow the actuall system color scheme. It stays on light. 

## Steps To Reproduce
1. Select the "Use System Color Scheme"
2. Launch a website while the browser is in the darkmode setting `OS Theme 	Dracula / Adwaita` in the troubleshooting info page.

## Expected Behavior
Dark reader should follow the `layout.css.prefers-color-scheme.content-override` setting and synchronize based on the browser setting.

## Actual Behavior
Dark Reader remains in light mode unless I switch it to dark manually.

## System Information

- OS: Linux (Arch linux with Wayland)
- Browser:Firefox 106.0.5
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment] 2022-11-16 17:43
Hi @bagnaram,

1. Do you have `privacy.resistFingerprinting` enabled?
2. Could you please check the output of `matchMedia('(prefers-color-scheme: dark)').matches`(ctrl + shift + i -> Console tab)

**Comment by Gusted** [comment] 2022-11-20 13:05
> 2\. `matchMedia('(prefers-color-scheme: dark)').matches` equals `true` when I shift to a dark theme and changes back to `true` at a light theme.

Are you sure you worded this correct? As in both cases it stays `true`?

> but after launching new tabs it updates

Yeah browsers don't always notify Dark Reader and we do a check since a few versions on every new tab.

> Is there a way for the light/dark option to follow the systemwide dark setting rather?

That's possible,

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Go back to the popup.
- Go to Settings -> Automation.
- Change automation behavior setting.

**Comment by mherrmann3** [comment] 2022-12-06 09:22
Thanks @Gusted for pointing to the new interface, but also this suggestion doesn't work for me.

I observed that in Firefox, Dark Reader perfectly follows the Dark/Light Website appearance setting in _Settings > General_ (when switched manually), but not the OS theme (in my case of Windows).
Interestingly, manually switching the Dark/Light theme in _Add-ons and themes_ **does not** work properly and confuses Dark Reader: it either switches only for a brief moment properly (~0.5s; then, only the top bar and some sites are in proper dark mode; definitely not the `about:` pages), or it ends up in a loop where it flips between Light and Dark mode by itself (rarely) 😕. Perhaps there could be the culprit?

On Chromium Dark Reader switches according to OS theme as expected.

**Comment by freebrowser1** [comment] 2022-12-09 15:52
Same here.
Firefox 107.0 on macOS 13.0 (M1).

**Comment by bagnaram** [comment] 2023-01-11 19:41
I have revisited this issue after the suggestion to switch to the new interface and enable automation. Thank you @Gusted for that! I seem to still be seeing this issue on Firefox intermittently. I even set the schedule to timer instead of "follows system theme" and occasionally it will be stuck in dark during daytime or light. I think the commonality is waking from suspend during a day-night cycle but I need to capture a bit more evidence to be certain.

**Comment by bcutter** [comment] 2023-01-11 21:24
> I think the commonality is when the system waking from suspend during a day-night cycle but I need to capture a bit more evidence to be certain.

I tend to confirm this. Just from what I experience regularly - not sure how to technically prove it.

**Comment by tigerjack** [comment] 2023-01-17 16:26
For me the behavior is not completely consistent. On a fresh start, it follows the system theme, and the `matchMedia('(prefers-color-scheme: dark)').matches` is correctly `false` or `true` when the system theme is `light` or `dark` respectively. 
However, at some later point it decides to not toggle anymore, and the only way to have the correct theme is to restart the browser. Opening new tabs doesn't change the situation.

I'm on Linux, using Firefox 108, and I observe the same behaviour in all my profiles.

**Comment by AustinHarisch** [comment] 2023-01-23 23:40
I'm experiencing this issue on Windows 11. Strangely, the auto-switching only has trouble on Edge (manually toggling the extension works fine though). Chrome and Firefox both seem to switch just fine. (I'm running Version 109.0.1518.61 in case it helps.)

**Comment by 392781** [comment] 2023-03-06 03:16
I am experiencing this as well.  It started happening out of nowhere.  In fact, Dark Reader changed to dark mode (as was intended with my system theme change) but then a few hours later it automatically switched to light mode.

**Comment by benjamin051000** [comment] 2023-03-13 15:30
I'm experiencing this as well: 

Fedora 37 Wayland
Firefox 110.0 deb
Dark reader latest

I experience either the dark/light mode toggling several times a minute unexpectedly, or it generally doesn't consistently follow the system light/dark mode.

**Comment by bcutter** [comment] 2023-05-22 18:48
On Firefox 113.0.1 I still need to manually turn to
1) DarkReader icon
2) settings
3) automation
4) disable "use system color scheme"
5) reactivate "use system color scheme"

That's a "workaround" for closing and starting the browser. Very nice and quick. Not.

**Comment by bagnaram** [comment] 2024-04-02 13:47
https://github.com/darkreader/darkreader/commit/94760a5cfd9a1af71494ef888833941aa780c10a fixed it for me 👍🏼

**Comment by mherrmann3** [comment] 2024-04-02 15:18
For me, automatic switching works fine as well for some time. I don't remember since when and I'm not sure if it was fixed on Dark Reader's or Firefox' side. I guess this issue could be closed?

**Closed** 2024-04-02 16:25 UTC
Labels: bug
