### ISSUE TITLE
Some issue on baidu.com

### ISSUE THREAD

**Issue by qq994865664** [darkreader/darkreader#903] opened 2018-12-11 03:23 UTC
have a issue on www.baidu.com, hope to fix this bug. thanks.

**Comment by alexanderby** [comment] 2018-12-18 11:33
Duplicate of #898

**Comment by Gusted** [comment] 2020-04-15 16:08
Closed as it a duplicate and main issue has been fixed with https://github.com/darkreader/darkreader/commit/9b24e3d0c4e1d4eb1c7cf94c5a149fab3afb5aa4.

**Closed by Gusted** 2020-04-15 16:08 UTC
Labels: Dynamic Theme, bug, duplicate
