### ISSUE TITLE
[Broken Website] msn.com - Not Fully Darkened

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8380] opened 2022-03-06 15:48 UTC
# Broken Website Report

## Website Address
https://www.msn.com/tr-tr/spor/futbol/turkiye-super-lig

## Problem to Reproduce

There are white bars at top, you will see.

## Screenshots

Disabled
![Screenshot_184410_2022-03-06](https://user-images.githubusercontent.com/15933805/156930496-a76fa085-83cf-45d0-954b-7a8406128c84.png)

Enabled
![Screenshot_184357_2022-03-06](https://user-images.githubusercontent.com/15933805/156930504-fe5b9541-a16d-479a-a318-60f468ed7730.png)

## System Information

- OS: Windows 10
- Browser: Firefox 97.0.2
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment] 2022-03-07 21:39
Duplicate of #7953

**Closed by Gusted** 2022-03-07 21:39 UTC
Labels: Broken Website
