### ISSUE TITLE
[Idea] Link to mac OS dark mode

### ISSUE THREAD

**Issue by joshkaplan** [darkreader/darkreader#1113] opened 2019-02-18 01:52 UTC
This extension is a great compliment to the "dark mode" released in macOS Mojave. It would be awesome if we had the option to link the two together, such that toggling dark mode in macOS also toggles dark reader. 

Not sure if this is even possible with a chrome extension. [This](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) does not seem to work in chrome yet.

**Comment by alphachung** [comment] 2019-02-21 22:07
I think M74 supports macOS' dark mode in the UI Chrome, but not sure if extension can detect if Chrome is in dark mode or light mode.

**Comment by nelsonjchen** [comment] 2019-03-13 16:27
Duplicate of #745 ?

**Comment by Gusted** [comment] 2020-12-06 10:56
#745

**Closed by Gusted** 2020-12-06 10:56 UTC
