### ISSUE TITLE
[BUG] High CPU usage.

### ISSUE THREAD

**Issue by ACodingGenie** [darkreader/darkreader#3747] opened 2020-09-29 17:28 UTC
### **Describe the bug**
There are times when I'll be surfing around the web and my CPU usage for a particular tab will spike > 100 and stays there. There seems to be no way of bringing it down unless I close that particular tab. I have tried troubleshooting by deactivating different extensions so see if any of my other extensions (including Brave Shields) are interfering with Dark Reader and I can't figure it out. I disable Dark Reader and keep my other extensions running as usual and all is well. This happens on GiitHub a lot with me and other websites I don't remember of the top of my head. I have noticed "Socket-worker.js" sometimes has high CPU usage on Github so maybe that has something to do with this issue (?)
I am currently latest release version of Brave Browser, with Bitwarden, Dark Reader, DuckDuckGo Privacy Essentials, LocalCDN and Cookie AutoDelete actively running.

### **Steps to reproduce**
Not sure, just go to GitHub on Brave Browser with those extensions enabled and there are times when CPU usage will spike up to 100% and remain > 99% for that tab (See screenshot below).

### **Expected behavior**
No constant CPU spike / tab should behave normally.

### **Actual behavior**
CPU spikes to 100% and remains there unless that offending tab is closed. 

### **Screenshots**
![image](https://user-images.githubusercontent.com/68975831/94590472-b14c2d00-0254-11eb-9bd5-51b9097e9b24.png)

### **System Information:**
 - OS: Windows 10 1909
 - Browser: Brave Browser Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
 - Dark Reader version: 4.9.21

**Comment by Gusted** [comment] 2020-09-29 20:55
Hi @ACodingGenie!

Do you have any experiences with the dev tools of Chromium?
As I seems to not reproduce this issue.

Regards,
Gusted

**Comment by ACodingGenie** [comment] 2020-09-29 20:58
I don't sadly although I'll try my best to narrow it down to what's causing it.

**Comment by Gusted** [comment] 2020-09-29 21:01
Well,
I still hope you can follow these simple instructions it's rather to detect what's code is actually being actively called.

When having this 100% utilization.
Open chrome dev tools (ctrl + shift + i)
Go to the sources tab.
Press the F8. 
Make a screenshot.

**Comment by ACodingGenie** [comment] 2020-09-29 21:26
I was able to get a snapshot three different times when the CPU spikes however, the issue disappears when I either hit F8 or open devtools. The first time the result was different but after that it would always go the same place. The third screenshot shows a little more than the second. Here's what I have:
![image](https://user-images.githubusercontent.com/68975831/94618215-cc309880-0278-11eb-9a13-66a3f29b3012.png)
![image](https://user-images.githubusercontent.com/68975831/94618224-cfc41f80-0278-11eb-8241-bffca9a4f599.png)
![image](https://user-images.githubusercontent.com/68975831/94618229-d2267980-0278-11eb-8ed1-4915d772b4fa.png)

**Comment by Gusted** [comment] 2020-09-29 21:31
Hmm,
The first screenshot isn't ours, but looking at Bitwarden(which has a notficationBar.js) it seems to be running every second also normal behavior...
Does task manager shows any high CPU spikes. Also could you try to have a try with the `Performance tab` and profile for a few seconds when you have this 100% utilization.
The other 2 are normal loops from Dark Reader to check for changes in stylesheets.

**Comment by ACodingGenie** [comment] 2020-09-29 21:43
GitHub wouldn't let me upload the JSON so here's a screenshot instead:
![image](https://user-images.githubusercontent.com/68975831/94619549-1450ba80-027b-11eb-8194-651c929294cd.png)

![image](https://user-images.githubusercontent.com/68975831/94619689-4cf09400-027b-11eb-9b5e-ae5df25b8c40.png)

**Comment by Gusted** [comment] 2020-09-29 21:44
> GitHub wouldn't let me upload the JSON so here's a screenshot instead:

ZIP it

**Comment by ACodingGenie** [comment] 2020-09-29 21:45
[Profile-20200929T174205.zip](https://github.com/darkreader/darkreader/files/5302020/Profile-20200929T174205.zip)

**Comment by Gusted** [comment] 2020-09-29 21:52
It doesn't seems to have any weird quirks other than normal Dark reader code.
Do you experience also any slowdown when you have a high CPU usage?

**Comment by ACodingGenie** [comment] 2020-09-29 22:03
I haven't noticed any slowdowns, but I do hear the fans ramp up. Maybe because of the fact that the issue doesn't persist when I open up devtools. As soon I run the performance snapshot it stops and all you get is the normal stuff I guess. I'll try to do more troubleshooting whenever I can and also see what Windows Task Manager shows, currently I've been relying on the Chrome task manager.  Thanks

**Comment by ACodingGenie** [comment] 2020-09-29 22:23
I have my suspicions on LocalCDN because I was able to reproduce the issue several times in Brave's private tab with LocalCDN and Dark Reader while surfing around the issues on Brave's GitHub repo. Without LocalCDN having access to private tab, I can't reproduce it. 

![image](https://user-images.githubusercontent.com/68975831/94622186-bd011900-027f-11eb-8563-8d4b5583fa65.png)
![image](https://user-images.githubusercontent.com/68975831/94622220-c9857180-027f-11eb-99e7-c5d500a7ba51.png)

Doing F8 shows the following:
![image](https://user-images.githubusercontent.com/68975831/94622797-dbb3df80-0280-11eb-8569-8fcb844ec2d4.png)

**Comment by FireMasterK** [comment] 2020-10-02 13:38
I've noticed this on Brave, it seems to happen of after a few minutes from my experience, but I'm not sure what's causing this: Bitwarden or Dark Reader, this also happens when you watch youtube

**Comment by ACodingGenie** [comment] 2020-10-03 02:08
Good so I'm not crazy lol. I noticed it was happening on Vocareum's dashboard today while I was doing some AWS work and my computer became pretty laggy. The only way I could make it stop is closing the tab. Still haven't pin pointed the issue, if you notice anything please post it here. It's a very mysterious bug.

**Comment by Gusted** [comment] 2020-10-04 12:18
It seems to be same issue with #1222 as of the inline styles that's being used.

**Comment by zetok** [comment] 2020-10-04 19:26
> Do you experience also any slowdown when you have a high CPU usage?

For me (on Firefox 81) the huge CPU usage with Dynamic theme actually slows down page loading by a few seconds(!), while with other themes pages load pretty much instantly.

On FF however the CPU usage goes down once the page has been rendered(?).

**Comment by Gusted** [comment] 2020-10-04 19:31
> For me (on Firefox 81) the huge CPU usage with Dynamic theme actually slows down page loading by a few seconds(!), while with other themes pages load pretty much instantly.

Dynamic has to analyze the whole page and that can cause for some slow down on initial loading. After that Dark Reader will go `idle`(Just checking some things, but nothing heavy)

**Comment by FireMasterK** [comment] 2020-10-05 07:10
I just noticed this again, it looks this happens when the tab is unloaded, when I switched to the tab, the CPU usage became normal again

**Comment by Gusted** [comment] 2020-10-05 12:36
I've such sinking feeling it could be the inline styling causing this.
To confirm this, I've added a simple 'logger' to log inline styling.
[debug.zip](https://github.com/darkreader/darkreader/files/5327327/debug.zip)
If someone could side-load this.
And check the console tab when their is high CPU usage. To see how many inline styles where logged and if it still logs new inline styles.

**Comment by FireMasterK** [comment] 2020-10-05 12:37
Awesome, I'll do that 👍

**Comment by FireMasterK** [comment] 2020-10-05 14:29
Here are the logs after opening the tab just after it went to 100%, the CPU usage immediately dropped after doing so.
```
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
log.ts:9 CSSRule type not supported CSSKeyframesRule
logWarn @ log.ts:9
inline-style.ts:172 Array(2)
log.ts:5 Inverting dark image data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAUCAMAAACzvE1FAAAADFBMVEUzMzMzMzMzMzMzMzMKAG/3AAAAA3RSTlMAf4C/aSLHAAAAPElEQVR42q3NMQ4AIAgEQTn//2cLdRKppSGzBYwzVXvznNWs8C58CiussPJj8h6NwgorrKRdTvuV9v16Afn0AYFOB7aYAAAAAElFTkSuQmCC
log.ts:5 Inverting dark image data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAYAAACddGYaAAAAGUlEQVQI12M4Kyb2/6yY2H8GBgYGJgYkAABURgPz6Ks7wQAAAABJRU5ErkJggg==
log.ts:5 Inverting dark image data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjIiIGhlaWdodD0iMjIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTExIDBDNC45MjMgMCAwIDQuOTIyIDAgMTFjMCA0Ljg2OCAzLjE0OSA4Ljk3OSA3LjUyMSAxMC40MzYuNTUuMDk3Ljc1Ni0uMjMzLjc1Ni0uNTIyIDAtLjI2Mi0uMDEzLTEuMTI4LS4wMTMtMi4wNDktMi43NjQuNTA5LTMuNDc5LS42NzQtMy42OTktMS4yOTMtLjEyNC0uMzE2LS42Ni0xLjI5Mi0xLjEyOC0xLjU1My0uMzg0LS4yMDYtLjkzNS0uNzE1LS4wMTMtLjcyOS44NjYtLjAxNCAxLjQ4NS43OTggMS42OTEgMS4xMjguOTkgMS42NjMgMi41NzEgMS4xOTYgMy4yMDQuOTA3LjA5Ni0uNzE1LjM4NS0xLjE5Ni43MDEtMS40NzEtMi40NDgtLjI3NS01LjAwNS0xLjIyNC01LjAwNS01LjQzMiAwLTEuMTk2LjQyNi0yLjE4NiAxLjEyNy0yLjk1Ni0uMTEtLjI3NS0uNDk1LTEuNDAyLjExLTIuOTE1IDAgMCAuOTIyLS4yODggMy4wMjUgMS4xMjguODgtLjI0OCAxLjgxNS0uMzcyIDIuNzUtLjM3MnMxLjg3LjEyNCAyLjc1LjM3MmMyLjEwNC0xLjQzIDMuMDI2LTEuMTI4IDMuMDI2LTEuMTI4LjYwNSAxLjUxMy4yMiAyLjY0LjExIDIuOTE1LjcuNzcgMS4xMjcgMS43NDcgMS4xMjcgMi45NTYgMCA0LjIyMi0yLjU3MSA1LjE1Ny01LjAxOSA1LjQzMi4zOTkuMzQzLjc0MyAxLjAwNC43NDMgMi4wMzUgMCAxLjQ3MS0uMDE0IDIuNjU0LS4wMTQgMy4wMjUgMCAuMjg5LjIwNi42MzIuNzU2LjUyMkMxOC44NTEgMTkuOTggMjIgMTUuODU0IDIyIDExYzAtNi4wNzgtNC45MjMtMTEtMTEtMTF6IiBmaWxsPSIjMUIxRjIzIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz48L3N2Zz4=
2log.ts:5 Inverting dark image https://github.githubassets.com/images/modules/ajax/error.png
2log.ts:5 Inverting dark image https://github.githubassets.com/images/modules/ajax/error@2x.png
log.ts:5 Dimming light image https://github.githubassets.com/images/modules/pulls/progressive-disclosure-line@2x.png
log.ts:5 Inverting dark image https://github.githubassets.com/images/modules/jobs/logo.png
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/octoface-pattern.svg
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/chevron-up-pattern.svg
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/dot-fill-pattern.svg
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/dot-pattern.svg
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/heart-fill-pattern.svg
log.ts:5 Inverting dark image https://github.githubassets.com/static/images/icons/spotlight/plus-pattern.svg
2log.ts:5 Dimming light image https://github.githubassets.com/images/modules/commit/trans_bg.gif
```

**Comment by Gusted** [comment] 2020-10-05 14:35
> inline-style.ts:172 Array(2)

Hmm, not what I really expected...

[debug.zip](https://github.com/darkreader/darkreader/files/5328022/debug.zip)
This debug counts all inline-styles that's being styled by Dark Reader.

**Comment by FireMasterK** [comment] 2020-10-06 04:26
I was able to replicate this issue twice, here are the logs.
Log 1: https://paste.ubuntu.com/p/sVg4NNcMtF/
Log 2: https://paste.ubuntu.com/p/dJPBrdvFpZ/

**Comment by Gusted** [comment] 2020-10-06 16:16
That's definitely a higer Inline style usage than normal. By any chance you have a `auto-fill` setting enabled in BitWarden or something else different than Default settings.

**Comment by FireMasterK** [comment] 2020-10-06 16:19
Yes, I do, I have `Enable Auto-fill On Page Load` enabled, could that cause any issues?

**Comment by Gusted** [comment] 2020-10-06 16:20
> 
> 
> Yes, I do, I have `Enable Auto-fill On Page Load` enabled, could that cause any issues?

I think so, could you disable it for a while and check if you still can reproduce the issue.

**Comment by FireMasterK** [comment] 2020-10-06 16:21
Ok, I will do so 👍

**Comment by FireMasterK** [comment] 2020-10-07 04:32
I am still able to reproduce this with autofill disabled, this time I noticed something odd
![image](https://user-images.githubusercontent.com/20838718/95287643-0951e780-0884-11eb-955d-d993c3f27299.png)
System seems to be using a lot of CPU time, why could that be?

**Comment by ashish-yadav11** [comment] 2020-10-07 07:38
I am also encountering the same problem in brave and chromium. Due to the issue I switched to firefox. The issue never happens in firefox. Opening devtools in brave and chromium causes the cpu usage to go down to normal levels for me too.

**Comment by ACodingGenie** [comment] 2020-10-07 13:19
I appreciate you brothers and sisters working hard towards this issue because I haven't had time :( I don't use Bitwarden's Auto-fill feature, I basically use defaults and I've had the issue as well. Thanks.

**Comment by Gusted** [comment] 2020-10-07 13:35
I'm getting more and more confused....
As it's now also seems to be System(Chromium's native code) having a hard time, maybe `chrome://tracing/` can give us some better insight.

**Comment by ACodingGenie** [comment] 2020-10-07 14:16
Don't you just love being a developer loool? What do you need from chrome://tracking/? We got several different things here and for how long?

**Comment by ACodingGenie** [comment] 2020-10-07 14:28
That's not what I meant, I think you may have misunderstood me. First part was sarcasm because issues like this are frustrating and I was simply poking fun at the fact that code likes to be tricky and we essentially have to chase after it in a way to fix it. I apologize if I came across otherwise. Second, chrome://tracing offers several different options inside Brave as I am sure you already know, and I wanted to know which one to run and for what duration because there's a stop button. I am a complete noob at this so I seek your guidance please. 
Brave://tracing/ shows the following:
![image](https://user-images.githubusercontent.com/68975831/95344539-bf6b0080-0887-11eb-98f3-824d1d5d38d2.png)

**Comment by Gusted** [comment] 2020-10-07 14:34
Well, it's more to confirm my theories on inline-styling being the issue. But I think it's more appropriate to remove the possible causing code. So here it's a stripped down version of dark reader without the possible causing code.
[debug.zip](https://github.com/darkreader/darkreader/files/5341429/debug.zip)

**Comment by ACodingGenie** [comment] 2020-10-07 14:53
So here's what I did: 
- I unzipped the folder you gave me to a directory.
- I "side-loaded" that as my extension onto Brave using chrome://extensions and "developer mode"
- I disabled the current version of Dark Reader and restarted my browser.
- I reproduced the CPU usage with the following result:
![image](https://user-images.githubusercontent.com/68975831/95347670-25a55280-088b-11eb-8667-62687e653f96.png)
- I disabled all my extensions except for debug version of Dark Reader and restarted my browser.
- I was able to reproduce the issue again with the new result:
![image](https://user-images.githubusercontent.com/68975831/95347815-54232d80-088b-11eb-85ba-e35fffd59274.png)

**Comment by Gusted** [comment] 2020-10-07 14:55
> I disabled all my extensions except for debug version of Dark Reader and restarted my browser.

Wait, but this issue was about Bitwarden causing this issue alongside Dark Reader to be high CPU usage....

**Comment by ACodingGenie** [comment] 2020-10-07 14:56
I honestly don't even know anymore because it happens like you see above with no extensions enabled. This might just be a chromium source code bug like you suggested.

**Comment by Gusted** [comment] 2020-10-07 15:30
@alexanderby Could you have a look at this? Am I overseeing something as I'm running out of ideas...

**Comment by ACodingGenie** [comment] 2020-10-07 16:59
I think this is definitely an issue with the current version of chromium which is Chromium: 85.0.4183.121 and NOT something with DarkReader because I can't reproduce this issue using the above steps or whatever in Brave Beta which runs on Chromium 86.0.4240.68. I tried this with Darkreader (Debug) and from Chrome Web Store and they both behave as they should. Like you mentioned Dark Reader or that tab should idle once the dynamic theme is applied and that is exactly what I'm seeing here. No CPU spikes etc... I think it may be safe to assume that the next update of Brave which introduces Chromium 86 will fix this. and maybe likewise for Google Chrome. I am fine with you all closing this issue if others find results similar as me. Thanks folks and @Gusted !

**Comment by Gusted** [comment] 2020-10-07 17:05
> I think this is definitely an issue with the current version of chromium which is Chromium: 85.0.4183.121 and NOT something with DarkReader because I can't reproduce this issue using the above steps or whatever in Brave Beta which runs on Chromium 86.0.4240.68. 

My ungoogled chromium was still on v84 could explain the not reproducing behavior...

@FireMasterK Could you check and if v86 of Brave Beta resolves this issue? As than I can close this issue knowing it was a system bug, which may explain the high `System` utilization.

**Comment by FireMasterK** [comment] 2020-10-07 17:08
Sure, I will try to replicate it on nightly which runs on v86

**Comment by FireMasterK** [comment] 2020-10-07 17:25
Can confirm it no longer happens in nightly, It's safe to close this issue as it is not related to darkreader.

**Comment by ACodingGenie** [comment] 2020-10-07 17:28
SWEET. To anyone who might look back at this issue or whatever, just use Filter, Filter+ or Static until Chromium 86 comes around. Peace!

**Comment by Gusted** [comment] 2020-10-07 17:31
Great.

**Closed** 2020-10-07 17:30 UTC
Labels: bug
