### ISSUE TITLE
[Broken Website] youtube.com channel banners not visible

### ISSUE THREAD

**Issue by Fadexz** [darkreader/darkreader#7981] opened 2022-01-17 23:52 UTC
# Broken Website Report

## Website Address
https://www.youtube.com/channel/*
https://www.youtube.com/user/c

## Steps To Reproduce
Go to youtube.com
Select a channel
Look at the channel banner which should be missing in dynamic and static mode

## Problematic Observation
Channel banner image is removed from visibility on the page in dynamic and static mode

## Screenshots
https://i.imgur.com/iFd9oCE.png

## System Information
- OS: Windows 11
- Browser: Chrome 97.0.4692.71
- Dark Reader Version: 4.9.43

## Additional Context
Started to notice this happening a week or two ago I think, happens in a new window and profile as well

**Comment by Gusted** [comment] 2022-01-19 17:16
Duplicate of #7913 (Fixed in next version)

**Closed by Gusted** 2022-01-19 17:16 UTC
Labels: Broken Website
