### ISSUE TITLE
[Broken Website] Google links to "Dead Birds" in Vivaldi

### ISSUE THREAD

**Issue by dejunai** [darkreader/darkreader#13207] opened 2024-09-02 07:39 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

With "Dark Reader" as the only extension in Vivaldi... After a Google Search returns, left-clicking any returned link, results in Vivaldi's error page, known as a "Dead Bird". Center-clicking for "Open in New Tab" works fine. Also "Refining Search" (editing the returned search in the search bar) returns "Dead Birds" as well. Any attempt to link away from the returned search and remain in the same "Tab" results in "Dead Birds".

### Website Address

Google.com

### Steps To Reproduce

1. Make any search on Google. (in Browser "Vivaldi")
2. Click on any returned link.
3. Result is the Vivaldi Error Page known as "Dead Bird"
4. Refresh "Dead Bird" Error Page.
5. Google Search results reappear.

### Operating System

Windows 11

### Web Browser name and version

Vivaldi	6.9.3447.37 (Stable channel) (64-bit)

### Dark Reader version

4.9.89

### Additional Context

Error began after most recent Vivaldi update.

**Comment by YngveNPettersen** [comment] 2024-09-02 17:03
FYI, this is NOT an issue caused by Vivaldi, and it also affects Google Chrome 128.

The code (a CHECK fatal assert breakpoint) causing the renderer crash has been in Chromium since May (was probably introduced in Chrome 127).

There is a [Chromium bug report](https://issues.chromium.org/issues/363544341) related to this issue, filed Sep 1 (yesterday), with a description of what is causing the problem, both by Dark Reader, and what it triggers inside Chromium.

**Comment by YngveNPettersen** [comment] 2024-09-02 17:18
Further FYI, this is the same issue as https://github.com/darkreader/darkreader/issues/13197

**Comment by alexanderby** [comment] 2024-09-02 17:38
Duplicate of #13197.

We made a patch on Sunday, it's still being "reviewed".

**Closed by alexanderby** 2024-09-02 17:38 UTC
Labels: Broken Website
