### ISSUE TITLE
[BUG] Domains and Subdomains Behave Differently on Site List

### ISSUE THREAD

**Issue by Swivelgames** [darkreader/darkreader#3359] opened 2020-08-07 00:18 UTC
After further reading, this appears to be a bug, and not a Broken Website. I've updated the issue to reflect that.

**Dark Reader Version**: 4.9.16

### **Bug Description**

- In the case of toggling Dark Reader on a subdomain, the entry into the list is specific, i.e., only effecting `docs.gitlab.com`, and not `gitlab.com` or any other subdomains.
- In the case of toggling Dark Reader on a domain, the entry into the list is generic, i.e., it effects `gitlab.com`, **_as well as_** `docs.gitlab.com` and any other subdomain.

This behavior is inconsistent and seems more like a bug.

**Potential Bugfix**: Even adding a future that would allow you to manually input `//gitlab.com` to limit it to the domain (i.e., excluding sub-domains) would be a great way to compromise on this bug! :smile: 

A broader discussion on this started in [this comment below](#issuecomment-672573736).

------------------------------------------------------

### ORIGINAL POST

> **Website**
> https://docs.gitlab.com/ee/ci/quick_start/
> 
> **How to Reproduce**
> Steps to reproduce the behavior:
> An example of this is
> > 1. Go to Gitlab Docs website
> > 2. Attempt to activate Dark Reader
> 
> **Expected behavior**
> Dark Reader activates and Dark Reader generates a dark theme
> 
> **Actual behavior**
> docs.gitlab.com remains disabled
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/1456302/89595179-7bbd3180-d819-11ea-918c-e32ad0110bb5.png)
> 
> 
> 
> **System info:**
> - OS: All OS's (screenshot is from Arch; tried on macOS and Windows as well)
> - Browser: Attempted with both Chrome and Firefox

**Comment by rokastve** [comment] 2020-08-07 05:33
Could not reproduce, issues whatsoever for me. I'm on Chrome, Windows 10. Tried Firefox and it's also working
![image](https://user-images.githubusercontent.com/36890057/89612364-4b60ac00-d888-11ea-9899-4e964c98ab26.png)

**Comment by Gusted** [comment] 2020-08-07 11:54
1. What's your version of dark reader?
2. How does your sitelist look like?

**Comment by Simsimpicpic** [comment] 2020-08-08 17:53
I am using Darkreader on Firefox for Windows 10, and the site is white...

**Comment by Gusted** [comment] 2020-08-08 17:57
>     1. What's your version of dark reader?
> 
>     2. How does your sitelist look like?

@Simsimpicpic could you answer question 2?

**Comment by Simsimpicpic** [comment] 2020-08-08 18:29
Yep or course !
There some sites but no docs.gitlab.com :/

**Comment by Gusted** [comment] 2020-08-08 18:35
Anything related to gitlab.com?

Also what if you try a new fresh profile?

**Comment by Swivelgames** [comment] 2020-08-12 05:00
@Gusted Yes, I have `gitlab.com` on the list. However, `docs.gitlab.com != gitlab.com`.

Is there a way to exclude `gitlab.com`, while not affecting sub-domains?

`gitlab.com` provides a dark theme, and due to the nature of CI/CD jobs, Dark Reader can become a little intensive when jumping around a lot, so I try to use the built-in dark theme.

`docs.gitlab.com`, however, is a completely different website and does not offer a Dark Theme.

Specifying something like `//gitlab.com` has no effect, and `www.gitlab.com` does not work because it simply redirects to `gitlab.com`.

Having a way, even manually, to specify "explicitly no subdomain" would be super helpful, especially since toggling Dark Reader on `docs.gitlab.com` adds an entry with the specific subdomain.

- In the case of toggling Dark Reader on a subdomain, the entry into the list is specific, i.e., only effecting `docs.gitlab.com`, and not `gitlab.com` or any other subdomains.
- In the case of toggling Dark Reader on a domain, the entry into the list is generic, i.e., it effects `gitlab.com`, **_as well as_** `docs.gitlab.com` and any other subdomain.

This behavior is inconsistent and seems more like a bug. Even adding a future that would allow you to manually input `//gitlab.com` to limit it to the domain (i.e., excluding sub-domains) would be a great way to compromise on this bug! :)

**Comment by Gusted** [comment] 2020-08-12 11:12
> `docs.gitlab.com != gitlab.com`.

Well, it is. But check for #373 how it in the future will look like.

> Is there a way to exclude `gitlab.com`, while not affecting sub-domains?

Add this into your sitelist `^gitlab.com`

It's a bug/feature? It depends how you see it. If you need every subdomain controlled it's a feature. But a bug if you just need the main domain. I'm hoping my PR #2517 can be merged soon in order to get it more controllable and than make more logic to get it working for subdomains/domain not having conflicts.

**Comment by Swivelgames** [comment] 2020-09-02 04:00
@Gusted I wouldn't say that being able to control every subdomain is a bug, I would say that the syntax is inconsistent and therefore a bug. It's the inconsistency between using partials when a subdomain isn't specified, but treating entries as complete when a subdomain is specified.

I think we both agree that DarkReader would be awesome with the ability to be restrictive in both cases, though! And I can see how it may be open for interpretation.

As for adding `^gitlab.com` to my sitelist, it unfortunately didn't work. Doing so enabled DarkReader for both `gitlab.com` and `docs.gitlab.com`, suggesting that DarkReader didn't like the `^` caret very much, unfortunately.

**Comment by Gusted** [comment] 2020-09-02 06:59
> suggesting that DarkReader didn't like the `^` caret very much, unfortunately.

We have `^` and `$` implemented in the current URL logic. 
As seen un this code https://github.com/darkreader/darkreader/blob/master/src/utils/url.ts#L51

**Comment by HatScripts** [comment] 2020-10-29 11:21
So here's a prominent example of where I found this bug/feature to be the most frustrating:

If for whatever reason you disable `stackexchange.com`, then every one of the [~166 subdomains](https://stackexchange.com/sites?view=list#traffic) (e.g. `english.stackexchange.com`, `math.stackexchange.com`, `unix.stackexchange.com`) will also be disabled.

But not only disabled, also impossible to enable again the intuitive way of clicking the button:

![](https://user-images.githubusercontent.com/5691865/97561869-e48d0200-1a34-11eb-8da5-7357f4a87f77.gif)

**Comment by BoltonBailey** [comment] 2020-11-05 07:41
I am having the same problem as @HatScripts with `stackexchange.com` subdomains. I generally have dark reader on for stackexchange, but in some cases I want to use Option-Shift-A to toggle, but I can't due to my being on a subdomain where the superdomain interferes. The ideal functionality for me would be for the toggle button to only toggle the current domain and not affect subdomains, so that each of the subdomains can be toggled individually.

**Comment by Gusted** [comment] 2020-11-05 08:34
Hi @HatScripts and @BoltonBailey!

I almost forget to make a comment on this issue, but after @HatScripts comment I was turned and made a change to the existing PR(#2517) which if everything goes as plan should replace the current matching logic. The change was purely targeted to fix the subdomain problem matching more info at https://github.com/darkreader/darkreader/issues/373#issuecomment-720103647 and https://github.com/darkreader/darkreader/pull/2517#issuecomment-720103367

Regards,
Gusted

**Comment by Tealk** [comment] 2021-04-24 18:35
this is a very annoying problem, has anything happened to this yet?

**Comment by Gusted** [comment] 2021-04-24 19:26
> this is a very annoying problem, has anything happened to this yet?

Well, we have all waited for #2517 to be merged 😄

**Comment by tylerR94** [comment] 2022-07-06 05:17
I've encountered this issue for a very long time now. I did not realize it was a bug until reading [another post](https://github.com/darkreader/darkreader/issues/4520#issuecomment-826292683).

I'm on Chrome Windows 10. The issue was with app.hive.com. I must have disabled dark reader on hive.com at subpoint, and therefore it blocked it on their app subdomain.

**Comment by Matthew-Burkard** [comment] 2022-09-10 20:09
I've also encountered this issue for some time, also with `docs.gitlab.com`
Running Firefox on Linux.

**Comment by jaroslawjanas** [comment] 2022-09-16 22:58
I experience the same problem.
If there is a website `domain.com` that has `subdomain.domain.com`, the `domain.com` setting for **page specific on/off**, carries over to the `subdomain.domain.com`.

As such, there is no way to disable the **DarkReader** on `domain.com` but enable it on `subdomain.domain.com`.

**Comment by Francewhoa** [comment] 2023-02-04 23:20
This is to confirm this bug with Dark Reader V4.9.62. Using [Firefox](http://mozilla.org/firefox) V102.7 or [Ungoogle Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) V109.0.

For users facing this challenge, I published [this easy, quick, and temporary workaround](https://github.com/darkreader/darkreader/issues/1896#workaround).

For developers interested to contribute to resolving this bug, you might be interested in this:
* [Steps to reproduce](https://github.com/darkreader/darkreader/issues/1896#steps)
* Pull request at https://github.com/darkreader/darkreader/pull/2517

**Comment by alexanderby** [comment] 2024-04-02 13:33
Should be fixed now.

**Closed by alexanderby** 2024-04-02 13:33 UTC
