### ISSUE TITLE
Unable to view cursor within CodeBlocks addon in Google Doc.

### ISSUE THREAD

**Issue by tarrenj** [darkreader/darkreader#671] opened 2018-08-13 16:21 UTC
Not sure if this is within the scope of darkreader to fix or not. Please close this issue with `WontFix` if not.

https://chrome.google.com/webstore/detail/code-blocks/ebieibfdjgmmimpldgengceekpfefmfd?hl=en-US

Inside of a Code Blocks block with the zenburn theme, the cursor is not visible. This only happens when using Dark mode, and works as expected when using the Light mode.

**Comment by ShangxuanWu** [comment] 2019-11-11 22:41
Did you find any solution to this? Thanks!

**Comment by tarrenj** [comment] 2019-11-11 22:53
No I didn't.  Good luck!

**Comment by Gusted** [comment] 2020-07-24 21:37
can't reproduce should be fixed.

**Closed by Gusted** 2020-07-24 21:37 UTC
Labels: Dynamic Theme, bug
