### ISSUE TITLE
Site not dark (probably a bug?): archlinux packages

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#1339] opened 2019-05-22 19:32 UTC
Hello! If you visit this site: https://www.archlinux.org/packages/?q=plasma you can see the background white. But if you turn Dark Reader off and then on, the background goes dark. Is this a bug in dark reader?

Thank you very much.
Regards.

**Comment by SeriousHoax** [comment] 2019-05-24 15:06
Working fine on my Firefox.

**Comment by prodigeris** [comment] 2019-05-24 15:44
Same here.

**Comment by Aqa-Ib** [comment] 2019-05-24 17:57
Hmm it seems like sometimes it can show dark when you first open it. But if you reload the page or if you click on any of the packages links it goes white, at least on my setup.

**Comment by ardadem** [comment] 2019-05-24 20:27
Same

**Comment by linuunix** [comment] 2019-06-16 18:40
currently archlinux.org and DR don't play well, See #1224 #1313    
In my experience, the "problem" exists only on Firefox.

**Comment by ShalokShalom** [comment] 2019-09-09 19:40
This site is never dark for me (Firefox)

**Comment by inthreedee** [comment] 2019-09-18 16:21
Duplicate of #1224

**Comment by Gusted** [comment] 2020-07-28 14:27
Fixed.

**Closed by Gusted** 2020-07-28 14:27 UTC
