### ISSUE TITLE
Firefox White Flashes

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#512] opened 2018-05-17 02:16 UTC
With the actual model, Firefox emit bright flashes on some sites because the content of the site is displayed before Dark Reader styles are available. Examples:
https://www.google.com/
http://www.wordreference.com/es/en/translation.asp?spen=hola

Using an API like contentScripts.register instead would be more efficient and would make Dark Reader styles available before the content is first displayed, avoiding the bright flashes.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts/register

**Comment by Aqa-Ib** [comment] 2018-05-17 03:15
I don't know if in the current state of the API it will be possible to implement it into Dark Reader. I read that it currently has these problems, maybe we have to wait until they are fixed:

>    1.) `script.remove()` does not remove the CSS from loaded tabs. 
>        Patches are welcome: https://bugzilla.mozilla.org/show_bug.cgi?id=1423323 
>    2.) There is no way to specify the `cssOrigin`, so `@-moz-document` rules won't work (https://bugzilla.mozilla.org/show_bug.cgi?id=1035091). 
>        I see two possible solutions: 
>         * Request a `cssOrigin` property either on the `contentScriptOptions` or each entry in its `.css`. 
>         * Use the content scripts `.matches` option to include it only on the desired domains in the first place. 
>           This should again be faster than injecting it everywhere and then filtering through `@document` blocks, 
>           but `.matches` only supports match patterns. They can emulate `url()`, `domain()`, and `url-prefix()`, 
>           but not `regexp()` includes, which again leaves two options: 
>            * Use `.register({ matches: [ ..., ], })` where possible, and the current implementation for `regexp()`. 
>            * Request RegExps in `.matches`.

**Comment by Aqa-Ib** [comment] 2018-05-17 09:04
Stylus developer is trying to fix this too. Possibly this is useful information for Dark Reader too:

> So I've used contentScripts.register to get rid of the "racy" asynchronous messaging and provide the style CSS as a variable in our content script synchronously at document_start. The CSS was applied via style DOM elements like previously.
> 
> It didn't help. Only direct registration of literal CSS code helps, which means the problem is not the "racy" messaging like that Firefox dev said. The problem is that Firefox sometimes needlessly renders a completely empty page before or somewhere around document_start. Chrome did it in the past until they've fixed it recently.
> 
> I'm not sure what to do next, as I don't want to use direct registration of CSS due to its lack of stylesheet ordering, which is needed for our LivePreview of styles in the editor and dynamic toggling of styles. So far the only solution is to re-register all styles that have a higher id on each change of the style code. Yuck.

**Comment by Aqa-Ib** [comment] 2018-05-17 09:26
Stylus developer is trying to fix this issue. It could be useful for Dark Reader as well:
https://github.com/openstyles/stylus/issues/287

**Comment by Aqa-Ib** [comment] 2018-05-19 03:34
According to Stylus developer, "contentScripts.register can be used to 1) run JavaScript code with the style CSS that's added to the page as style DOM element 2) insert CSS directly." 

To avoid the bright flashes, he says that "only direct registration of literal CSS code helps".

**Comment by Aqa-Ib** [comment] 2018-05-19 04:40
Actually I am seeing this same bright flashes on Chrome too. In this browser they are much less common than in Firefox, but they happen too. I can see the unstyled page first, then it gets styled right after, giving the damned bright flash.

**Comment by Aqa-Ib** [comment] 2018-05-22 05:04
Actually, the "workaround" that I have to this problem is adding this code into userContent.css for those sites who give white flashes:
`@-moz-document domain("wordreference.com"), domain("google.com"), domain("google.es") {  * {background-color: #222  !important}   }`

**Comment by narcolepticinsomniac** [comment] 2019-01-16 23:59
Yeah, I get  that FF may has its own separate issues, but why is it ever late in Chromium? Seems like the lighter the page, the more consistently you can repro FOUC. Doesn't matter which mode.

Example: https://www.jeffersonscher.com/temp/Stylish211Fx/

**Comment by Aqa-Ib** [comment] 2019-05-22 19:08
In the current version of Firefox and Dark Reader (using ShadowFox as well), I don't have any white flashes anymore. This can be closed. 

Thanks!

**Comment by Aqa-Ib** [comment] 2019-05-22 19:20
@alexanderby what was the change that made Dark Reader to have its styles ready from the very beginning? I would like to let other developers know about this change to help the community! 

Thank you very much.

**Comment by Aqa-Ib** [comment] 2019-05-24 22:18
Well, it is not perfect yet. Most of the time the styles are ready from the very beginning, but sometimes not, giving a white flash on the same website. It is weird, so it is not totally solved, but it has improved A LOT.

**Comment by bfred-it** [comment] 2019-07-01 06:12
Is this issue a duplicate of #469?

**Comment by alexanderby** [comment] 2024-01-16 10:29
Duplicate of https://github.com/darkreader/darkreader/issues/469

**Closed by alexanderby** 2024-01-16 10:29 UTC
Labels: enhancement
