### ISSUE TITLE
Dark Mode Glitchy in GITHUB

### ISSUE THREAD

**Issue by Chidhambararajan** [darkreader/darkreader#2095] opened 2020-03-09 06:20 UTC
The plugin always worked perfectly , but recently it is been showing up some glitches in github

![Screenshot from 2020-03-09 11-48-46](https://user-images.githubusercontent.com/26043350/76187668-f6970780-61fb-11ea-9871-c8c5e239e3d8.png)

**Comment by Gusted** [comment] 2020-03-09 08:06
Cannot reproduce the issue Do you have any other extension that can cause this?
![](https://i.imgur.com/05xOzky.jpg)

**Comment by Gusted** [comment] 2020-03-14 07:56
Hello, I just found the problem and the solutions to this.Wwhen I was modifying dakreader and build it. Putted the build version into chrome, that exact thing happend. But when I putted the debug version into chrome It was all fixed.

**Comment by tmpm697** [comment] 2020-03-16 02:15
I've got this issue from the beginning when I use dark reader with my on-going add-ons. After some tests: disable/enable dark reader with one/some of add-ons.

Https everywhere and ghostery most caused glitchy issue. Other add-ons sometimes have this issue but not so often and acceptable for me. So two add-ons go away :)

**Comment by KOLANICH** [comment] 2020-03-19 06:01
After 4.9.2 update it got especially broken. I almost always see GH white. The most often broken pages are https://github.com/notifications/beta?query=is%3Aunread (the very farthest background is black, but everything else is of orig. colors), https://github.com/settings/profile (everything is of orig colors). Though after some reloads they finally got black.

**Comment by Chidhambararajan** [comment] 2020-04-15 05:28
I don't know why , but the color issue gets fixed by toggling between dark and light mode in the plugin repeatedly

I.e when the page loads ,the dark theme looks very bad with a lot of issues, but if I toggle light mode and again dark mode , everything becomes normal

**Comment by Chidhambararajan** [comment] 2020-04-15 06:06
Below is a gif demonstrating the issue I am facing with dark reader. I am using Chromium browser with the extenstions: Cookie AutoDelete , uBlocker , Dark Reader and BitWarden

In the below gif , you can see that the dark theme implementation in GitHub is glitchy upon loading, 
I tried turning off and on the dark reader extension , it didn't help, but toggling between dark and light mode in the extension surprisingly fixes the issue

![output](https://user-images.githubusercontent.com/26043350/79303224-fe894c00-7f0b-11ea-8469-ce32dbc894ca.gif)

Whenever there is a glitchy implementation of dark theme , in any website . I see the below error in the browser console

![Screenshot from 2020-04-15 11-34-36](https://user-images.githubusercontent.com/26043350/79303685-21683000-7f0d-11ea-8cf1-70a85e1987be.png)

Hope this helps!!

**Comment by Gusted** [comment] 2020-04-15 08:29
> Below is a gif demonstrating the issue I am facing with dark reader. I am using Chromium browser with the extenstions: Cookie AutoDelete , uBlocker , Dark Reader and BitWarden
> 
> In the below gif , you can see that the dark theme implementation in GitHub is glitchy upon loading,
> I tried turning off and on the dark reader extension , it didn't help, but toggling between dark and light mode in the extension surprisingly fixes the issue
> 
> ![output](https://user-images.githubusercontent.com/26043350/79303224-fe894c00-7f0b-11ea-8469-ce32dbc894ca.gif)
> 
> Whenever there is a glitchy implementation of dark theme , in any website . I see the below error in the browser console
> 
> ![Screenshot from 2020-04-15 11-34-36](https://user-images.githubusercontent.com/26043350/79303685-21683000-7f0d-11ea-8cf1-70a85e1987be.png)
> 
> Hope this helps!!

Thank you for giving an error message! That will gonna help a lot more in fixing this issue.

**Comment by Gusted** [comment] 2020-04-15 09:07
Hmm found the code that cause the error, just now need to reproduce it. Could you give your OS and Browser (version)

**Comment by Gusted** [comment] 2020-04-15 09:16
Faulty code: https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts#L138

**Comment by Chidhambararajan** [comment] 2020-04-15 10:25
My specs are : Chromium 79.0.3945.79 Built on Ubuntu , running on Ubuntu 19.04

**Comment by Chidhambararajan** [comment] 2020-04-15 10:38
I tired running Dark Reader extension in incognito with no other extension running , so that I could check its perfomance when no other extensions are present parallely . It worked !

i.e Dark Reader works well alone , but with other extensions such issues are showing up

I think you can reproduce the same issue with a Chromium browser and with the following extensions : Cookie AutoDelete , uBlocker , Dark Reader and BitWarden

**Comment by Chidhambararajan** [comment] 2020-04-15 10:42
Update : I tried removing uBlocker extension form my browser , After that the issue got fixed!!

Is ubloker blocking some code inserted by Dark Reader?

**Comment by Gusted** [comment] 2020-04-15 11:31
> Update : I tried removing uBlocker extension form my browser , After that the issue got fixed!!
> 
> Is ublocker blocking some code inserted by Dark Reader?

Hmm Ublocker will investigate. I think it's blocking some manager thing for malicious reasons(to prevent of course).. Switch to another adblocked like Ublock Origin or Privacy Badger or Ghostery.

**Comment by Gusted** [comment] 2020-04-15 12:04
Going to close this issue as the author's issue has been fixed and may be not or may be related to your issues @KOLANICH @tmpm697 If this issue still persist after

> I tried removing uBlocker extension form my browser , After that the issue got fixed!!

Than you're free to make a new issue with details about the issue!

Thank you for reporting this issue!

**Closed** 2020-04-15 12:04 UTC
