### ISSUE TITLE
[Broken Website] docs.microsoft.com switches to "High Contrast" theme even if excluded

### ISSUE THREAD

**Issue by RayKoopa** [darkreader/darkreader#3618] opened 2020-09-10 01:09 UTC
**Website**
https://docs.microsoft.com/en-us/

**How to Reproduce**
1. Go to the site above
2. Refresh once or twice
3. See that it switches to the "High contrast" scheme (which is also available at the bottom "Theme" menu) instead of keeping the "Dark" or "Light" theme.
4. Even if this domain is excluded, the High Contrast scheme is always picked after a refresh or immediately.

**Expected behavior**
The website should stick to the actually selected theme and not magically switch to "High contrast"

**Actual behavior**
The website always switches to "High contrast".

**Screenshots**
Note how the
- website is excluded
- website thinks "Dark" is selected
- obvious "High contrast" theme is active, however
![image](https://user-images.githubusercontent.com/9631152/92669665-7b312280-f312-11ea-9895-7cfd014e20fe.png)

**System info:**
 - OS: Windows 10 2004
 - Browser: edge-chromium 85.0.564.51
 - Darkreader Version: 4.9.16 - this started happening not more than a month ago.
 
**Additional context**
Of course, high contrast mode is _not_ enabled in my operating system, or this issue would be redundant.
I reset and reinstalled my browser, and tried in Incognito: But as soon as I install / enable Darkreader, docs.microsoft.com forces the High contrast scheme on me.

**Comment by Gusted** [comment] 2020-09-10 14:55
Directly connected to #3241 Same underlying issue

**Comment by ShadowJonathan** [comment] 2020-11-17 09:39
I have this same issue, even when turning off dark reader for the site, it switches to high contrast.

**Comment by kevin-he-01** [comment] 2021-08-06 03:30
Please reopen. Still happening in the latest version of DarkReader: 4.9.34, which means PR #4291 and [this commit with 4.9.34 tag](https://github.com/darkreader/darkreader/commit/1c1354dc31d5654c87783d940d83ab4189425a9d) do not seem to fix it

I reproduced it when I refreshed enough times. If docs.microsoft.com works fine the first time (regular dark theme), keep refreshing until it goes to high contrast, where afterwards it will not switch back unless I disable the DarkReader extension.

![image](https://user-images.githubusercontent.com/32375681/128451073-b3a80743-fb67-4520-883b-877cc6358e5f.png)

Very annoying to have to disable the extension _globally_ for Chrome just to fix the issue with this specific website.

**Comment by Gusted** [comment] 2021-08-06 11:16
Just use the theme setting on the footer to "reset" the behavior,

> Very annoying to have to disable the extension globally for Chrome just to fix the issue with this specific website.

You can disable specific sites in dark reader. Which you currently have according to your screenshot.

**Comment by kevin-he-01** [comment] 2021-08-06 16:52
> You can disable specific sites in dark reader. Which you currently have according to your screenshot.

@Gusted Please read the title of this issue (**emphasize mine**): "docs.microsoft.com switches to "High Contrast" theme **even if excluded**" There is currently no way in Chrome to disable an extension for a specific website. I have to rely on DarkReader honoring my setting and not tampering/modifying random stuff on the website which it doesn't.

**Comment by kevin-he-01** [comment] 2021-08-06 17:00
@alexanderby Reposting [my reopen request above](https://github.com/darkreader/darkreader/issues/3618#issuecomment-893974889). Sorry for the at mention but I don't have a way to ensure some collaborator get notification on this (closed issues tends to be unsubscribed). Otherwise I would have to [create an duplicate issue just to get this reopened](https://stackoverflow.com/a/63693335).

> Please reopen. Still happening in the latest version of DarkReader: 4.9.34, which means PR #4291 and [this commit with 4.9.34 tag](https://github.com/darkreader/darkreader/commit/1c1354dc31d5654c87783d940d83ab4189425a9d) do not seem to fix it
> 
> I reproduced it when I refreshed enough times. If docs.microsoft.com works fine the first time (regular dark theme), keep refreshing until it goes to high contrast, where afterwards it will not switch back unless I disable the DarkReader extension.
> 
> ![image](https://user-images.githubusercontent.com/32375681/128451073-b3a80743-fb67-4520-883b-877cc6358e5f.png)
> 
> Very annoying to have to disable the extension _globally_ for Chrome just to fix the issue with this specific website.

**Comment by Gusted** [comment] 2021-08-06 17:46
The title indeed implied that even if dark reader excluded the site it was set to high contrast. This behavior was caused by dark reader due to how variables worked at that time and some other factors which has by now fixed - I checked this again on a fresh new profile without any previous history and docs.microsoft.com works as intended and doesn't default to high-contrast even with darkreader enabled and when disabled. 




> I have to rely on DarkReader honoring my setting and not tampering/modifying random stuff on the website which it doesn't.

This sounds like you don't trust dark reader and things it will do stuff without any reason, I can ensure you that dark reader only does the bare minimum necessary to make a good experience. You can check the source code yourself if you'd like.


You don't have to ping alexander for this, I have the same rights to reopen issues and was quite frankly also the one to triage this issue and resolve it so you most likely want me to check the issue again and decide to reopen it. Like I said, I've checked it on different machines by now to ensure I wasn't crazy or just a flook and I was correct that dark reader doesn't let docs.microsoft.com default to high contrast anymore. 

Regards,
Gusted

**Comment by kevin-he-01** [comment] 2021-08-06 18:20
Sorry I didn't realize you are a collaborator. I will clear my cookies, reset DarkReader Dev Tools, and try again tonight: I set DarkReader to switch themes according to system dark modes and I turn on dark mode only at night. For docs.microsoft.com it has its own Dark/Light theme so I went with that instead of Dark Reader (I don't like applying 2 potentially conflicting layers of dark theme, it makes the site less visually appealing). I did it by disabling Dark Reader specifically for this site. The good thing is that docs.microsoft.com also syncs with my system theme.

However my setup seems to make the issue a lot more harder to reproduce. The issue does not appear when I set my system to light theme (where Dark Reader is disabled on all sites and sites themselves know to display light themes) now.

**Comment by kevin-he-01** [comment] 2021-08-08 03:58
@Gusted Unfortunately, this is still happening for me. I even tried creating a blank new profile in Chrome (so all Chrome and Dark Reader settings are default settings) and this bug still occurs.
![image](https://user-images.githubusercontent.com/32375681/128620011-55dbe997-e615-4a85-aea4-8e2c006787c7.png)
I know intermittent bugs are the hardest to reproduce, but I have a few tips (or maybe superstitions since I have no way of verifying whether they actually work) on when the bug is more likely to occur:

My "superstitious" steps to reproduce:
1. Turn on dark reader (using the "Toggle Extension" switch) when visiting docs.microsoft.com and then turn it off again. (seems superstitious, but trust me this is necessary)
2. Do around 10-20 refreshes on docs.microsoft.com
3. The bug will occur: site switches to high contrast mode
4. If you do more refreshes, the site might switch back to normal dark mode
4. Afterwards, the bug will **not** reproduce no matter how many refreshes is done (until you toggle the switch on and off again as in step 1, or possibly by other means I have not discovered yet.)

My system info in case that is important in reproducing the bug:
OS: `Microsoft Windows [Version 10.0.19042.1110]`
Chrome version: `Version 92.0.4515.131 (Official Build) (64-bit)`

**Comment by Gusted** [comment] 2021-08-08 14:54
I still can't reproduce the problem.

I'm around 200-250 refreshes by now. Had some other looks on another machine, but same result. It is not going into high contrast modem, It might help contacting microsoft of this problem. Because it's most likely in this point that they've some bugs in their high contrast system. As we cannot influence that behavior ourself.

**Comment by kevin-he-01** [comment] 2021-08-08 21:25
@Gusted Sorry for taking your precious time away, but I discovered an additional setting needed to reproduce this bug:
Your system must be in Dark Mode (not Light Mode) when you visit the website to reproduce the bug (on Windows 10, it is Settings -> Personalization -> Colors):
![image](https://user-images.githubusercontent.com/32375681/128645798-c97f02c4-d3dd-4939-ba5e-cd20cace8f26.png)
This way docs.microsoft.com will try to automatically set dark mode for its website without having you to manually scroll to the bottom and select. (websites can detect your system light/dark mode) For some reason this contributes to the bug being reproduceable. When the _system is in light mode_ (**even if the website is set to dark mode** using the setting at the bottom of the page), the bug **will not** reproduce. An example of a nonreproducing setup is here (notice the light Windows taskbar on the left):
![image](https://user-images.githubusercontent.com/32375681/128645980-78e1b554-1aa2-4462-b883-cc1a066080d6.png)

I recommend reproducing the bug with a blank profile in Chrome (or use the Guest profile) so all cookies etc. are cleared, after the system is set to dark mode

Same reproduction steps as in my previous post after _system_ theme is dark:

> 1. Turn on dark reader (using the "Toggle Extension" switch) when visiting docs.microsoft.com and then turn it off again. (seems superstitious, but trust me this is necessary)
> 2. Do around 10-20 refreshes on docs.microsoft.com
> 3. The bug will occur: site switches to high contrast mode
> 4. If you do more refreshes, the site might switch back to normal dark mode
> 5. Afterwards, the bug will **not** reproduce no matter how many refreshes is done (until you toggle the switch on and off again as in step 1, or possibly by other means I have not discovered yet.)

In case you still can't reproduce, can you give out your system configuration when trying to reproduce?
1. Are you using Windows, macOS, Linux, or other OS?
2. Are you using Chrome, or some other browser?
3. What are the versions Are you using the latest build of Dark Reader from the `master` branch or the Chrome Web Store version (4.9.34)?

**Comment by Gusted** [comment] 2021-08-08 21:42
The dark mode will be a bit weird because of Chromium and As well Firefox, both currently doesn't detect dark mode correctly on linux distro's. Firefox can be set to force them. But chromium doesn't. So thats already a point which might not be able to reproduce, but could explain a symptom.



1. Linux(Arch Linux)
2. Firefox Nightly, Chromium stable and nightly (also a test round with user-agent switched to edge as their current linux package sucks, but microsoft only does user-agent detection.).
3. First tried with v4.9.34 and later-on with master.

I think now you mention dark-mode, I might have a idea why this is happening.

**Comment by Gusted** [comment] 2021-08-08 21:50
Could you try to side-load 
[extensions.tar.gz](https://github.com/darkreader/darkreader/files/6951497/extensions.tar.gz)

**Comment by kevin-he-01** [comment] 2021-08-08 23:38
The site turned high contrast on my first load using the side-loaded extension.

**Comment by kevin-he-01** [comment] 2021-08-08 23:41
I wonder whether the side-loaded version is built directly from the master branch or has some custom experimental fixes.

**Comment by Gusted** [comment] 2021-08-09 08:58
> The site turned high contrast on my first visit to Microsoft Docs using the side-loaded extension.

That isn't a good sign 😄, let's try this one: 
[build.zip](https://github.com/darkreader/darkreader/files/6953144/build.zip)


These 2 are fresh from the master branch + a little experimental fix to enable/disable some features which might be able to let microsoft do this. This extension should disable most features I can think off that might be able to do this. As otherwise I really don't know why microsoft is doing it and just going to blame it on their detection.

**Comment by kevin-he-01** [comment] 2021-08-09 18:23
Nice. With your [build.zip](https://github.com/darkreader/darkreader/files/6953144/build.zip) side-loaded I can no longer reproduce the bug on my side using all the methods I know. So I would say this experimental fix is a success.

**Comment by Gusted** [comment] 2021-08-09 19:20
Okay thank you, I'd like to tell you a story. My dog came over to my keyboard, and for no reason it thought it was a dog treat and somehow typed out this piece of text:
```javascript
onDomLoad.then((function() {
    const newDivElement = window.createElement("div");
    newDivElement.style.cssText = "position:absolute;top:0;left:-2300px;background-color:#878787";
    newDivElement.textContent = "hc";
    window.body.appendChild(newDivElement);

    const computedBackgroundStyle = window.getComputedStyle(newDivElement).backgroundColor.toLowerCase();

    window.body.removeChild(newDivElement);
    if ("#878787" !== computedBackgroundStyle && "rgb(135, 135, 135)" !== computedBackgroundStyle) {
        window.documentElement.className += " os-high-contrast-enabled theme-high-contrast";
        isHighContrastEnabled = true;
    }
}));
```

Which seems awfully like the _possible_ code that microsoft is using to determining if a system is high contrast or not. And because of this code(which I assume is microsoft is using) dark reader is using a "fallback" style that overrides all element's (background)-color, and thus microsoft will assume that the system is high contrast. I will implement a fix to avoid this.

Regards,
Gusted

**Comment by kevin-he-01** [comment] 2021-08-09 21:35
Ah I see. Thanks for your time in debugging the issue. From the code it seems that Microsoft Docs is determining high contrast mode by getting the computed background style of a temporary `<div>` element. I suppose the unfixed version of Dark Reader will modify the style of that `<div>` and create a false positive high contrast detection. Tell me if I am missing something.

To be honest I just need to have this fixed when I exclude the website: if Microsoft is using ugly hacks like that, let that be and don't bother falling to its trap. So maybe a stretch goal is to make dark reader not modify style when a site is excluded. But anyways, I never developed browser extensions before so I don't know how hard that may be. This is just a suggestion to prevent  more websites breaking because of this.

**Comment by Gusted** [comment] 2021-08-09 21:46
>  I suppose the unfixed version of Dark Reader will modify the style of that `<div>` and create a false positive high contrast detection. Tell me if I am missing something.

Correct!



> So maybe a stretch goal is to make dark reader not modify style when a site is excluded

We're still looking into that, as this style is no matter what always injected to prevent white flashes as soon as possible(as any code to check if the site is excluded or not is too slow). Anyway, #6456 should be sufficient for now for microsoft.

**Closed** 2021-08-09 23:26 UTC

**Comment by awshelley-beckman** [comment] 2021-10-05 14:14
This is still happening for me.

**Comment by kevin-he-01** [comment] 2021-10-05 21:59
@Gusted  Still happening for me as well. This need to be re-opened. Apparently the Microsoft dev dogs changed their code again!

**Comment by kevin-he-01** [comment] 2021-10-07 04:22
It seems to be much less frequent than before. But I am able to reproduce it if I follow the exact same steps as [my comment above](https://github.com/darkreader/darkreader/issues/3618#issuecomment-894857887). Most notably, you need to be in system dark mode in the first place. Also do more refreshes since not every refresh trigger the bug (it seems to be some race condition here, could be caused by new Chrome version and its "priority" in loading extensions and main website I suppose, though I have no proof for that).

My Chrome version: 94.0.4606.61
Windows version: 10.0.19042.1237

Also hopefully this bug does not depend on the display driver (will see if I try run Chrome without hardware acceleration but that's gonna be very hard for complex software like Chrome). Everyone's graphic drivers are pretty different so reproducing it would be hard this way. My driver is "AMD Radeon (TM) Graphics" with version 27.20.14021.2001

**Comment by jeremyVignelles** [comment] 2021-10-07 05:11
I'll tell you if it happens again, but I'm pretty sure I had the bug once or twice after this has been marked as fixed. Not sure which browser and didn't had time to report a proper bug, so I didn't want to reopen.

my config is intel+nvidia, so that doesn't seem to be related to the driver.

**Comment by Gusted** [comment] 2021-10-18 08:32
> and used the "previous" button of my browser (chrome here).
> Now, other clicks on links give me a 80% chance of being broken :

Thanks, that seems to be reproduce-able. See #7124

**Comment by Decimation** [comment] 2021-12-06 11:03
This is still happening for me, even on version `4.9.42`.

**Comment by TheWarHam** [comment] 2021-12-22 17:12
Still happens to me on version `4.9.43`.

**Comment by Merlin2001** [comment] 2024-01-25 15:13
Still happens on version `4.9.76`

**Comment by Decimation** [comment] 2024-01-25 23:33
I stopped using Dark Reader after `4.9.42`, when I made [this comment](https://github.com/darkreader/darkreader/issues/3618#issuecomment-986668298). 

I'm amazed to see this issue is still present 2 years later on `4.9.76`.
