### ISSUE TITLE
Dynamic issues dev.to

### ISSUE THREAD

**Issue by narcolepticinsomniac** [darkreader/darkreader#1048] opened 2019-01-26 03:20 UTC
Chromium 

[Example](https://dev.to/awwsmm/101-bash-commands-and-tips-for-beginners-to-experts-30je)

Style loads all kinds of funky before the majority seems to be removed, leaving light text on light backgrounds and randomly applied styling everywhere.

**Comment by SoptikHa2** [comment] 2019-01-28 20:06
Firefox 64.0, can confirm the same issue (Dark Reader v 4.7.5).

**Comment by alexanderby** [comment] 2019-02-01 13:43
Duplicate of #956.

**Closed by alexanderby** 2019-02-01 13:43 UTC
