### ISSUE TITLE
[Broken Website] HP.com seems to be broken

### ISSUE THREAD

**Issue by osfanbuff63** [darkreader/darkreader#8533] opened 2022-03-27 22:03 UTC
# Broken Website Report

## Website Address
[hp.com](https://www.hp.com)

## Steps To Reproduce
- Open any page on hp.com

## Problematic Observation
The primary portion is only partially affected by Dark Reader, as the text is white and the background is also white.

## Screenshots
![Screenshot 2022-03-27 180103](https://user-images.githubusercontent.com/91388253/160302797-8db2700c-bb32-4d61-b85f-5cb2ed078677.png)

## System Information

- OS: Windows 10
- Browser: Chrome 99
- Dark Reader Version: 4.9.47

## Additional Context
Opened an email from HP and this extension did not work correctly. I use this extension so much, it's an absolute life-saver for my eyes!

**Comment by q1800** [comment] 2022-03-27 22:26
Duplicate of #8491.

Issue has already been resolved with #8496.

**Closed** 2022-03-27 22:27 UTC
Labels: Broken Website
