### ISSUE TITLE
Rules created with the developer tool are not properly reapplied.

### ISSUE THREAD

**Issue by milochristiansen** [darkreader/darkreader#143] opened 2017-12-06 14:48 UTC
I have created a few custom rules via the developer tool, but they are only applied to the site when you open the tool and click "apply". Refreshing the page works, but navigating to a new page on the same site does not apply the custom rules until you open the editor and click apply again.

It seems anything entered in the developer tool only affects the page that was open when "apply" was clicked.

(By "rules" I mean "invert" and "noinvert" entries, as well as "rules" entries.)

Note: Sometimes, very rarely, it works. I have no idea what causes it to work or not work at a particular time. Furthermore, if you go back to a page you visited before (via a link, not the browser back button) it often works fine on that page (well, maybe not *often*, but more often than it does normally it seems).

**Comment by fwpowell** [comment] 2017-12-15 00:15
I can confirm this behavior on Chrome 64.0.3282.24 (Linux) / Chrome 63.0.3239.84 (Windows).
When you create the rules using the developer tool, initially, they're applied and function for a period of time. After a number of automatic refreshes (or duration), the rules are seemingly 'forgotten' and require opening the developer tool and clicking 'Apply'.

To recreate this you can use the Observium demo site: demo.observium.org (U: demo / P: demo) as an example (set the refresh period to ~1 min, top right drop-down menu).

Same as @milochristiansen, I have little idea as to what's causing this. Doesn't seem to be very common either as I've been looking for around a month and this is the first other mention I've seen. 

Truly an amazing extension, the absolute best I've tried in the category - thank you for all the effort that went into it.
Please let me know if there's any additional info I can provide

**Comment by alexanderby** [comment] 2017-12-15 13:29
Every 15 minutes the config is loaded from GitHub and overrides your editor values. Currently I'm doing UI refactoring, editor will be placed into separate page, then I will think about merging GitHub config values with user's values. Currently you can submit a PR for GitHub config.

**Comment by jordancrane** [comment] 2017-12-15 18:55
The ability to merge GitHub and user config would be useful in some cases. My specific example is that I have some work-specific internal sites that I have fixed with the developer tool, but since they are internal sites it would be useless for everyone else to have them in their configuration files as well. It's not a huge annoyance to just press the "apply" button again when I visit the sites in question, but it would be a nice feature to have local configuration changes persist.

**Comment by Mav3r1x** [comment] 2017-12-19 11:17
Glad to know that you're already working on this issue. Maybe create a section called " local rules" in the developer tools, completely different from the inversion json file that is pulled from github.

**Comment by Gusted** [comment] 2020-05-29 22:57
@milochristiansen check with latest darkreader version.

**Closed** 2020-06-01 20:14 UTC
Labels: bug
