### ISSUE TITLE
LaTeX content in Wikipedia cannot be handled correctly.

### ISSUE THREAD

**Issue by Frederisk** [darkreader/darkreader#1567] opened 2019-09-14 05:47 UTC
The image after LaTeX parsing is black. It should be converted to white in dark mode. But for now, there is no correct conversion, which makes the content seem to disappear.

![msedge_ursPhJRnZK](https://user-images.githubusercontent.com/29837738/64904003-8cdaec80-d6f5-11e9-963f-094fb8f278cc.png)
![msedge_vNIhv9pWqc](https://user-images.githubusercontent.com/29837738/64904007-b5fb7d00-d6f5-11e9-91a4-939200838d88.png)

**Comment by tabjy** [comment] 2019-09-23 16:32
Duplicate of #1273?

**Closed** 2020-04-20 09:55 UTC
