### ISSUE TITLE
[Feature Request] Memory for settings

### ISSUE THREAD

**Issue by Shadoweee77** [darkreader/darkreader#7637] opened 2021-12-14 08:15 UTC
# Feature Request
Make settings remember the automation setup - when You turn the DarkReader On/Off and set auto again it resets to the computer theme mode, which is annoying to set again to the hours I chose.

**Comment by Gusted** [comment] 2021-12-14 17:29
Duplicate of #3268

**Closed by Gusted** 2021-12-14 17:29 UTC
Labels: enhancement
