### ISSUE TITLE
[Bug] Broken website => stripe [dashboard]

### ISSUE THREAD

**Issue by MullerHub** [darkreader/darkreader#10290] opened 2022-11-11 20:44 UTC
# Bug Report

## Bug Description

After logging into the stripe site, when you get to the dashboard if the dark reader is activated it will break the site and freeze everything, everything related to the stripe is "hidden"

## Screenshots

![Captura de tela de 2022-11-11 17-38-05](https://user-images.githubusercontent.com/105472842/201427578-903603b9-5783-470b-a778-ac600b1b9166.png)

## System Information

- ### Tested on
- OS: Ubuntu 22.04
- OS: Manjaro (I don't remember the version)
- OS:  Windows 10 (version 21h2) <br><br/>
- Browser: Brave
- Browser: Chrome
- Dark Reader Version: 4.9.60

**Comment by MullerHub** [comment] 2022-11-11 20:47
DarkReader disabled

![Captura de tela de 2022-11-11 17-38-21](https://user-images.githubusercontent.com/105472842/201428385-91b50f53-aae4-46b0-8cbf-98ec5893a074.png)

**Comment by MullerHub** [comment] 2022-11-11 20:49
DarkReader activated

![Captura de tela de 2022-11-11 17-37-55](https://user-images.githubusercontent.com/105472842/201428618-79726bb9-5dd0-43be-a969-63670d05fe9f.png)

**Comment by Gusted** [comment] 2022-11-13 21:21
Duplicate of #6799

**Closed by Gusted** 2022-11-13 21:21 UTC
Labels: bug
