### ISSUE TITLE
[Feature Request] Custom HTML tag or equivalent to bypass darkreader

### ISSUE THREAD

**Issue by neverlink** [darkreader/darkreader#6693] opened 2021-09-04 17:26 UTC
# Feature Request
Something like `class="bypass-darkreader"` or equivalent to stop the extension from altering elements which are already dark or others which are simply supposed to be light.
## Is this feature request related to a problem?

Besides darkening minor or such elements which aren't brighter than needed, it's completely breaking one of the sites I'm working with.
## Screenshots

With a background colour of # 040305 (to be seamless with the logo), even after replacing it with an image of the same colour, it still gets turned into this grey which completely screws up everything. The colour is basically black anyway.
https://kill4love.rip
![](https://i.imgur.com/elRI4Or.png)

**Comment by neverlink** [comment] 2021-09-05 07:29
> I'm first not sure why need DR on that site as it already appears to be dark.
DR is not only breaking the design, but also making the background brighter than intended.

If the extension doesn't read any of the the HTML rendering my initial suggestion useless, surely it could at least not ignore the `!important` flag added to the background color which is literally black to the untrained eye.

**Comment by Gusted** [comment] 2021-09-05 10:09
> DR is not only breaking the design, but also making the background brighter than intended.

Well, Dark reader is simply making sure that all colors are within the new darker color-scheme. So yes it can happen that darker background colors will be brighter.



> If the extension doesn't read any of the the HTML rendering my initial suggestion useless

Well the extension heavily reads the CSS content, better said it iterates over all CSS that's being used on the HTML. 

>  surely it could at least not ignore the `!important` flag added to the background color which is literally black to the untrained eye.

Ignoring the `!important;` flag? That will be a bad bad bad idea. 

Dark reader doesn't really care(to a certain degree) if the original color is already dark, it will adjust the color to the user-set background-color so it will all appear within the new color-scheme.

**Comment by neverlink** [comment] 2021-09-05 11:30
> Ignoring the `!important;` flag? That will be a bad bad bad idea.

That's exactly what I'm saying, DR does not care at all if I have `!important;` in my CSS.

If you're going to replace every single colour regardless of its brightness, let us opt out, be it with an `!important;` flag or an arbitrary class in the HTML which tells DR not to override the element's appearance. Really anything that stops the extension from altering my site when unwaneted. That's my request.

**Comment by Gusted** [comment] 2021-09-05 11:34
Going to mark it as duplicate of #4325

**Closed** 2021-09-05 11:37 UTC
Labels: enhancement
