### ISSUE TITLE
[Feature Request] A default list of domain -> recommended engine mappings

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#4049] opened 2020-11-05 19:40 UTC
**Is your feature request related to a problem? Please describe.**

Some engines work better for certain websites. With numerous websites on the Internet, and four different choices for dark mode engine (or even light mode as a fallback). If the user tries to enable dark mode across the board, with any of the four available engines, than many websites are either aesthetically displeasing, or break functionality, or have very low contrast for important UI elements.

**Describe the solution you'd like**

It would be helpful for the default configuration to apply a mapping of domain regex -> preferred engine. This way, more and more websites will look and function well, with reasonable levels of contrast, out of the box.

Another option would be for more effort put into fixing the engines so that all FOUR work very well with every website online. However, a simple "preferred engine" map would be a much faster stopgap while waiting for low-level engine enhancements to develop.

Overall, this list operates similarly to AdBlock Plus' allowlist.

The keys to this map could be URL regular expressions. Where AdBlock Plus might use a boolean for the map values, DarkReader would have a selection of (Filter, Filter+, Static, Dynamic, or Off) for the map values.

**Comment by Gusted** [comment] 2020-11-05 22:23
> Some engines work better for certain websites. 

Agreed. 

 >  than many websites are either aesthetically displeasing

Oh...

> or break functionality,

That's a bug report worthy and shouldn't be happening at all.

>  or have very low contrast for important UI elements.

That's a broken website worthy and should be fixed by CSS.

> This way, more and more websites will look and function well, with reasonable levels of contrast, out of the box.

No, this doesn't solve the problem you're describing. The problem is that websites don't look good or don't work, therefore just have some list in place to override the engine to some other engine will avoid the problem and don't get the actual problem fixed.

> Another option would be for more effort put into fixing the engines so that all FOUR work very well with every website online. 

We take a lot of time of polishing the engines and dedicate a lot of time to it. I don't agree with you on this. 

> However, a simple "preferred engine" map would be a much faster stopgap while waiting for low-level engine enhancements to develop.

It won't work as if you first have some proffered engine map. It will be released with the next release, in that same time the fix can be made and be merged into the source code which will be released that same release.

I don't think some weird list should be put in place to simply override the user's preferred engine, because something breaks or doesn't work. The problem should be fixed inside dark reader code and have a better effect overall.

Regards,
Gusted

**Closed** 2020-11-08 10:39 UTC
Labels: enhancement
