### ISSUE TITLE
[Bug] Theme editor forgets custom rules on browser restart

### ISSUE THREAD

**Issue by aledmb** [darkreader/darkreader#7277] opened 2021-11-06 10:54 UTC
# Bug Report

## Bug Description
I have the following rules for trello.com, and they are getting wiped out every time i restart the browser (they're gone from the theme editor).

================================

trello.com

CSS
._2w6KZMbwKqxZVN._3TTqkG5muwOzqZ.ZOUktZwsING7-0, .board-header-btn.mod-board-name, .board-header-btn.js-star-board, .js-board-header-btn-org-wrapper, .board-header-btns.mod-left { display: none !important; }
.board-canvas { background-color: #111 !important; }
#board { background-color: #111 !important; }
#board.collapsed-workspace-nav { padding-left: 0 !important; }
nav[data-test-id=workspace-navigation-nav] { display: none !important; }
#header { background-color: #111 !important; }
#header > div:first-child > div:first-child { display: none !important; }
.board-header { background-color: #111 !important; }
.list-wrapper { width: 310px !important; }
.list-card-details { width: 280px !important; background-color: #181818 !important; }
.list-wrapper.mod-add { display: none !important; }
.list { background-color: #222 !important; }
.list-card { background-color: black !important; }
.card-detail-window { background-color: #222 !important; }
.card-detail-window .card-label.card-label-yellow .label-text { color: #222 !important; }
.card-detail-window .card-label.card-label-red .label-text { color: #222 !important; }
.card-detail-window .card-label.card-label-green .label-text { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-yellow { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-red { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-green { color: #222 !important; }
.js-new-checklist-item-button { border: 2px solid #555 !important; }
::-webkit-scrollbar { display: none !important; }
.js-butler-card-buttons, .js-plugin-buttons, .card-back-card-back-upgrade-prompt-section, .js-cf-disabled.disabled, .js-change-card-members, .js-date-range-picker, .js-card-cover-chooser { display: none !important; }
.window-module hr, .js-copy-card, .js-subscribe, .js-convert-to-template, .js-more-menu, .new-comment.js-new-comment.mod-card-back, .card-detail-activity { display: none !important; }
.card-detail-item.card-detail-item-labels h3 { display: none !important; }
.window-header-inline-content.js-current-list p { color: #222 !important; margin-left: -38px !important; }
.window-header-inline-content.js-subscribed-indicator-header { display: none !important; }
.js-card-record-button, .js-card-templates-button { display: none !important; }
.checklist-item-due.js-checklist-item-due, .checklist-item-assignee.js-checklist-item-assignee { display: none !important; }
.checklist-progress { display: none !important; }
._3K09J3xqj8n-uQ._3TTqkG5muwOzqZ.ZOUktZwsING7-0 span:not(.icon-sm) { display: none !important; }
.board-header-btn.mod-show-menu span:not(.icon-sm) { display: none !important; }
.js-checklist-copy-source { display: none !important; }
label[for=js-checklist-copy-source] { display: none !important; }
._1c8QdR-OBBffEh { display: none !important; }
.board-header { display: none !important; }
.card-label.mod-card-front { height: 5px; min-width: 30px !important; max-width: 30px !important; border-radius: 1px !important; }
.list-wrapper:nth-child(6) .list-card-details { background-color: #282828 !important; }
.list-wrapper:nth-child(6) .list-card-details * { color: #888 !important; }
.list-wrapper:nth-child(6) .list-card-details .list-card-title { text-decoration: line-through !important; }
.list-wrapper:nth-child(6) .list-card-details .badge.js-checkitems-badge.is-complete { background-color: inherit !important; }
.card-label-red { background-color: #FF6347 !important; }
.card-label-yellow { background-color: #FFD700 !important; }
.card-label-green { background-color: rgb(87, 143, 54) !important; }
.quick-card-editor-buttons-item.js-edit-members { display: none !important; }
.quick-card-editor-buttons-item.js-edit-cover { display: none !important; }
.quick-card-editor-buttons-item.js-move-card { display: none !important; }
.quick-card-editor-buttons-item.js-edit-due-date { display: none !important; }
.quick-card-editor-buttons-item:first-child { display: none !important; }
.description-fake-text-area { background-color: #282828 !important; }
textarea.field.full.single-line.js-checkitem-input { background-color: #282828 !important; }
.nch-button.hide-on-edit.js-confirm-delete { background-color: #333 !important; color: #888 !important; }
.nch-button.js-new-checklist-item-button.mt-4.hide-on-edit { border: none !important; background-color: #333 !important; color: #888 !important; }

## Website Address
trello.com

## Steps To Reproduce
Input the custom rules above in theme editor and restart the browser.

## Expected Behavior
Rules stick between sessions.

## Actual Behavior
Rules are forgotten.

## System Information
- OS: Windows 10
- Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- Dark Reader Version: 4.9.40

**Comment by Gusted** [comment] 2021-11-06 14:58
Most likely due to #6429 @bershanskiy

**Comment by aledmb** [comment] 2021-11-06 15:07
Thanks. That's probably it.

Do you know if there's a way to revert to a previous version of the extension where this was working? Or is it related to a recent chrome update?

**Comment by Gusted** [comment] 2021-11-06 15:09
> Do you know if there's a way to revert to a previous version of the extension where this was working? Or is it related to a recent chrome update?

You can side-load(via chrome://extension + enable developer mode) the extension: https://github.com/darkreader/darkreader/releases/tag/v4.9.39

**Comment by xSeekTruthx** [comment] 2021-11-09 19:31
4.9.42 Same problem, everything erases. Backup setting is missing as well. Same on Opera browser too.

Google Chrome	94.0.4606.81 (Official Build) (64-bit)
Revision	5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS	Linux

**Comment by aledmb** [comment] 2021-11-12 05:17
@xSeekTruthx @gtpeter The solution provided by @Gusted works perfectly fine for now (using version 4.9.39).

**Comment by Elaborendum** [comment] 2021-11-12 05:26
Unless it's intended behaviour (is it? Maybe I misunderstood something) and not a bug, I don't think it's a good idea to close it so soon. Besides, using an outdated version might not hold up as a fix in the long term.

**Comment by xSeekTruthx** [comment] 2021-11-12 13:05
> @xSeekTruthx @gtpeter The solution provided by @Gusted works perfectly fine for now (using version 4.9.39).

A rollback is not a fix for this issue. I wouldn't close it either. @aledmb if you just don't want to receive notifications for this any more please remove your id from notifications, but please keep it open for others until this is actually fixed.

**Comment by aledmb** [comment] 2021-11-12 13:50
I closed it because this is not the issue itself. The real issue is being worked on in #6429.

**Comment by RhavoX** [comment] 2021-11-12 23:12
#6429 is merged already, they are not working on a solution right now

**Comment by Gusted** [comment] 2021-11-13 13:38
> Unless it's intended behaviour (is it? Maybe I misunderstood something) and not a bug

It could be, I've never recommended anyone to use the dev tools for CSS editing of some sort. It's quite bad, as situations like these could happens and poof all your CSS is gone. But it's a bug ;)




> they are not working on a solution right now

Well, then you know more than I do. The problem is kinda weird, because while I'm trying to figure out what's going wrong, the code that might be faulty does get executed but the devtools(from the browser) just simply refuses to "break" on them, so I can see step-for-step what is going on.

**Comment by Gusted** [comment] 2021-11-13 14:02
@alexanderby Given that people find this behavior not nice, should it be a hot-fix release?

**Closed** 2021-11-13 14:01 UTC
Labels: bug

**Comment by Overwatching** [comment] 2021-12-10 08:17
This bug still exists, and the flood of bug reports that are being closed because they "duplicate" this one is an issue on it's own.

If a bug exists, you don't close all the bug reports. You keep at least 1 core report.

Why? Because otherwise, people doing their good-faith searches for open bug reports describing their problem are going to see nothing. And then they are going to make another report. Which will then get closed because it is a "duplicate".

This thread needs to be reopened until the bug is actually solved, whether the bug is being worked on or not.

If a mod is tired of getting notifications on a legitimate thread, they can turn the notifications on that thread off. The solution is NOT to keep closing threads.

**Comment by Gusted** [comment] 2021-12-13 12:40
> This bug still exists

Yeah, I've noticed that(#7582) which only happens on Firefox(I only tested chromium for: #7359) as Firefox is harder to debug such issues and more or less just a pain in the ass.


> and the flood of bug reports that are being closed because they "duplicate" this one is an issue on it's own.

Well, if you don't disagree with the method or whatever you're trying to imply, as having only 1 issue to track the bug is better than having a multiple of issues which all has their own information, which is still the same bug. You can always read [this section of Code of Conduct](https://github.com/darkreader/darkreader/blob/master/CODE_OF_CONDUCT.md#enforcement) to report my behavior. 


> If a bug exists, you don't close all the bug reports. You keep at least 1 core report.

Well, that's this one. Yet it's closed as it's fixed in the master branch(not necessarily as in the current released version) which is how I deal with bug reports, I don't like to keep bug reports open when they are fixed. Switching to holding it open until the version released will add a burden to me, by keeping track of all fixed issues. As well as the possible confusion that a bug is open, when they are fixed, given that I see people doing time-to-time "Is this being worked on?" "When is this fixed" etc.

 

> If a mod is tired of getting notifications on a legitimate thread, they can turn the notifications on that thread off. The solution is NOT to keep closing threads.

Well, if someone is watching a particular issue they reasonably have this issue or have been impacted by it, they shouldn't feel like they have to unwatch the issue.
