### ISSUE TITLE
[Bug] My "not invert" list got wiped out for unknown reasons

### ISSUE THREAD

**Issue by SixelAlexiS90** [darkreader/darkreader#11931] opened 2023-11-22 10:06 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Yesterday everything was fine as always, today I've opened my browser and the "not invert" list was gone.
The other settings are still there, it seems that only the "not invert" list got completely wiped out.

### Website Address

N/A

### Steps To Reproduce

1. Open the browser
2. Finding out your "not invert" list is gone

### Expected Behavior

1. Open the browser
2. Not having your "not invert" list completely wiped out

### Actual Behavior

1. I've opened the browser
2. I've saw that my gmail had Dark Reader enabled even if it was supposed to be in the "not invert" list 
3. I've checked out the "not invert" list and it was empty

### Operating System

Windows 10 Pro 22H2 (19045.3693)

### Web Browser name and version

Chrome 119.0.6045.160 (Official build) (64 bit)

### Dark Reader version

4.9.69

**Comment by alexanderby** [comment] 2023-11-22 10:40
Hi, could you please go to [chrome://extensions](Extensions Page), enable Developer Mode and open the Dark Reader's background Console. Execute the following there
```js
chrome.storage.sync.get({schemeVersion: 0, siteList: [], siteListEnabled: [], enabledFor: [], disabledFor: []}, s => console.log(s));
```
Do you see your websites in the lists?

**Comment by alexanderby** [comment] 2023-11-22 10:52
I'm afraid I know the cause. Could you please run the following?
```js
chrome.storage.local.get(
    {
        schemeVersion: 0,
        syncSettings: false,
        siteList: [],
        siteListEnabled: [],
        enabledFor: [],
        disabledFor: [],
    },
    s => console.log(s),
);
```

**Comment by TheGreenkey** [comment] 2023-11-22 10:53
I have the same issue on my system. Executing the first code snippet returns all my previously enabled/disabled sites. The second one returns the new ones I've saved already.

**Comment by alexanderby** [comment] 2023-11-22 10:58
@TheGreenkey What do you get if you run
```chrome.storage.local.get(
    {
        schemeVersion: 0,
        syncSettings: true,
    },
    s => console.log(s),
);

**Comment by TheGreenkey** [comment] 2023-11-22 11:00
@alexanderby 

for `.local`:
```
{
    "schemeVersion": 0,
    "syncSettings": false
}
```

for `.sync`:
```
{
    "schemeVersion": 2,
    "syncSettings": false
}
```

**Comment by alexanderby** [comment] 2023-11-22 11:05
Oh no, seems like the synchronisation was disabled for you and the locally saved lists are wiped out. I will push a fix shortly, but your lists can't be restored unfortunately. There's only a way to enable synchronisation or copy the sites from a synced listed into a local list:
```js
chrome.storage.sync.get(
    {
        enabledFor: [],
        disabledFor: [],
    },
    sites => {
        chrome.storage.local.set(
            sites,
            () => chrome.runtime.reload(),
        );
    },
);
```

**Comment by TheGreenkey** [comment] 2023-11-22 11:32
That's unfortunate..
What's the difference between `enabledFor`/`disabledFor` and `siteList`/`siteListEnabled`? It seems like some (maybe all) of the sites I manually disabled Dark Reader were still in the `sync` `disabledFor`. `siteList` seemed to be empty in both.
With the snippet you posted both `local` and `sync` don't contain any sites now.

**Comment by alexanderby** [comment] 2023-11-22 12:49
Sorry for this. There was a long standing issue: a single site list was reused for `Invert listed only` and `Not invert listed` modes. Now there are 2 separate lists. We are moving towards Dark Reader v5 release and the settings structure need to be gradually changed.

Users who have a lot of websites in the list have settings synchronisation disabled due to storage size limitation. Unfortunately I didn't check that case. As soon as you modify the Site List they are gone.

In future we will prevent the site list from becoming too large, e.g. by allowing disabling some websites temporarily. But right now there are 2 options:
1. `Detect dark theme` option will disable Dark Reader for a website where it detects a dark theme.
2. In `Invert listed only` mode Dark Reader will only affect website that you toggle manually.

**Comment by alexanderby** [comment] 2023-11-22 13:21
@DianaNites Please try running:
```js
chrome.storage.sync.get(
    {
        enabledFor: [],
        disabledFor: [],
    },
    sites => {
        chrome.storage.local.set(
            sites,
            () => chrome.runtime.reload(),
        );
    },
);
```

**Comment by alexanderby** [comment] 2023-11-22 13:21
Did you use `Invert listed only` mode?

**Comment by ImSkully** [comment] 2023-11-22 13:23
Opened up Chrome today to see my list has also been wiped out. Checked both `chrome.storage.local` and `chrome.storage.sync` but unfortunately nothing there except the few in `local` I re-added to the disabled list today after noticing this.

Lost settings for ~600 websites. This really should have been caught with proper testing of https://github.com/darkreader/darkreader/commit/6db4210350e133af4d3f69d8786636cc1dd0477b before allowing it to be released.

**Comment by MaxLebled** [comment] 2023-11-22 13:58
Same here, extension is resetting itself to "don't invert listed" even though I'm setting it to "only invert listed" (I hit the keyboard shortcut when I want to use it). Both lists are completely gone

**Comment by VitalSkib** [comment] 2023-11-22 14:00
The same thing happened to me too, but on the latest Firefox Nightly.
I updated to the v4.9.69 version today and all my saved sites disappeared. 
Oh no.. 
Any way to restore this?

**Comment by SixelAlexiS90** [comment] 2023-11-22 14:01
Btw the "not invert" list got wiped once again for me.

**Comment by alexanderby** [comment] 2023-11-22 14:49
@DianaNites The migration process activates if `schemeVersion` is below `2`. If it is already set to `2`, the old Site List will not be read.

**Comment by VitalSkib** [comment] 2023-11-22 15:10
> same problem. reverting back to 4.9.68 brings back. 4.9.69 and 4.9.70 uses different list.

Oh that worked! 
Thanks a lot.



> @DianaNites The migration process activates if `schemeVersion` is below `2`. If it is already set to `2`, the old Site List will not be read.

Then how to update to .70 without losing the Site List ?

**Comment by MaxLebled** [comment] 2023-11-22 15:19
> @MaxLebled Do you remember you had `Invert listed only` before, or are you able to reproduce the extension switching itself to `Not invert listed`?

I'm 100% certain I've always had the extension set to "invert listed only" before, and that the lists wipe + the mode setting itself back to "don't invert listed" happened today.

I believe the extension then reset itself once more two hours after my first browser launch today, but I'm not 100% sure at this point. If I see it happen again, and/or if I find a reliable repro case, I'll make sure to let this thread know.

**Comment by alexanderby** [comment] 2023-11-22 15:37
The update 4.9.70 was approved earlier today. I've just checked that the migration works when updating from 4.9.68 to 4.9.70 with `syncSettings: false` and `enabledByDefault: false` (invert listed only).

I apologise for this error. I hope you will consider using the Dark Theme detection.

Here I left some instructions on restoring the part of the Site List https://darkreader.org/tips/restore-site-list-v4.9.69/

**Comment by BlafKing** [comment] 2023-11-27 14:00
After each reboot, versions 4.9.69 and 4.9.70 consistently reset the Site list for me.
Not sure what could be causing this, I will be reverting back to version 4.9.68 to avoid losing my site list with each reboot.

Browser: Brave v1.60.118
OS: Windows 10 22H2 (10.0.19045)

**Comment by alexanderby** [comment] 2023-11-27 15:35
@BlafKing, @VitalSkib, could you please share your settings? Please run:
```js
chrome.storage.local.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
```
and then:
```js
chrome.storage.sync.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
```
If it contains any sensitive date, please send to `support@darkreader.org`

**Comment by BlafKing** [comment] 2023-11-27 15:37
@alexanderby Sure thing, hope this helps!

Local:
```
{
    "disabledFor": [],
    "enabledByDefault": true,
    "enabledFor": [],
    "schemeVersion": 2
}
```

Sync:
```
{
    "automation": {
        "behavior": "OnOff",
        "enabled": false,
        "mode": "system"
    },
    "changeBrowserTheme": false,
    "customThemes": [
        {
            "theme": {
                "brightness": 100,
                "contrast": 100,
                "darkColorScheme": "Catppuccin",
                "darkSchemeBackgroundColor": "#1e1e2e",
                "darkSchemeTextColor": "#cdd6f4",
                "engine": "dynamicTheme",
                "fontFamily": "Segoe UI",
                "grayscale": 0,
                "immediateModify": false,
                "lightColorScheme": "Default",
                "lightSchemeBackgroundColor": "#dcdad7",
                "lightSchemeTextColor": "#181a1b",
                "mode": 1,
                "scrollbarColor": "auto",
                "selectionColor": "auto",
                "sepia": 0,
                "styleSystemControls": false,
                "stylesheet": "",
                "textStroke": 0,
                "useFont": false
            },
            "url": [
                "soundcloud.com"
            ]
        }
    ],
    "detectDarkTheme": true,
    "disabledFor": [],
    "displayedNews": [
        "filter-mode",
        "news-2023",
        "thanks-2023"
    ],
    "enableContextMenus": false,
    "enableForPDF": false,
    "enableForProtectedPages": false,
    "enabled": true,
    "enabledByDefault": true,
    "enabledFor": [],
    "fetchNews": true,
    "location": {
        "latitude": null,
        "longitude": null
    },
    "presets": [],
    "previewNewDesign": true,
    "readNews": [
        "filter-mode",
        "thanks-2023"
    ],
    "schemeVersion": 2,
    "syncSettings": true,
    "syncSitesFixes": false,
    "theme": {
        "brightness": 100,
        "contrast": 100,
        "darkColorScheme": "Catppuccin",
        "darkSchemeBackgroundColor": "#1e1e2e",
        "darkSchemeTextColor": "#cdd6f4",
        "engine": "dynamicTheme",
        "fontFamily": "Segoe UI",
        "grayscale": 0,
        "immediateModify": false,
        "lightColorScheme": "Default",
        "lightSchemeBackgroundColor": "#dcdad7",
        "lightSchemeTextColor": "#181a1b",
        "mode": 1,
        "scrollbarColor": "auto",
        "selectionColor": "auto",
        "sepia": 0,
        "styleSystemControls": false,
        "stylesheet": "",
        "textStroke": 0,
        "useFont": false
    },
    "time": {
        "activation": "18:00",
        "deactivation": "9:00"
    }
}
```

**Comment by VitalSkib** [comment] 2023-11-27 15:52
> @BlafKing, @VitalSkib, could you please share your settings? Please run:
> 
> ```js
> chrome.storage.local.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
> ```
> 
> and then:
> 
> ```js
> chrome.storage.sync.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
> ```
> 
> If it contains any sensitive date, please send to `support@darkreader.org`

Emm, I'm afraid I'm not that good in this matter.. 
Could you tell me where and how I can run this commands on Firefox? 
Thanks in advance.

**Comment by alexanderby** [comment] 2023-11-27 16:01
@BlafKing I couldn't reproduce this in Chrome and Firefox unfortunately. Do you see any errors in the background Console when you toggle sites?

**Comment by alexanderby** [comment] 2023-11-27 16:03
@VitalSkib Please go to [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox) page, and click Inspect button near Dark Reader.

**Comment by ooliver1** [comment] 2023-11-27 20:52
@alexanderby but the commands that were provided are quite specific to chrome as it is literally `chrome.storage`. I just had this happen today on Firefox Developer (aurora) `121.0b3 (64-bit)` too

**Comment by ooliver1** [comment] 2023-11-27 20:56
Just happened for me in Firefox Developer (aurora)

no trace of my old settings, which is quite irritating, the sites in the second one are just today, which doesn't detect all too well either as these have pretty obvious dark themes:
```
>> chrome.storage.local.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
<- undefined
{
    "disabledFor": [],
    "displayedNews": [
        "filter-mode",
        "news-2023",
        "thanks-2023"
    ],
    "enabledByDefault": true,
    "enabledFor": [],
    "readNews": [
        "filter-mode",
        "v5-survey",
        "mobile",
        "detect-dark-theme",
        "no-war",
        "chrome-favorites-2021",
        "thanks-2021",
        "5m-users",
        "v4-9-16",
        "v4-9",
        "attention",
        "dr-5-announcement",
        "2m-users",
        "automation",
        "product-hunt-golden-kitty-2018",
        "time-settings",
        "safari",
        "500k-users",
        "stylish",
        "product-hunt",
        "custom-site-settings",
        "thanks-for-contribution",
        "dynamic-theme",
        "news-2023",
        "thanks-2023"
    ],
    "schemeVersion": 2,
    "ui-hidden-highlights": [
        "new-toggle-menus"
    ]
}
>> chrome.storage.sync.get(null, settings => console.log(JSON.stringify(settings, null, 4)));
<- undefined
{
    "disabledFor": [
        "twitter.com",
        "www.reddit.com",
        "github.com"
    ],
    "changeBrowserTheme": false,
    "syncSettings": true,
    "syncSitesFixes": false,
    "time": {
        "activation": "18:00",
        "deactivation": "9:00"
    },
    "automation": {
        "enabled": false,
        "mode": "",
        "behavior": "OnOff"
    },
    "enableContextMenus": false,
    "location": {
        "latitude": null,
        "longitude": null
    },
    "enableForPDF": true,
    "enableForProtectedPages": false,
    "fetchNews": true,
    "enabled": true,
    "displayedNews": [
        "filter-mode",
        "news-2023"
    ],
    "schemeVersion": 2,
    "theme": {
        "mode": 1,
        "brightness": 100,
        "contrast": 100,
        "grayscale": 0,
        "sepia": 0,
        "useFont": false,
        "fontFamily": "Open Sans",
        "textStroke": 0,
        "engine": "dynamicTheme",
        "stylesheet": "",
        "darkSchemeBackgroundColor": "#181a1b",
        "darkSchemeTextColor": "#e8e6e3",
        "lightSchemeBackgroundColor": "#dcdad7",
        "lightSchemeTextColor": "#181a1b",
        "scrollbarColor": "auto",
        "selectionColor": "auto",
        "styleSystemControls": false,
        "lightColorScheme": "Default",
        "darkColorScheme": "Default",
        "immediateModify": false
    },
    "presets": [],
    "customThemes": [],
    "enabledByDefault": true,
    "enabledFor": [],
    "detectDarkTheme": true,
    "previewNewDesign": false,
    "readNews": [
        "filter-mode",
        "v5-survey",
        "mobile",
        "detect-dark-theme",
        "no-war",
        "chrome-favorites-2021",
        "thanks-2021",
        "5m-users",
        "v4-9-16",
        "v4-9",
        "attention",
        "dr-5-announcement",
        "2m-users",
        "automation",
        "product-hunt-golden-kitty-2018",
        "time-settings",
        "safari",
        "500k-users",
        "stylish",
        "product-hunt",
        "custom-site-settings",
        "thanks-for-contribution",
        "dynamic-theme"
    ]
}
```

**Comment by alexanderby** [comment] 2023-11-28 11:51
Unfortunately I still can't reproduce the problem with these settings. Please try the following:
1. Go to `about:debugging#/runtime/this-firefox` page.
2. Click Inspect in Dark Reader section.
3. Do you see any errors in the Console?
4. Try toggling some website. Do you see any errors?
5. Type `chrome.runtime.reload()` and press Enter. Are there any errors? Is the list of websites still present?

**Comment by BlafKing** [comment] 2023-11-28 12:02
> @BlafKing I couldn't reproduce this in Chrome and Firefox unfortunately. Do you see any errors in the background Console when you toggle sites?

Unfortunately no further indication as to what the issue is.
Toggling a site on or off doesn't log any errors.
And triggering `chrome.runtime.reload()` doesn't cause any errors either, and keeps the site list in tact.

Let me know if there's anything else that might give you an indication as to what could be going wrong 😅

**Comment by alexanderby** [comment] 2023-11-28 12:04
@BlafKing If you do a reboot, does it still clear the list for you?

**Comment by BlafKing** [comment] 2023-11-28 12:08
> @BlafKing If you do a reboot, does it still clear the list for you?

Just did a quick reboot to test, and it's no longer wiping after reboot!
Not sure what changed but looks like the issue no longer occurs for me :)

**Comment by BlafKing** [comment] 2023-11-28 21:11
Well I restarted again today and the list got wiped again, I can't wrap my head around this😕

I'll try to capture an error to hopefully provide some useful info.

**Comment by TheArgentinian** [comment] 2023-11-29 01:27
Same here. Thought I messed something up. Really f.....g annoying to disable it on every dark website.

**Comment by Athanasius** [comment] 2023-11-29 09:01
> about:debugging#/runtime/this-firefox

This needs to be on https://darkreader.org/tips/restore-site-list-v4-9-69/

**Comment by mattschlosser** [comment] 2023-11-29 21:45
Lost all my sites when I restarted to update Firefox. I believe I was already on 4.9.70 when I restarted, as it says it was last updated Monday in manage extension settings. Thanks for looking into this



Firefox (aurora) 121.0b5 (64-bit)
Dark Reader 4.9.70 last updated Monday

// local 
```json 
{
    "disabledFor": [],
    "displayedNews": [
        "mobile",
        "v5-survey",
        "filter-mode",
        "news-2023",
        "thanks-2023"
    ],
    "enabledByDefault": true,
    "enabledFor": [],
    "readNews": [
        "v4-9",
        "thanks-2023"
    ],
    "schemeVersion": 2,
    "ui-hidden-highlights": [
        "new-toggle-menus"
    ]
}
```

// sync 
```json
{
    "readNews": [
        "v4-9"
    ],
    "enableForProtectedPages": false,
    "enabled": true,
    "notifyOfNews": false,
    "automation": {
        "enabled": false,
        "mode": "",
        "behavior": "OnOff"
    },
    "fetchNews": true,
    "changeBrowserTheme": false,
    "theme": {
        "mode": 1,
        "brightness": 100,
        "contrast": 100,
        "grayscale": 0,
        "sepia": 0,
        "useFont": false,
        "fontFamily": "Segoe UI",
        "textStroke": 0,
        "engine": "dynamicTheme",
        "stylesheet": "",
        "darkSchemeBackgroundColor": "#181a1b",
        "darkSchemeTextColor": "#e8e6e3",
        "lightSchemeBackgroundColor": "#dcdad7",
        "lightSchemeTextColor": "#181a1b",
        "scrollbarColor": "auto",
        "selectionColor": "auto",
        "styleSystemControls": true,
        "lightColorScheme": "Default",
        "darkColorScheme": "Default",
        "immediateModify": false
    },
    "time": {
        "activation": "18:00",
        "deactivation": "9:00"
    },
    "enableForPDF": true,
    "presets": [],
    "automationBehaviour": "OnOff",
    "customThemes": [],
    "enabledByDefault": true,
    "enabledFor": [],
    "previewNewDesign": false,
    "enableContextMenus": false,
    "schemeVersion": 2,
    "disabledFor": [
        "lms.albertabcsafety.com",
        "192.168.7.90:8480",
        "localhost",
        "github.com",
        "mail.google.com"
    ],
    "syncSettings": true,
    "location": {
        "latitude": null,
        "longitude": null
    },
    "syncSitesFixes": false,
    "detectDarkTheme": false,
    "displayedNews": [
        "mobile",
        "v5-survey"
    ]
}
```

**Comment by lumynou5** [comment] 2023-11-30 07:29
I don't know why, but the list on my Windows isn't wiped out, and then the list on my Linux was back when I restarted.

**Comment by redwo1f** [comment] 2023-11-30 18:05
Mine got wiped, nothing in local or sync storage.

**Comment by derritter88** [comment] 2023-12-01 07:47
I have the same troubles but on Firefox.

**Comment by truncsphere** [comment] 2023-12-02 15:11
Just chiming in that I've lost my Inverted Site List twice now on Firefox in the span of a week.

**Comment by Speedy-VonGofast** [comment] 2023-12-02 15:42
Having same issue, my not inverted list got wiped multiple times.

**Comment by VitalSkib** [comment] 2023-12-02 16:54
Yeah, I had to roll back to version 4.9.68 and disable extensions auto-update in Firefox.. 😟

**Comment by alexanderby** [comment] 2023-12-04 14:53
Do you guys use Dark Reader on multiple machines? Oh no, I suppose the following scenario:
1. The settings are successfully migrated on Computer 1 with v4.9.70. Old lists are wiped out.
2. You turn on the Computer 2 with v4.9.68. It uses old lists that are wiped out now. When it updates to v4.9.70 it migrates those wiped out lists into new lists.
3. Now both machines have lists wiped out.

I will make a patch for this.

**Comment by VitalSkib** [comment] 2023-12-04 15:27
> Do you guys use Dark Reader on multiple machines?

Hmm, in my case I only have and use one computer. 
If I update to version .70 then my list is blank, if I install version .68 back my old list is available again.

**Comment by truncsphere** [comment] 2023-12-04 15:33
> Do you guys use Dark Reader on multiple machines? Oh no, I suppose the following scenario:

Yes, I do use it on multiple PC's that sync.

**Comment by derritter88** [comment] 2023-12-04 16:36
> Do you guys use Dark Reader on multiple machines? Oh no, I suppose the following scenario:
> 
>     1. The settings are successfully migrated on Computer 1 with v4.9.70. Old lists are wiped out.
> 
>     2. You turn on the Computer 2 with v4.9.68. It uses old lists that are wiped out now. When it updates to v4.9.70 it migrates those wiped out lists into new lists.
> 
>     3. Now both machines have empty lists.
> 
> 
> I will make a patch for this.

Yes, Firefox on Windows desktop and Firefox on Macbook Pro.

**Comment by echocrow** [comment] 2023-12-04 22:46
> Do you guys use Dark Reader on multiple machines?

Yup - also list the list today, and cannot recover it via `chrome.storage`. 🪦 RIP white-list (technically: dark-list).

**Closed** 2024-04-01 16:01 UTC
Labels: bug

**Comment by Ghoelian** [comment] 2024-07-18 07:22
I think I'm still having this issue, every time I add a new device to Firefox Sync, dark reader seems to reset everything.

Why was this issue closed? Should I make a new issue?

**Comment by lumynou5** [comment] 2024-07-18 07:52
> I think I'm still having this issue, every time I add a new device to Firefox Sync, dark reader seems to reset everything.
> 
> Why was this issue closed? Should I make a new issue?

IIRC, this issue was confirmed the reason is that the migration from old version of configuration scheme to new version had wiped out the old-version configuration and then another device synchronized the empty old-version configuration, and is patched.

I believe the problem you encountered is different from this and you should open a new issue.
