### ISSUE TITLE
[Broken Website] https://outlook.live.com/owa/

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#7965] opened 2022-01-16 00:05 UTC
# Broken Website Report

## Website Address
https://outlook.live.com/owa/ (Homepage URL)
https://outlook.live.com/mail/0/ (URL displayed once signed in to the site.)

## Steps To Reproduce
Visit the site. (See screenshots for the original and the Dark Reader versions (normal & with error) of the site.)
Create account / Use existing account.
Sign in.
Refresh the page 1 time, let the page fully load, then try refreshing again and letting the page load, repeat as needed until the issue manifests.

## Expected Behavior
The site displays correctly when using Dark Reader regardless of how many times the page is refreshed.

## Actual Behavior
The site displays black text on a dark background when using Dark Reader after the page is refreshed a few times.

## Screenshots
Original:

![outlook-regular-no-dr](https://user-images.githubusercontent.com/95879668/149641467-8d687f51-021d-4c61-a159-f23df7de01cf.png)

Dark Reader normal:

![outlook-regular-with-dr](https://user-images.githubusercontent.com/95879668/149641471-636534e9-ecf2-4aa4-8638-523ace475845.png)

Dark Reader with error (After refreshing the page a few times):

![outlook-with error-with-dr](https://user-images.githubusercontent.com/95879668/149641475-541d8f76-38ca-4f34-955c-cbfec680cde4.png)

## System Information

- OS: Windows 10 21H2 (19044.1466)
- Browser: Firefox Nightly 98.0
- Dark Reader Version: 4.9.43

## Additional Context
This issue is very similar to #6215, however this issue requires you to refresh the page a few times before it will manifest.

**Comment by Gusted** [comment] 2022-01-16 12:16
Hi @q1800!

I'm not able to reproduce this, as mentioned #6215 was a similar report which almost seems to be the same. Which was fixed by #6217. You could check if this behavior reproduces on a new profile(`about:profiles`), it could be a interfering extension or a Firefox setting.

Regards,
Gusted

**Comment by q1800** [comment] 2022-01-16 16:46
Hey @Gusted,

I was using a new profile in Firefox Nightly when I created those screenshots and the issue.

I have created a screen capture video showing the issue manifesting itself using a new profile and uploaded it to YouTube.

https://www.youtube.com/watch?v=5lSpI_5822k

The video is about 3 minutes in length. It shows the issue manifesting itself towards the end of the video. I recorded the whole process from start to finish from me opening the browser, to logging into the account, letting the page fully load for the first time and refreshing the page and letting the page fully load again, and repeating until the issue manifests itself.

The video does blank out from about 2:37 - 2:41 due to the screen recording software glitching out. The video will come back and finish showing the issue.

---

I am more than willing to help further troubleshoot this issue or provide any other information needed to help solve this issue.

Is there any debugging tools or settings or software I can use to help?

Please let me know.

Thank you again for all the help! 👍

**Comment by Gusted** [comment] 2022-01-16 21:04
So I'd had a good look and thought about it. This is a problem that relied in Dark Reader not having a correct order of certain operations. However I've gone trough the steps and they should work as outlooks does them. So, it could be somehow a Firefox Regression as you're on Firefox 98, whereby I'm still on 97.0a1(I haven't received any update notice so far). Could you check if this persist on a older version(Firefox ESR)?

**Comment by q1800** [comment] 2022-01-16 21:10
Thanks for further looking into the issue. I will be glad to give the current Firefox ESR and Firefox 97 (now in Beta) a thorough try. I will get to work immediately and report my findings.

**Comment by q1800** [comment] 2022-01-16 21:47
Firefox 96.0.1, Firefox Beta 97.0b3, & Firefox ESR 91.5.0esr all do not have the issue. It looks like the issue is specifically within Firefox Nightly 98.0a1.

I tried to reproduce the issue in all 3 of the other browser versions by refreshing the page at least 15 times in each. The issue never manifested itself once.

What would be the next troubleshooting step or next thing to try, if any?

**Comment by Gusted** [comment] 2022-01-19 17:12
So I finally got a update to Firefox Nightly 98, I'm using [Chaotic AUR](https://aur.chaotic.cx/) btw. I'd prefer to use the package manager to avoid conflicts. Anyhow, I've tried to reproduce bug, but unfortunate I'm still not able to reproduce it. To avoid that I'm somehow avoiding the bug due a setting, I've spinned up a fresh Ubuntu image and downloaded Firefox Nightly. But I don't seem to reproduce the problem either...

**Comment by q1800** [comment] 2022-01-20 20:37
@Gusted,

I have switched to Manjaro Linux KDE today and I am not able to reproduce this issue.

How do you wish to proceed with this issue report? I do know for a fact it is definitely still an issue on Windows 10 with Firefox Nightly 98 as of earlier today. Should we close this issue report or leave it open?

Thanks!

**Comment by Gusted** [comment] 2022-01-21 11:23
I think we can close it, I will hold this issue in mind when a new issue comes in.

**Closed by Gusted** 2022-01-21 11:23 UTC
Labels: Broken Website
