### ISSUE TITLE
[Bug] There is no "Back" button under Settings in version 5 preview (Firefox only)

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9539] opened 2022-08-11 17:21 UTC
# Bug Report

## Bug Description
There is no "Back" button under Settings in version 5 preview (Firefox only).

## Screenshots
Brave
<img width="353" alt="Screen Shot 2022-08-11 at 10 20 09 AM" src="https://user-images.githubusercontent.com/11276349/184194711-1b0eb62c-3f9b-4526-8206-0fbc543698d4.png">

Firefox
<img width="271" alt="Screen Shot 2022-08-11 at 10 19 50 AM" src="https://user-images.githubusercontent.com/11276349/184194747-65cbd0b5-e31d-471d-bb02-8c4532726ce2.png">

## System Information
- OS: macOS
- Browser: Firefox 103.0.2
- Dark Reader Version: 4.9.55

**Comment by Gusted** [comment] 2022-08-12 12:01
Duplicate of #9112

**Closed** 2022-08-12 12:02 UTC
Labels: bug
