### ISSUE TITLE
[Bug] "Toggle current site" context menu option doesn't work for files in Firefox.

### ISSUE THREAD

**Issue by Scr34mik** [darkreader/darkreader#7836] opened 2022-01-03 12:35 UTC
# Bug Report

## Bug Description

"Toggle current site" menu option doesn't work for files in Firefox.

## Website Address

file:///D:/whatever/path/to/html/file.htm

## Steps To Reproduce

Any *.htm file opened in Firefox.

## Expected Behavior

Should make htm files preview dark.

## Actual Behavior

Doesnt toggle views for htm files stored on HDD.

## System Information

- OS: Windows 10, build 19042.1202 (20H2)
- Browser: Firefox 95.0.2
- Dark Reader Version: 4.9.43

## Additional Context

Adding a full path to file from address bar forcefully turns preview into dark mode, however toggling view still doesn't work for some reason. Other than that, i really don't know what else can i add to help with debugging this.

**Comment by Gusted** [comment] 2022-01-03 13:29
Duplicate of #4345

**Closed by Gusted** 2022-01-03 13:29 UTC
Labels: bug
