### ISSUE TITLE
[Feature Request] Dark Loading Screen

### ISSUE THREAD

**Issue by hakaneroztekin** [darkreader/darkreader#1519] opened 2019-08-24 17:24 UTC
Dark reader is awesome especially at night, but when you open a new tab (Ctrl+T), the loading screen for the tab is pure white that is the Firefox default and it is annoying. If it is possible to make loading screen of new tabs dark too, it would be awesome.

**Comment by privacyguy123** [comment] 2019-09-05 19:03
+1 on this - my poor retinas. I can't get the custom CSS to understand about:newtab.

**Comment by privacyguy123** [comment] 2019-09-05 19:13
Bump.

**Comment by Polyterative** [comment] 2019-09-11 09:22
That does not depend on dark reader I think. On chrome the same issue is solved by changing the browser's theme

**Comment by privacyguy123** [comment] 2019-09-17 10:43
I'm already using FireFox built in Dark Theme - pretty sure this is reader specific.

**Comment by inthreedee** [comment] 2019-09-18 16:08
What you're seeing is just Firefox's default background canvas and changing the theme doesn't solve it.  I don't think addons have access to change this for security reasons, so there's probably nothing Dark Reader can do.

Shadowfox applies a userChrome.css change that mostly, but not completely, fixes it.  This is how they do it:
https://github.com/overdodactyl/ShadowFox/blob/master/css/userChrome-files/remove_white_flash.css

You could take that code, replace `var(--in-content-page-background)` with an actual color (ie.  `#2d2d2d`), and put it in a `[profile]/chrome/userChrome.css` file.  In Firefox 69, userChrome.css files aren't read by default as part of their security improvements.  You can enable it in about:config.

**Comment by jpuris** [comment] 2019-09-19 08:26
Until dark reader is able to do this, I've settled on https://github.com/overdodactyl/ShadowFox to solve this issue.

**Comment by joelostblom** [comment] 2020-04-23 03:47
Put the following in `userChrome.css` in your default profile:

```css
.browserContainer {
    background-color: #3d3d3d !important;
}
```

and the below in `userContent.css` in the same folder:

```css
@-moz-document url("about:blank") {
	html {
	  background-color: #3d3d3d;
	}
}

@-moz-document url(about:newtab) {
	body, #newtab-customize-overlay {
       background-color: #3d3d3d !important;
       color: rgb(166,166,166) !important;
    }
}
```

This worked for me while using `about:blank` as my new tab page. Removes both the flash and restyles the page background in the new tab.

**Comment by Gusted** [comment] 2020-04-23 12:34
As of Darkreader the first time we actually can do is document_start and that's after the DOM(we than got the HTML of the site) has been loaded(I think) so making connection with the site TLS handsake etc is the time you see the white flash. Above me https://github.com/darkreader/darkreader/issues/1519#issuecomment-618160093 comment is a good workaround but darkreader can't improve on this.

**Comment by inthreedee** [comment] 2020-04-23 12:43
This shouldn't be necessary in Firefox anymore.  Since Firefox version 70, it will respect the system theme and automatically switch the default background canvas color based on your OS theme settings.  I have a dark theme set in Gnome and no longer need to use any userChrome.css workarounds.

https://www.mozilla.org/en-US/firefox/70.0/releasenotes/
> Built-in Firefox pages now follow the system dark mode preference

Just as a quick caveat, there is always the occasional white flash even with the above userChrome.css workarounds so there is no perfect solution to this.  I only mean to say that the new built-in dark mode works as well as any userChrome.css hacks used to.

**Comment by joelostblom** [comment] 2020-04-23 15:27
@ineentho I haven't tried with a dark desktop theme (on i3), but there is no white flash for me with the tweak above.

**Comment by Gusted** [comment] 2020-06-19 16:34
1. Update to latest Firefox they changed some behaviour for this.
2. 
> Open dark reader extension pop-up, go to 'More' and click on 'Default`
> Press ctrl + shift + a Click on 'themes' Disable & Enable Dark theme.

We can't do anything more.

**Comment by Gusted** [comment] 2020-06-24 13:40
https://github.com/darkreader/darkreader/issues/1219#issuecomment-648826202

**Comment by Gusted** [comment] 2020-08-15 11:50
Duplicate of #1219

**Closed by Gusted** 2020-08-15 11:50 UTC
