### ISSUE TITLE
Darkreader adding multiple seconds to feedly load time

### ISSUE THREAD

**Issue by singhkays** [darkreader/darkreader#991] opened 2019-01-09 21:23 UTC
Everytime I have dark reader enabled, the load time for Feedly homepage is delayed by 5+ seconds

**Comment by alexanderby** [comment] 2019-01-21 20:49
Are you using Firefox?

**Comment by singhkays** [comment] 2019-01-21 21:16
@alexalekseyenko Yes, that's correct

**Comment by alexanderby** [comment] 2019-01-21 22:01
Then I'm afraid this is a duplicate of #535. But thanks for the example of a slow webpage, maybe it will give some more ideas.

**Closed by alexanderby** 2019-01-21 22:01 UTC

**Comment by alexanderby** [comment] 2019-01-21 22:02
@singhkays Yes, and you picked a wrong user into this post. This is a common mistake, similar user names :)
