### ISSUE TITLE
[Broken Website] How to solve this from happening? 

### ISSUE THREAD

**Issue by shyamal890** [darkreader/darkreader#3864] opened 2020-10-15 20:16 UTC
**Website**
https://app.smarttask.io 

**How to Reproduce**
- Go to calendar or board view

**Expected behavior**
- I guess there should be able to avoid so much processing that it just crashes. 

**Actual behavior**
Crashes the browser tab

- Latest version

**Comment by Gusted** [comment] 2020-10-15 20:18
Hi @shyamal890!

If the tab crashes, please use Filter(+) for this site.

Regards,
Gusted

**Comment by shyamal890** [comment] 2020-10-15 20:23
@Gusted I am using the npm version for our own site -> app.smarttask.io but it crashes with many elements. How to avoid that?

**Comment by Gusted** [comment] 2020-10-15 20:25
Oh, I didn't understand it was a API issue.
Is the crashing of the browser tab reproduce-able on multiple machines?

**Comment by shyamal890** [comment] 2020-10-15 20:54
@Gusted yes. You can try it with 

email-id: rohit@acme.io 
password: trialpass

I would delete this credentials once you let me know.

**Comment by Gusted** [comment] 2020-10-15 21:26
Their is a known issue with Dark reader and certain functions that intent to revert our changes to element's inline style  `<p style="Here">`. It seems this was also the case on your site. I already had a good idea to fix this issue, but never got the motivation/time around to create this fix. So here it is #3865 I will try to push this to a high priorty fix and hopefully gets merged soon.

I no longer need the credentials.

Regards,
Gusted

**Closed** 2020-10-21 17:00 UTC

**Comment by shyamal890** [comment] 2020-10-25 17:02
Hi @Gusted this problem still persists. Any chance we can get a fix released on npm soon?

**Comment by Gusted** [comment] 2020-10-25 17:08
> Hi @Gusted this problem still persists. Any chance we can get a fix released on npm soon?

Their is no planned released however it has been a month since last update and a fix for #3914 should be pushed ASAP. So I think next week a release will be released.
