### ISSUE TITLE
[Broken Website] Colors in Google Shopping Are Inverted

### ISSUE THREAD

**Issue by sileeb** [darkreader/darkreader#8084] opened 2022-01-31 23:09 UTC
- I reproduced this same issue on both Firefox and Edge. 
- I tried it in a new profile and the issue was again reproduced. 

# Broken Website Report

## Website Address
https://www.google.com/search?q=car&client=firefox-b-1-d&sxsrf=APq-WBs0nuDGnslHFBEFMmv5AJSmHaP31g:1643669940947&source=lnms&tbm=shop&sa=X&ved=2ahUKEwj6x9TXi931AhWQdN8KHbCcBzsQ_AUoAnoECAEQBA&biw=1741&bih=897&dpr=1.11

## Steps To Reproduce
I go to google.com. From there, I click on the shopping link which takes me to google shopping. There, the colors of the page are inverted.

## Problematic Observation
The colors of every element of the page become inverted. 

## Screenshots
![22](https://user-images.githubusercontent.com/73712645/151887948-09a3a2ab-1328-4140-828d-b0b8eadb5203.png)

## System Information
OS: win 10
Browser: firefox 96.0.3
Dark Reader version: 4.9.43

**Comment by zhenjie1999** [comment] 2022-02-01 05:46
https://hitomi.la/ also pls check

**Comment by rgbk** [comment] 2022-02-01 15:54
Same here!

**Comment by rgbk** [comment] 2022-02-01 15:58
Fixed, culprit: https://chrome.google.com/webstore/detail/colorblind-dalton-for-goo/afcafnelafcgjinkaeohkalmfececool

**Comment by Gusted** [comment] 2022-02-01 17:44
Hi @sileeb, @rgbk!

Is the issue that dark reader adds the weird looking background image? The provided screenshot seems to also have other styles applied. Could a better screenshot be made that clearly says what the issue is?

**Comment by sileeb** [comment] 2022-02-01 18:32
> Fixed, culprit: https://chrome.google.com/webstore/detail/colorblind-dalton-for-goo/afcafnelafcgjinkaeohkalmfececool

No the issue has NOT been fixed. I dont know why you posted this addon especially when the issue is primarily firefox related

**Comment by sileeb** [comment] 2022-02-01 18:34
> https://hitomi.la/ also pls check

Stop posting filth. This is a serious site to help people not a porn one.

**Comment by sileeb** [comment] 2022-02-01 18:37
> Hi @sileeb, @rgbk!
> 
> Is the issue that dark reader adds the weird looking background image? The provided screenshot seems to also have other styles applied. Could a better screenshot be made that clearly says what the issue is?

No, that background is from my CSS. DR still inverts the background of google shopping whether I turn off my CSS or not. 
When can you fix this?

**Comment by Gusted** [comment] 2022-02-01 19:30
> No, that background is from my CSS.

Which is essentially another style being applied IMO.

I've checked the website, but I wasn't able to reproduce the issue. But this sounds like: #7512

**Comment by rgbk** [comment] 2022-02-01 19:32
Sorry I see this GH is related to a chrome extension. I don’t think my
issue was related. I found this via googling “Google shopping inverted bug”

But I figured out it was being caused by a Color blindness extension I was
testing.

Cheers.

**Comment by sileeb** [comment] 2022-02-01 19:39
> Which is essentially another style being applied IMO.

It doesnt matter if CSS is applied or not. The error still applies with CSS on or off. 

> I've checked the website, but I wasn't able to reproduce the issue. But this sounds like: #7512

Its exactly the same issue. The website from #7512 and mine is google shopping... its the same site. Not to sound arrogant, but I dont understand why you dont see that theres no difference.

**Comment by Gusted** [comment] 2022-02-01 20:19
> It doesnt matter if CSS is applied or not. The error still applies with CSS on or off.

It does matter for me, as it can cause interference and I had no clue beforehand if it was caused by darkreader(and thus what the bug report was about) or some other CSS. Anyhow it's sorted out now.



> > Which is essentially another style being applied IMO.
> 
> It doesnt matter if CSS is applied or not. The error still applies with CSS on or off.
> 
> > I've checked the website, but I wasn't able to reproduce the issue. But this sounds like: #7512
> 
> Its exactly the same issue. The website from #7512 and mine is google shopping... its the same site. Not to sound arrogant, but I dont understand why you dont see that theres no difference between these 2 issues

Well I've found in the past that when I did say that it sounded like the same issue and then closed the issue that certain people wouldn't accept it(as it wasn't really the same issue). But this seems like the case now, closing.

**Closed by Gusted** 2022-02-01 20:19 UTC
Labels: Broken Website

**Comment by sileeb** [comment] 2022-02-01 20:30
Hi Gusted.. So just making sure we're on the same page. In your last response you said the case is closed. I'm confused by that. Do you mean to say that the error has been fixed or that its presently being fixed and you'll update the addon soon? I checked  just now and the error continues to persist

**Comment by aminomancer** [comment] 2022-05-22 23:12
Google Shopping is currently inverted at the body for me on both Firefox and Edge, with or without "detect dark theme" enabled
