### ISSUE TITLE
An old bug is back

### ISSUE THREAD

**Issue by ice-ivanov** [darkreader/darkreader#3505] opened 2020-08-23 00:36 UTC
Should be fixed

_Originally posted by @Gusted in https://github.com/darkreader/darkreader/issues/1183#issuecomment-674582008_

Haven't noticed this bug for about half a year now but ironically as you've closed the case, it's back >_<
Specifically, on inoreader.com and Reddit. These websites have dark themes that I'm using so there's no need for DR, yet it turns on the website every time I switch to another tab.

**Comment by Gusted** [comment] 2020-08-23 16:53
Hi @ice-ivanov!

Does it show in the Popup It's enabled?

Regards,
Gusted

**Comment by Kaldo** [comment] 2020-09-26 06:59
I am experiencing the same bug and I can easily reproduce it. If I middle mouse click on the link to open it in a new tab, when I switch to that tab the dark theme will be applied even if it's not turned on for that site. If I left mouse click on the link to open it in the current tab, the dark theme does not get applied. Seems to be an issue if the page gets loaded in the background. I'm using firefox.

**Comment by Gusted** [comment] 2020-09-26 07:29
> I am experiencing the same bug and I can easily reproduce it. If I middle mouse click on the link to open it in a new tab, when I switch to that tab the dark theme will be applied even if it's not turned on for that site. If I left mouse click on the link to open it in the current tab, the dark theme does not get applied. Seems to be an issue if the page gets loaded in the background. I'm using firefox.

Hi @Kaldo!

Fortunately, thst bug has been fixed by #3715. And is currently avaible in the extension store as 4.9.21

**Comment by Kaldo** [comment] 2020-09-26 07:35
> 
> 
> > I am experiencing the same bug and I can easily reproduce it. If I middle mouse click on the link to open it in a new tab, when I switch to that tab the dark theme will be applied even if it's not turned on for that site. If I left mouse click on the link to open it in the current tab, the dark theme does not get applied. Seems to be an issue if the page gets loaded in the background. I'm using firefox.
> 
> Hi @Kaldo!
> 
> Fortunately, thst bug has been fixed by #3715. And is currently avaible in the extension store as 4.9.21

I see the new version after checking for updates manually and seems to be working fine. Thanks!

**Comment by Gusted** [comment] 2020-11-13 00:12
Update to v4.9.22/23 #3605 fixes this

**Closed by Gusted** 2020-11-13 00:12 UTC
