### ISSUE TITLE
Time based switching of Dark Mode

### ISSUE THREAD

**Issue by anishmittal2020** [darkreader/darkreader#705] opened 2018-08-30 09:18 UTC
Can the dark mode switch `on` by itself say at 8 pm and say switch off at 6 am?

**Comment by risualiser** [comment] 2018-08-30 10:11
Duplicate of #10. It's already in [roadmap](https://github.com/darkreader/darkreader/projects/1).

**Closed** 2018-09-07 14:07 UTC
Labels: duplicate
