### ISSUE TITLE
Cannot toggle on mail.yandex.com

### ISSUE THREAD

**Issue by vitaly-zdanevich** [darkreader/darkreader#265] opened 2018-03-05 06:28 UTC
![darkreader-defect--cannot-toggle](https://user-images.githubusercontent.com/3514015/36960321-870bdbd0-2057-11e8-912c-4c84d85b4270.gif)

**Comment by alexanderby** [comment] 2018-03-07 10:55
Maybe you have yandex.com in list. If so, then the behavior should be fixed some way.

**Comment by DrupaListo-com** [comment] 2018-03-17 18:09
This happens specifically when:
- you darken and then un-darken domain.com
- then you go to sub.domain.com and try to darken it - never works because domain.com was added to exclusion list of sites - i.e. sites to never darken, so all the subdomains now will follow the main domain policy and can't be darken-ed.

This sux if you ask me. For some use-cases it's a feature, for others - where the subdomain is a separate site - it's a bug.

Can we add a toggle in settings to enable/disable the subdomain inheritance globally? I suggest that's disabled by default, but that might be just me.
Another option is to give the user control over the global PLUS local per-domain/site behaviour.
There are several ways to do it in the UI, having not 1 but 2 white/black lists... or having not 1 but 2 toggle site buttons - one toggling domain + all subdomains (current one).AND another new one that toggles ONLY domain.com. 1st button adds a *.domain.com entry in whitelist/blacklist while 2nd button adds a domain.com entry only or a sub.domain.com entry only. All current domains in blacklist should be migrated from  domain.com -> *.domain.com cause this is the current logic and we need to stay with it and only after that allow for changes...

Making sense?

I've had the same unexpected behaviour and wanted for a long time Dark Reader to be more flexible when handling subdomains ...  adding this will be needed by many users I think.

**Comment by alexanderby** [comment] 2018-03-17 18:57
We will implement glob-like behavior, so it will be possible to use ignore patterns like `!sub.domain.com`.

**Comment by alexanderby** [comment] 2018-04-17 17:45
Here is what is planned to do https://github.com/alexanderby/darkreader/issues/373

**Comment by Ryonez** [comment] 2019-03-02 07:05
This tripped me up today. Didn't even notice that the root domain had a rule that was in place.

**Comment by Yash-Singh1** [comment] 2020-11-17 19:42
I think this is already implemented

**Closed** 2020-11-17 23:17 UTC
Labels: enhancement
