### ISSUE TITLE
[Broken Website] https://chromestatus.com/roadmap

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#10522] opened 2022-12-22 10:45 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Address

https://chromestatus.com/roadmap

### Screenshots

![Screenshot 2022-12-22 184348](https://user-images.githubusercontent.com/121229410/209117515-389663a2-a0b2-46e5-9b6d-5b41df505f66.jpg)

### Operating System

Windows 10

### Web Browser name and version

Chrome 108

### Dark Reader version

4.9.60

**Comment by Gusted** [comment] 2023-01-03 22:36
Duplicate of #4682 (same underlying issue)

**Closed by Gusted** 2023-01-03 22:36 UTC
Labels: Broken Website
