### ISSUE TITLE
[Bug] Vimvixen cause white box

### ISSUE THREAD

**Issue by ryan-c-dev** [darkreader/darkreader#9149] opened 2022-06-29 13:38 UTC
# Bug Report

## Website Address

all sites

## Bug Description

Firefox 102.0 on Arch Linux
Horizontal white bar when dark mode enabled. Persistent even after disabling

## System Information

- OS: Arch Linux 2022.06.01 release
- Browser: Firefox 102.0
- Dark Reader Version: 4.9.52

## Additional Context
Only occured in most recent patch!
![pic-full-220629-0634-47](https://user-images.githubusercontent.com/50060288/176450313-2d0aa07a-935f-4e3c-bbf8-695415130329.png)

**Comment by alexanderby** [comment] 2022-06-29 14:49
Are you using Filter mode or Dynamic?

**Comment by ryan-c-dev** [comment] 2022-06-29 15:04
dynamic

**Comment by ryan-c-dev** [comment] 2022-06-29 15:09
switching to filter and filter+ seems to fix it, as well as static.
Only in most recent patch this it start happening. Running DWM w/ x11
if that helps.

**Comment by ryan-c-dev** [comment] 2022-06-29 15:15
Also, just tried setting with Filter+, opened up github and screen was black.
Issue seems to be soley with the extension, when it's
disabled/uninstalled everything goes back to normal on restarting
firefox. Lemme know if you need any help!

**Comment by tolson-vkn** [comment] 2022-06-29 16:34
@alexanderby I am also hitting this issue hope this helps. I do not see this regression in Chrome. Happy to debug additionally.
![Peek 2022-06-29 11-30](https://user-images.githubusercontent.com/14153338/176489329-bc9b0ab7-80a0-4165-b009-1fa520d6bd34.gif)

**Comment by tolson-vkn** [comment] 2022-06-30 00:43
I figured out what the problem is. The extension vim-vixen (which adds vim functionality to firefox) is the culprit. The white box at the bottom is an iframe that is used for page search. I'm attaching a gif to show that.

The iframe is: 
```
![Peek 2022-06-29 19-30](https://user-images.githubusercontent.com/14153338/176568989-268701ae-d720-41e5-b640-46e118fd06ca.gif)

<iframe src="moz-extension://d6419ac8-9f6b-420c-8aab-71153f439885/build/console.html" id="vimvixen-console-frame" class="vimvixen-console-frame"></iframe>
```

Unfamiliar with the nuances of CSS but I would think the dynamic theme editor CSS can include a stanza like how it does for `.vimvixen-hint` and then we just ignore it, or change the position attribute.

**Comment by ryan-c-dev** [comment] 2022-06-30 02:19
Yes, i'm using vim-vixen as well.
If anyone knows CSS, and how to ignore the iframe, let me know!

**Comment by Gusted** [comment] 2022-06-30 20:00
```css
#vimvixen-console-frame {
    z-index: -1 !important;
}
```

Adding that CSS resolves the issue. Quite weird why they have a positive z-index, given that the iframe is not used at all. Does someone want to open a issue at vim-vixen for this?

**Comment by xeruf** [comment] 2022-07-01 23:02
Hitting the same:
![image](https://user-images.githubusercontent.com/13354331/176976136-a53eb549-4b2d-45f1-a889-ab5b53da7f46.png)
See also #7852

I am guessing the positive z-index is so it can pull focus for search, maybe?

**Comment by xeruf** [comment] 2022-07-01 23:04
See https://github.com/ueokande/vim-vixen/issues/1424

**Comment by Salomanuel** [comment] 2022-08-25 11:00
maybe it's obvious, but Dark Reader has a global option to set it once for all websites:
![image](https://user-images.githubusercontent.com/14359139/186647488-97f8b49c-7b55-46a0-8017-0cf673bb2d59.png)

Settings/Dev tools

**Comment by xeruf** [comment] 2022-08-27 21:50
I switched to Tridactyl to avoid it ;)

**Comment by alexanderby** [comment] 2024-04-02 13:30
Should be fixed by https://github.com/darkreader/darkreader/commit/2e7500084d504c7a9b4ad3df3f85a04103a74b0e

The fix will be available in the next release.

**Closed by alexanderby** 2024-04-02 13:30 UTC
Labels: bug
