### ISSUE TITLE
[Dynamic Theme] Hang on new Confluence Page Editor when insert Info/Warn/Error/Note Panel

### ISSUE THREAD

**Issue by quangkieu** [darkreader/darkreader#1595] opened 2019-10-01 22:56 UTC
As the title mention, when I create/edit a New Editor of Confluence page, the page would hang when I insert an Info/Warn/Error/Note Panel.
There is no problem when I switch to Filter/Filter+ theme.

**Comment by ey51** [comment] 2020-05-18 16:35
+1 on this. Can't edit pages with /info panels. Chrome window hangs unresponsive.

**Comment by ey51** [comment] 2020-05-18 16:40
When this is added, the window hangs:
```
<div class="ak-editor-panel" data-panel-type="info"><span class="ak-editor-panel__icon"><span class="sc-gzVnrw doMcuc" role="img" aria-label="Panel info"><svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M12 20a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-8.5a1 1 0 0 0-1 1V15a1 1 0 0 0 2 0v-2.5a1 1 0 0 0-1-1zm0-1.125a1.375 1.375 0 1 0 0-2.75 1.375 1.375 0 0 0 0 2.75z" fill="currentColor" fill-rule="evenodd"></path></svg></span></span><div class="ak-editor-panel__content"><p><br></p></div></div>
```
![image](https://user-images.githubusercontent.com/39327343/82238041-4ce09f00-993f-11ea-9d00-750b5db5ea36.png)

**Comment by Gusted** [comment] 2020-05-18 18:03
I don't get it really, can someone explain it a little bit more in details 😅

**Comment by ey51** [comment] 2020-05-20 12:49
Confluence is What comes with Atlassian's Jira as the documentation platform. You write there in some extended markdown format.

When DarkReader is enabled 
AND You are in editing mode of some page on Confluence, and you add an Info/Warning/Error/Note Panel,
Then the page hangs.
It seems like DarkReader can't handle something with Confluence's Info/Warning/Error/Note Panel when in editing mode.

As soon as you click on this, the tab uses 100% CPU and freezes.
![image](https://user-images.githubusercontent.com/39327343/82447297-c3e97500-9ab0-11ea-9986-40381867fccb.png)

If you are in edit mode on a page that has one of these panels, as soon as you turn on DarkReader, the same happens. the tab uses 100% CPU and freezes.
![image](https://user-images.githubusercontent.com/39327343/82446870-19715200-9ab0-11ea-97d3-56a1d5b72875.png)
![image](https://user-images.githubusercontent.com/39327343/82446889-20986000-9ab0-11ea-9eaf-e2dff9d97910.png)
```
<div class="ak-editor-panel" data-panel-type="info"><span class="ak-editor-panel__icon"><span class="sc-gzVnrw doMcuc" role="img" aria-label="Panel info"><svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M12 20a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-8.5a1 1 0 0 0-1 1V15a1 1 0 0 0 2 0v-2.5a1 1 0 0 0-1-1zm0-1.125a1.375 1.375 0 1 0 0-2.75 1.375 1.375 0 0 0 0 2.75z" fill="currentColor" fill-rule="evenodd"></path></svg></span></span><div class="ak-editor-panel__content"><p><br></p></div></div>
```

View mode (works):
![image](https://user-images.githubusercontent.com/39327343/82446937-33ab3000-9ab0-11ea-9e19-468cc2b5efb3.png)
![image](https://user-images.githubusercontent.com/39327343/82447174-9270a980-9ab0-11ea-8780-595c9fa699f9.png)

```
<div class="ak-editor-panel" data-panel-type="info" style="background: rgb(222, 235, 255);"><span class="ak-editor-panel__icon" style="color: rgb(0, 82, 204);"><span class="sc-gzVnrw doMcuc" role="img" aria-label="Panel info"><svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M12 20a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-8.5a1 1 0 0 0-1 1V15a1 1 0 0 0 2 0v-2.5a1 1 0 0 0-1-1zm0-1.125a1.375 1.375 0 1 0 0-2.75 1.375 1.375 0 0 0 0 2.75z" fill="currentColor" fill-rule="evenodd"></path></svg></span></span><div class="ak-editor-panel__content"><p>&nbsp;</p></div></div>
```

**Comment by Gusted** [comment] 2020-05-20 13:03
Got it!
Can you provide an example link?

**Comment by Myshor** [comment] 2020-05-23 20:41
I will try to mess something in confluence in my daily work on Monday. Most of confluence pages are behing some VPN so I don't know if it will be easy for you Gusted to try.

**Comment by Gusted** [comment] 2020-05-23 20:43
Well it's enterprise so I couldn't do much about it :/

**Comment by Myshor** [comment] 2020-05-23 20:44
I will try to break chrome with infopanel on Monday. :D

**Comment by romansavrulin** [comment] 2020-11-30 09:24
I confirm that page hangs with dark mode on. It is true for both any modern style editor in JIRA, and Confluence editor. Simple copy-paste causes page hang, especially when there's formatting applied to the copied block

**Comment by tedivm** [comment] 2021-02-18 21:04
I'm also seeing this issue.

**Comment by Myshor** [comment] 2021-02-18 22:10
It will be hard to reproduce by me as I work in a project where we are not using confluence.

**Comment by sebekz** [comment] 2021-02-24 11:33
It's still an issue and happens in all of the Atlassian web apps supporting the /info panel feature (Jira, Confluence). @Gusted both Jira and Confluence are free to try in the cloud versions, where the issue can be easily reproduced as explained up above by @ey51 

I will see if I can find time to debug the issue, but I have my hands full at the moment :(

**Comment by Gusted** [comment] 2021-02-24 12:46
> @Gusted both Jira and Confluence are free to try in the cloud versions, where the issue can be easily reproduced as explained up above by @ey51

I will have check soon after I figure this nonsense [terms of services](https://www.atlassian.com/legal/cloud-terms-of-service) on a special note 3.3i which would prevent me from making an possible fix inside's dark reader and say it's for performance improvements and linking it to the issue which would mean I violate that **** term. Hmm I definitely willing to look into it this and see if we can improve and see what's legal, but I don't want their lawyers contacting me.

**Disclamer: IANAL**

**Comment by tirish** [comment] 2021-04-26 17:51
+1 here, causing a glorious tab crash on both Firefox and Chromium Edge. Curious if there are any updates here? I really don't want to have to go back to all-white Confluence pages 🙏

**Comment by Gusted** [comment] 2021-06-03 10:50
Hi, I'm Gusted's dog with a little hint:

When #5949 is merged, I recommend to checkout: https://github.com/darkreader/darkreader#site-fixes and see if the issue is gone. Please don't tell my owner!

Regards,
Gusted's dog.

**Closed by Gusted** 2021-06-03 10:50 UTC
