### ISSUE TITLE
[Bug] Cannot set website to light mode when the url ends with a "["

### ISSUE THREAD

**Issue by longhirar** [darkreader/darkreader#9053] opened 2022-06-09 19:26 UTC
# Bug Report

## Website Address

Any website that ends with "["
http://google.com/aaa[
(it seems that you have to type it in the address bar yourself for it to work)

## Bug Description

The website cannot be turned to light mode if the http path ends with a "["
If the website has already been set to light mode, it will be ignored in the page ending with "["

## Steps To Reproduce

Go to http://google.com/aaa[ (you have to type yourself on the address bar, clicking it will work normally) and try to set the website to light mode.

## Expected Behavior

The website changes to light mode.

## Actual Behavior

The website goes to dark mode, even when you try to set to light mode.

## Screenshots

![image](https://user-images.githubusercontent.com/72895064/172928832-9c1e11aa-77f9-45ae-bdee-4e3d3da1ffcf.png)

![image](https://user-images.githubusercontent.com/72895064/172929031-24adc6c3-a436-475a-a044-c743e054a019.png)

## System Information

- OS: Windows 11
- Browser: Firefox 101.0
- Dark Reader Version: 4.9.51

## Additional Context

When clicking on [this link](http://google.com/aaa[) for example, the bug wont show because you are visiting  /aaa%5B instead of /aaa[
This means you will have to type it yourself on the address bar.

**Comment by Gusted** [comment] 2022-06-11 21:16
Duplicate of #7206 (Same incorrect detection in current code)

**Closed by Gusted** 2022-06-11 21:16 UTC
Labels: bug
