### ISSUE TITLE
[Broken Website] defectivebydesign.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13145] opened 2024-08-17 08:39 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Main page:

Hard to see section.

https://www.defectivebydesign.org/

![image](https://github.com/user-attachments/assets/870c4d3b-0824-4d69-8032-ad88648eb01f)

------------------------------------

In any subpage (such as https://www.defectivebydesign.org/node/2430):

Banner disappears.

Dark Reader ON:
![image](https://github.com/user-attachments/assets/5be7d244-5a64-4d6b-b8fc-2a6923f0d197)

OFF:
![image](https://github.com/user-attachments/assets/c2061c79-20f9-4069-885d-8ecdd13b9566)

--------------------------------

In any page where the background is yellow and it has text (such as 
the top of the page and the footer on https://www.defectivebydesign.org/node/2430):

Text is white, where originally it is black.

![image](https://github.com/user-attachments/assets/75699c44-c20d-4ec8-952b-94cb2d7f93af)

![image](https://github.com/user-attachments/assets/3af2cc1c-7a8c-43a4-a779-14e10975a856)

### Website Address

https://www.defectivebydesign.org/

### Steps To Reproduce

Explained above.

### Operating System

Linux

### Web Browser name and version

Firefox 129

### Dark Reader version

4.9.88

**Comment by Myshor** [comment] 2024-08-18 17:51
Problematic things on https://www.defectivebydesign.org/ added to sitefix.

Video progress bar Invert added to sitefix for separate URL too.

**Comment by Myshor** [comment] 2024-08-18 17:54
P.S. Not touched text on yellow sections as it is readable IMHO. 😋

**Comment by Myshor** [comment] 2024-08-18 18:28
OK... If I break something then it will be your fault! 😈

**Comment by Myshor** [comment] 2024-08-20 18:26
> Black text is not applied to yellow backgrounds in some parts. Example:

It's part of article... Same as article here: https://www.defectivebydesign.org/node/2430

If I set color for article for black it will be not readable at all on subpages.


> One more issue: you can see black backgrounds from the PNGs.

If PNG has white background it will be black after invert... I won't do anything with it. 😝

I will add the "ugly" fix for the footer.

P.S. That's why I didn't touch text colors as they were automaticly generated by Dark Reader. If you want some part of page not touched it's not that easy to say - do not touch it at all. 😋
P.P.S. One more complaining about color text and I will revert everything related to the text color fixes here as I already said: 

> it is readable IMHO

without any text color fixes.

**Comment by Myshor** [comment] 2024-08-20 18:29
Sitefix merged.

If anything else is broken on the site after fixes then remember... It's defective by design. 😈

**Comment by Myshor** [comment] 2024-08-20 20:08
So for the colors I'll think we need leave original Dark reader ones as it will be looking strange.

For the invert I'll take a look tomorrow as I already turned off my PC and I'm commenting from my phone. 😉

Still thinking if I should only revert links color or whole text color fixes.
For me this black one is inconsistent too. 😝

**Comment by Myshor** [comment] 2024-08-21 08:14
For the fix:
- I remove the links red color.
- Change invert selector to include only offenders.
- Add invert to DRM Free picture as it started to be black when selector above was changed.

**Closed** 2024-08-21 08:21 UTC
Labels: Broken Website
