### ISSUE TITLE
[Dynamic] After 4.6.10 new tabs don't render properly

### ISSUE THREAD

**Issue by psofiterol** [darkreader/darkreader#811] opened 2018-11-02 07:33 UTC
Behaviour of new tabs on 4.6.10+:
![4 10](https://user-images.githubusercontent.com/25620559/47955608-4ed44e80-dfa3-11e8-8470-dbfd233f191f.gif)

Behaviour of new tabs on 4.6.9:
![4 9](https://user-images.githubusercontent.com/25620559/47955615-690e2c80-dfa3-11e8-8db5-81bafe0a37d4.gif)

**Comment by alexanderby** [comment] 2018-11-02 08:12
Great bug report, thank you.

**Comment by psofiterol** [comment] 2018-11-03 09:49
Glad I could help. Thanks for developing and maintaining this amazing extension btw!

Regarding this bug, on a closer look I was most likely wrong pinpointing this to 4.6.11. The commit [Perform single dynamic rendering when activating tab](https://github.com/darkreader/darkreader/commit/926ea3fce2709dc976068d1d4e0fbd5e7bd2210f) made just before 4.6.10 was pushed is pretty self explanatory in what it does - exactly what I described.

Previously tabs were already fully rendered before being activated (i.e. when opening them after they have loaded nothing moved/rendered, everything was already done).

I do not know why the change was made (performance, fixing a different bug, etc) but could the old behaviour be restored?

It is perfectly fine having the rendering performed when loading a page on the current tab as the loading itself causes many moving parts on screen. But for links opened in new tabs I strongly prefer/expect them to be fully loaded when I activate them and having nothing moving/rendering right at that moment.

Thanks again!

**Comment by vredesbyyrd** [comment] 2018-11-03 16:53
Can confirm the same behavior with Vivaldi using Darkreader 4.10+. Going back to 4.9 the issue is not present. Thanks for the detailed bug report.

**Comment by psofiterol** [comment] 2018-11-03 18:17
Your comment prompted me to check how to run older versions of extensions (on Firefox) - turns out it's pretty easy.

So I updated the top comment with a head to head comparison of versions 4.6.9 and 4.6.10+ performing the loading of the exact same links on new tabs:

- On 4.6.10+ they appear "ready" very soon but rendering happens on demand when you activate them.
- On 4.6.9 loading takes a lot longer, but when they are "ready" they are actually fully rendered when activated.

As I expressed already in my second comment, I strongly prefer the old approach. I dont't mind having to wait longer for new tabs to load. And them loading rapidly certainly isn't any good if I have to watch the render take place when I open them. I much prefer it being performed "under the hood".

**Comment by vredesbyyrd** [comment] 2018-11-08 01:49
> As I expressed already in my second comment, I strongly prefer the old approach. I dont't mind having to wait longer for new tabs to load. And them loading rapidly certainly isn't any good if I have to watch the render take place when I open them. I much prefer it being performed "under the hood".

Strongly agreed. I would much prefer a fully 'painted' new-tab even if there is a perceived performance cost. That's assuming this bug was the result of a optimization related change, I have not looked into it so I have no idea. 

I spent way too much time over the years hacking at chrome/vivaldi to try and mitigate its own 'white flash' issues, thats finally been resolved. Now this is giving me flash-backs... :)

I am sure this will be fixed soon though. For now I will stay on 4.6.9

**Comment by psofiterol** [comment] 2019-05-12 21:30
So, I'm still on 4.6.9...

I just updated hoping commits [#1](https://github.com/darkreader/darkreader/commit/cd6d688c7c915266a333c959de2ae38a63030de5) and [#2](https://github.com/darkreader/darkreader/commit/0dfb091b5014c038dc7e282c2183983d47118d8b) pushed in early March would fix this issue. Reporting in that it is a lot better, but I still experience flashes in various websites. There are parts of the webpage "transforming" with dynamic filter when I switch to an opened tab as before, but it's now more subtle and it would be ok if it was all dark, but there are still flashes (i.e. at [anandtech.com](https://www.anandtech.com/)).

I still prefer the behaviour prior to commit [#3](https://github.com/darkreader/darkreader/commit/926ea3fce2709dc976068d1d4e0fbd5e7bd2210f), where the webpage is fully loaded in the background and when I move to the tab nothing is "moving".

Any chance we can have that behaviour back, or an option in the add-on preferences to enable it? Since Firefox only holds the last [25 versions](https://addons.mozilla.org/en-US/firefox/addon/darkreader/versions/) of an add-on, there will soon come a time when we lose access to 4.6.9. Please consider adding it as an option in preferences before that happens.

I also miss out on new features such as the new youtube code by holding back due to this, but those flashes are extremely disturbing and force my hand.

Thank you, and keep up the good job!

**Comment by Gusted** [comment] 2020-07-28 14:36
fixed

**Closed by Gusted** 2020-07-28 14:36 UTC
Labels: Dynamic Theme, bug
