### ISSUE TITLE
[Bug] PDF Background and Menus get inverted in Edge, making them light mode instead

### ISSUE THREAD

**Issue by agentmerlot1412** [darkreader/darkreader#7904] opened 2022-01-10 07:22 UTC
# Bug Report

## Bug Description

PDFs when opened in Dark Mode Edge with Dark Reader enabled end up having the background changed to White from Gray, and the same applies to the menu buttons.

## Website Address

Any PDF file.

## Steps To Reproduce

Open any PDF file in Edge, applicable for both local files and web hosted stuff. The extension requires the "Allow access to file URLs" to be enabled from extension settings to work on local files.

## Expected Behavior

It should only invert the PDF (if the PDF isn't already dark by default) instead of inverting the background and the menu buttons too.

## Actual Behavior

Inverts everything indiscriminately, PDF and background and buttons alike.

## Screenshots

Dark Reader enabled:
![image](https://user-images.githubusercontent.com/58659715/148730053-fa1053b0-1610-4498-ab5b-def30351ef10.png)
Dark Reader disabled:
![image](https://user-images.githubusercontent.com/58659715/148730130-637a66cb-7ec1-4c91-a318-209a9450264d.png)

## System Information

- OS: Windows 11 22000.376 (Beta) 
- Browser: Edge 98.0.1108.15 (Dev) 
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment] 2022-01-10 20:41
Duplicate of #3585

**Closed by Gusted** 2022-01-10 20:41 UTC
Labels: bug
