### ISSUE TITLE
[Broken Website] Google Search Engine

### ISSUE THREAD

**Issue by ross-spencer** [darkreader/darkreader#13212] opened 2024-09-03 07:00 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Accessing any navigation tab on Google after searching fails.

 on Ubuntu

### Website Address

google.com

### Steps To Reproduce

1. Access google.com
1. Search
1. For the search results click another tab, e.g. images,
1. Website crashes

### Screenshots

![image](https://github.com/user-attachments/assets/21c8a081-cd3b-4046-be71-dfe7798ff5ca)

### Operating System

Ubuntu 22.x and 24.04

### Web Browser name and version

Google-chromium version 128.0.6613.119 (Official Build) (64-bit)

### Dark Reader version

4.9.89

### Additional Context

This has started happening in the last week. I have since uninstalled (purged) chrome and reinstalled it. 

If there are any debug outputs I can access I can provide these.

**Comment by alexanderby** [comment] 2024-09-03 10:17
I wonder if you receive notifications within the app. This is probably broken in our Manifest V3 build. You should see a link to a blog post in the app's popup window.

**Comment by ross-spencer** [comment] 2024-09-03 11:15
> You should see a link to a blog post in the app's popup window.

Not sure, definitely don't have notifications and couldn't see the link.

That being said, it did prompt me to look at the settings and I just disabled the extension for google.com specifically and that helps as a workaround.

**Comment by alexanderby** [comment] 2024-09-03 15:47
Version 4.9.90 fix a patch should be available now.

Duplicate of #13197.

**Closed by alexanderby** 2024-09-03 15:47 UTC
Labels: Broken Website
