### ISSUE TITLE
[Broken Website] https://bugs.chromium.org/

### ISSUE THREAD

**Issue by davidpanic** [darkreader/darkreader#9860] opened 2022-09-19 13:58 UTC
# Broken Website Report

## Website Address
https://bugs.chromium.org/

## Steps To Reproduce

- Go to the site

## Problematic Observation

- There is black text on a black background when you open a project or issue and the site just looks awful.

## System Information

- OS: Linux
- Browser: Firefox 104.0.2
- Dark Reader Version: 4.9.57

**Comment by shssoichiro** [comment] 2022-09-19 15:38
Same results on Windows 11, same FF and Dark Reader versions.

**Comment by Gusted** [comment] 2022-09-20 11:24
Duplicate of #8850

**Closed by Gusted** 2022-09-20 11:24 UTC
Labels: Broken Website
