### ISSUE TITLE
White flashes in Firefox Quantum

### ISSUE THREAD

**Issue by Gagnef03** [darkreader/darkreader#992] opened 2019-01-10 18:50 UTC
Every time you search for something on Google, or enter a website you get a bright white flash, this doesn't happen on Chrome.

**Comment by Aqa-Ib** [comment] 2019-01-16 09:53
Watch out #512

**Comment by waz0wski** [comment] 2019-01-18 03:19
take a look at shadowfox, it prevents this behavior on pages as well as provides other 'dark mode' benefits to firefox

https://overdodactyl.github.io/ShadowFox/

**Comment by Gagnef03** [comment] 2019-01-20 16:45
> take a look at shadowfox, it prevents this behavior on pages as well as provides other 'dark mode' benefits to firefox
> 
> https://overdodactyl.github.io/ShadowFox/

Thank you for this :D

**Comment by laurentS** [comment] 2019-02-07 14:08
Duplicate of #695 ?

**Closed** 2019-02-08 09:08 UTC
Labels: bug, duplicate
