### ISSUE TITLE
[Broken Website] Miro.com Board Inverted Images

### ISSUE THREAD

**Issue by livejamie** [darkreader/darkreader#9465] opened 2022-08-03 22:18 UTC
# Broken Website Report

## Website Address
https://miro.com

## Steps To Reproduce
- Create a board on miro.com
- Images appear inverted
-->

## Problematic Observation
- Images should appear as they were originally updated
- 
## Screenshots
![image](https://user-images.githubusercontent.com/49513/182721933-de7348e9-a9b6-4c87-a4de-d20217bce31c.png)

## System Information
n/a occurs on every browser

## Additional Context
There have been two previous reports for miro.com #4226 #7254 both were fixed by @Gusted 

I also found a potentially similar issue related to Google Docs in #8730

**Comment by Gusted** [comment] 2022-08-06 20:33
Hi @livejamie!

Could you open the dev tools(ctrl + shift + i) and check if the image is a separate element? I have a feeling that this is part of the canvas as thus not able to fix this issue(similar to https://github.com/darkreader/darkreader/issues/8730)

**Comment by livejamie** [comment] 2022-08-09 17:51
Yeah, seems like it.  

![image](https://user-images.githubusercontent.com/49513/183724677-c767de4d-6082-45cd-8272-33f595cb6013.png)

So this isn't something Dark Reader can handle?

**Comment by Gusted** [comment] 2022-08-09 19:40
> So this isn't something Dark Reader can handle?

Yeah unfortunately not. It's the same situation we currently have with Google docs... So closing as won't fix/duplicate of https://github.com/darkreader/darkreader/issues/8730

**Closed by Gusted** 2022-08-09 19:40 UTC
Labels: Broken Website
