### ISSUE TITLE
An option to change the color of the text.

### ISSUE THREAD

**Issue by zk-g** [darkreader/darkreader#1514] opened 2019-08-22 09:39 UTC

**Comment by jtraub** [comment] 2019-08-22 10:28
Isn't it a duplicate of #650?

**Comment by annoying258** [comment] 2019-08-22 16:11
from https://github.com/darkreader/darkreader/issues/650#issue-346465289

>and text tone/color selector

---

Yep, it is a duplicate. 

The title of #650 is vague, title of #1514 is clear.  I had to read https://github.com/darkreader/darkreader/issues/650#issue-346465289  twice to realise that since its poorly worded.

**Comment by Gusted** [comment] 2020-08-15 11:48
Dup of #650 and has been resolved.

**Closed by Gusted** 2020-08-15 11:48 UTC
Labels: duplicate
