### ISSUE TITLE
[Feature Request] Add an option not to change the scrollbar view to dark mode.

### ISSUE THREAD

**Issue by younyokel** [darkreader/darkreader#9036] opened 2022-06-07 22:41 UTC
# Feature Request
As a user of Windows 11, I think it is necessary to use new interface elements. This includes the scrollbar. On Edge, it works on some websites, but you have to turn on a flag in the settings for it to work everywhere. Dark Reader changes these scrollbars to their own, somewhat old-fashioned. If the devs have free time, it would be nice to have a switch to disable changing the scrollbars.

## Is this feature request related to a problem?

It may not be necessary at the moment, but one day Microsoft will make these scrollbars enabled by default on all websites. Also, Chrome will probably work with the Windows 11 UI elements as well.

## Screenshots

Windows 11's default scrollbars, on Edge:
![image](https://user-images.githubusercontent.com/53343081/172495082-965af3be-a907-44ba-b33b-9465792bf049.png)

**Comment by Gusted** [comment] 2022-06-08 09:43
Duplicate of #8125

**Closed by Gusted** 2022-06-08 09:43 UTC
Labels: enhancement
