### ISSUE TITLE
[Bug] PDF colors when reading

### ISSUE THREAD

**Issue by juanmad** [darkreader/darkreader#10389] opened 2022-11-27 02:44 UTC
# Bug Report

## Website Address
PDF Reading

## Bug Description
When reading PDF files the surrounding background becomes white.

## Steps To Reproduce

When opening any PDF in the browser, dark reader is able to invert the PDF, however for some reason the background which is already black gets inverted to a whiteish color instead of remaining its original color or making it darker.

## Expected Behavior
Invert PDF file content and also the surrounding background to a dark color.

## Actual Behavior
When inverting PDF the surrounding background also gets inverted to a white color.

## Screenshots
![Screenshot from 2022-11-27 03-26-45](https://user-images.githubusercontent.com/11527689/204117087-be5dea8b-e109-49b1-a728-2866847453bb.png)
![Screenshot from 2022-11-27 03-31-05](https://user-images.githubusercontent.com/11527689/204117091-98693f70-7d69-4479-b2d7-fb24516d397b.png)

## System Information
- OS: Linux Mint
- Browser: Brave, Firefox
- Dark Reader Version: Version 5 Preview 4.9.60

## Additional Context
This issue also happens in all browsers and OS I use dark reader, like Brave and Firefox in both Linux and Windows.

**Comment by juanmad** [comment] 2022-11-27 02:50
![Screenshot from 2022-11-27 03-26-45](https://user-images.githubusercontent.com/11527689/204117063-1f8a2a52-1bb8-4a06-bcb1-b346f963ef30.png)
![Screenshot from 2022-11-27 03-31-05](https://user-images.githubusercontent.com/11527689/204117064-a3fcd043-cea2-46a7-ab77-9fb120dff76f.png)

**Comment by Gusted** [comment] 2022-11-27 11:06
Duplicate of #3585

**Comment by Gusted** [comment] 2022-11-27 11:07
> and Firefox

Firefox doesn't use this specific PDF viewer, it would be impossible to see this issue on Firefox. FWIW PDF inversion is totally disabled in Firefox.

**Closed by Gusted** 2022-11-27 11:06 UTC
Labels: bug

**Comment by luo-chuan** [comment] 2024-04-15 18:23
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
