### ISSUE TITLE
[Broken Website] Math equations colored dark in physics.stackexchange.com

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#12025] opened 2023-12-15 15:55 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The math equations are invisible in dark mode as they are colored black.

### Website Address

https://physics.stackexchange.com/questions/456214/semiconductors-insulators-why-is-the-fermi-energy-between-the-valence-and-condu

### Steps To Reproduce

1. Click on website link.
2. Notice that math equations are not legible.

### Screenshots

![Screenshot from 2023-12-15 16-54-46](https://github.com/darkreader/darkreader/assets/59497618/d7ac7027-1f8b-4102-a961-b71a96339348)

### Operating System

Arch linux

### Web Browser name and version

Firefox v120.0.1

### Dark Reader version

4.9.73

**Comment by Myshor** [comment] 2023-12-16 18:51
There was similar issue which is already fixed.

And because I can not reproduce the issue look here:
https://github.com/darkreader/darkreader/issues/12001#issuecomment-1850878597

When you will enable laset site fixes check again if you can still reproduce this issue and come back with the feedback.

**Comment by Myshor** [comment] 2023-12-27 16:46
No comment from 2 weeks and I still can't reproduce problem with newest site fixes. Closing issue.

**Closed by Myshor** 2023-12-27 16:46 UTC
Labels: Broken Website
