### ISSUE TITLE
[Broken Website] ALL of them

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#3540] opened 2020-08-28 20:49 UTC
**Website**
Any website. A good test case is docs.rs, but many MediaWikis have this issue, the AUR, sometimes even GitHub.

**How to Reproduce**
1. Go to a website on Linux Firefox

**Expected behavior**
I want links to be blue, and syntax highlighting to have color, etc. This happens when I toggle on and off Dark Reader

**Actual behavior**
Everything is white

**Screenshots**
![image](https://user-images.githubusercontent.com/4723091/91613713-e8b57a00-e934-11ea-92f6-e585f8284bb8.png)

After toggling Dark Reader, this is how it should look:

![image](https://user-images.githubusercontent.com/4723091/91613789-15699180-e935-11ea-93c7-1f4ce90a27e1.png)

**System info:**
 - OS: [e.g. Windows, MacOS, Linux] Arch Linux
 - Browser: [e.g. chrome, safari] Firefox 80.0 on X11
 - Darkreader Version: [e.g. 4.9.9] 4.9.16
 
**Additional context**
This does not happen on macOS Chrome.

**Comment by Gusted** [comment] 2020-08-28 21:04
Hi @LoganDark!

Let's go trough the standard troubleshooting to understand the cause of this problem.
1. Does it work on normal sites(non MediaWiki related) like Google and YouTube.
2. Could you try creating a additional clean profile to install stock dark reader and have a look at the same sites again.
3. Do you use any custom settings or something for this sites?

Regards,
Gusted

**Comment by LoganDark** [comment] 2020-08-28 21:07
> Does it work on normal sites(non MediaWiki related) like Google and YouTube.

The answer, like MediaWiki sites, is "not always". It doesn't happen every time on MediaWiki, or docs.rs, but those are just the sites off the top of my head where it has happened.

> Could you try creating a additional clean profile to install stock dark reader and have a look at the same sites again.

I installed this OS from scratch just a few weeks ago, and haven't made any customizations to Dark Reader at all, so this is a pretty clean profile already.

> Do you use any custom settings or something for this sites?

Noope.

**Comment by Gusted** [comment] 2020-08-29 10:39
> The answer, like MediaWiki sites, is "not always". It doesn't happen every time on MediaWiki, or docs.rs, but those are just the sites off the top of my head where it has happened.

Okay, when this is the `not always`.
1. Save the page (ctrl + s) zip it(the .html and files folder) and comment it into your next comment.
2. Export the dynamic generated theme, [read more about it here](https://darkreader.org/blog/v4-9-16/)
3. Toggle the extension(on/off) and Export the dynamic generated theme. Now compare the 2 .css files and check if the line count is the same.

> I installed this OS from scratch just a few weeks ago (I believe Aug 3 or so), and haven't made any customizations to Dark Reader at all, so this is a pretty clean profile already. I don't have any userscripts on any of the pages where this happens either, so that can't be the problem either.

I meant Firefox Profile as it could be a custom setting(about:config or about:preferences).

**Comment by Gusted** [comment] 2020-11-14 18:59
Update to 4.9.23 should be fixed.

**Closed by Gusted** 2020-11-14 18:59 UTC
