### ISSUE TITLE
[Broken Website] www.bedbathandbeyond.com (Bed Bad and Beyond)

### ISSUE THREAD

**Issue by craymichael** [darkreader/darkreader#7985] opened 2022-01-18 20:45 UTC
# Broken Website Report

## Website Address
https://www.bedbathandbeyond.com

## Steps To Reproduce

- Go to https://www.bedbathandbeyond.com (dark mode works)
- Click any link
- The next page will have a broken version of dark mode (background is white on all 4 theme generation modes)
- Disable and enable for the site gets dark mode working again

## Problematic Observation

See above. When moving between different pages on the website, the dark mode theme ceases to work. This occurs in both FireFox and Chromium for me.

## Screenshots

![Screenshot 2022-01-18 at 20-42-20 Lamps Floor Table Lamps Bed Bath Beyond](https://user-images.githubusercontent.com/20629897/150015754-d976085c-6639-474e-b15d-aae69c7802e5.png)
![Screenshot 2022-01-18 at 20-42-01 Fire Pits Outdoor Heating Bed Bath Beyond](https://user-images.githubusercontent.com/20629897/150015758-dabbfc3c-ab68-4314-a471-83c56273b29e.png)

## System Information

- OS: Linux
- Browser: Firefox 95, Chromium 96
- Dark Reader Version: 4.9.43

## Additional Context

None.

**Comment by Gusted** [comment] 2022-01-19 17:34
Underlying issue is a duplicate of #4682

**Closed by Gusted** 2022-01-19 17:34 UTC
Labels: Broken Website
