### ISSUE TITLE
[Bug] Settings won't persist anymore

### ISSUE THREAD

**Issue by gabrielfin** [darkreader/darkreader#6873] opened 2021-09-22 22:39 UTC
# Bug Report

## Bug Description
Since last update (4.9.36), whenever I change any setting, close the Dark Reader dialog, and reopen it, the setting is reverted to the previous value.
This did not happen in previous versions (at least in 4.9.34)

## Steps To Reproduce
- Update to latest version (4.9.36)
- Change any setting (reduce brightness for example)
- You'll see that the setting is changed correctly (the brightness is indeed reduced)
- Close the settings dialog
- Reopen the settings dialog

## Expected Behavior
The brightness value should have persisted

## Actual Behavior
The brightness value is shown with the original value

## Screenshots
https://i.imgur.com/ckjBkn0.mp4

## System Information

- OS: Ubuntu MATE 20.04
- Browser: Firefox 92.0
- Dark Reader Version: 4.9.36

## Additional Context
I can reproduce the issue on a clean profile.

I can see the following error in the browser console:
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
index.js:1312
    disconnect moz-extension://07fd650a-7e0d-4a0a-aa37-791aa18fae1c/ui/popup/index.js:1312
```

EDIT: I have just realized that the settings *do* persist, if I immediately close Firefox after changing them (i.e. before opening the settings dialog for a second time)

**Comment by alexanderby** [comment] 2021-09-23 04:39
Hmmm, we have code like this, maybe it's related:
```typescript
// Thunderbird don't has "tabs", and emails aren't 'frozen' or 'cached'.
// And will currently error: `Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved`
if (!isThunderbird) {
    addEventListener('pagehide', onPageHide);
    addEventListener('freeze', onFreeze);
    addEventListener('resume', onResume);
}
```

**Comment by gabrielfin** [comment] 2021-09-23 20:32
I just checked installing the previous version (4.9.35), and I get the same error message, but the settings are correctly persisted. So it seems to be an unrelated error.

**Comment by RedSpid3r** [comment] 2021-09-24 18:06
Having the same issue. Disable DR on a page, then refresh and it's re-enabled itself again

**Comment by judemille** [comment] 2021-09-25 02:49
Same issue here.

**Comment by Gusted** [comment] 2021-09-25 06:19
I havent been able to see any of this behavior since it was reported, so I guess someone have to run a git bisect and find the faulty commit. After that it will be more clear what the problem is and whats causing it.

**Comment by chris-kwl** [comment] 2021-09-25 06:58
The same problem as https://github.com/darkreader/darkreader/issues/6848

**Comment by emarsk** [comment] 2021-09-27 11:01
Same problem here, on both macOS and Windows 10, with latest stable Firefox release (92.0.1).

Dark Reader 4.9.34 works fine.

**Comment by GabeVilela** [comment] 2021-09-29 03:53
Having the same issue with DR 4.9.37.1 and Firefox 92.0.1

_PS: It seems to be an FF related issue, since Vivaldi 4.2.2406.52 (Chromium 93.0.4577.99) and DR 4.9.38 works just fine_ 🤔

**Comment by Gusted** [comment] 2021-09-29 14:43
After fiddling with the code and re-looking the logic I think I was able to find the culprit. I'm currently fixing it and hope it should be fixed over a few hours and do a hotfix for it.

**Comment by alexanderby** [comment] 2021-09-29 14:48
Thank you!

**Closed** 2021-09-29 20:14 UTC
Labels: bug

**Comment by Gusted** [comment] 2021-10-04 12:11
**Update:** Firefox got the 4.9.39 update
