### ISSUE TITLE
[Bug] PDF Navigation Elements are Brightened Instead of Darkened on Brave

### ISSUE THREAD

**Issue by unL33T123** [darkreader/darkreader#8123] opened 2022-02-03 15:52 UTC
# Bug Report

## Website Address

PDFs

## Bug Description

When you have Dark Reader enabled and open a PDF, the PDF content is darkened but the navigation elements are brightened rather than darkened.

## Steps To Reproduce

Open a PDF in Brave with Dark Reader enabled.

## Expected Behavior

PDF content darkened and navigation elements either darkened or ignored.

## Actual Behavior

PDF content darkened, navigation elements brightened.

## Screenshots

PDF with Dark Mode enabled. Note light grey surround.
![Dark Mode Enabled](https://files.catbox.moe/ebnydn.jpg)

PDF with Dark Mode disabled. Note dark grey surround.
![Dark Mode Disabled](https://files.catbox.moe/78qwds.jpg)

## System Information

- OS:  Windows 10 20H2 build 19042.1469
- Browser:  Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)
- Dark Reader Version:  4.9.43

**Comment by Gusted** [comment] 2022-02-03 17:16
Duplicate of #3585

**Closed by Gusted** 2022-02-03 17:16 UTC
Labels: bug
