### ISSUE TITLE
[Broken Website] Google Search

### ISSUE THREAD

**Issue by DAmNRelentless** [darkreader/darkreader#4246] opened 2020-11-23 00:57 UTC
**Website**
https://www.google.com/

**How to Reproduce**
The whole page isn't changed, nothing to reproduce.

**Expected behavior**
I had Dark Reader like a year ago where Google worked just fine.
Now I am using it again and it works everywhere except for this site.

**Actual behavior**
It's unchanged.

**Screenshots**
https://i.imgur.com/ZLZdtDw.png

**System info:**
- OS: Windows 10 20H2
- Browser: Opera GX (Chromium) LVL2 (core: 71.0.3770.323)
- Darkreader: 4.9.24

**Additional context**
I do not have any custom settings, I reinstalled the extension, I don't have any websites blacklisted, I activated the new design of the extension and reset everything in the dev tools.
It literally doesn't work.

**Comment by Gusted** [comment] 2020-11-23 09:24
Hi @DAmNRelentless!

As the Opera gaming browser is only available for Windows it will be hard to reproduce. But I know Opera have issues with installing add-ons from non-Opera store.
- How did you install it?
- Is this issue only specific to google?
- Are their errors/warning in the console tab(ctrl + shift + i)?

Regards,
Gusted

**Comment by DAmNRelentless** [comment] 2020-11-23 13:28
I also tried it on Brave with the same result. I also have a pending issue where the import option doesn't work on the current browser. Seems like Chromium based browsers have issues in general.

*How did you install it?*
I went to the [chrome webstore dark reader page](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) and clicked `Add`.
After that you have to confirm that you really want to install something from the Chrome store.
I did that and then I was installed. I have all my extensions from the Chrome web store and installed them the same way and they work fine.

*Is this issue only specific to google?* 
Afaik, yes. I am browsing quite a lot and only found this issue for Google yet.

*Are there errors/warning in the console?*
Yes, I have 3 errors:
![](https://i.imgur.com/M6i93Dc.png)

Here is the full error log: [www.google.com-1606137917290.log](https://github.com/darkreader/darkreader/files/5583226/www.google.com-1606137917290.log)

And here is the mentioned `browser.js`: https://pastebin.com/x0JQRZ1D

**Comment by Gusted** [comment] 2020-11-23 18:41
Hi @DAmNRelentless!

It doesn't seems to be an issue with the browser.js neither an reason why it doesn't happen on dark reader.
Hmm, if you go to `chrome://extensions` and click on background/index.html 
![image](https://user-images.githubusercontent.com/25481501/100001649-beece180-2dc3-11eb-83d6-e29e7cff88c1.png)
Go to the console tab and load google.com once again.
Does it say something like this
![image](https://user-images.githubusercontent.com/25481501/100001725-d88e2900-2dc3-11eb-830e-5b861dab7f77.png)
`Creating CSS for url`

Regards,
Gusted

**Comment by DAmNRelentless** [comment] 2020-11-23 19:46
![](https://i.imgur.com/HIXOtit.png)
![](https://i.imgur.com/xwdWAhR.png)

**Comment by bishshoy** [comment] 2020-11-23 20:29
Here are some examples of the same website (google) that I am seeing as broken. Version 1.4.0, macOS Catalina 10.15.7,  Safari 14.0.1.

<img width="986" alt="Screen Shot 2020-11-24 at 1 46 45 AM" src="https://user-images.githubusercontent.com/18286974/100011948-7ef42180-2df8-11eb-9b46-13f5a85481fa.png">
<img width="953" alt="Screen Shot 2020-11-24 at 1 46 38 AM" src="https://user-images.githubusercontent.com/18286974/100011951-81567b80-2df8-11eb-95a1-4463c2090887.png">
<img width="1005" alt="Screen Shot 2020-11-24 at 1 46 29 AM" src="https://user-images.githubusercontent.com/18286974/100011954-83203f00-2df8-11eb-9b58-522f445d8ce3.png">
<img width="928" alt="Screen Shot 2020-11-24 at 1 46 20 AM" src="https://user-images.githubusercontent.com/18286974/100011959-83b8d580-2df8-11eb-9154-cb779cdfac58.png">

**Comment by Gusted** [comment] 2020-11-23 21:22
Seems like their is now some error causing in dark reader, it should be fixed #4255

**Comment by Gusted** [comment] 2020-11-25 10:33
https://github.com/darkreader/darkreader/issues/4218#issuecomment-733621009

**Comment by DAmNRelentless** [comment] 2020-11-25 14:51
The initial issue wasn't fixed in 4.9.25.
My Google page is still completely unchanged. @Gusted

**Comment by Gusted** [comment] 2020-11-25 14:52
Then wait for #4255 to be merged

**Comment by alexanderby** [comment] 2020-11-25 15:34
@DAmNRelentless Opera? Go to chrome://extensions page, find Dark Reader and click "Allow for search results".

**Comment by alexanderby** [comment] 2020-11-25 15:40
@bishshoy Please try 1.4.1.

**Comment by DAmNRelentless** [comment] 2020-11-25 15:54
> @DAmNRelentless Opera? Go to chrome://extensions page, find Dark Reader and click "Allow for search results".
Interesting. That fixed it.
Well, seems like the error was discovered by chance at the same time then. Thanks a lot!

**Closed** 2020-11-25 15:55 UTC

**Comment by bishshoy** [comment] 2020-11-25 16:33
The Google search issue is only partially fixed. On some occasions the bug still shows up. It happens when I reload a search results page. It does not happen on the first initial search. It happens only when I reload an existing search page. I have attached a video (in the zip file) below to demonstrate the issue. I am on version 1.4.1 macOS 10.15.7.

[dark_reader_issues_480p.mov.zip](https://github.com/darkreader/darkreader/files/5598002/dark_reader_issues_480p.mov.zip)
