### ISSUE TITLE
Disable darkreader scrollbar in dynamic mode

### ISSUE THREAD

**Issue by maxloh** [darkreader/darkreader#974] opened 2019-01-05 05:06 UTC
In dynamic mode, darkreader use a custom scrollbar in websites.

Is there a option/way to use Chrome's native scrollbar instead of darkreader's one?

If that option is not there, can you consider adding it?

![darkreader darkreader dark reader chrome and firefox extension](https://user-images.githubusercontent.com/35831069/50720518-b4e76a00-10e9-11e9-8682-384f21644f60.png)

**Comment by alexanderby** [comment] 2019-01-05 10:01
Not yet, I think your request is a duplicate of https://github.com/darkreader/darkreader#how-to-contribute https://github.com/darkreader/darkreader/issues/858

**Closed by alexanderby** 2019-01-05 10:01 UTC
