### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by larry77** [darkreader/darkreader#6914] opened 2021-09-25 21:13 UTC
# Broken Website Report

## Website Address
www.paypal.com

## Steps To Reproduce
go to paypal.com
Insert yousername and password
Click next when prompted for a text to your mobile phone to verify your identity

finally you get an error message that something went wring

## Expected Behavior

I expected to simply be able to request a text to my mobile phone to access paypal.
## Actual Behavior

finally you get an error message that something went wring
## System Information

- OS:  Debian 11
- Browser: Firefox 92
- Dark Reader Version: 4.9.37.1

**Comment by Gusted** [comment] 2021-09-26 07:14
Duplicate of #6860

**Closed by Gusted** 2021-09-26 07:14 UTC
Labels: Broken Website
