### ISSUE TITLE
vidiq with dark reader

### ISSUE THREAD

**Issue by zedrood** [darkreader/darkreader#5910] opened 2021-05-29 15:45 UTC
I use two addons together, [vidIQ](https://addons.mozilla.org/en-US/firefox/addon/vidiq-vision-youtube/) is great addons for helping for upload videos in youtube , it's make hard without this addons.
any help for solve this problems ??  this issue https://github.com/darkreader/darkreader/issues/4859 mention that but problem not solve. 
![image](https://user-images.githubusercontent.com/58371257/120075978-c5348100-c0b8-11eb-90ee-d7a2dcdd0c56.png)
![image](https://user-images.githubusercontent.com/58371257/120075991-d087ac80-c0b8-11eb-8234-dbbf1eecfc4c.png)
![image](https://user-images.githubusercontent.com/58371257/120076006-e4331300-c0b8-11eb-829c-633f8039918b.png)
![image](https://user-images.githubusercontent.com/58371257/120076026-f1500200-c0b8-11eb-8674-e91fc7cc3dcc.png)
![image](https://user-images.githubusercontent.com/58371257/120076032-fc0a9700-c0b8-11eb-877b-30c4c4062e2b.png)

**Comment by Gusted** [comment] 2021-05-29 15:46
Please take a "no" for this question. And actually duplicate of #4859

**Closed by Gusted** 2021-05-29 15:46 UTC
Labels: question
