### ISSUE TITLE
[Feature Request] Option to disable/enforce darkreader for websites that has own dark theme

### ISSUE THREAD

**Issue by LB22** [darkreader/darkreader#8135] opened 2022-02-04 11:36 UTC
Some websites have both dark theme and light theme available on their sites.

Applying darkreader to a page that already is styled in a dark theme will often mess the styling up a bit. 

My suggestion is to have two options:
-Strictly enforce darkreader for all pages.
-Enforce darkreader for pages that hasn't been set to use a dark theme specifically. (I personally would want this by default)

To do this, look if the site has a dark theme set and enabled, if so, disable darkreader while on it.
For example, look for something like this: `<html data-theme="dark" style="color-scheme: dark;">`
This would allow websites styled with a dark theme to just use that dark theme the way the developer intended it to be, without darkreader altering it. 

I would imagine it's very rare for a website that has been styled in a dark theme to actually not be dark, hence I see this as a somewhat safe option.

The option to strictly enforce darkreader would just do what darkreader is already doing - apply darkreader to all pages, even those that are already styled dark. This is of course for those that won't take any chances of stupid developers making dark themes that are actually bright, and that would rather have darkreader to be in full control.

Darkreader is an awesome project, recommending it to all my friends :)
Let me know how I can further help contributing.

**Comment by LB22** [comment] 2022-02-04 12:16
I see that there is actually not a default of WHERE to place the data regarding whether it's using a dark theme or not. I see why this could be problematic.

My website: <html data-theme="dark" style="color-scheme: dark;">
Github: <html data-color-mode="dark" data-light-theme="light" data-dark-theme="dark">
Netlify: <body class="tw-dark">

**Comment by Gusted** [comment] 2022-02-05 16:24
Duplicate of #4325

**Closed by Gusted** 2022-02-05 16:24 UTC
Labels: enhancement
