### ISSUE TITLE
[Bug] Can't open addon settings if different useragent string is set on Firefox Android Beta

### ISSUE THREAD

**Issue by CennoxX** [darkreader/darkreader#7442] opened 2021-11-21 23:16 UTC
# Bug Report

## Bug Description
When a different useragent string is set, the addon settings are not accessible. 

## Steps To Reproduce
Set a different useragent string on Firefox Android Beta (open `about:config`, create a string-entry with the title `general.useragent.override` and an Chrome useragent string as content, like `Mozilla/5.0 (Linux; Android 10; POCOPHONE F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36`), now open the addon settings on any website, the addon settings will show `Loading, please wait` and the page will load forever. If the useragent string is reset, the settings are shown again. 

## Expected Behavior
Show the addon settings 

## Actual Behavior
The addon settings will show `Loading, please wait` and the page will load forever. 

## System Information
- OS: Android 10
- Browser: Firefox Android Beta 95.0.0-beta.4 
- Dark Reader Version: Version 5 Preview 4.9.42
(but this has been going on for a while now...)

**Comment by Gusted** [comment] 2021-11-22 08:13
Hi @CennoxX!

Browsers are different, tend to behave differently in edge-cases. Dark Reader hits such cases, luckily per-browser there are workarounds, however these workarounds are guarded by checks, in this case the user-agent. I'm not so sure if this is per se a bug, as this could be seen as expected behavior for having a "incorrect" user-agent - as Dark Reader now treats the environment as a chromium-like one.

Regards,
Gusted

**Comment by wrhou** [comment] 2022-01-28 08:48
I'd like to see this resolved too. That config is meant for websites, not browser extensions.

**Comment by Gusted** [comment] 2022-01-28 09:58
> I'd like to see this resolved too (using desktop Firefox, happens there too). That config is meant for websites, not browser extensions.

I'm sorry but what do you mean with config is meant "for websites, not browser extensions"?

Regardless, I will to close this as "Wontfix" as this is just a technical implementation which is necessary in our codebase. Firefox & Chromium behave differently and we need to change certain things accordingly due to that, nothing that can bypass this.

**Closed by Gusted** 2022-01-28 09:58 UTC
Labels: bug

**Comment by CennoxX** [comment] 2022-01-28 11:54
> nothing that can bypass this
Well there are more reliable methods (https://stackoverflow.com/a/9851769/6743844), but okay.

**Comment by CennoxX** [comment] 2022-01-28 11:54
> nothing that can bypass this
Well there are more reliable methods (https://stackoverflow.com/a/9851769/6743844), but okay.

**Comment by Gusted** [comment] 2022-01-28 13:05
> Well there are more reliable methods

I've had a look at those methods and they seem to use a duck test, "If it walks like a duck, sounds like a duck, acts like a duck, it must be a duck", which can be very inconsistent between versions and future versions of browsers, as most of these are relying on experimental features, which come and go between releases. UA is currently the method to recognize browsers for dark reader as we need to apply workaround and patches for certain applications as it will otherwise not work(hence why you can't open addon settings).

Note: It's really shooting yourself in the foot by using a completely other browser user-agent than the current browser. I'd recommend to use a Addon to do this(which can't conflict to Dark Reader).
