### ISSUE TITLE
[Bug] Dark Reader registers media query listener incorrectly

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9542] opened 2022-08-11 22:43 UTC
# Bug Report

## Website Address
[www.google.com](www.google.com)

## Bug Description
Google search results page does not load completely when Dark Reader is on. The browser then shows an Unresponsive Page window with options to close the page or wait. Turning off Dark Reader or setting the extension to always on (instead of Auto), followed by redoing the search resolves the issue.

## Steps To Reproduce
- Turn on Dark Reader.
- Open a new tab and Google a query (e.g., "adjust ergonomic chair").
- Observe the spinning wheel rotating indefinitely.

## Expected Behavior
Almost instant page load.

## Actual Behavior
Search results are partially shown, but the page load does not complete. This prevent extensions that need the page to be fully loaded from working properly.

## System Information
- OS: macOS
- Browser: Brave [Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (arm64)]
- Dark Reader Version: 4.9.55

**Comment by MahdiNazemi** [comment] 2022-08-11 22:45
Can reproduce the bug on Firefox 103.0.2 as well.

**Comment by Gusted** [comment] 2022-08-12 11:59
Not reproduce-able for me, this only happens when you have the "Auto" option enabled? Which automation settings are you using?

**Comment by MahdiNazemi** [comment] 2022-08-12 16:47
"Auto" and "Toggle dark/light". I can still reproduce the issue on Brave.
Setting the extension to "Off" or "On" resolves the issue. The only problematic case is "Auto."

**Comment by MahdiNazemi** [comment] 2022-08-12 16:50
"Use system color scheme"

**Comment by Gusted** [comment] 2022-08-12 16:52
CC @alexanderby Could you check on your apple laptop if you have similar behavior? I wouldn't be surprised if there's something going wrong just in this specific code path with MacOs.

**Comment by MahdiNazemi** [comment] 2022-08-12 17:03
Downgrading to 4.9.52 resolves the issue.

**Comment by bershanskiy** [comment] 2022-08-12 21:24
@MahdiNazemi Do you have any other extensions installed? Also, I see you use Brave (which is Chromium, but a bit differnt), so could you try to reproduce on Google Chrome?

**Comment by MahdiNazemi** [comment] 2022-08-12 23:58
> @MahdiNazemi Do you have any other extensions installed? Also, I see you use Brave (which is Chromium, but a bit differnt), so could you try to reproduce on Google Chrome?

@bershanskiy, I installed Chrome and ran the same experiment. Please see the attached video and how the "Auto" mode prevents the page from fully loading. I had to compress the video quite a bit, so you may need to zoom in to see all the details.
[Video](https://user-images.githubusercontent.com/11276349/184457947-7fe307ce-e3e5-4479-9c34-bd1bf65f0382.mp4)

I ran `git bisect` as @Gusted had suggested and arrived at #9526 on Brave. I suspect the same would happen on Chrome based on the attached video.

P.S. Would it be possible to release a new version as soon as this issue is fixed? It has made using the extension somewhat annoying.
Thank you 🙏🏼

**Comment by bershanskiy** [comment] 2022-08-13 05:54
@MahdiNazemi Thanks for the video! Unfortunately, I can't reproduce this, the only difference I see is on your video Google displays a full YouTube frame with a video.

Your video:
![image](https://user-images.githubusercontent.com/45960703/184470660-11fae684-056d-4f48-bd86-54d96d410ebd.png)

What I see:
![image](https://user-images.githubusercontent.com/45960703/184470693-81d24d47-5e5b-401f-aff5-1048f5a44fc6.png)

Could you please [build from current `main`](https://github.com/darkreader/darkreader/pull/9526#issuecomment-1213760762)  and test that build?

Also, please open Developer Tools and check if there are any errors in the page (press "F12" and select "Console") and in extension background context (go to `chrome://extensions` and click on "Inspect views background/index.html" and go to "Console"). Thanks!

**Comment by alexanderby** [comment] 2022-08-13 08:14
> CC @alexanderby Could you check on your apple laptop if you have similar behavior? I wouldn't be surprised if there's something going wrong just in this specific code path with MacOs.

Yes, when "Toggle Dark/Light" and "System Automation" is on, the page loads infinitely.

**Comment by alexanderby** [comment] 2022-08-13 08:18
@MahdiNazemi I suggest you to set automation behaviour to "Toggle On/Off" until we find out what's wrong.

**Comment by bershanskiy** [comment] 2022-08-13 08:20
> Yes, when "Toggle Dark/Light" and "System Automation" is on, the page loads infinitely.

Anything in the console or network tab? Also, could you test current `master` to see if #9554 has any effect?

**Comment by alexanderby** [comment] 2022-08-13 08:59
Sorry, already left home, but will try in the evening.

**Comment by MahdiNazemi** [comment] 2022-08-13 13:59
@bershanskiy, thanks for the follow-up. The extension's console is empty, but the browser's console prints a few `net::ERR_BLOCKED_BY_CLIENT` errors, as shown in the attachment:
[www.google.com-1660398811830.log](https://github.com/darkreader/darkreader/files/9331545/www.google.com-1660398811830.log)

A query without videos from YouTube has the correct behavior, e.g., if you search for "ergonomic chair," the page loads without any issues, but searching for "ergonomic chair adjustments," which shows a few videos, leads to the said errors.

**Comment by MahdiNazemi** [comment] 2022-08-13 14:09
@bershanskiy, compiling the latest version from source resolves the issue. I will investigate the other related bugs, i.e., #9540 and #9541, to see if those are also fixed.

**Comment by bershanskiy** [comment] 2022-08-13 14:10
@MahdiNazemi Thanks for the details!

> A query without videos from YouTube has the correct behavior, e.g., if you search for "ergonomic chair," the page loads without any issues, but searching for "ergonomic chair adjustments," which shows a few videos, leads to the said errors.

This is useful to know. Unfortunately, I do not know how to enable these full videos on my end.

> compiling the latest version from source resolves the issue.

Thanks for testing!

**Comment by MahdiNazemi** [comment] 2022-08-13 14:15
You are very welcome!
#9554 also fixes the other two bugs.

**Comment by bershanskiy** [comment] 2022-08-13 14:15
If anyone ever finds a way to make Google Search display full videos like above, please let me know so that I can add a regression test for posterity. I could only find this (but it displays only an image with a link to YouTube.com): https://www.seroundtable.com/google-full-size-youtube-videos-18062.html

**Comment by bershanskiy** [comment] 2022-08-13 14:22
I'm reopening this because we fixed the issue by ignoring extra messages, but there should be a way to avoid these messages in the first place.

**Comment by bershanskiy** [comment] 2022-08-13 14:27
@alexanderby @Gusted The issue with stuck loading was confirmed to to be fixed by #9554 which simply ignores these extra messages. We probably can make a minor release now.

I'll try to find a way to display full videos and reproduce the bug causing extra messages and fix that, but we do not need it for release and I have no ETA on that.

**Comment by bershanskiy** [comment] 2022-08-18 22:18
#9619 might fix this bug, but I'm still looking for a way to test this fix on a system which can reproduce this bug.

**Comment by bershanskiy** [comment] 2022-08-21 10:03
I believe I found the cause of this bug and it was not the YouTube frames as I assumed earlier. We were registering media event listener incorrectly (multiple times instead of once, causing background to hang eventually and not deliver results to the page). I fixed that bug in #9619, but I can not directly test this bug, so I'm leaving it open for now. I would appreciate if you could test the new build from `master` before the next release.

**Comment by MahdiNazemi** [comment] 2022-08-22 03:39
@bershanskiy, I compiled the extension from source and ran the same Google search using Brave. The extension works as expected 👍🏼

**Comment by bershanskiy** [comment] 2022-08-25 07:53
Thanks for testing, the fixed version was already released in all extension stores.

**Closed** 2022-08-25 07:53 UTC
Labels: bug
