### ISSUE TITLE
[Bug] Automation doesn't work on Android Firefox.

### ISSUE THREAD

**Issue by DKMikolajczyk** [darkreader/darkreader#8832] opened 2022-05-05 20:04 UTC
# Bug Report

## Bug Description
Automation doesn't work for Firefox on Android. When I set a specific time range, after reaching the selected time, nothing happens.

## Steps To Reproduce
Just set automation on Android Firefox and wait for a specific time.

## Expected Behavior
Dark mode will turn on after reaching of specific time.

## Actual Behavior
After reaching a specific time nothing happens. But if you will go to the setting and turn off/on automation, the correct mode will turn on.

## System Information

- OS: Android 11
- Firefox 100.1.1 for Android
- Dark Reader Version: 4.9.50

## Additional Context
Hi, automation doesn't work on Firefox for Android, some time ago I reported the bug [https://github.com/darkreader/darkreader/issues/7996](7996), but after this fix, automation still did not work. 

The current behaviour is, for example, I set to start dark mode at 8 pm, after reaching this time dark mode is still disabled, very rarely it turns on after some random time during browsing internet (last time it happened to me after 40 minutes). The same behaviour is when the dark mode is turned on, after reaching 8 am it is still enabled but very rarely it turns off after some random time.

**Comment by Gusted** [comment] 2022-05-05 22:20
Duplicate of #8515

**Closed by Gusted** 2022-05-05 22:20 UTC
Labels: bug
