### ISSUE TITLE
[Broken Website] Published google doc getting black text

### ISSUE THREAD

**Issue by Posese** [darkreader/darkreader#10474] opened 2022-12-13 15:10 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When applying the dark reader filter, the background remains dark grey but the text becomes black. Without dark reader, the background is grey-ish with white text, but all the borders, frames, etc. are bright, so it would still be worth using.

### Website Address

https://docs.google.com/document/d/1OePqvZocw3FYPphmUGQpzExeHPK1J7TBncij3w4cyHc/edit

### Steps To Reproduce

1. Open the webpage
2. Notice how the text is black

### Screenshots

![image](https://user-images.githubusercontent.com/68168745/207370295-3475ade9-0f34-40e4-ab16-c210987f76f8.png)

### Operating System

Windows 10

### Web Browser name and version

Firefox 107.0.1 (64-bit)

### Dark Reader version

4.9.60

**Comment by Gusted** [comment] 2022-12-14 14:07
Duplicate of #8730 (same [underlying issue](https://github.com/darkreader/darkreader/issues/8730#issuecomment-1108952036))

**Closed by Gusted** 2022-12-14 14:07 UTC
Labels: Broken Website
