### ISSUE TITLE
[Feature Request] - Lighter Color Scrollbar on firefox and chrome dark mode

### ISSUE THREAD

**Issue by the123blackjack** [darkreader/darkreader#995] opened 2019-01-11 16:06 UTC
Kudos for implementing the Scroll bark color to align with the overall dark theme , however its not quite visible , i use rescroller for something like below: Dark Background and a light themed scrollbar , 

Please if we would have similar on darkreader itself it would be great.
   
![image](https://user-images.githubusercontent.com/39509137/51045048-14f37a00-15dc-11e9-95b3-5f3ef672c3ff.png)

**Comment by alexanderby** [comment] 2019-01-21 20:57
I think this is a duplicate of https://github.com/darkreader/darkreader/issues/993

Primitive issue to fix.

**Closed** 2019-01-21 20:58 UTC
Labels: bug, duplicate
