### ISSUE TITLE
The font is too light with google translate

### ISSUE THREAD

**Issue by namhbnam** [darkreader/darkreader#860] opened 2018-11-25 07:45 UTC
The font is too light with google translate
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
![image](https://user-images.githubusercontent.com/13607813/48976805-63969480-f0c0-11e8-81d9-494c2ff76a87.png)

**Comment by alexanderby** [comment] 2018-12-06 08:53
Duplicate of https://github.com/darkreader/darkreader/issues/625

**Closed by alexanderby** 2018-12-06 08:53 UTC
