### ISSUE TITLE
[Bug] Dynamic theme editor no longer saves changes

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#6824] opened 2021-09-21 02:04 UTC
# Bug Report

## Bug Description
Regression: Trying to save changes in dynamic theme editor no longer works in v4.9.35

## Website Address
N/A

## Steps To Reproduce
1. Click on devtools in DR UI to edit the dynamic theme
2. Spend 20 minutes of your life making edits
3. Click Apply
4. All edits get reverted
5. Stay calm
6. Breathe deeply
7. Remember to smile

## Expected Behavior
Edits get saved

## Actual Behavior
Edits do not get saved

## System Information

- OS: Windows
- Browser: Firefox 92
- Dark Reader Version: v4.9.35

**Comment by Gusted** [comment] 2021-09-21 06:04
Closing this as this fixed in master #6802 Hotfix will pretty sure be released after we fixed the regression caused by v4.9.35

**Closed** 2021-09-21 06:04 UTC
Labels: bug

**Comment by Gitoffthelawn** [comment] 2021-09-21 06:14
Looking forward to the hotfix.

BTW, not surprisingly, tried this in a new profile, and same regression.

Interestingly, found a workaround in which you can use the "Switch to old version" / "Preview new version" button in devtools to get new edits to not be deleted.
