### ISSUE TITLE
How to set YouTube comment text to white?

### ISSUE THREAD

**Issue by HubKing** [darkreader/darkreader#1622] opened 2019-10-10 12:24 UTC
When I inspect the comment elements, I see the alpha value is set to 50%.
```
#content-text.ytd-comment-renderer {
    color: rgba(255, 255, 255, 0.5);
}
```
So the text is not white but grey. In the "Dev Tools" of Dark Reader, I could find this:
`    --ytd-comment-text-color: ${hsl(0, 0%, 6.7%)} !important;`

but how to set the alpha value to 100%? I have tried changing it to `#FFFFFFFF`, but it did not work.

**Comment by kevinhhuynh** [comment] 2019-10-11 19:06
I added the following outside of the "html:not(.style-scope)" brackets

```
#content-text.ytd-comment-renderer {
  color: #fff !important;
}
```

Seems to be working for me - cheers!

**Comment by HubKing** [comment] 2019-10-11 20:44
Thanks. It worked. I wish the developer would add code that to the extension.

**Comment by RsPlayer** [comment] 2019-10-11 21:09
last week I did a pull request about it and then I closed it because I realised that the problem is only with Firefox. In Chrome the text is already white

**Comment by Gusted** [comment] 2020-07-24 22:20
Copy paste of youtube's CSS and that what dynamic should do. For any style fixes like brighter color use Stylus.

**Closed by Gusted** 2020-07-24 22:20 UTC
