### ISSUE TITLE
[Bug] Automation following system theme keeps reverting to dark

### ISSUE THREAD

**Issue by Terrance** [darkreader/darkreader#9908] opened 2022-09-24 08:30 UTC
# Bug Report

## Bug Description

I'm using Windows and [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) in order to enable my system dark theme on a schedule, and Dark Reader set to follow system in order to inherit that.

Windows is currently set to light theme, and Dark Reader keeps intermittently switching back to its dark theme.  Navigating in another tab seems to make it notice and revert to light again.  I've tried turning automation off and on again, but there's no change there.

Possibly related to #9903 or #9533?

## Steps To Reproduce

1. Enable "system dark mode" automation, and have the system's dark mode disabled.
2. Go to a light theme website (currently observing it on GitHub).
3. Wait a few minutes...
- Dark Reader switches to dark mode by itself.
4. Open another tab and navigate to any website.
- Dark Reader switches back to light mode by itself.

## Expected Behavior

The system dark theme remains off throughout, and so should Dark Reader.

## Screenshots

The resulting state, dark Dark Reader on light Windows:

![Dark Dark Reader on light Windows](https://user-images.githubusercontent.com/4025899/192088760-9f38b1f5-48a4-49f5-9421-19a630b02b85.png)

## System Information

- OS: Windows 10
- Browser: Firefox 106 dev
- Dark Reader Version: 4.9.58

**Comment by bershanskiy** [comment] 2022-09-24 13:11
I can reproduce a very similar bug on Firefox 105, Auto Dark Mode, and Windows 11. Will look into it.

**Comment by bershanskiy** [comment] 2022-09-24 13:15
As an aside, Auto Dark Mode seems to produce bugs with Windows 11 itself when Auto Dark Mode changes color from Light to Dark:
 - this happens to Auto Dark Mode's own UI
   
![image](https://user-images.githubusercontent.com/45960703/192099931-f6c1c4c6-7816-4d43-b9a8-12950749ed4b.png)

 - Windows 11 Settings app displays "Light" in the dropdown
 - Windows 11 Taskbar has black text when it should have changed to white

So there is more than just a Dark Reader bug here.

**Comment by janxkoci** [comment] 2022-11-03 14:41
I see this in Firefox on Linux (elementary OS 6, based on Ubuntu 20.04). The worst offender is Trello (JS-heavy), but last few days it keeps happening a lot even on simple static sites (e.g. made with Github Pages).

**Comment by rafawendel** [comment] 2023-02-09 11:24
Quite the same here, it's been happening for some time now. MacBook Air M1 2020 MacOS 13.2 in Firefox 109.0.1.
For some reason, it doesn't happen in my work MacBook Pro M1 Pro 2021 in Firefox Developer edition evergreen.

**Comment by d3EyedRaven** [comment] 2023-05-04 17:49
Same thing happening for Windows 11 Firefox version 112.0.2. Since 2 weeks for me.

**Comment by st-den** [comment] 2023-05-06 21:28
It's started happening for me for the last week or so (Firefox 113.0 currently) on both Windows and macOS. Pretty randomly for other sites, but there's one particular case I noticed: while using the [Google Container](https://addons.mozilla.org/en-US/firefox/addon/google-container/) add-on, when I open google.com, Dark Reader toggles the correct theme in about 5 seconds. This can be reproduced every time I refresh the tab or open a new one. Not sure what is happening here.

**Comment by Terrance** [comment] 2023-05-07 08:42
@bershanskiy Did anything come up from your earlier investigations?

I know you took issue with Auto Dark Mode before, though that seems to be unrelated given the above reports (and I've also tried running without it and a manual theme switch in Windows -- Dark Reader continues to jump between modes by itself).

**Comment by georgh-** [comment] 2023-05-13 20:51
These might be duplicates:
#11257
#10828
#11264

**Comment by alexanderby** [comment] 2024-04-02 11:25
Works fine for me. Probably this was related to a wake up problem and was fixed by https://github.com/darkreader/darkreader/commit/94760a5cfd9a1af71494ef888833941aa780c10a

**Closed by alexanderby** 2024-04-02 11:25 UTC
Labels: bug

**Comment by Terrance** [comment] 2024-04-02 17:14
This is an old issue and I "worked around" it ages ago by switching to location-based automation, which didn't seem to be affected in the same way but would just disagree in times with Auto Dark Mode by a few minutes.  I'll switch back to following the system theme and see how it goes.

**Comment by janxkoci** [comment] 2024-04-03 10:39
The automated theme switching worked for me for months now, in Firefox on both desktop Linux and mobile Android.

**Comment by alexanderby** [comment] 2024-04-03 11:12
Wonderful, thanks for confirming.

**Comment by Terrance** [comment] 2024-04-03 21:33
Also can confirm I think, had it back on follow system for the last two nights and it seems to be staying consistently dark.

**Comment by b-hayes** [comment] 2024-07-21 22:53
It's still a common issue for me on Chrome on Macos and Windows. My system theme on both systems changes at sunset and sunrise but dark reaer always needs to have the automation turned on and off to detect it.

**Comment by raine** [comment] 2025-02-07 08:52
Same issue on Brave and Mac. Dark Reader does not refresh the system theme status. Clearly a bug.
