### ISSUE TITLE
Google Chart indicators Gets a weird text style with the dark reader applied;

### ISSUE THREAD

**Issue by Tainan404** [darkreader/darkreader#696] opened 2018-08-24 20:08 UTC
Dark reader on:
![with-dark-reader](https://user-images.githubusercontent.com/15806883/44605558-3c2de400-a7c0-11e8-8910-2fe5afcb4aa9.png)

Dark reader off:
![without-drak-reader](https://user-images.githubusercontent.com/15806883/44605578-55369500-a7c0-11e8-8cb3-998df6a2772d.png)

**Comment by krupenja** [comment] 2018-11-02 23:49
This is a duplicate of #552

**Closed** 2018-11-03 13:32 UTC
Labels: Dynamic Theme, bug, duplicate
