### ISSUE TITLE
[Feature Request] Different icon when the site is disabled

### ISSUE THREAD

**Issue by khangly** [darkreader/darkreader#9953] opened 2022-09-29 04:17 UTC
# Feature Request
Basically, show a different icon when the site is disabled. 

## Is this feature request related to a problem?
No

## Screenshots
N/A

## Additional Context

**Comment by Gusted** [comment] 2022-09-29 20:51
Duplicate of #1671

**Closed by Gusted** 2022-09-29 20:51 UTC
Labels: enhancement
