### ISSUE TITLE
[Broken Website] GitHub

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#3979] opened 2020-10-30 09:06 UTC
**Website**
https://github.com/

**How to Reproduce**
- Create an issue or PR
- Comment an issue, PR or commit

**Expected behavior**
Everything is dark

**Actual behavior**
Some things are not

**Screenshots**

![2020-10-30 09_58_58-New Issue · AlexandraKreidich_SwitchGithubAccounts et 12 pages de plus - Personn](https://user-images.githubusercontent.com/21284089/97680565-2c447580-1a97-11eb-96b5-516d1a25beba.png)![2020-10-30 09_59_12-New Issue · AlexandraKreidich_SwitchGithubAccounts et 12 pages de plus - Personn](https://user-images.githubusercontent.com/21284089/97680564-2babdf00-1a97-11eb-960a-9f2f89280e8b.png)
![2020-10-30 09_59_58- BUG  DarkReader sometimes ignores Stylus CSS variable overrides · Issue #3972 ·](https://user-images.githubusercontent.com/21284089/97680563-2babdf00-1a97-11eb-8000-6430d7110e25.png)
![2020-10-30 10_00_32- BUG  DarkReader sometimes ignores Stylus CSS variable overrides · Issue #3972 ·](https://user-images.githubusercontent.com/21284089/97680562-2b134880-1a97-11eb-860e-c0df9af9bb9c.png)
![2020-10-30 10_01_31-Add function to API (#3872) · darkreader_darkreader@8fcbee0 et 12 pages de plus ](https://user-images.githubusercontent.com/21284089/97680561-2b134880-1a97-11eb-932f-23b408d38f8c.png)
![2020-10-30 10_01_45-Add function to API (#3872) · darkreader_darkreader@8fcbee0 et 12 pages de plus ](https://user-images.githubusercontent.com/21284089/97680558-2a7ab200-1a97-11eb-846e-526c8d919ebb.png)

**System info:**
 - OS: Windows & Linux
 - Browser: Chromium-based Brave & Edge
 - Darkreader Version: [e.g. 4.9.9] 4.9.22
 
Thanks

**Comment by Gusted** [comment] 2020-10-30 09:08
Reinstall the extension or restart the browser.

**Comment by KaKi87** [comment] 2020-10-30 09:28
If you're saying it's not a CSS filter issue, then what is it ?
Restarting the browser won't work, and I don't want to reinstall because I would have to rebuild my configuration from scratch.
Thanks

**Comment by Gusted** [comment] 2020-10-30 15:54
It's a css issue. And this is as well a duplicate of the pinned issue #3914. You might update the extension but in most cases it doesn't get a fresh restart theirfor REINSTALLING the extension or Restarting the browser should resolve this issue.

**Comment by KaKi87** [comment] 2020-10-30 16:12
Okay, is there a way to backup and restore the configuration between reinstallations ?
And I retried restarting the browser, and I still got the issue... :/

**Comment by Gusted** [comment] 2020-10-30 16:13
Hi @KaKi87!

It might be another issue...
How does your devtools looks like?
Does it contain ` --color-previewable-comment-form-bg: var(--darkreader-neutral-background) !important;` if you ctrl + F it?

Regards,
Gusted

**Comment by KaKi87** [comment] 2020-10-30 16:18
Yes.
![2020-10-30 17_17_54-DevTools - github com_darkreader_darkreader_issues_3979](https://user-images.githubusercontent.com/21284089/97730269-efe33a80-1ad3-11eb-8f5d-397ff4e9f8ba.png)

**Comment by KaKi87** [comment] 2020-10-30 16:28
It worked, actually without even refreshing the page ! So what happened ?

**Comment by Gusted** [comment] 2020-10-30 16:33
Well it seems like the CSS fix wasn't being applied by Dark Reader I suspect you had Syncronize Site fixes enabled which can cause this in rare cases *not sure, it could be that a old version was being forced due to a error*

**Closed by Gusted** 2020-10-30 16:33 UTC
