### ISSUE TITLE
Dark Reader ineffective on LinkedIn

### ISSUE THREAD

**Issue by insanityfarm** [darkreader/darkreader#792] opened 2018-10-26 17:29 UTC
For some reason, Dark Reader seems unable to do anything on linkedin.com. None of the changes I make for the site have any effect. I even tried installing a Stylish theme in the CSS editor and it did nothing (the same theme works fine when installed with the Stylus extension). Dark Reader, including the CSS editor, works fine for me on other sites, it's just LinkedIn that I'm having trouble with.

I'm using Firefox Developer Edition, version 64.0b4 on macOS 10.14.

**Comment by alexanderby** [comment] 2018-10-29 22:19
Please, check your Site List, maybe Linkedin is there. I will make a Toggle button state more clear.

When using themes from userstyles.org, remove the `@-moz-document { ... }` wrapper, this is invalid CSS, I will make it removing automatically later.

**Comment by insanityfarm** [comment] 2018-10-30 13:49
Good ideas, but I have confirmed that it's not in my site list, and I did remove the wrapper from the CSS as well. I also tried some basic tests like styling elements bright red in my the Firefox dev tools and then creating rules to do the same thing through Dark Reader, but literally nothing I attempt to do with DR has any effect on this site.

**Comment by alexanderby** [comment] 2018-10-30 14:57
Do you have "Only for linkedin.com" button checked? Maybe you should un-check it. Unfortunately the state of current website is not clear, I'm going to display it using a checkbox. For me everything works fine on Linkedin, so I think something is wrong with your settings. Also please have a look in browser's console, maybe there are some errors.
<img width="1276" alt="screen shot 2018-10-30 at 17 55 58" src="https://user-images.githubusercontent.com/9638588/47727246-211e9b00-dc6d-11e8-8fa7-7785de58ae9f.png">

**Comment by alexanderby** [comment] 2018-10-30 22:10
Thank you for the video. I will have to investigate were this Content Security Policy comes from. Looks like the server disables adding stylesheets.

**Comment by abhijitvalluri** [comment] 2019-09-24 06:39
I want to concur with this issue and say I still have the same problem now. Looks like this bug was not fixed or is unfixable due to what Linkedin does on its end. 

Also, I need verify if this is related or not, but after going to Linkedin, I am now unable to get dark mode on any website. Even reinstalling the extension seems to not work.

**Comment by chaitannah** [comment] 2019-10-26 06:30
Hi guys, I am currently facing the same issue on Firefox Quantum (69.0.3) on both my Windows10 and my Ubuntu 18.04
Is there any way I can help resolving this?

**Comment by xqwtsz** [comment] 2020-02-07 09:43
Update:
MacOS: 10.15.2 - Firefox: 72.0.1

Site not in the list.

<img width="1136" alt="Screenshot 2020-02-07 at 10 37 06" src="https://user-images.githubusercontent.com/3916893/74018608-81cf7400-4996-11ea-95f0-02ab9e84ef77.png">

LinkedIn in the list.

<img width="1143" alt="Screenshot 2020-02-07 at 10 37 25" src="https://user-images.githubusercontent.com/3916893/74018622-872cbe80-4996-11ea-821f-dce315820bde.png">

**Comment by Orionsg** [comment] 2020-03-22 08:18
I have the same issue for any pages under www.linkedin.com not being handled by Dark Reader.

 Windows 10, Firexfox 74.0 (64 bit). 

However, when opening LinkedIn pages in the Chrome browser there are no issue, all are rendered in dark colours.

**Comment by fmigneault** [comment] 2020-04-22 20:12
I see the same behavior as @xqwtsz under Firefox 75.0 (64-bit).
Works as expected under Chrome 81.0.4044.122 (64-bit).
Using Windows 10, no specific setting for linkedin.

**Comment by Swivelgames** [comment] 2020-05-12 15:23
@alexanderby @darkreaderdev Any updates on this? Seems to be one of the only sites that doesn't work, which is really unfortunate...

**Comment by Gusted** [comment] 2020-05-12 15:25
Seems like someone is going to create an linkedin account..

**Comment by Gusted** [comment] 2020-05-12 17:48
Didn't get any smarter by profiling it just that Linkedin is also a huge mess with images loading and not capable of some performance in their code.

**Comment by Gusted** [comment] 2020-05-12 18:52
Images are the real bottleneck on linkedin.. Seems like we need to have good look at https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/image.ts and optimize here and their
#2502 is a good begin but only improves around 7 seconds

**Comment by Omar-Os** [comment] 2020-05-16 15:13
Will this ever get fixed ????

**Comment by Gusted** [comment] 2020-05-16 15:17
> Will this ever get fixed ????

Be patient we aren't color wizards :) I created an PR to cache image analysing #2519 that was heavily used by LinkedIn it should Improve a lot on second load and on first load a bit but still not acceptable(first load was with my poor laptop still 1.5x slower than darkreader disabled). 

Darkreader v5 is also in the make I can't just focus on this issue I hope you all understand that.

Regards, 
Gusted

**Comment by Omar-Os** [comment] 2020-05-16 17:55
> 
> 
> > Will this ever get fixed ????
> 
> HI @Omar-Os
> 
> Be patient we aren't color wizards :) I created an PR to cache image analysing #2519 that was heavily used by LinkedIn it should Improve a lot on second load and on first load a bit but still not acceptable(first load was with my poor laptop still 1.5x slower than darkreader disabled).
> 
> Darkreader v5 is also in the make I can't just focus on this issue I hope you all understand that.
> 
> Regards,
> Gusted

It's just the only website I know that doesn't work with DarkReader at all !
Also it doesn't work with Instagram, I have to disable and enable DarkReader to make it work on Instagram every single time!
These 2 websites are two of the most visited websites on the internet! Just saying..

**Comment by Gusted** [comment] 2020-05-16 17:59
> It's just the only website I know that doesn't work with DarkReader at all !
> Also it doesn't work with Instagram, I have to disable and enable DarkReader to make it work on Instagram every single time!
> These 2 websites are two of the most visited websites on the internet! Just saying..

I'm sorry but can you check if you use the latest version of darkreader as we have fixed Instagram and LinkedIn a while ago and they work great especially Instagram is doing fine. LinkedIn is just slow atm where's being worked on. For your next reply 1 tip we aren't wizards and don't use overuse of '!'

**Comment by Omar-Os** [comment] 2020-05-16 18:05
> 
> I'm sorry but can you check if you use the latest version of darkreader as we have fixed Instagram and LinkedIn a while ago and they work great especially Instagram is doing fine. LinkedIn is just slow atm where's being worked on. For your next reply 1 tip we aren't wizards and don't use overuse of '!'

I'm using DarkReader v4.9.8 with Firefox 76.0.1

**Comment by Gusted** [comment] 2020-05-16 18:07
> I'm using DarkReader v4.9.8 with Firefox 76.0.1

Then open a seperate issue

**Comment by aogier** [comment] 2020-05-16 19:12
@Omar-Os please stop polluting this space with frustrations that, understandable though they may be, certainly don't help if they become a goad for developers that you don't seem to be helping in any way other than insisting on how much this bug disturbs you. Every user is indeed impacted by this issue, but as you can see no one is being toxic like that. Cmon

**Comment by fmigneault** [comment] 2020-05-16 19:41
Adding more detail to my previous https://github.com/darkreader/darkreader/issues/792#issuecomment-618013979. 
Using DarkReader 4.9.8
Side-by-side view Chrome 81.0.4044.138 (64-bit) | Firefox 76.0.1 (64-bit).
Issue is clearly specific to Firefox (maybe others too, not tested).

![image](https://user-images.githubusercontent.com/19194484/82128711-16fab980-978b-11ea-81c9-457501c6c11c.png)

**Comment by Omar-Os** [comment] 2020-05-16 19:50
> 
> 
> @Omar-Os please stop polluting this space with frustrations that, understandable though they may be, certainly don't help if they become a goad for developers that you don't seem to be helping in any way other than insisting on how much this bug disturbs you. Every user is indeed impacted by this issue, but as you can see no one is being toxic like that. Cmon

Me being toxic ?? Are you sure it's me? 😂
Also this issue is almost 2 yeas old now so.....

**Comment by Omar-Os** [comment] 2020-05-16 19:51
> 
> 
> Adding more detail to my previous [#792 (comment)](https://github.com/darkreader/darkreader/issues/792#issuecomment-618013979).
> Using DarkReader 4.9.8
> Side-by-side view Chrome 81.0.4044.138 (64-bit) | Firefox 76.0.1 (64-bit).
> Issue is clearly specific to Firefox (maybe others too, not tested).
> 
> ![image](https://user-images.githubusercontent.com/19194484/82128711-16fab980-978b-11ea-81c9-457501c6c11c.png)

That mean they don't care about Firefox !
If I'm using Edge or Chrome I would be using the force dark mode option and won't be needing the slow DarkReader !

**Comment by Gusted** [comment] 2020-05-16 19:58
Well @Omar-Os As I need to hold some proffesional here and speak from Dark Reader.
I say this once and polite please don't react to this issue anymore and get your ass out of this terrain and come back when you learned manners, thank you.



> Adding more detail to my previous [#792 (comment)](https://github.com/darkreader/darkreader/issues/792#issuecomment-618013979).
> Using DarkReader 4.9.8
> Side-by-side view Chrome 81.0.4044.138 (64-bit) | Firefox 76.0.1 (64-bit).
> Issue is clearly specific to Firefox (maybe others too, not tested).
> 
> ![image](https://user-images.githubusercontent.com/19194484/82128711-16fab980-978b-11ea-81c9-457501c6c11c.png)

Quite Intresting! Seems like it pursuits on Firefox, the orginal bug. Thank you for reporting this as I hadn't checked on Firefox Yet 😅

**Comment by Gusted** [comment] 2020-05-16 19:58
> Adding more detail to my previous [#792 (comment)](https://github.com/darkreader/darkreader/issues/792#issuecomment-618013979).
> Using DarkReader 4.9.8
> Side-by-side view Chrome 81.0.4044.138 (64-bit) | Firefox 76.0.1 (64-bit).
> Issue is clearly specific to Firefox (maybe others too, not tested).
> 
> ![image](https://user-images.githubusercontent.com/19194484/82128711-16fab980-978b-11ea-81c9-457501c6c11c.png)

Quite Intresting! Seems like it pursuits on Firefox, the orginal bug. Thank you for reporting this as I hadn't checked on Firefox Yet 😅

**Comment by Omar-Os** [comment] 2020-05-16 20:01
> 
> Quite Intresting! Seems like it pursuits on Firefox, the orginal bug. Thank you for reporting this as I hadn't checked on Firefox Yet 😅

I literally said the issue is on Firefox but my comment was ignored... but this one is interesting somehow.. wow !

**Comment by fmigneault** [comment] 2020-05-16 23:30
@Omar-Os  
It's not like they are ignoring your comment or purposely ignoring Firefox... It's just impossible for one dev to have tested every combination. Also, just pressing them to fix it quickly without more insight or guidance, or being straight up negative about their software doesn't help at all nor speeds up fixing the problem. This is not a customer service or tech support forum to share your feelings about the program, it's about helping them fix a known problem with constructive information. 

Speaking from software dev's perspective, being one myself, when submitting issues, you need at least to provide some kind of detail to help identify the source of the bug. My comment is simply more relevant as I explicitly demonstrated the unwanted behavior so they can actual know what is not working well.

**Comment by Omar-Os** [comment] 2020-05-17 10:51
> 
> 
> Also, just pressing them to fix it quickly without more insight or guidance, or being straight up negative about their software doesn't help at all nor speeds up fixing the problem. This is not a customer service or tech support forum to share your feelings about the program, it's about helping them fix a known problem with constructive information.

This is literally what's this page about, all the info they are in here and they know it and know how to fix it, they said that too.

**Comment by Gusted** [comment] 2020-05-17 11:04
> know how to fix it, they said that too.

Well you say 'they' I think your than referring to me and Alexander. Well we have here and their fixes but that was after long researching the problem and understanding why it got caused. I don't know why Firefox is now broken if I see somethings broken I can't just see from the text or a picture why :) I'm not a wizard. 
I simply don't know why this is caused I only knew that analyzing images were slow and that's is fixed(When PR is merged) but the first load is still slow and I don't know why that yet. 





> > Also, just pressing them to fix it quickly without more insight or guidance, or being straight up negative about their software doesn't help at all nor speeds up fixing the problem. This is not a customer service or tech support forum to share your feelings about the program, it's about helping them fix a known problem with constructive information.
> 
> This is literally what's this page about, all the info they are in here. 

This is an issue page to report a issue and give information on it not to ask things like if this ever will get fixed we are doing our best but their are another 600 issues that also wants to get fixed. 
Let me explain what an issue page is:
1. Someone reports a issue 
2. A person looks into it 
3. A fix is being made or their will be questions asked by the developer for more information 
4. The issue is being closed or put on hold as it takes a long time and it's a big issue. 
5. After a time you take a look with a fresh mind and see the problem
6. Issue is being solved 

What your referring to is a customer service to be toxic to and say you require immediate help Well they don't do much other than create a issue and help the next person. 
Or a tech support forum that is mainly used by users and not for developers(mostly) and ask questions about it and discuss about the program. Not to fix issues either :) 

Regards, 
Gusted

**Comment by Gusted** [comment] 2020-05-17 12:26
> Adding more detail to my previous [#792 (comment)](https://github.com/darkreader/darkreader/issues/792#issuecomment-618013979).
> Using DarkReader 4.9.8
> Side-by-side view Chrome 81.0.4044.138 (64-bit) | Firefox 76.0.1 (64-bit).
> Issue is clearly specific to Firefox (maybe others too, not tested).
> 


I also tested it with stock darkreader from addon store 4.9.8 and Firefox 76.0.1 (64-Bit) But it seems like it could be an another issue
![](https://i.imgur.com/mmkeslo.png)
I suggest to allow darkreader to be in private window and check again with linkedin(Without any other addon's that are allowed in private of course) and check the console for any errors...

**Comment by fmigneault** [comment] 2020-05-17 23:26
When I reload LinkedIn page with private and only DarkReader enabled, the page appears blackish with only the LinkedIn logo in the center for a brief moment. Then, when the page fully loads, it reverts to "normal" style. 

Seems to have problem loading the styles. 
See `style sheet could not be loaded` as well as the multiple warnings related to contrast.
I got somewhat limited knowledge about style sheets, but I know it's a mess to support all platform variations. Seems MS might be at cause here.

![image](https://user-images.githubusercontent.com/19194484/82162601-c1e6a280-9873-11ea-99d5-4eab3778cfa4.png)

**Comment by fmigneault** [comment] 2020-05-17 23:39
I'm definitely seeing warnings related to `style-src`.

![image](https://user-images.githubusercontent.com/19194484/82162910-d3c94500-9875-11ea-9e2b-edecfc8f859f.png)

I don't know if it's related, but I sometime see the same message as in this PR: https://github.com/darkreader/darkreader/commit/632d74d307427108fcacdab2bdf11d90e39f01be

**Comment by Gusted** [comment] 2020-05-18 11:38
More CSP smh.
I tought it got fixed but I will see what it's causing.

@fmigneault Do you see any trace of darkreader in the HTML of the site?

**Comment by fmigneault** [comment] 2020-05-19 22:53
@Gusted Doesn't seem like it. It looks like after the site refreshed, any style gets dropped.

**Comment by Gusted** [comment] 2020-05-20 08:13
> @Gusted Doesn't seem like it. It looks like after the site refreshed, any style gets dropped.

@fmigneault Can you try with a fresh new firefox profile or something and try a fresh darkreader maybe something is messed up in current settings.

**Comment by fmigneault** [comment] 2020-05-20 14:37
@Gusted 
Oh! Retried with another Firefox account and it worked. I have absolutely no clue why it works on one side and not the other... 
I can definitely see that the difference is all the `-ms-[...]` definitions that are not resolved correctly.
I have tried reinstalling it completely on the side it's not working but still produces the same result. I'm not too sure what to do to fix the issue in this case.

![image](https://user-images.githubusercontent.com/19194484/82458669-f8dfd280-9a84-11ea-9e26-fcca70a0ffea.png)

**Comment by Gusted** [comment] 2020-05-20 14:41
> @Gusted
> Oh! Retried with another Firefox account and it worked. I have absolutely no clue why it works on one side and not the other...
> I can definitely see that the difference is all the `-ms-[...]` definitions that are not resolved correctly.
> I have tried reinstalling it completely on the side it's not working but still produces the same result. I'm not too sure what to do to fix the issue in this case.
> 
> ![image](https://user-images.githubusercontent.com/19194484/82458669-f8dfd280-9a84-11ea-9e26-fcca70a0ffea.png)

Well pff at least not something with darkreader, but it's resolving -ms correctly that's weird behaviour that's maybe I couldn't reproduce it as mine profile resolved it okay. 
Seeing from the script where it comes from it's not an darkreader related issue as we use index.js and not giberish names. Well maybe they is something wrong in your old/current profile that caused this.

Regards,

Gusted

**Comment by fmigneault** [comment] 2020-05-20 18:04
Is there some cache that would need to be cleaned up?
I have tried reinstalling DarkReader completely and also removed cached site data. 
There must be some setting somewhere that causes this, but I really cannot identify it.

**Comment by Gusted** [comment] 2020-05-20 18:08
Well if a new profile works it sure must be something in the profile folder.

**Comment by Gusted** [comment] 2020-05-22 15:23
Hi guys!

Well the main issue that had been reported that it didn't styled at all is already fixed a while ago alongside optimizations. Only thing to speed up for low-end laptops/pc is analyzeImage but that's another story not related to this issue. So I will close this issue a monday If I don't hear any other problems(that aren't comfirmed fixed) for this issue if it's related to performance it's being worked on and not tracked trough this issue. If your problem is with latest version of Dark reader and it doesn't style or doesn't style correctly linkedin that it's the right problem to be posted here otherwise if not performance feel free to open a new Issue.

Have a nice weekend!

Regards,
Gusted

**Comment by xqwtsz** [comment] 2020-05-22 18:29
> Oh! Retried with another Firefox account and it worked. I have absolutely no clue why it works on one side and not the other...

Does not work for me with a fresh a Firefox account + a fresh darkreader.

**Comment by Gusted** [comment] 2020-05-22 18:31
> Does not work for me with a fresh a Firefox account + a fresh darkreader.

Any errors in console or trace in devtools of dark reader? You can try to install another edition of firefox to be sure as Firefox account still can have underlaying links.

**Comment by xqwtsz** [comment] 2020-05-22 18:52
![Annotation 2020-05-22 203456](https://user-images.githubusercontent.com/3916893/82700126-e674bd00-9c6d-11ea-9ffc-519ce81dc466.png)

So here is the console with my normal setup.

I just tried on another machine now with a fresh Firefox with no Firefox Account and fresh darkreader, it worked.

This is really weird. How can a Firefox Account have anything to do with what darkreader can or cannot do?

**Comment by Gusted** [comment] 2020-05-22 18:55
1. Anything that could be related in any way is browser.storage.sync <- From what I know of the codebase this storages our settings into sync so when you reinstall it have the same settings.
2. Linkedin use some secret code :) *Conspiracy*
3. Firefox is being Firefox and does something we don't know of. *Yet*

**Comment by xqwtsz** [comment] 2020-05-22 19:04
So I just checked my `Browser Privacy` options for Firefox.

I had the following settings:

![Annotation 2020-05-22 210207](https://user-images.githubusercontent.com/3916893/82700957-8252f880-9c6f-11ea-8851-b8284de6b9c5.png)

After changing to **_Standard_** _voila_ darkreader works on linkedin again. I cant believe I did not try that before.

Anyway if someone with the same issue wants to confirm that this fix also works for them, would be great.

**Comment by Gusted** [comment] 2020-05-22 19:10
Can confirm that this is was most likely the problem with current people. Well as this isn't out of the box I will see if can determine the issue, but not put of the box so low priority alongside school.

**Comment by fmigneault** [comment] 2020-05-22 23:54
@xqwtsz @Gusted 
I tried the above switch to 'standard' and it worked. Very nice find 👍 
Probably it resets some value somewhere as I can switch back to 'custom' and it still works after.

**Comment by Gusted** [comment] 2020-05-29 23:00
Closing issue as Linkedin styles again on fresh profile customized privacy settings are not supported? apperantly but is probably a bigger problem than just a focus on LinkedIn. It styles correctly performance is being worked on if not mostly already fixed in last version.

**Closed by Gusted** 2020-05-29 23:00 UTC
Labels: bug
