### ISSUE TITLE
[Broken Website] kamudankariyer.com - Not darkened

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8385] opened 2022-03-07 19:15 UTC
# Broken Website Report

## Website Address
http://www.kamudankariyer.com/meb-tarafindan-1-588-sozlesmeli-destek-personeli-pozisyonuna-alim-yapacak-6660h.htm

## Screenshots

**Enabled, but not darkened..**
![Screenshot_221238_2022-03-07](https://user-images.githubusercontent.com/15933805/157102063-c6b1c5a5-a668-4189-8707-1a09e1a0e4dc.png)

## System Information

- OS: Windows 10
- Browser: Firefox 98
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment] 2022-03-07 21:55
Duplicate of #5937

**Closed by Gusted** 2022-03-07 21:55 UTC
Labels: Broken Website
