### ISSUE TITLE
[Broken Website] pixai.art in FF Nightly

### ISSUE THREAD

**Issue by Sneffel** [darkreader/darkreader#11321] opened 2023-05-26 07:46 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

pixai.art has completely broken for the last circa 10 FF Nightly versions. Disabling the darken option in the menu doesn't work, I have to fully disable the add-on, otherwise the website is unusable.

### Website Address

https://pixai.art/

### Steps To Reproduce

1. [Install Firefox Nightly ](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)
2. [Install Dark Reader](https://addons.mozilla.org/firefox/addon/darkreader/) for Firefox
3. Go to [pixai.art](https://pixai.art/) (graphics are broken)
4. Create account or login (graphics are broken)
5. Click generate (graphics are broken)

### Operating System

Edition	Windows 10 Pro 
Version	22H2 
Installed on	‎17/‎10/‎2022 
OS build	19045.2965 
Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Web Browser name and version

Firefox Nightly 115.0a1 (2023-05-25) (64-bit)

### Dark Reader version

4.9.63

**Comment by jxn-30** [comment] 2023-05-26 20:49
Other examples where this happens too:
* https://hub.docker.com/
* https://www.dictionary.com/browse/based

This seems to be more a Firefox-Nightly issue than a Dark-Reader one and it is already tracked on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1834786

**Comment by tukusejssirs** [comment] 2023-05-27 10:11
While it indeed seems to be an issue of Firefox Nightly, I just want to say that I am affected by this bug too and besides dictionary.com, it fails to work on any and all Grafana instances. Here’s a public demo server → https://play.grafana.org/d/000000012/grafana-play-home?orgId=1. I think when Mozilla fixes this, Dark Reader should add a test that the reported websites work as expected.

**Comment by tukusejssirs** [comment] 2023-05-29 07:37
A user at [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1834786#c7) found a workaround: simply disable `layout.css.inline-style-caching.always-enabled` in `about:config`. I can confirm that this works around this issue on FF Nightly 115.0a1 (2023-05-27) (64-bit).

I might be wrong, but it seems to me like Dark Reader needs to support inline styles in order to make this work even when `layout.css.inline-style-caching.always-enabled` is enabled.

**Comment by SuperTux88** [comment] 2023-05-29 15:13
The bug got fixed in the latest nightly (2023-05-29) and I was able to revert `layout.css.inline-style-caching.always-enabled` back to default.

And so I think this can also be closed now.

**Comment by tukusejssirs** [comment] 2023-05-30 07:52
I can confirm that all four websites mentioned in this issue are working as expected after the latest FF Nightly update.

**Closed** 2023-05-31 09:55 UTC
Labels: Broken Website, External dependency
