### ISSUE TITLE
[Bug] System color theme not always updating

### ISSUE THREAD

**Issue by ThomasOrlita** [darkreader/darkreader#8828] opened 2022-05-04 10:35 UTC
# Bug Report

## Bug Description
The system theme detection is done using the `prefers-color-scheme` media query. If it changes, the `onChange` listener is fired.

https://github.com/darkreader/darkreader/blob/master/src/inject/utils/watch-color-scheme.ts

This works fine when the system theme change is done while the extension is active. If it is scheduled to change automatically when the device is not used (for example via [Windows Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)), it seems that the theme change is not registered.

## Steps To Reproduce
1. Enable "Use system color scheme" in Dark Reader
2. Schedule the system theme change to happen when the device is not used (not sure when this happens exactly)

## Expected Behavior
Dark Reader matches current system theme

## Actual Behavior
Open Dark Reader and observe it is On even when the system theme is light (or vice versa)

## System Information
- OS: Windows 10
- Browser: Chrome 100
- Dark Reader Version: 4.9.48

## Additional Context
Additional color theme changes are registered once the device is used. I am not sure if this is an issue with  Chrome or this Chrome extension. It seems to happen occasionally. Other system apps do not suffer from this issue.

**Comment by scottrpaterson** [comment] 2022-05-04 20:28
Where is the Use system color scheme setting located? Not seeing it.

**Comment by Gusted** [comment] 2022-05-04 23:44
Duplicate of #7041 (Events not registered after suspend)

**Closed by Gusted** 2022-05-04 23:44 UTC
Labels: bug
