### ISSUE TITLE
[Broken Website] NPM Runkit

### ISSUE THREAD

**Issue by Revadike** [darkreader/darkreader#5103] opened 2021-02-21 01:21 UTC
# NPM Runkit

## Website
https://npm.runkit.com/

## How to Reproduce
  - Go to the site
  - See that the sandbox environment isn't loading

## Expected behavior
The sandbox environment (where you put in your node.js code) should be loading

## Actual behavior
It is not loading

## Screenshots
![image](https://user-images.githubusercontent.com/4411977/108612680-3514da80-73eb-11eb-88a0-a089b839e0b7.png)
![image](https://user-images.githubusercontent.com/4411977/108612693-4b229b00-73eb-11eb-8eaa-fbfd9e053455.png)

## System Information

- OS: Windows
- Browser: Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
- Dark Reader Version: 4.9.27

## Additional context
N/A

**Comment by Trunks8257** [comment] 2021-03-24 15:05
same on firefox

**Comment by simon-pct** [comment] 2021-05-23 15:32
duplicate of #2420

**Closed** 2021-05-23 15:33 UTC
Labels: Broken Website

**Comment by Revadike** [comment] 2021-05-23 16:24
Not sure why it needs closing when the issue is unresolved.

**Comment by Gusted** [comment] 2021-05-23 16:25
This is a duplicate issue.
