### ISSUE TITLE
The newest version breaks a lot of websites

### ISSUE THREAD

**Issue by d4f5409d** [darkreader/darkreader#5439] opened 2021-04-02 18:14 UTC
The latest version (published on April 1, 2021) breaks a lot of websites. Mastodon, Protonmail, etc.

Additional informations:
OS: Windows
Browser: Mozilla Firefox
Browser version: Latest (88.0b6)
Dark reader version: Latest (4.9.30)

I had to reinstall 4.9.29, because the previous version isn't breaking any of these sites.

**Comment by shaneutt** [comment] 2021-04-02 18:20
I'm having similar experiences: https://github.com itself is freezing a lot and Firefox is pointing the finger at Darkreader, I had to disable the addon to get here to report, I'll downgrade to `v4.9.30` to work around it for now.

**Comment by Harshsrcc** [comment] 2021-04-02 19:25
Same issue. Same Environment as @d4f5409d . Haven't tested on many sites, but css for reddit.com is definitely broken. Many website elements are white. 

![1](https://user-images.githubusercontent.com/75267713/113447303-33412c80-9417-11eb-8f8c-a387f04b4771.png)

**Comment by ColinVT** [comment] 2021-04-02 23:53
I'm having the same problems, also windows, also firefox. Seeing issues (boxes -- ember-paper cards specifically among other elements -- have turned white that were previously dark) on our own site which I am 100% positive has not had any changes made to it in 2 weeks.

**Comment by vipulgupta2048** [comment] 2021-04-03 09:43
Same, Firefox and Chrome both complain about Dark Reader slowing down the website load.

**Comment by Gusted** [comment] 2021-04-03 10:56
Hello everyone!

We are aware of the problems and where expected with this release due new behavior that might break some sites but fixed a lot of sites. Thereby unknowingly came an performance problems For the ones interested([Firefox's profiler](https://profiler.firefox.com/public/rpkcsw90fr02jxqqchha3y1fc9jqf3y51c1w1x8/flame-graph/?globalTrackOrder=9-10-0-1-2-3-4-5-6-7-8&localTrackOrderByPid=114547-5-0-1-2-3-4~232342-0~328919-0~&thread=13&v=5)).

This thread can be developed for sites that got broken(visualized) and not for performance problems. Please open an new issue about(kind of mega-thread) for reported website with noticeable slowdowns(github.com confirmed) and not your average _Oh just 0.5 seconds slowdown this isssss baddddd fIx It!!_.

For the now reported website, I'd like some more information for it. E.g. an link where I can see it goes wrong so an CSS fix can be made for it.

Thank you all for reporting!

Regards,
Gusted

**Comment by Harshsrcc** [comment] 2021-04-04 10:12
@Gusted This page for ex: https://www.reddit.com/r/uBlockOrigin/comments/mjp4c6/is_using_umatrix_ublockorigin_in_easy_mode_with/

**Comment by Gusted** [comment] 2021-04-04 11:11
> @Gusted This page for ex: https://www.reddit.com/r/uBlockOrigin/comments/mjp4c6/is_using_umatrix_ublockorigin_in_easy_mode_with/
> or this:
> https://www.reddit.com/r/uBlockOrigin/comments/mhli5s/twitch_once_again_has_modified_something_to_get/
> or this:
> https://www.reddit.com/r/firefox/comments/mjt7u2/firefox_ram_usage/

Do you have any special scripts? CSS? Add-ons? For reddit. I don't get any problems with it.

**Comment by Harshsrcc** [comment] 2021-04-04 12:51
> > @Gusted This page for ex: https://www.reddit.com/r/uBlockOrigin/comments/mjp4c6/is_using_umatrix_ublockorigin_in_easy_mode_with/
> > or this:
> > https://www.reddit.com/r/uBlockOrigin/comments/mhli5s/twitch_once_again_has_modified_something_to_get/
> > or this:
> > https://www.reddit.com/r/firefox/comments/mjt7u2/firefox_ram_usage/
> 
> Do you have any special scripts? CSS? Add-ons? For reddit. I don't get any problems with it.

So, I had uBlockOrigin enabled, along with Drak Reader. Just to be sure, I disabled it, cleared browser cache, and visited the first link again. I still get the same issue

I've tested on 6 browsers: 
1. Chromium (91.0.4442.0)
2. Edge Chromium Dev (91.0.838.3)
3. Firefox Dev (88.0b6)
4. Firefox Nightly (89.0a1)
5. Firefox Android Beta
6. Firefox Android Nightly

All barebone browsers. No script, No CSS, No Addons (except Dark Reader). 

I'm including Screenshots for Chromium and Edge Chromium. Can't for Firefox, since I reverted back to 4.9.29 on it.

![4](https://user-images.githubusercontent.com/75267713/113509316-87acef00-9572-11eb-8f9b-9abeebc12a35.png)
![5](https://user-images.githubusercontent.com/75267713/113509322-8c71a300-9572-11eb-82a7-54bc73d604cf.png)

**Comment by Gitoffthelawn** [comment] 2021-04-05 09:58
Please report performance issues here: https://github.com/darkreader/darkreader/issues/5471

Thanks!

**Comment by alexanderby** [comment] 2021-04-05 10:27
Hello, version 4.9.31 with a fix should be already available. Please check it out.

We've found a performance bottleneck in Firefox and will soon report it. Please share the links to websites that still work slower or look worse than before.

**Comment by ColinVT** [comment] 2021-04-05 13:12
@Harshsrcc You mentioned you reverted back to 4.9.29 in your comment, could you please let me know (or even just point me to where I can find out) how to do that? I can't see to figure it out.
Thank you!

**Comment by Harshsrcc** [comment] 2021-04-05 15:03
@alexanderby 4.9.31 does fix reddit.com's white background. Thankyou! There's a minor issue. Elements which were earlier white, are now colored in #191F25. In 4.9.29, one could apply any custom color to website background. However, in 4.9.31, elements colored in #191F25 remain the same, even after specifying a custom background color. Is this intended behavior?

**Comment by Harshsrcc** [comment] 2021-04-05 15:09
@ColinVT If you're using Firefox, you can go to Extension's page in addons.mozilla.org, scroll down, and find "See all Versions" under "More Information" section on the left. There you can uninstall the current version, and install any previous version. 

This is the page for Dark Reader: https://addons.mozilla.org/en-US/firefox/addon/darkreader/versions/

**Comment by rakleed** [comment] 2021-04-05 19:40
@Gusted Sometimes the background on https://vk.com does not change (it remains light) and the logo is not inverted (although there is such a rule). Helps turn DarkReader off and on. And reloading the page doesn't help.
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/113618069-d1273800-965f-11eb-99ff-e9ede690e9df.png)
</details>

**Comment by joshsleeper** [comment] 2021-04-05 21:14
jenkins, a self-hosted CI system, has alternating white rows in some tables when Dark Reader is
enabled which wasn't the case before the recent update.

I couldn't find a publically accessible jenkins server to point you at, so here are some simple
directions to get you running one locally as long as you have `docker` available.

## repro

1. start a local jenkins container with `docker` on port `8080`, skipping the unneeded setup wizard

    ```
    sudo docker run --rm -it \
        -p 8080:8080 \
        --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" \
        jenkins/jenkins
    ```

1. once the container has started navigate to https://127.0.0.1:8080, which should be a jenkins dashboard
1. click "New Item" in the side nav, give it a random name, select "Freestyle project", and click OK
1. click the jenkins logo in the top left to navigate back to the home dashboard
1. create a second item just like the first but with a different name
1. toggle Dark Reader on, notice that the bottom row of the two jobs created isn't dark

![image](https://user-images.githubusercontent.com/849941/113628045-55fb5d00-9632-11eb-982f-fb1ec5b8e7f1.png)

**Comment by devwatchdog** [comment] 2021-04-06 09:47
https://archlinux.org is affected too

**Comment by Chriskins6** [comment] 2021-04-06 16:54
@alexanderby, 

The last two updates (4.9.30 and 4.9.31) black out critical elements of color on the main website I use for work. I need to revert to 4.9.29 because everything displayed fine with it.

I downloaded 4.9.29.zip, unzipped it and attempted to install the src file via Google Chrome’s Developer Mode> Load unpacked, but received this message: 


Failed to load extension
 
File          ~\Downloads\darkreader-4.9.29\darkreader-4.9.29\src
Error	Localization used, but default_locale wasn't specified in the manifest.
 
                                                                Could not load manifest.
 
 
I’ve exhaustively searched Google, YouTube and Chrome Developers documentation for extensions manifest file format,, but I can’t figure out how to get it to load. I’m not a developer. However I can competently research and follow directions, but I’ve not found a solution. 
 
Please let me know what I need to do to get it installed. Thanks.

**Comment by Gitoffthelawn** [comment] 2021-04-07 02:35
On eBay, the top menu row has a couple issues:

1. The notifications icon is invisible (dark on dark).
2. The dropdown menu markers are invisible (dark on dark) (for example for the *Watchlist* and *My eBay* menus as well as the menu with the label *Hi [account name]!*).

TBH, I don't know if these are new or old issues.

**Comment by Chriskins6** [comment] 2021-04-07 04:34
On www.startinfinity.com, the label attributes colors - which are changeable via a hex code setting in their edit menu - are invisible, dark on dark. 

Here below is an example, it's their Project Management Template page. Set Dark Reader to 150% Brightness, 150% Contrast, Dark Scheme and Dynamic Mode, and observe the Project Planning Preview Template thumbnail (top right). The thumbnail displays the template in its original white background with many labels attribute's various colors visible. Now click on the thumbnail, and observe that when the template opens, all the labels colors are blacked out and not visible. The text for each label displays but their colors don't:

[https://startinfinity.com/templates/project-management](url)

This is how label attributes render and display when working in the application in Chrome since v4.9.30 and v4.9.31. However, it didn't happen in v4.9.29, where all elements displayed clearly. 

Thanks.

**Comment by d4f5409d** [comment] 2021-04-08 07:09
@Chriskins6 you should try download that version from Firefox addons page in versions section. Rename the file to crx format. It could work.

**Comment by Chriskins6** [comment] 2021-04-09 08:03
@d4f5409d, 

Thanks for the suggestion, but it didn’t work. 

Is there anyone on this thread who knows how to install v4.9.29. Again, here is the error message I’m getting: 


Failed to load extension
File ~\Downloads\darkreader-4.9.29\darkreader-4.9.29\src
Error Localization used, but default_locale wasn't specified in the manifest.
							
                                                                                       Could not load manifest

 
It seems like there’s a simple way to do this that is right in front of my face...I’m just not seeing it. ‘
Thanks.

**Comment by Harshsrcc** [comment] 2021-04-09 08:27
@Chriskins6 You can't use it as is. You'll have to build it first. Follow the Instructions: https://github.com/darkreader/darkreader#building-for-use

**Comment by Chriskins6** [comment] 2021-04-09 11:18
@Harshsrcc,

Thanks. I appreciate you providing the link, but unfortunately that is way beyond the scope of my technical ability, and I don’t have the luxury of time necessary to devote to learning how to do it. 

I don’t understand why reverting back two versions of the extension in Chrome is complicated. I find it hard to believe that the only way to do so is to build it from - what appears to my novice eye - scratch.

I have v4.9.31 installed now. 

v4.9.29 already exists. I just need to know how to install it in Chrome.

**Comment by AndrewDaGuy** [comment] 2021-04-10 05:12
> Same issue. Same Environment as @d4f5409d . Haven't tested on many sites, but css for reddit.com is definitely broken. Many website elements are white.
> 

I can also reproduce this for reddit
![image](https://user-images.githubusercontent.com/66189242/114259028-876d8300-99ba-11eb-8b1a-b926345a6043.png)

- Browser: "Hardened" Firefox 87.0 
- OS: macOS Catalina
- DR: `4.9.31`

**Comment by Harshsrcc** [comment] 2021-04-12 18:42
@Chriskins6 You can download it [here](https://github.com/Harshsrcc/Extensions)

**Comment by felixonmars** [comment] 2021-04-13 22:57
> https://archlinux.org is affected too

I would like to add more details here: The CSS seems broken that, the logo is gone, all the text are in the same color, etc.

It worked fine in previous versions of Darkreader, though.

![2021-04-14-065556-fe82b9](https://user-images.githubusercontent.com/1006477/114631114-97ed6880-9cee-11eb-889a-a4e2864f4434.png)
![2021-04-14-065539-bb4ce5](https://user-images.githubusercontent.com/1006477/114631119-99b72c00-9cee-11eb-952d-653a6c23c707.png)

**Comment by Chriskins6** [comment] 2021-04-15 07:16
@Harshsrcc, Thanks a lot, much appreciated! I downloaded it to keep as a back up. I changed the colors and settings of Filter+ mode in 4.9.31 so that it works for the web app I use most for work. Hopefully if I have to go back to 4.9.29 for any reason, I'll be able to install the one you provided.

**Comment by felixonmars** [comment] 2021-04-21 21:31
Just want to update that the newly released 4.9.32 fixed archlinux.org here.

**Comment by an-eternity** [comment] 2021-04-22 09:48
After web-browser recent update (to Chromium version 90) all the sites now appear in the Dark Mode always, even if the Dark Reader extension is uninstalled.
Is there any solution for this problem?

**Comment by Gitoffthelawn** [comment] 2021-04-23 03:54
@an-eternity I might be mistaken, but it sounds like Chromium is detecting dark mode in the underlying OS and then doing a poor job implementing its own dark mode.

When Dark Reader is uninstalled, it should not effect the web browser in any way.

**Comment by Gusted** [comment] 2021-04-23 05:58
> After web-browser recent update (to Chromium version 90) all the sites now appear in the Dark Mode always, even if the Dark Reader extension is uninstalled.

Could you tell me if this dark mode appears the same way as Dark Reader does, because I can recall some issues where people still had a dark mode, but knowing that's Chrome and they have their own dark mode under a flag and like to make certain decision that people tend to disagree. It could be that Chrome is the one doing this and is pretty unexpected user behavior, however in the case it's still somehow Dark Reader doing it, I should get it reproduced and a bug filed as having an extension still doing it's job after removing it is a big security concern.

**Comment by an-eternity** [comment] 2021-04-23 13:25
Thanks for the suggestions.
Now i see this issue is probably related to a new Chromium version (or to web-browser, in this case - Brave browser), and not to Dark Reader extension.
Apparently, after the recent update it has begun to use the OS color scheme settings for all the web-pages it displays (OS has a high contrast dark color scheme), but this never happened before, browser was updating many times with no problems.

---

In order to figure out what happens i have checked out 2 else Chromium based web-browsers by updating them from some older versions to a recent available one. Important condition is that Dark Reader extension is not installed and was never installed in both of them.

After updating the first one (Opera) from version 81 to 89 - exactly the same problem (as with Brave) has happened.
After updating the second one (SlimJet) from version 87 to 88 - no such problem happened.
So, at the moment, i can only suppose 2 possible cases where this issue might be related to:
1. Chromium version 89 and newer.
2. Recent versions of specific browsers (Brave, Opera).

Maybe somebody else can do the tests and to reproduce this issue too, if this somehow might be useful for Dark Reader further development.

**Comment by an-eternity** [comment] 2021-04-23 13:44
> Could you tell me if this dark mode appears the same way as Dark Reader does
Yes, definitely not the same way.
Previously, since such problems never happened, i didn't actually look into this in details.
What i find strange is that now, when the dark color scheme is copied from the OS to web-browser, Dark Reader doesn't override the colors (fonts and background) anymore the way it did before - now even if the Light mode is selected, appearance of the web-page remains dark.

**Comment by Gusted** [comment] 2021-04-24 08:15
> Dark Reader doesn't override the colors (fonts and background) anymore the way it did before - now even if the Light mode in Dark Reader settings is selected, appearance of the web-page remains dark.

Could you open a new issue for this? As this certainly the behavior we want to have within Chrome.

**Comment by quick007** [comment] 2021-04-27 05:08
Vercel is now broken. A few days ago it worked fine.
![image](https://user-images.githubusercontent.com/69743171/116188254-f4cc2400-a6db-11eb-935e-0110661cfe40.png)
![image](https://user-images.githubusercontent.com/69743171/116188272-fc8bc880-a6db-11eb-8a3c-89405e38904c.png)

**Comment by Gusted** [comment] 2021-04-27 10:52
^ Make sure to have light theme enabled in the settings.

**Comment by quick007** [comment] 2021-04-27 16:15
> ^ Make sure to have light theme enabled in the settings.

I do

**Comment by Gitoffthelawn** [comment] 2021-04-28 02:27
> I do

By the power vested in me by the Land of GitHub, I now pronounce you wed.  You may kiss.

**Comment by Gusted** [comment] 2021-04-28 09:28
> By the power vested in me by the Land of GitHub, I now pronounce you wed. You may kiss.

😮 ☺️

**Comment by BlueStaggo** [comment] 2021-05-01 08:41
Here on Dark Reader 4.9.32, docs.oracle.com is now broken. [Reference](https://docs.oracle.com/javase/8/docs/technotes/guides/awt/)
![image](https://user-images.githubusercontent.com/71090710/116776619-36a0f580-aa61-11eb-87ae-dedb85f7785d.png)
I assumed it has something to do with this update, so I reported the website here.

**Comment by an-eternity** [comment] 2021-05-01 09:26
> > Dark Reader doesn't override the colors (fonts and background) anymore the way it did before - now even if the Light mode in Dark Reader settings is selected, appearance of the web-page remains dark.
> 
> Could you open a new issue for this? As this certainly the behavior we want to have within Chrome.

Yes, but i have quite a little experience in this area and currently almost no free time to look into it in more details... I still keep the browser not reinstalled to preserve this behavior for the case if it may appear useful for some tests with Dark Reader.
In the next days i will see if similar issue is already opened by somebody else, and if not opened then i will try to open it.

**Comment by Turkyden** [comment] 2021-05-12 09:09
## React Darkreader

🌓 A React Hook for adding a dark / night mode to your site.

https://github.com/Turkyden/react-darkreader

[: : : Live Demo : : :](https://react-darkreader.vercel.app/)

**Comment by Gusted** [comment] 2021-05-12 09:10
@Turkyden Don't use this issue for advertising.

**Comment by Turkyden** [comment] 2021-05-12 09:11
OK, sorry @Gusted

**Comment by Gusted** [comment] 2021-06-03 08:01
4.9.33 was released with a bunch of fixes and should cover most cases now if the breaking changes that caused this issues and related.

**Closed by Gusted** 2021-06-03 08:01 UTC

**Comment by Gusted** [comment] 2021-06-03 08:02
For anyone, wanting to comment for a breaking site(new or still perusing), please open up a new issue with the Broken website template. Thanks!
