### ISSUE TITLE
[Bug] Can't enable Dark Reader at all on some websites

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#1896] opened 2020-01-15 09:11 UTC
There are specific websites from which I can't enable Dark Reader at all : nothing happens when I click on the switch button and it stays on disabled state.

Here is the list :
- https://education.github.com/pack/offers
- https://github.community/

**Comment by KaKi87** [comment] 2020-03-10 17:05
up

**Comment by alexanderby** [comment] 2020-03-12 17:52
The first one requires login, the second works well with the latest build, wait for an update.
<img width="1199" alt="Screen Shot 2020-03-12 at 20 51 10" src="https://user-images.githubusercontent.com/9638588/76550565-62e76480-64a3-11ea-8b98-46c1179bcb8c.png">

**Comment by Gusted** [comment] 2020-05-19 18:49
@KaKi87 Can you comfirm that this works with the latest version of darkreader

**Comment by KaKi87** [comment] 2020-05-19 19:14
Yes, here is proof :

![2020-05-19-21-09-07](https://user-images.githubusercontent.com/21284089/82368234-60f6d000-9a15-11ea-902e-3779b99589eb.gif)

My version is 4.9.8, I don't know if it's the latest one, since there are no more git release tags since 2018...

**Comment by Gusted** [comment] 2020-05-19 20:38
What's your sitelist?
4.9.8 is the latest version of darkreader we don't publish anymore to release tab.

**Comment by KaKi87** [comment] 2020-05-19 20:44
> What's your sitelist?

I can only select it line-by-line, is there another way ?

> we don't publish anymore to release tab

Why so ? What's the purpose of versioning then ?

**Comment by Gusted** [comment] 2020-05-19 20:46
> I can only select it line-by-line, is there another way ?

Screenshot?

> Why so ? What's the purpose of versioning then ?

Wasn't my decision https://github.com/darkreader/darkreader/issues/2452#issuecomment-628196533

**Comment by KaKi87** [comment] 2020-05-19 21:00
> Screenshot?

Too much scroll height, here's another GIF ^^

![2020-05-19-22-54-30](https://user-images.githubusercontent.com/21284089/82377495-09ac2c00-9a24-11ea-9bd5-b366d45707e0.gif)

**Comment by Gusted** [comment] 2020-05-19 21:01
Their we got it an old but if you remove github.com temporarily from the list you can toggle subdomains

**Comment by KaKi87** [comment] 2020-05-19 22:04
Do you mean that disabling darkify on a domain prevents all subdomains to be darkified ? That's a hell of a bug !
What about `github.community` ? It's not a subdomain ! So what, it the site list works using `String.includes` ? 😅
I can't enable Dark Reader on GitHub, because I'm actually using the GitHub Dark userscript instead, which is more complete for this specific use case.

**Comment by Gusted** [comment] 2020-05-19 22:07
It use complex regex https://github.com/darkreader/darkreader/blob/master/src/utils/url.ts#L44

But it's planned to move a more usable case with negative patterns support #2517 and after some tweaking should resolve this...

**Comment by KaKi87** [comment] 2020-05-20 19:05
@Gusted I'm sorry that you had to lock down #2452, but I was in the middle of writing my answer when you did so and I really want to answer, so I have no other choice but to do it here.

-----
> Is open source equal to fighting for freedom?

We'd had to define _fighting_ and _freedom_ first, but this is kinda off-topic.

However, there is, in my opinion, an open source spirit : it states that open source is not only about publishing a source code and allowing contributions, but also making efforts for transparency (e.g. by creating release tags and writing changelogs, etc.), and stay close to the consumers (e.g. always receiving feedback positively, ensure the project's continuity, etc.)

> Have auto-update?

Yes, indeed.
However, you asked me in #1896 to confirm that my issue is still present _on the latest version of Dark Reader_.
So, in order to answer properly, I wanted to make sure I was running the latest version of Dark Reader, even while knowing that Chrome is updating extensions automatically.

Thanks

**Comment by Gusted** [comment] 2020-05-20 19:10
> @Gusted I'm sorry that you had to lock down #2452, but I was in the middle of writing my answer when you did so and I really want to answer, so I have no other choice but to do it here.

No problem posting here. Was more that it did go a bit to wrong side as you saw his comment...

> > Is open source equal to fighting for freedom?
> 
> We'd had to define _fighting_ and _freedom_ first, but this is kinda off-topic.
> However, there is, in my opinion, an open source spirit : it states that open source is not only about publishing a source code and allowing contributions, but also making efforts for transparency (e.g. by creating release tags and writing changelogs, etc.), and stay close to the consumers (e.g. always receiving feedback positively, ensure the project's continuity, etc.)

I try my best with doing this and makes everyone happy, but I also just have someone who review and can reject and dismiss my idea's an PR's.

> > Have auto-update?
> 
> Yes, indeed.
> However, you asked me in #1896 to confirm that my issue is still present _on the latest version of Dark Reader_.
> So, in order to answer properly, I wanted to make sure I was running the latest version of Dark Reader, even while knowing that Chrome is updating extensions automatically.

Will try to come talk with Alexander and see if their is a possible for this a the changelogs and tags, Like I said I don't mind if I need to do those tasks, so long more people are getting happy I'm fine with it.

**Comment by KaKi87** [comment] 2020-05-20 19:13
> No problem posting here. Was more that it did go a bit to wrong side as you saw his comment...

Indeed I saw... Wouldn't have it been possible to only "mute" him ?

**Comment by Gusted** [comment] 2020-05-20 19:15
> Indeed I saw... Wouldn't have it been possible to only "mute" him ?

Was beter to lock the issue as the whole issue was going wrong way and so far I know their is no `mute` option or something that related other than blocking.

**Comment by KaKi87** [comment] 2020-05-20 19:20
Understood.

Regarding #2517, what's left to do ?

**Comment by Gusted** [comment] 2020-05-20 19:21
Well Alexander review it first blame it with 100 issues and over a week I finally would be done and finish my headache fixing it :)

**Comment by Gusted** [comment] 2020-06-02 17:07
![](https://i.imgur.com/iS682VI.png) Changelogs are now kind of implemented. https://addons.mozilla.org/en-US/firefox/addon/darkreader/versions/

Tags are being made from of now. ![](https://i.imgur.com/FVnWwrW.png) 

About the release tab I will try to discuss with him how and what.

A update for your other question and not related to the OP's issue.

**Comment by KaKi87** [comment] 2020-06-02 17:49
Nice !
Did you actually completely deleted the other issue ? 😅

**Comment by Gusted** [comment] 2020-06-02 17:52
![Screenshot_20200602_195026](https://user-images.githubusercontent.com/25481501/83552720-83efac80-a50a-11ea-86cd-05ca571c75a3.jpg)
Take a wild guess.

**Comment by Gusted** [comment] 2020-06-02 17:52
Nope ^ github probably did.

**Comment by austinhuang0131** [comment] 2020-12-08 21:35
Problem persists 4.9.26. Basically `github.community` inherits `github.com` settings and cannot be separately enabled once `github.com` is disabled.

**Comment by Gusted** [comment] 2020-12-08 21:40
> Problem persists 4.9.26. Basically `github.community` inherits `github.com` settings and cannot be separately enabled once `github.com` is disabled.

Wait for #2517 to get merged. Currently this can bypassed to add `github.com$` instead of `github.com` in the sitelist.

**Comment by austinhuang0131** [comment] 2020-12-08 21:41
meh, github dark mode < dark reader filter+ for me, so it's a non-issue but ig thanks

**Comment by Gusted** [comment] 2020-12-08 21:43
> meh, github dark mode < dark reader filter+ for me, so it's a non-issue but ig thanks

#4182 I'm now using the github dark mode, but honestly they didn't even account for the contrast, e.g. icons are just dark-gray-ish on a dark-ish blackground-color and the text on labels etc is weird formatted.

**Comment by m4heshd** [comment] 2020-12-31 20:15
I had to write a userstyle to be used with Stylus just for GitHub gists and docs because of this issue. Glad it's being fixed. Can't live without darkreader.

**Comment by steph643** [comment] 2021-06-09 07:58
I'm a bit lost with this thread. Have the issue been fixed? There's [this website](https://docs.simplefoc.com/) where Dark Reader cannot be enabled (nothing happens when I click on the switch button and it stays on disabled state).

**Comment by m4heshd** [comment] 2021-06-09 14:28
@steph643 Works for me. Check your sites list to see if there's an entry for that domain or a subdomain for that domain.

**Comment by m4heshd** [comment] 2021-06-09 18:45
@steph643 The issue in your case was when you have the domain added to the site list, darkreader can't deal with any subdomains for that domain. So what you have to do is use `^domain.com` in the site list instead of just `domain.com` and that will enable you to have different settings for different subdomains on the same domain in site list.

**Comment by cool-RR** [comment] 2021-10-19 18:44
This bug happens to me too.  @m4heshd The workaround with `^` doesn't work for me. Also removing the past appearances in the list didn't help.

**Comment by m4heshd** [comment] 2021-10-19 19:04
@cool-RR That's strange. Still works for me perfectly fine. I don't see any PRs changing that functionality either.

**Comment by CorneliusCornbread** [comment] 2022-03-15 01:56
> There are specific websites from which I can't enable Dark Reader at all : nothing happens when I click on the switch button and it stays on disabled state.
> 
> Here is the list :
> 
> * https://education.github.com/pack/offers
> * https://github.community/

Subdomains are also borked 
https://docs.vrchat.com/
conflicts with
https://vrchat.com/

**Comment by jakubgs** [comment] 2022-11-17 09:15
I have experienced this weird bug many times, and here's the weird thing:

- Clicking the toggle button for the site does nothing, has no visual effect or doesn't switch the button.
- Clicking the "Site List" section and switching between "Invert listed only" and "Not invert listed" does work

So it's not an issue with inability to invert the site, but something wrong with the toggle button itself.

Video: [darkreader_toggle_issue.webm](https://user-images.githubusercontent.com/2212681/202405181-363992d4-80da-4e15-a93e-16587886bdb2.webm)

Really weird and really annoying.

**Comment by jakubgs** [comment] 2022-11-17 09:23
Actually, if I look a bit closer, I can see that the toggle button does indeed add and remove the domain from the "Not invert listed" list below, but that has no effect on the site itself until the "Site List" switch between tabs is used. And this is regardless of whether the domain is in the list or not.

Also, if I uninstall the plugin and then install it again, so the list of sites is clear, it starts working again on the problematic site.

**Comment by jensim** [comment] 2023-02-02 05:54
Here's another one, in case it helps:
* 🐛⬜️ https://docs.spring.io/spring-data/jpa/docs/1.6.0.RELEASE/reference/html/jpa.repositories.html


P.S.
❤️ Dark Reader 💋 🦄 my eyes Love the plugin ❤️

**Comment by KaKi87** [comment] 2023-02-02 06:08
@jensim I'm guessing you added `spring.io` to your dark list because of the toggle available, so now you can't enable it on `docs.spring.io` because of this.

Please have a look at [this workaround](https://github.com/darkreader/darkreader/pull/2517#issuecomment-1411459125) that I created, that domain isn't on the list yet but I'll add it in a few hours, as well as others mentioned here and there.

**Comment by Francewhoa** [comment] 2023-02-04 23:00
This is to confirm this bug with Dark Reader V4.9.62. Below are both the [steps to reproduce](#steps), and an easy, quick, and temporary [workaround](#workaround).

<a name="steps"></a>
## Steps to Reproduce

1. Using either [Firefox](http://mozilla.org/firefox) (FF) V102.7 or [Ungoogle Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) (Chrome is powered by Chromium) V109.0, go to a domain name. In this example, we go to https://substack.com
      * Note: This first step is the most important one. For the next steps to reproduce to be a success, double check that you go to a **domain** name. Otherwise, if you go to a **subdomain** name, the next steps would fail.

1. Using Dark Reader (DR) V4.9.62, select the **Theme for substack.com** option. Which is showed by the number 4 in this screenshot below. Leave DR other settings to their default.
![create_theme_for_domain---screenshot---francewhoa---ksnip---2023-02-04---160506](https://user-images.githubusercontent.com/119942/216790005-8c3f0bcb-85b7-44ad-b9a6-ad7a88a0f1c8.png)

1. Using DR, for the same domain name, toggle to **Disabled for this current website** option. Which is showed by the number 1 in this screenshot below.
![disabled_for_current_website---screenshot---francewhoa---ksnip---2023-02-04---162258](https://user-images.githubusercontent.com/119942/216790283-5aef9984-705d-45db-abdf-a84eec0e91b8.png)

1. Using FF, go to any subdomain name. Which is owned by the same domain name. In this example, we go to https://bioclandestine.substack.com/archive
      * Note: For the next steps to reproduce to be a success, double check that you go to a **subdomain** name which is owned by the same domain name. Otherwise, if you go to either any **domain** name, or any subdomain name, the next steps would risk to fail.

1. Using DR, try to toggle to **Enabled for this current website** option. Which is showed by the number 1 in this screenshot below. This always fails. This is the challenge. The toggle permanently shows **Disabled for this current website**. Somehow it can't be changed. When the user click on this button. Nothing happens.
![disabled_for_current_website---screenshot---francewhoa---ksnip---2023-02-04---162258](https://user-images.githubusercontent.com/119942/216790659-dff584e7-85f3-4d71-8c9a-ffb3f2a99f51.png)

1. The needed end result is that when the user click on the **Enabled for this current website** option, DR toggle between enabled and disabled.


<a name="workaround"></a>
## Temporary Workaround

Steps: 

1. Using any modern and appropriate browser to your liking, such as [Firefox](http://mozilla.org/firefox) (FF) or [Ungoogle Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) (Chrome is powered by Chromium), go to the domain name which owned the subdomain name. For example, if the bug is presently with this subdomain https://bioclandestine.substack.com/archive Then go to its domain at https://substack.com

1. Using Dark Reader (DR), toggle to **Enabled for this website**. Which is showed by the number 3 in this screenshot below. Leave DR other settings to their default.
![Enabled_for_current_website---screenshot---francewhoa---ksnip---2023-02-04---164853](https://user-images.githubusercontent.com/119942/216791046-5e67f440-b719-4328-91e2-dcbddaf3e782.png)

1. Using FF, go to the subdomain, in this example, go to https://bioclandestine.substack.com/archive 
 
1. Using DR, toggle to **Enabled for this website**. Now it WORKS. You successfully temporarily resolved this challenge :) 

1. In the future, until this bug is resolved, this is your reminder that if you deactivate DR for a domain name, DR will automatically disable itself for all its subdomaines. And before it does so, DR will not notify you about this. If you're a developer interested to contribute to resolve this challenge, this pull request might be of interest at https://github.com/darkreader/darkreader/pull/2517



<a name="context"></a>
## Context

For more than 2 years, this bug was frequently reported to the Dark Reader (DR) community. So why is it not fixed? My guess is that the users who reported this but with subdomain names were unaware of the required first steps to reproduce. About configuring the **domain** name. In turn, those end users reported the bug only with the subdomain steps. As you know, most user are not developer. They are often unaware of all the backend dependencies. In turn, the community is not able to reproduce this bug. In turn, the community claims that it is either a user error or a misconfiguration by the user. But it is none of those. From the point of view of an end user, this is really a bug. In other words, I believe that all the people above did their best efforts in good faith. While at the same time, two years later, this bug is not yet resolve. 

That I know of, the closest effort to resolve this bug is this pull at https://github.com/darkreader/darkreader/pull/2517 After this pull is included in a future release of DR, this bug will likely be resolved.

**Comment by ondvpoh** [comment] 2023-05-02 11:08
Another one: https://www.aida64.com
I can't enable DR on this site on FF but can on Edge.

**Comment by bershanskiy** [comment] 2023-05-02 16:32
> * Chrome

I am unable to reproduce this issue. Could you please provide more info (e.g., console log if it appears interesting)?

**Comment by BraveDude8** [comment] 2023-06-04 09:58
Confirming that this is still an issue in v4.9.63 on Firefox 133.0.2.
I can individually exclude subdomains, but on one website I specifically want domain.com to be excluded and subdomain.domain.com (a completely distinct service) to be forced into dark mode, and this is not possible because excluding the core domain forces all subdomains to be excluded too.

If I change the "Site list" tab to "Invert listed only" I can specify subdomain.domain.com here, which solves the issue, but that means websites aren't forced to dark mode by default and it defeats the purpose of me using this extension.

https://github.com/darkreader/darkreader/issues/3359 is a great description of the issue and how it should be fixed.

**Comment by KaKi87** [comment] 2023-06-04 10:08
@BraveDude8 Until then if you give me that domain then I'll add it to my userscript so that Dark Reader will be disabled on `domain.com` while remaining enabled on `subdomain.domain.com`.

**Comment by BraveDude8** [comment] 2023-06-04 10:10
@KaKi87 This is an internal subdomain for a microservice, unfortunately. How does your userscript for this work?

**Comment by KaKi87** [comment] 2023-06-04 10:16
If it is only accessible from your machine (e.g. using a custom `hosts` file) or from your network (e.g. using a local DNS) then my userscript isn't meant to handle it.

But if it's accessible from the Internet then I still can add it even if it replies with 401 as long as the page it's dark.

Thanks

**Comment by lednerg** [comment] 2023-06-04 21:02
None of this stuff about domains and subdomains can explain why it's also happening to IP addresses, something I brought up back in October. There's something fundamentally broken with how this plugin decides where it's disabled, and it's been this way for years.

**Comment by Francewhoa** [comment] 2023-06-09 13:03
>None of this stuff about domains and subdomains can explain why it's also happening to IP addresses, something I brought up back in October.

Thanks for confirming that this challenge is also with IP address. Not just subdomain names.

As a user, I don't know what is causing this challenge. My guess is that it's related to the second and following dot(s) `.` As you know, both subdomain names and IP addresses include 2 or more dots. 

For example, two dots in `subdomain.domain.ca` And more than two dots in `123.456.789.012`

In our case, what we need is to be able to apply a Darkreader Theme for each additional dot. For exemple:

1. Theme 1 `domain.ca`
1. Theme 2 `subdomain.domain.ca`

or

1. Theme 1 `123`
1. Theme 2 `123.456`
1. Theme 3 `123.456.789`
1. Theme 4 `123.456.789.012`

**Comment by KaKi87** [comment] 2023-06-09 15:28
There's no need to investigate, the specific reason of this behavior is already known, which has nothing to do with domains nor IPs, but with the matching method : when the visited URL *includes* any string in the blacklist, then Dark Reader is disabled.

For example : if you add `u` to the blacklist then Dark Reader will be disabled on any URL that includes `u` anywhere, like `github.com`, `youtube.com`, `reddit.com/user/foo`, etc.

It's as simple as that.

**Comment by holocronweaver** [comment] 2023-07-26 20:19
One thing that would be (relatively) low implementation effort and would reduce user pain significantly is if the site list item that matched the current site was surfaced to the user, so they could remove it from the site list immediately without manually scanning the list.

In my case I had a list of over 200 sites and could not find the one impacting a particular site, so I had to delete them all to resolve the issue.

**Comment by alexanderby** [comment] 2024-04-01 15:57
Hopefully this is resolved now.

**Closed by alexanderby** 2024-04-01 15:57 UTC

**Comment by BraveDude8** [comment] 2024-04-01 16:01
Working for me, domain.com is toggled off and subdomain.domain.com is toggled on, both can be toggled individually without impacting the other.

Thank you very much to all involved.

**Comment by nttldnknwn** [comment] 2025-12-31 05:32
GitHub only displays with a light theme for me, and it doesn't respond to any Dark Reader settings at all.

Dark Reader 4.9.118
LibreWolf 146.0.1-1
