### ISSUE TITLE
[Broken Website] Atlassian.net

### ISSUE THREAD

**Issue by erhanyumer** [darkreader/darkreader#8566] opened 2022-03-31 17:01 UTC
# Broken Website Report

## Atlassian
atlassian.net

## Steps To Reproduce
I cannot provide a set of steps since it is a private page to my company but in Jira software, issue pages are mostly white now. 

## Problematic Observation
White areas in the screenshot were black before the latest update.

## Screenshots

![image](https://user-images.githubusercontent.com/33106364/161109895-cc9499a5-acfe-4daf-9058-c4b2b46ec143.png)

I erased the texts in the white areas because of privacy.

## System Information

  I specified browser and dark reader versions below.

- OS: Windows 10
- Browser: Firefox 98
- Dark Reader Version:  e.g. 4.9.47

**Comment by markhealy88** [comment] 2022-03-31 23:22
Same issue here.  It was working yesterday, today is broken.
Thanks @FiveElementNinja, the hover thing works temporarily

**Comment by erhanyumer** [comment] 2022-04-01 05:59
@FiveElementNinja you're right, also scrolling to bottom solves the problem completely, you should try. It is still a bug anyway.

**Comment by garrafote** [comment] 2022-04-01 08:53
Also hapening on Chrome Version 100.0.4896.60

Scrolling to the bottom doesnt solve the problem for me.

**Comment by orval** [comment] 2022-04-01 09:42
Same for me on Firefox 99.0b8 and Chrome 99.0.4844.84 with Dark Reader v4.9.47.

**Comment by EduardoPerezExt** [comment] 2022-04-01 13:01
Same here, I'm on Dark Reader 4.9.47 and Chrome 99.0.4844.84

**Comment by EricTercasio** [comment] 2022-04-01 13:45
A quick fix is to change to "Filter" or "Filter+" in more than toggling only for atlassian.
This does make it completely black instead of a dark theme, but it is still much better 🙂
![image](https://user-images.githubusercontent.com/17280714/161275902-36e71c84-06ed-4c22-84d2-1ba9fb22f1b2.png)

**Comment by MahmoudSenSei** [comment] 2022-04-01 17:21
same problem here, now I have to use Filter+ witch does not as good.

**Comment by Gusted** [comment] 2022-04-02 21:17
Well like last time with the atlassian issue I wasn't able to diagnose is remotely(because atlassian likes to have issue with Dark Reader on a deep level which requires a good few hours with the debugger). So unless somebody stumbles on a diagnose of what has changed that caused this 🤷🏽 I'm afraid there won't be a fix for this.

**Comment by Roukanken42** [comment] 2022-04-04 07:49
Well, I'm not familiar with how Dark Reader works, so unsure what exactly you need, but the cause of whiteness on the issue page is this little giant div with its inline style:

```html
<div id="jira-frontend">
<style>
    body#jira {
        overflow-x: hidden;
        overflow-y: auto;
    }

    #jira-frontend {
        background: var(--ds-surface, white);
    }

    #jira_request_timing_info {
        margin: 0;
    }
</style>
```

Specifically, the `background: var(--ds-surface, white);` part - `--ds-surface` is not set, so it just defaults to white. DR detects it (I think?) and inserts its own inline style, but it has the exact same line, so it's not effective.

**Comment by svegaca** [comment] 2022-04-04 10:43
Same problem here! For me, it works with `Filter` or `Filter+`, but the results are not as good as it was before 😞

**Comment by svegaca** [comment] 2022-04-04 10:46
https://github.com/darkreader/darkreader/pull/8588

**Comment by Gusted** [comment] 2022-04-05 15:23
Will be fixed in the next release or get the config files early via: https://github.com/darkreader/darkreader#site-fixes

**Closed** 2022-04-05 15:22 UTC
Labels: Broken Website
