### ISSUE TITLE
[Bug] Issue with Iframes when embedding on external sites

### ISSUE THREAD

**Issue by Scania-Creations-16** [darkreader/darkreader#6918] opened 2021-09-26 16:24 UTC
# Bug Report

## Bug Description

I've noticed that when I'm embedding **darkreader** on websites using 

```<script src="https://unpkg.com/darkreader@4.9.35/darkreader.js"></script>```
```<script>```
```DarkReader.enable({```
```    brightness: 100,```
```    contrast: 100,```
```    sepia: 0```
```});```
``` </script>```

Iframes aren't getting inverted, whereas using **darkreader** as my webbrowser extension, the Iframes are iinverting. The Issue is happening only during Embedding.

Could you please fix this Issue ?

## Website Address

Sorry,I don't have a Website :(

## Steps To Reproduce

Embed some iframe and import darkreader.js package and you can see what I've told now

## Expected Behavior

I Expect it to have same performance as it's Browser Extension
(Like the iframe getting inverted except the images inside it )

## Actual Behavior

The Iframes are not getting Inverted :(

## Screenshots

Yeah,I have Screenshots , here they are

Using Embed method ("Background colour turned black from white")
https://i.ibb.co/bb0Xpsw/issue1.png

Using Browser Extension ("Working Perfectly Fine :heart: ")
https://i.ibb.co/1vk8TvL/issue2.png
(P.S. That white background is not a problem since website background will be different)

## System Information

- OS:  Ubuntu 18.04
- Browser:  Firefox 
- Dark Reader Version: Latest Version(Browser Extension) and How do we get latest version when Embedding ?

**Comment by Gusted** [comment] 2021-09-26 16:33
Duplicate of #5082

**Closed by Gusted** 2021-09-26 16:33 UTC
Labels: bug

**Comment by Scania-Creations-16** [comment] 2021-09-26 16:44
> Duplicate of #5082

But bro, Why is it like that, like working as Browser extension and not working when Embedded
Is there any tweaks to make it happen ? :question:

**Comment by Gusted** [comment] 2021-09-26 16:46
> But bro, Why is it like that, like working as Browser extension and not working when Embedded
> Is there any tweaks to make it happen ? question

If you have read the issue, I've stated in my first comment why it's a hard feature to add, as we have to solve 2 problems.
