### ISSUE TITLE
[Bug] Named anchors colored as links

### ISSUE THREAD

**Issue by stanio** [darkreader/darkreader#10442] opened 2022-12-06 19:40 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Non-link named anchor elements get colored as links causing weird coloring, probably more noticeable but not limited to some legacy pages:

![sample-darken-page](https://user-images.githubusercontent.com/1247730/206002261-269b9ff3-7545-4695-8443-4abacdae6f1e.png)

The first couple of paragraphs and list item 1) are unexpectedly colored blue.

### Website Address

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/prepapp002.html

### Steps To Reproduce

1.  Create HTML file:

    ```html
    <!DOCTYPE html>
    
    <style>
      h2, p a:not(:link):not(:visited) {
        color: green;
      }
    </style>
    
    <h1><a id="main-heading">Main heading</a></h1>
    
    <p><a href="https://github.com/darkreader/darkreader/issues"
      title="Issues · darkreader/darkreader">Sample link</a></p>
    
    <a name="legacy-markup">
    <p>Buffalo dolor ham, picanha nostrud short loin filet mignon. Biltong enim ex,
    velit deserunt chislic cupim non esse exercitation officia ut adipisicing
    proident. Ad aute anim beef ribs kielbasa labore, ham hock sausage beef
    exercitation ut lorem ball tip picanha jerky. Kielbasa shoulder dolore beef
    leberkas, cupidatat rump. Quis capicola dolore sirloin. Ad tri-tip tongue
    bacon porchetta, laboris cupim eu pancetta ham hock pariatur voluptate.</p>
    </a>
    
    <h2><a id="sub-heading">Sub-heading</a></h2>
    
    <p><a id="inline-anchor" title="Inline anchor">Ipsum eiusmod ham</a> short loin
    turkey frankfurter sirloin lorem landjaeger shank filet mignon. Eu esse
    biltong ut tempor drumstick. Do cupim ut, jowl in alcatra nostrud strip
    steak. Voluptate kevin labore cupim eiusmod, shoulder shankle pork belly
    ipsum velit. Rump enim in shankle cillum laborum dolore ullamco aute alcatra
    chuck nulla qui. Occaecat ad enim pork beef ribs tempor.</p>
    ```

2.  Open in the browser with Dark reader theme enabled.

### Expected Behavior

![expected-dark-theme](https://user-images.githubusercontent.com/1247730/206003915-f6308b94-9f4c-4c6f-8029-c772cb98692d.png)

### Actual Behavior

![actual-dark-theme](https://user-images.githubusercontent.com/1247730/206004076-b4f66f0a-fa7f-4abd-a134-10b504fc8940.png)

### Screenshots

Default light theme preview:

![light-theme](https://user-images.githubusercontent.com/1247730/206003718-1e9ee700-90cc-4502-a009-adbd03e83372.png)

### Operating System

Windows 10

### Web Browser name and version

Firefox Developer Edition 108.0b9

### Dark Reader version

4.9.60

### Additional Context

Using the browser DOM/style inspector tool, after the Dark reader theme is applied I'm observing the following style rule applied:

```css
a {
    color: #3391ff;
}
```

I guess it should be better defined as:

```css
a:link, a:visited {
    color: #3391ff;
}
```

so it doesn't get applied to non-link named anchors.

I'm currently working around this by applying custom CSS (in the Dark reader "Dynamic theme editor"):

```css
a:not(:link):not(:visited) {
    color: unset;
}
```

**Comment by Gusted** [comment] 2022-12-07 22:44
This seems to be a duplicate of #9836

**Comment by stanio** [comment] 2022-12-08 06:17
Yes, looks like it.  At least I have provided some real-world examples (the Java 8 docs).  I've encountered it on other sites I can't remember/point to at the moment, as well.  Please close this one at your discretion.

**Comment by Gusted** [comment] 2022-12-08 12:55
Closing, referenced this issue in the other issue. Many thanks for the information!

**Closed by Gusted** 2022-12-08 12:55 UTC
Labels: bug
