### ISSUE TITLE
[Broken Website] https://skribbl.io/

### ISSUE THREAD

**Issue by RafeeDaBoy** [darkreader/darkreader#8614] opened 2022-04-09 15:17 UTC
# Broken Website Report

## Website Address
https://skribbl.io/

## Steps To Reproduce

- Visit the website with Dark Reader enabled.
- Bottom half of the website is blank

## Problematic Observation
Bottom half of the website is blank instead of the website wallpaper

## Screenshots
![image](https://user-images.githubusercontent.com/69535896/162580098-2e1ff70d-327e-4cfb-9326-2d0529161a9f.png)
![image](https://user-images.githubusercontent.com/69535896/162580099-b6e30ac4-37f8-4f17-9cc3-1b91e9041dc2.png)

## System Information
- OS: Windows 10
- Browser: Firefox 98.0.2
- Dark Reader Version:  4.9.47

**Comment by Gusted** [comment] 2022-04-11 19:49
Closing as wontfix, as the is caused by fundamental behavior by dark reader(the site's root element's background-color must be dark). But this unfortunately overwrites the existing background-images partially.

**Closed by Gusted** 2022-04-11 19:49 UTC
Labels: Broken Website
