### ISSUE TITLE
google docs - photos have reversed (negative) colors (Windows OS - Chrome)

### ISSUE THREAD

**Issue by yorgos-s** [darkreader/darkreader#8784] opened 2022-04-29 18:01 UTC
# Bug Report

## Bug Description
All images inside google docs application have their colors inverted - Chrome - Windows 10 OS

## Steps To Reproduce
Open any google docs document that has images inside. Logically you'll see their colors inverted

## Expected Behavior
images have their original colors

## Actual Behavior
About 3 days ago all the photos of my google docs have their colors inverted (negative)
At first I thought it was some broken option in my account
but then I tested the same issue in a friend's computer with a different google account and again dark reader inverted the images' colors inside google docs. 
Tested in all modes filter, filter+, dynamic  with the same results : the colors of the images have been inverted
The only mode that doesnt invert images' colors is the "static mode" - but for me is not useful
because it leaves all the content unaffected from the dark mode.

## Screenshots
inverted colors in modes  filter, filter+,dynamic
![image](https://user-images.githubusercontent.com/16538262/165997682-18234747-bd17-4822-9f60-407d782e871f.png)

not inverted colors in static
![image](https://user-images.githubusercontent.com/16538262/165997463-dd8e86b8-8a2d-43b3-b361-2affed655e63.png)

## System Information
Tested in two separate laptops (Windows OS) with different google accounts
Both i7, bought after 2019 - the first computer has a good GPU.

- OS: 
- Browser: 
- Dark Reader Version: 

## Additional Context
if you notice even the thumbnail of my account has its color inverted inside the google docs document

**Comment by Gusted** [comment] 2022-04-30 21:27
Duplicate of https://github.com/darkreader/darkreader/issues/8730

**Closed by Gusted** 2022-04-30 21:27 UTC
Labels: bug

**Comment by fmaribo** [comment] 2024-06-03 02:54
Please, will there be a fix for this? I'm an avid user of this extension. there is a chrome extension called Google Docs Dark Mode which does darkmode without inverting the image colors, but that extension has other issues like incomplete coverage and poor color choice.

**Comment by thorlaug** [comment] 2025-03-27 10:12
I have the same problem, Mac>Chrome>everything updated.
I uninstalled the Dark Mode extension and that didn't work. I have white on black text and all images inverted - only in Chrome. Firefox shows the pics normal, but their presentation of the docs interface is 'lacking'
