### ISSUE TITLE
[Feature Request] Automatic light/dark switching based on sunrise/sunset time

### ISSUE THREAD

**Issue by coder66** [darkreader/darkreader#9231] opened 2022-07-08 19:35 UTC
# Feature Request

## Is this feature request related to a problem?
Feature request: Add option to toggle light/dark mode according to sunset time.

## Additional Context
I would really like to have this option so that at daytime the browser is light and at night it is dark.

**Comment by Gusted** [comment] 2022-07-09 04:36
Duplicate of #9163

**Closed by Gusted** 2022-07-09 04:36 UTC
Labels: enhancement
