### ISSUE TITLE
Site list not synced

### ISSUE THREAD

**Issue by terrorist96** [darkreader/darkreader#1032] opened 2019-01-23 13:35 UTC
From searching, it appears this extension is supposed to sync across different computers. However, last night I added several sites that should be inverted, but this morning looking on a different computer that list of sites did not get synced. Though the shortcut I set for toggling a current site did get synced. Is the list of sites supposed to get synced?

**Comment by alexanderby** [comment] 2019-01-25 11:11
If you are signed into Chrome, they should sync. But if the count of such websites is large, they will not sync. Try right-click Dark Reader icon, click Insect Popup. Run this script in Console to see what happens:
```javascript
chrome.storage.sync.getBytesInUse((b) => {
  console.log(`Bytes in use: ${b}`);
  console.log(`Quota bytes: ${chrome.storage.sync.QUOTA_BYTES_PER_ITEM}`);
  chrome.storage.sync.get('syncSettings', (s) => console.log(`Is syncing: ${s.syncSettings}`));
});
```

**Comment by terrorist96** [comment] 2019-01-25 12:56
```
undefined
VM95:2 Bytes in use: 1258
VM95:3 Quota bytes: 8192
VM95:4 Is syncing: true
```

I think maybe it is because I had toggled the extension off on all my computers, then toggled it on on one computer, added some sites, and then toggled it from off to on on the other computers, and the custom shortcut I added was synced, but not the list of sites. The list of sites is just a handful, so it's not too large to be synced.

**Comment by terrorist96** [comment] 2019-02-01 14:14
> If you click on your profile icon in Chrome, does it say you are syncing?

Yes.

**Comment by terrorist96** [comment] 2019-02-06 15:08
Version 4.7.6 fixed the issue for me.

**Comment by alexanderby** [comment] 2019-02-06 15:52
There were no related changes.

**Comment by terrorist96** [comment] 2019-02-06 15:55
Maybe the new update "cleared the cache", so to speak, and synced everything again. See if you can reproduce the original issue:
1. Install on several computers.
2. Switch it off on all but one computer.
3. Add sites to be synced on the one active computer.
4. Switch it on on all the other computers.
5. Are the sites synced?

**Comment by terrorist96** [comment] 2019-02-07 12:45
Here's another issue: I added github as a site to be inverted on one computer yesterday. It synced with a second computer. But on a third computer, it did not sync, and if I disable/enable the extension from the extension page (chrome://extensions) then it synced.

**Comment by alexanderby** [comment] 2019-02-08 08:59
I checked that the extension the extension properly uses Chrome API for syncing settings. I will try to reproduce the issue on multiple computers, there could be some Google issue.

**Comment by terrorist96** [comment] 2019-02-16 16:43
So here's another issue: I added two more sites on one laptop. None of the other computers synced and even if I toggle the extension on/off in `chrome://extensions`. I open the one computer where I added the two sites and it was still showing there. I toggle the extension on/off and it "syncs" to remove those two sites.... so I had to add them again manually. :roll_eyes:

**Comment by mmseng** [comment] 2019-06-15 05:22
I'm also having strange syncing behavior. It seems like the syncing only happens when chrome is completely closed on all of the computers. And which computer's changes win out seems to depend on which computer had chrome open last.

**Comment by doronbehar** [comment] 2019-06-20 03:46
I'm also having sync issues, on Firefox. I don't even have many devices with the extension installed and I never feel like any website's URL is synced.

**Comment by fgimian** [comment] 2019-07-07 12:49
I can confirm the issue exists with Firefox, I just tested it out.  My site list was definitely not synced when signing into a fresh profile and letting Firefox sync.  Is there any way to solve this?  Would be extremely handy 😄 

Thanks heaps!
Fotis

**Comment by zheyuanWang** [comment] 2019-11-13 08:45
![Screenshot from 2019-11-13 09-44-06](https://user-images.githubusercontent.com/39280197/68747123-31948000-05fa-11ea-8fdf-7de3e162a805.png)

yeah, loading for 30 min, while I am searching all kinds of solutions on the same computer...

**Comment by mehmetaergun** [comment] 2019-11-16 12:45
> I can confirm the issue exists with Firefox, I just tested it out. My site list was definitely not synced when signing into a fresh profile and letting Firefox sync. Is there any way to solve this? Would be extremely handy smile
> 
> Thanks heaps!
> Fotis

I can confirm this too. I installed the extension on the latest stable Firefox version (Windows 7, up-to-date) yesterday and added a number of sites to the list during regular use. I made sure Fx sync'd before closing it. Today, I launched Firefox (latest version) on a different system (Ubuntu 16.04, up-to-date). Upon sync, the extension was installed but the sitelist was empty. 

PS. Is there a way to export the sitelist in a way I can import to another browser.
PSS. Sitelist-like functionality works well on ublock origin -their code could be used as a point of reference?

**Comment by prohtex** [comment] 2020-05-27 21:56
Any hope for syncing in Safari or with iCloud?

**Comment by Gusted** [comment] 2020-05-27 22:08
We are working on a import/export settings page.
I think syncing with third party's will give a lot of work to fit everyone's favourite syncing method. And of course a lot of privacy people will get triggered like always for no reason.

**Comment by prohtex** [comment] 2020-05-27 22:10
> We are working on a import/export settings page.
> I think syncing with third party's will give a lot of work to fit everyone's favourite syncing method. And of course a lot of privacy people will get triggered like always for no reason.

Thanks! Would there be some way to specify the location of the preferences file? Then it could be located on a user's Dropbox, iCloud drive, etc?

**Comment by Gusted** [comment] 2020-05-27 22:14
> Thanks! Would there be some way to specify the location of the preferences file? Then it could be located on a user's Dropbox, iCloud drive, etc?

Ehm let's speak for Windows 10. I don't know for Safari.
If you save a file with the same name Windows 10 will cache the directory where you last saved that file so if you export the settings again you only will need to click on the old settings so you will overwrite it and not append and increase useless storage... For other operating systems? I don't know I don't use them, we rely on the browser to let them provide a directory where it will save to we have 0% impact on that or could change that.

**Comment by fgimian** [comment] 2020-05-27 23:26
Just thought I'd also mention https://github.com/darkreader/darkreader/issues/615 which demonstrates how you can manually backup and restore settings for Firefox.  This may be a useful stopgap solution until syncing arrives 😄

**Comment by maciex** [comment] 2020-05-29 16:38
@alexanderby Maybe you could send a similar test/debug function for Firefox? It's not working for me on FF 76.0.1

**Comment by Gusted** [comment] 2020-05-29 16:49
`For Firefox a user must have Add-ons checked under the "Sync Settings" options in "about:preferences".` And make sure you are logged into a profile.

**Comment by maciex** [comment] 2020-05-29 16:50
I'm logged and I have "Add-ons" selected in `about:preferences` "Syncing: ON".

**Comment by Gusted** [comment] 2020-05-29 16:52
Than I will debug and see what's the problem later today. Bit unfortunate if Firefox user's wont sync.

**Comment by maciex** [comment] 2020-05-29 17:06
I have a local Mozilla sync server, but other extensions (just tested one) are syncing just fine.

**Comment by Gusted** [comment] 2020-05-29 17:07
Can you name some extension than I will check how they sync for Firefox and compare it.

**Comment by Gusted** [comment] 2020-05-29 17:31
https://i.imgur.com/ReqVtIp.gifv Can't reproduce.

**Comment by maciex** [comment] 2020-05-29 17:36
I tested using https://github.com/maciex/play-to-kodi
Some setting saving code is here, nothing fancy:
https://github.com/maciex/play-to-kodi/blob/features/beta_all/js/settings.js#L142

This extension is ported from Chrome to Firefox by me, so these are first steps in extension dev and my first port. So keep that in mind.

I see that darkreader uses `storage.sync` and `storage.local`, so you probably  won't find anything new in that extension. Maybe the `storage.local` is used in some place where `storage.sync` should be used? Just a guess...

**Comment by Gusted** [comment] 2020-05-29 17:39
No we use both for fallback etc. sync is being called first when saving.

**Comment by maciex** [comment] 2020-05-29 17:42
Checked your "video".
You're testing it the same browser in the same browser profile, just removing and reinstalling the add-on. My use case is two different browser processes with separate browser profiles, both have the same Firefox sync profile setup.

**Comment by Gusted** [comment] 2020-05-29 17:48
Different Browser -> Problem.

**Comment by maciex** [comment] 2020-05-29 18:08
So what the sync is for if not for syncing between browsers/profiles?

**Comment by Gusted** [comment] 2020-05-29 18:11
Ask browser we are just a extension who use their API for syncing we cant change that.

**Comment by maciex** [comment] 2020-05-29 18:15
[Wiki Mozilla: Services/Sync/Addon Sync: Are Add-on Settings Synchronized?](https://wiki.mozilla.org/Services/Sync/Addon_Sync#Are_Add-on_Settings_Synchronized.3F)

**Comment by Gusted** [comment] 2020-05-29 18:24
I will see what I can do but it can't event reproduce it.

**Comment by fgimian** [comment] 2020-05-30 01:26
Perhaps the best way to reproduce it would be:

1. On a fresh Firefox install, login with your account
2. Install the addon and add a few sites to the site list
3. Exit Firefox
4. Completely delete the Firefox folder containing all profiles
5. Start Firefox again (this should create a brand new profile)
6. Sign into your account
7. You should notice that Dark Reader is installed, but the site list is empty again

Huge love
Fotis

**Comment by Gusted** [comment] 2020-06-01 20:37
After A while?
Is that minutes? Seconds? Hours?
It could be Mozilla can have a rate limit on it?

**Comment by fgimian** [comment] 2020-06-02 03:57
I honestly didn't time it, but it seemed to take several minutes.

**Comment by Gusted** [comment] 2020-06-04 18:32
That could sign on that Mozilla have a rate limit for their sync server to not get their servers overspooled with requests.

**Comment by Gusted** [comment] 2020-11-22 19:14
#4117 resolves this issue.

**Closed by Gusted** 2020-11-22 19:14 UTC

**Comment by zeroepoch** [comment] 2022-07-21 05:31
> So here's another issue: I added two more sites on one laptop. None of the other computers synced even if I toggle the extension on/off in `chrome://extensions`. I open the one computer where I added the two sites and it was still showing there. I toggle the extension on/off and it "syncs" to remove those two sites.... so I had to add them again manually. roll_eyes

Thanks for the tip on quickly toggling the extension on and off (on an out of sync computer). That resolved my sync issue between 3 computers the minute I did that. I think I got into this state because I was not syncing extensions at all on one system and recently started syncing all Chrome settings.
