### ISSUE TITLE
Wikimedia Foundation websites bugs

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#12763] opened 2024-05-26 23:04 UTC
After the merge of https://github.com/darkreader/darkreader/pull/12754, I am seeing some bugs for dynamic theme.

Both screenshots below from the English Wikipedia:

![image](https://github.com/darkreader/darkreader/assets/30274161/690a8b94-371b-4e46-b7cf-07a750ef5718)

![image](https://github.com/darkreader/darkreader/assets/30274161/0f1e0eb1-6c5d-4934-b340-ad5bd4c8eb7b)

Making this issue to track all bugs related to Wikimedia Foundation websites.

**Comment by Myshor** [comment] 2024-05-27 08:15
Sorry... I won't help 😏

I checked what's going on in this examples and made fixes already. 😉

**Comment by Myshor** [comment] 2024-05-27 08:26
@Tiagoquix If you find something more you can put it here then I will reopen and we try to find solution for new problems. 😉

**Comment by Myshor** [comment] 2024-05-28 06:54
Added new selectors to the border color fix.
Sitefix will be here in a minute. 😉

**Comment by Myshor** [comment] 2024-05-29 07:07
I will take a look on your examples. Reopening issue. :)

**Comment by Myshor** [comment] 2024-05-29 08:21
> Wikibooks logo is inverted. Probably should not be.

It must be inverted as there are black text in this picture.
![obraz](https://github.com/darkreader/darkreader/assets/56877029/951ac67b-223b-4bc0-859f-fb8b8ed653db)

For wikimedia... it could not be inverted but it shares the same class as other logos (.mw-wiki-logo) and when this class is removed then other pages can have not visible parts of logo. Maybe it's a little bit lighter than original but it's at least readable.

To have some logos not inverted and some inverted then we should revert all merges for wikimedia into one fix and put fixes to separate pages again.

For the rest not mentioned in this comment I made a quick fix that I will push in a minute.

**Comment by Myshor** [comment] 2024-05-30 09:12
> By this you mean the white border at the top (and not the logo itself)?

I mean the logo itself...

The white border I could not reproduce yesterday but today I managed to do this... there was some `!important` part missing forcing settings in sitefix.

And I changed the color for the fixes to set correct when dark or light theme for darkreader is selected.

Fix will be in a minute. :)

**Comment by Myshor** [comment] 2024-05-30 09:17
Fix in #12777

**Comment by Myshor** [comment] 2024-05-31 07:31
For the light color on hover... there was some bug with some png file with some diagrams / mind map (or it was some math calculations) that was invisible on dark background so we made quick fix which makes transparent background for pictures lighter on hover... and we will leave it as it is. 😋

For the borders in this file site... I added forced setting for variable with the border color as it was not set at all on this site... and add one more selector because there still was 1 lighter border after fitst fix.

**Comment by Myshor** [comment] 2024-05-31 07:42
One more comment for that SPQR picture with "to light color" under text... it's picture with that effect - nothing can be changed... as you can see - when light background is added with hover it's not looking "strange" anymore...

That's  why we left that background adding for transparent pictures to have possibility how they look without Dark Reader enabled. 😉

**Comment by Myshor** [comment] 2024-06-17 17:34
This will be fast fix - just adding invert.

**Comment by Myshor** [comment] 2024-06-24 08:21
Template fix will be pushed in a minute (I hope I won't break anything different) 😋

For the different tones of dark I won't touch it as I already touched it after your comment https://github.com/darkreader/darkreader/issues/12763#issuecomment-2172277704
There was different tone because there was color force in sitefixes for that place. So when I apply "fix" for one page it breaks other. As it is not big and critical I would not touch it anymore.

Last mention - different colors on mobile and desktop... Like you shown the original colors without DarkReader it is the same "issue" without DarkReader so I wound not touch anything here either.

**Comment by Myshor** [comment] 2024-06-25 09:54
> Alert: scary penguin!

Told ya 

> (I hope I won't break anything different) 🤣

I will make the selector for that template I fixed last time more detailed so there won't be scary penguins anymore. 🙂

**Comment by Myshor** [comment] 2024-06-25 11:26
Check if newest sitefixes are fetched... it's the same issue that was with Tux. I can not reproduce it with newest fix. 😉

**Comment by Myshor** [comment] 2024-06-28 07:52
Told ya I bet I will break something...

Sometimes it's better to leave one problematic page than break others...

Ok... I will go back to https://en.wikipedia.org/wiki/Rishi_Sunak and try to include this one svg.png in invert but If there will be more I would really consider if it's good to add all of that problematic pictures to invert separetely because the sitefixes will end with separate pictures inversion in wikimedia section 🤣

**Comment by Myshor** [comment] 2024-07-07 09:19
It seems it's setting wrong color variable sometimes for the background.
Forcing the variable which is set after making Dark Reader on/off on this page.

**Comment by Myshor** [comment] 2024-07-22 09:56
Color forced in html by wiki. 😋
I will push sitefix in a minute. 😉

**Comment by Myshor** [comment] 2024-07-22 14:29
One more fix in a minute.

**Comment by Myshor** [comment] 2024-07-23 14:46
> The color of the brackets are too "white" compared to the other white colors used in the page.

I push fixes to all except this one... After analysys the color is exactly the same as underline on the top. 😝

And this one: > Not exactly wrong, but the squares filled with colors look a bit off when compared to Dark Reader OFF.

The colors in boxes are exactly the same... there is an optic illusion that they are looking brighter because they are on the dark background.

**Comment by Myshor** [comment] 2024-08-01 10:25
The fix for Old Norse is not perfect, but It's better than this shown above.
![obraz](https://github.com/user-attachments/assets/58274c60-996a-40ac-a0dc-d3b3c95912cc)

I'll push all in a while.

**Comment by Myshor** [comment] 2024-08-01 14:35
I had to choose 3 options. 

1. Leave background colors untouched but then it would be needed to leave dark text to have it readable.
2. Same as above but adding invert which ends with white text and darker background. (This is used now in fixes).
3. Add text shadow to the text. (I even didn't think of making this to wiki because it would make text styling different)

**Comment by Myshor** [comment] 2024-08-02 09:51
I will add fix for catched issues however I will need to think if revert about forcing different colors and IGNORING INLINE can be more problematic as I thought. We will see.

For that lighter color for statuses. I am not touching it. I spent almost half an hour to do that locally and in the end it totally breaks appearance when light theme of Dark Reader is enabled.

For that infoboxes color problems If you find more problems then I will think about revert for all INLINE IGNORING.

**Closed** 2024-08-02 09:56 UTC
Labels: Broken Website

**Comment by Myshor** [comment] 2024-08-02 11:48
Adding one more fix (I bet it's not last. 😞)

**Comment by Myshor** [comment] 2024-08-02 11:55
And I propose to leave this bug closed and untouched and if you find some new issues on wikipedia then create new bug. My email which is grouping all notifications from this issue shows new ones below my whole screen and I need to scroll all that to see what's new here. 😂
