### ISSUE TITLE
[Bug] Sunset/Sunrise times don't activate after wake-up from suspend?

### ISSUE THREAD

**Issue by tmladek** [darkreader/darkreader#7041] opened 2021-10-08 11:19 UTC
# Bug Report

## Bug Description
When I suspend my computer while it's dark, and then wake it up after sunrise, Dark Reader does not switch off. I need to go to the settings, and toggle the "Automation" setting off and on, after which it (de)activates as expected.

I am not sure if this appeared in a recent version or if I simply hadn't ran into the issue before.

## Website Address
N/A

## Steps To Reproduce
- Activate Automation based on location and sunset/sunrise times
- Wait for the sun to set
- Suspend computer
- Go to sleep, wait for the sun to rise
- Wake up computer

## Expected Behavior
Dark Reader would be disabled. (Perhaps after some periodic interval has passed; I'm not sure it's possible to detect suspend/wake up events from the browser.)

## Actual Behavior
Dark Reader is still enabled as if it still were nighttime.

## Screenshots
N/A

## System Information
- OS: Arch Linux
- Browser: Firefox 93
- Dark Reader Version: 4.9.39

**Comment by jonschlu** [comment] 2021-10-10 10:52
Same here, and I can recreate it in all automation modes. Also FF latest version. Happens since a couple of weeks.

**Comment by bershanskiy** [comment] 2021-10-10 21:24
I think this is a browser bug in Alarms API (since Alarms are supposed to be fired even when background context is unloaded). I need to do more testing to file a Chromium/Firefox bug report.

Re to @tmladek:
> I am not sure if this appeared in a recent version or if I simply hadn't ran into the issue before.

It is likely a recent regression. Dark Reader used to run a loop which would check the time every 10 seconds. In #6347 we switched to Alarms API which apparently do not fire if time expires when computer is shut down.

Re to @Gusted:
> Is their some kind of event listener that we could use to just check this once the background page is enabled again after a long period of time?

I'm not aware of any such event. However, we can perform a time check once on every background context invocation (we can keep a non-persistent global flag which will be reset on every background reload). I can add this work-around in Tab Manager message handler logic to "fire" a shim alarm if needed. This is a rather poor solution, but it should work.

Re to @jonschlu:
> Happens since a couple of weeks.

For future, please consider reporting bugs as they arise and not waiting for weeks.

**Comment by bershanskiy** [comment] 2021-10-10 21:30
Testing results:

When browser is closed but PC is ON, alarms fire.
Steps:
 1. Enable automation with change 1 min into the future.
 2. Note the current state of Dark Reader
 3. Close the browser (all tabs)
 4. Wait for 2 minutes
 5. Open browser and note that Dark Reader changed state

**Comment by bershanskiy** [comment] 2021-10-11 21:29
I am able to reproduce this bug. Repro steps:
1. Install Dark Reader, enable automation
2. Set automation start time one minute into the future and end time to at least two minutes into the future
3. Note that Dark Reader is OFF
4. Activate "sleep" mode
5. Wait for one minute
6. Wake up computer
7. Note that Dark Reader is OFF
8. Click automation twice
9. Note that Dark Reader turns ON

**Comment by bershanskiy** [comment] 2021-10-20 19:11
I am no longer able to reproduce this on Chrome 94.0.4606.81 (Official Build) (64-bit).

**Comment by lumbo7332** [comment] 2021-10-20 21:35
I can still reproduce this bug on Firefox 93.0.

**Comment by ivashin** [comment] 2021-11-06 06:26
Still reproducible on Firefox 94.0 + Dark Reader 4.9.40 (Manjaro Linux)

**Comment by bershanskiy** [comment] 2021-11-06 07:59
I used to be able to reproduce this, but I'm not able now. Will continue investigating.

**Comment by lorenzofanchi-enpicom** [comment] 2021-11-10 07:14
Still reproducible on version 4.9.42 on Edge 95.0.1020.44 on macOS 12.0.1

**Comment by lorenzofanchi** [comment] 2021-11-10 07:15
Still reproducible on version 4.9.42 on Edge 95.0.1020.44 on macOS 12.0.1

Anything I can do to help pin this issue down?

**Comment by bandgeekdante** [comment] 2021-11-24 02:42
I am getting this issue on Chrome 96.0.4664.45 and Dark Reader 4.9.42, and it happens both when I enter geographic coordinates and when I try to sync it with the system theme.

**Comment by Gusted** [comment] 2021-11-24 08:33
@bershanskiy Given that the calculating if the extension is enabled or not is fairly performant, we could include the check(on a `debounce`) when we get a new site, it isn't the most optimal solution, but it will work better than in the current form.

**Comment by LordMethenor** [comment] 2022-01-23 16:01
I am having the same issue, both on windows when waking from sleep and on chrome OS (with light dark theme flag) when toggling the theme in quick settings disabling and re enabling 'use system color scheme' solves the issue

**Comment by ShinobiWPS** [comment] 2022-04-06 17:52
I add my occurence to confirm the bug on Windows 10 on Firefox 99

**Comment by iwconfig** [comment] 2022-04-23 11:42
Same issue with hibernation here: Debian 9, Firefox 99

**Comment by ThomasOrlita** [comment] 2022-05-05 06:11
Perhaps this (Chrome) API could help detecting the idle state to recheck to media query.

https://developer.chrome.com/docs/extensions/reference/idle/#event-onStateChanged

**Comment by Gusted** [comment] 2022-05-05 22:16
Seems to be somewhat use-able API. I will make a patch soon and generate a build(my current setup doesn't really like suspending).

**Comment by shtrom** [comment] 2022-05-24 00:44
Same issue on

* OS: OS X Monterey 12.4
* Browser: Firefox 100.0.1
* Dark Reader Version: 4.9.50

**Comment by dnut** [comment] 2022-06-01 18:05
It seems that the design choice of relying on the alarms API is conducive to flakiness. Even if the bug in the alarms API is fixed, I'd be concerned about running into new issues in the future that result in the event not being received. Generally speaking, the implementation is overly stateful, which exposes us to unnecessary risk of staleness.

Why not check the time whenever a page needs to be rendered?

**Comment by Gusted** [comment] 2022-06-04 17:59
> It seems that the design choice of relying on the alarms API is conducive to flakiness. Even if the bug in the alarms API is fixed, I'd be concerned about running into new issues in the future that result in the event not being received. Generally speaking, the implementation is overly stateful, which exposes us to unnecessary risk of staleness.

Please redirect your concern to Google/Chromium([they won't listen anyway](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/veJy9uAwS00/m/9iKaX5giAQAJ) to my experience) which are requiring this change by their "wonderful" new Manifest V3. This is the only reliable way of executing a certain task at X time(when some unknown bug is fixed) when [the background script isn't persistent](https://developer.chrome.com/docs/extensions/mv2/background_migration/#timers) which would be the new behavior of v3. 



> Why not check the time whenever a page needs to be rendered?

Because people expect when the clock hits the user defined time dark reader will do it's thing instead of requiring opening a new page to "wake up" Dark Reader.

**Comment by dnut** [comment] 2022-06-06 13:18
> Because people expect when the clock hits the user defined time dark reader will do it's thing instead of requiring opening a new page to "wake up" Dark Reader.

That actually sounds annoying. You're in the middle of reading an article, and suddenly it flashes to the opposite color? Not something I would have expected or desired.

To be clear, this just means that you need to rely on the alarms API to support the specific feature of spontaneous re-rendering. It doesn't mean checking the clock on render is not an option, does it? It just means that you'd have to support two mechanisms instead of one?

**Comment by Gusted** [comment] 2022-06-08 07:04
> That actually sounds annoying. You're in the middle of reading an article, and suddenly it flashes to the opposite color? Not something I would have expected or desired.

Well nobody _ever_ complained about the behavior, but please open up a new issue if this behavior should change/be configurable.



> To be clear, this just means that you need to rely on the alarms API to support the specific feature of spontaneous re-rendering.

Yeah, if we want to execute a function at x time, you now require to use the alarms API.



> It doesn't mean checking the clock on render is not an option, does it?

It's _possible_ to modify the code in order to be this an option.



> ? It just means that you'd have to support two mechanisms instead of one?

Yup, but that's not really unusual if there's a general consensus that this is a behavior that is "expected".

**Comment by sunhch** [comment] 2022-06-27 04:02
Same issue on Mac OS 12.4 + Chrome 103.0.5060.53 + Dark reader 3.9.51

**Comment by bershanskiy** [comment] 2022-06-28 14:32
I am able to [reproduce](https://github.com/darkreader/darkreader/issues/7041#issuecomment-940456221) this with 4.9.51, will look into it more.

**Comment by bershanskiy** [comment] 2022-06-30 08:41
I can no longer reproduce this bug on Chrome 103.0.5060.66. I tried 4.9.52 and `6203ec47ec1ae76cc5c3ab7d9e281312c44ead06`. Can't continue working on it.

**Comment by FrankSFLYS** [comment] 2022-08-06 11:06
I can reproduce this issue on both my computers (Windows 11, Edge). I think this can be fixed by checking system color actively. When I change the setting it instantly switches color scheme. So this switch action can be performed more frequently to avoid the bug.

**Comment by bershanskiy** [comment] 2022-08-06 18:43
@FrankSFLYS 

> I think this can be fixed by checking system color actively.

This bug is about time automation, not system color automation. Are you talking about "time" or "system" automation?

**Comment by FrankSFLYS** [comment] 2022-08-09 00:45
> Are you talking about "time" or "system" automation?

Yes... I was talking about system color automation. I was redirected here from #6948 and didn't look into the question.

**Comment by nocibambi** [comment] 2022-08-24 08:41
Having the same issue on Firefox 103.0.2, Ubuntu 20.04 and 22.04.

**Comment by bensums** [comment] 2022-09-21 06:10
Same issue here Dark Reader 4.9.57, Firefox 103.0.2, Manjaro.

**Comment by bershanskiy** [comment] 2022-09-21 21:24
I found a way to reproduce this bug reliably:

Platform: Google Chrome 105.0.5195.125 on macOS Montrey 12.6 on MacBook Pro (Retina, 13-inch, Early 2015) with 8GB RAM
Repro steps:
 - Open Google Chrome with Dark Reader installed
 - Open only protected tabs where extensions do not run (e.g., new tab page)
 - Set Dark Reader into Time Automation with a start time one or two minutes into the future
 - Make sure Dark Reader is still OFF, and make Mac go to sleep
 - Wait for two or three minutes for the automation time to pass
 - Wake up Mac from sleep
 - Observe that the Dark Reader icon is "OFF", open example.com and observe that Dark Reader is really off (page is white)
 - Toggle Automation OFF and then ON again to force it to re-calculate extension state, observe that extension turns ON, as it should

**Comment by bershanskiy** [comment] 2022-09-22 18:46
I tested again and found out that on aforementioned Google Chrome on macOS Montrey 12.6 on MacBook Pro the alarms do not fire at all. Repro steps:
```js
chrome.alarms.onAlarm.addListener(console.log);
chrome.alarms.create({when: 5});
```
Expected: alarm fires immediately, since Unix time `5` passed in 1970.
Real result: sometimes (no clear indication of why) under some circumstances the alarm does not fire.

This seems like a Chrome bug and not a DR bug.

**Comment by rkraneis** [comment] 2022-11-18 08:18
Chrome bug or not, still a problem with version 107.0.5304.110. It's a shame Chrome is so pervasive nowadays. DR+FF works a charm for me, just following the system color scheme (which I have automated).

**Comment by rkraneis** [comment] 2022-11-18 08:24
This Chromium bug looks related: https://bugs.chromium.org/p/chromium/issues/detail?id=471524

**Comment by Thrywyn** [comment] 2022-12-03 13:17
Having this exact same issue on Edge, Windows 11 using Windows Auto Dark Mode.

**Comment by Gusted** [comment] 2022-12-14 14:16
> We have a clear solution to this problem that doesn't rely on upstream fixes. What's delaying the implementation? Lack of developer resources? Should I open a PR?

Well, I would be happy to solve this, but I never figured out the real cause (only that it's really flaky due to browser implementations). @bershanskiy on the other hand had a quite good idea of the issue and how to solve it and made a lot of changes regarding this, but seems like there's still nits that needs to be figured out. I'm not happy about it either, as I'm still catching up with all the new code and how and what is currently impacted.

>  All new page loads will automatically be the correct color. 

This is actually already somewhat within Dark Reader and one of the suggested solutions by @bershanskiy, but I don't think it currently exists for the sunset/sunrise mode, I think it's reasonable to add this, given there aren't much other solutions.

**Comment by bershanskiy** [comment] 2023-01-22 23:44
I just managed to reproduce this bug, will try to fix it.

**Comment by bershanskiy** [comment] 2023-01-23 01:14
Unfortunately the typical page visibility check does not fire on wakeup, so we either need to check for a different event or accept that the time change will not be exact (upon user switching tabs or navigating current tab in a way which results in tab reload).

Using `idle` API is also an option, but it requires a warning-less permission `"idle"`.

I also tried `setTimeout()` in page context and it has the same bug. I found a way to detect wakeup using an autoplaying `<video>` and a `pause/play` event. Unfortunately, it triggers even when user simply changes tabs.

I'm on the fence here, but leaning toward using `idle` API for MV3 builds and using a simple check for expired timers on background context invocations.

**Comment by bershanskiy** [comment] 2023-01-24 12:51
I found the culprit here. It is indeed [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=471524). The problem is that internally Chromium uses the same back-end for `setTimeout`, `setInterval` and `chrome.alarms` and stores timers as time offsets relative to the current page epoch.

In particular:
[`chromium/extensions/browser/api/alarms/alarm_manager.cc`](https://github.com/chromium/chromium/blob/632253d2829cb69bc6b7c54892fa87e4adc47dd3/extensions/browser/api/alarms/alarm_manager.cc#L353) converts absolute `base::Time` into a `base::TimeDelta`:
```C
void AlarmManager::SetNextPollTime(const base::Time& time) {
  next_poll_time_ = time;
  timer_.Start(FROM_HERE, std::max(base::Seconds(0), time - clock_->Now()),
               this, &AlarmManager::PollAlarms);
}
```

**Comment by rwjack** [comment] 2023-02-26 10:04
2 Years later according to this issue, this bug still occurs.

FF latest on PopOS 22.04

**Comment by newjunkcity** [comment] 2023-03-24 11:06
Bug still occurring on FF 111.0.1, Ventura

**Comment by xrad** [comment] 2023-03-29 06:00
> I found the culprit here. It is indeed [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=471524). 

Have you checked if FF contains a similar bug? It seem many FF users are affected by this issue. I have also been wondering if alarms that go off during suspend could simply be dropped, so the extension would somehow need to detect a resume and then manually run the automation logic to detect a possible transition.

**Comment by shtrom** [comment] 2023-03-29 07:23
I (still) have the same issue in FF.
-- 
Olivier Mehani ***@***.***>
Sent from my mobile, please excuse my brevity.

**Comment by pschiffe** [comment] 2023-04-25 06:28
Still happening for me on firefox-112.0.1-1.fc38.x86_64, fedora 38

**Comment by kholgate** [comment] 2023-05-15 00:48
Happening non stop on firefox. 

113.0.1

**Comment by bcutter** [comment] 2023-05-22 18:48
https://github.com/darkreader/darkreader/issues/10302

+

https://github.com/darkreader/darkreader/issues/10302#issuecomment-1557728480

**Comment by rifuller** [comment] 2023-06-13 23:50
Still broken.

**Comment by Zorgodon** [comment] 2023-08-31 10:55
Still not fixed!

**Closed** 2023-11-20 16:52 UTC
Labels: bug

**Comment by alexanderby** [comment] 2023-11-20 16:54
I've made a fix, it will be published after Thanksgiving Day.

**Comment by rohanssrao** [comment] 2023-12-05 15:38
@alexanderby Thank you! It's working for me on version 4.9.70. However, it's a bit slow to recognize the change, IMO, with the check interval being 1 minute.
```js
const WAKE_CHECK_INTERVAL = getDuration({minutes: 1});
```
Does this check have a significant performance penalty that would prevent the interval from being something shorter, such as 10 seconds?
