### ISSUE TITLE
[BUG] Popup pages opened using window.open show white background for a fraction of second before turning to dark

### ISSUE THREAD

**Issue by yesvivek** [darkreader/darkreader#3710] opened 2020-09-25 13:46 UTC
### **Describe the bug**

Popup pages opened using `window.open()` show white background for a fraction of second before turning to dark.

### **Steps to reproduce**

- Access any page using window.open with specs option (3rd argument) to open a popup window, refer below code,
`window.open("https://www.w3schools.com", 'W3Schools', 'width=1024, height=768, scrollbars=1, resizable=1, menubar=1');`
- Or check [this page](https://codepen.io/yesvivek/pen/MWyRbEm).
- White background is seen for a fraction of second before turning to dark

### **Expected behavior**

The splash of white background should not be seen.

### **Actual behavior**

The splash of white background is seen for fraction of a second.

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 - Dark Reader version: 4.9.20

**Comment by Gusted** [comment] 2020-09-26 08:32
Hi @yesvivek!

Do you have system-wide dark mode enabled(In the windows settings)?

Regards,
Gusted

**Comment by yesvivek** [comment] 2020-09-28 06:48
Yes @Gusted, I have enabled systemwide Dark mode in Windows 10.

**Comment by Gusted** [comment] 2020-09-28 06:53
Could you try 4.9.21 as well?
Also I couldn't reproduce this problem on 2 whole different machines so far, do you have anything specials?

**Comment by yesvivek** [comment] 2020-09-28 06:57
I will host a minimal code to repro this. Give me a min please..

**Comment by yesvivek** [comment] 2020-09-28 07:11
I see this issue when clicking on "Pop it" button on https://codepen.io/yesvivek/pen/MWyRbEm page.

**Comment by Gusted** [comment] 2020-09-28 07:17
Hi @yesvivek!

I have suchs feeling that this is a chromium issue itself and reproduce-able without dark reader.
E.g.
Remove dark reader completly.
Change the `window.open` to
```javascript
window.open("https://store.steampowered.com", 'W3Schools', 'width=1024, height=768, scrollbars=1, resizable=1, menubar=1');
```
Steam store is dark by default.
And I see that I get that same weird white flash.

**Comment by yesvivek** [comment] 2020-09-28 07:25
I think you are correct @Gusted, I see white flash on steampowered.com without add-ons. Thank you for looking at this.
You can close this if it wont serve any purpose anymore.

**Comment by Gusted** [comment] 2020-09-28 07:26
> You can close this if it wont serve any purpose anymore.

It doesn't seem dark reader's problem anymore so I guess closing this and you could make a issue over at [Chromium bug list](https://bugs.chromium.org/p/chromium/issues/list)

**Closed** 2020-09-28 07:27 UTC
Labels: bug
