### ISSUE TITLE
darkreader overrides firefox browser theme on startup

### ISSUE THREAD

**Issue by LUS1N** [darkreader/darkreader#1613] opened 2019-10-08 07:14 UTC
Hi, I am using DarkReader together with firefox native dark theme and tree style tabs, every time I start the browser the dark firefox theme gets overridden with the less dark DarkReader theme, which I prefer less than the native one and it screws with the tree style tab a bit.

In order to fix it I have to go to settings and flip the firefox theme off and on again for it to come back up. That is quite annoying.

Would it be possible to not change the browser theme? maybe have an option to leave the browser theme unchanged, I think it would also be useful for other people that want to use different themes.

Expected:

![image](https://user-images.githubusercontent.com/10304156/66374513-7dc12480-e9ab-11e9-968d-b5bc93ba306d.png)

Actual:

![image](https://user-images.githubusercontent.com/10304156/66374534-8ade1380-e9ab-11e9-8f50-660307f1979c.png)

Otherwise loving the extension!

**Comment by heitorPB** [comment] 2019-10-14 21:01
I think this is related to #1593

**Comment by boltgolt** [comment] 2020-01-20 09:33
Might be related, but not the same issue. I have to disable and re-enable my browser theme on every startup

**Comment by boltgolt** [comment] 2020-01-20 10:42
The issue is in [this commit](https://github.com/darkreader/darkreader/commit/181ec067486ab4602d6d1c78ed5be9eac089139d), which switches between browser light or dark theme when the plugin is toggled. It's fixed by disabling the `resetWindowTheme` and `setWindowTheme` functions in background/index.js, but that's hard to keep working in normal firefox because the plugin will become unsigned

**Comment by brandonchastain** [comment] 2020-02-10 00:57
DarkReader should allow the user to configure that option from the GUI.

**Comment by boltgolt** [comment] 2020-02-10 01:04
Definitely, it's actually a really annoying issue for me because this bug causes my `about:newtab` page to be bright white

**Comment by Gusted** [comment] 2020-10-19 01:16
Preview Design Under Settings
![](https://i.imgur.com/ZeDD3S5.png)
Old Design under More
![](https://i.imgur.com/e87NBjJ.png)

**Closed by Gusted** 2020-10-19 01:16 UTC
