### ISSUE TITLE
[BUG] Can't Enable/Disable on discordapp.com and subdomains.

### ISSUE THREAD

**Issue by iGlitch** [darkreader/darkreader#2423] opened 2020-04-29 22:59 UTC
**Describe the bug**
Sorry, YET ANOTHER discordapp ISSUE. 
I can Enable or Disable (Alt+Shift+A) on most other websites just fine. But I cannot on discordapp.com or its subdomains (haven't tried them ALL). 
Was trying to find a way to disable it via internal settings such as a file on the computer, but no luck.

Edit: was able to find another website it didn't work on. So this can be an evergrowing list and not only discordapp. But let's just keep focus on discordapp because it could be the same bug that affects other sites. So fixing this one can probably fix em all for good :)

**To Reproduce**
> Go to 'discordapp.com'
> Click on the button to enable for current website.
> Stays enabled (check mark)

**Expected behavior**
Can turn on or off.

**Screenshots**
https://gfycat.com/gleefuldescriptivegoldenmantledgroundsquirrel

**System Information:**
 - OS: mac OS Catalina 10.15.4
 - Browser: Firefox Latest Beta
 - Version: 4.9.7

**Comment by Gusted** [comment] 2020-04-30 10:31
Duplicate of #773 A patch is on it's way to fix this, I hope alongside with the release of darkreader v5

**Closed by Gusted** 2020-04-30 10:31 UTC
Labels: bug
