### ISSUE TITLE
[Broken Website] Sagemcom home gateway control panel's login page

### ISSUE THREAD

**Issue by MPeti1** [darkreader/darkreader#3328] opened 2020-08-03 17:20 UTC
**Website**
I would say it's 192.168.0.1.. but it wouldn't mean much to you. Since it's a special case and you would need a specific ISP to test it, I'm open to get you every information that you need

**How to Reproduce**
1. Go to 192.168.0.1
2. That's all

**Expected behavior**
The login form appears as it should
![2020-08-03 19_12_58-Greenshot](https://user-images.githubusercontent.com/9215491/89209055-d8bcab80-d5bd-11ea-92ec-8967784f88ea.png)

**Actual behavior**
Sometimes when you load the page, the box containing the login form does not appear. You either need to reload the page a bunch of times (that does not always work, sometimes it stays bad even after the 10th attempt), or temporarily disable dark reader. 
![2020-08-03 19_12_50-Greenshot](https://user-images.githubusercontent.com/9215491/89209095-ed993f00-d5bd-11ea-9b35-9624284c2a89.png)

**System info:**
 - OS: Windows 10 1903
 - Browser: Firefox 79.0
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment] 2020-08-03 20:33
Are you Familiar with the devtools and how to use it?

**Comment by MPeti1** [comment] 2020-08-06 12:55
Yes, I think so, I use it frequently for different reasons. I've looked into the login page of my router's control panel earlier if I can see some major differences, but the divs that hold the form, and the form itself is always there. What I suspect is that there is a CSS attribute that causes this, but I'm not good enough in CSS to recognize which of them has such a side effect

**Comment by Gusted** [comment] 2020-08-06 14:00
Well, if you know that their isn't any personal details in the site you can make (with darkreader on) a ctrl + s to save the current state of the site, I could have a look. As If I see it, this could be a bug to get fixed within the code possibly.

**Comment by MPeti1** [comment] 2020-08-06 14:26
I haven't found any personal information in it, so here it is:

[HomeBox.zip](https://github.com/darkreader/darkreader/files/5035471/HomeBox.zip)

**Comment by Gusted** [comment] 2020-08-06 14:36
Mostly their is a HomeBox_files folder, could you include it as well?

**Comment by MPeti1** [comment] 2020-08-06 14:39
Haven't seen it, sorry! Should've had saved it into an other folder than Downloads :D
[HomeBox_elemei.zip](https://github.com/darkreader/darkreader/files/5035536/HomeBox_elemei.zip)

**Comment by Gusted** [comment] 2020-08-06 14:44
Hmmmm 
![](https://i.imgur.com/yVXvovS.png)

Welp this is a weird situation.
Could you try to add somethings special into the div like `background-color: red`

**Comment by MPeti1** [comment] 2020-08-06 15:17
To which one?

I've gone through the elements on this path (from body to the login form). The first word is the type, and the second is the id of the element (or class if it didn't have an id)
1. body
2. div main-ui-view
3. ui-view ng-scope
4. div ng-scope
5. div form-main has-frq
6. div form-div
7. div form-div-login

How did I add the attribute (just so we are in the same page):
1. selected the element on the left side
![kép](https://user-images.githubusercontent.com/9215491/89548216-09435600-d807-11ea-90bb-66d6a8b57ccd.png)

2. At every element I've added this attribute: `background-color: red`
![kép](https://user-images.githubusercontent.com/9215491/89548327-2d069c00-d807-11ea-94ee-6dbfadb4bcf6.png)


Up until the div with the id "form-div" (6. element above) there was no change when I added the attribute.
Only when I added the attribute to that one, did one of the magenta rectangles change it's color to red:
![kép](https://user-images.githubusercontent.com/9215491/89548818-c9c93980-d807-11ea-89a8-ae7f35605c1f.png)

**Comment by MPeti1** [comment] 2020-08-06 15:22
I'm trying to find out why doesn't the page work as it should for you, but now I can't even find how did I make the HomeBox_elements (elemei, for me) folder, Saving the page with Ctrl+S only saves the .html file

**Comment by Gusted** [comment] 2020-08-06 15:27
Hmm, I guess could you copy paste the in used background-color when you don't have the red background-color enabled.

**Comment by MPeti1** [comment] 2020-08-06 15:32
Not sure if I understand, could you elaborate?

**Comment by MPeti1** [comment] 2020-08-06 15:37
If you mean the default background color, then it is this: `rgba(176, 13, 96, 0.6)`
It seems to be coming from the element with these: `.has-frq #form-div`
![kép](https://user-images.githubusercontent.com/9215491/89551620-6fca7300-d80b-11ea-86ba-89bb8be7b4a1.png)

**Comment by Gusted** [comment] 2020-08-06 18:07
Hmm what if you reset it back to it's original value the one from `.has-frq #form-div` as well, but the crossed one.

**Comment by MPeti1** [comment] 2020-08-06 22:14
Could you describe more in detail what should I change?

**Comment by Gusted** [comment] 2020-08-06 23:25
set it to `background-color: rgba(226,0,116,0.6)` it's original value. While dark reader on.

**Comment by MPeti1** [comment] 2020-08-07 21:55
I've set the value, but the form did not appear.

![kép](https://user-images.githubusercontent.com/9215491/89691483-54459200-d909-11ea-843b-fefd88b92c58.png)

Please note that this is a fresh load of the page, so it only has this modification

**Comment by Gusted** [comment] 2020-08-07 23:14
Hmm try have it for other elements as well like the child elements etc.

**Comment by MPeti1** [comment] 2020-08-10 22:33
What is the goal with doing this? What should change by adding that background color property to different elements?

**Comment by Gusted** [comment] 2020-08-10 22:42
Detecting what's the wrong element and than make a fix according to it.

**Comment by MPeti1** [comment] 2020-08-11 15:30
Just asking so I better understand what should I do :)

> Hmm try have it for other elements as well like the child elements etc.

So do the same as before, but for all child elements of `#form-div` too, right? Should I skip greyed out elements?

An other question: how do I know if I found a wrong element? Is it that it inherits the background color from the parent element, but doesn't apply it if it's set directly on itself?

**Comment by Gusted** [comment] 2020-08-11 18:58
> So do the same as before, but for all child elements of `#form-div` too, right?

yes



> Should I skip greyed out elements?

no




>  how do I know if I found a wrong element?

You should see the element again.



>  Is it that it inherits the background color from the parent element, but doesn't apply it if it's set directly on itself?

I really don't know It seems like that the color is not being darkend correct.

**Comment by MPeti1** [comment] 2020-08-13 12:40
I've added `background-color: rgba(226,0,116,0.6)` as an attribute to every element below (and including) `#form-div` while Dark Reader was turned on.
[This](https://gist.github.com/MPeti1/d5b7d07caa8d0db4f8f6a161315cf02f) is the resulting HTML, and the form did not reappear

![kép](https://user-images.githubusercontent.com/9215491/90135383-dc48f300-dd72-11ea-8e8c-21b7e55b31ea.png)

**Comment by Gusted** [comment] 2020-08-13 18:25
Oh I'm so stupid every CSS you enter will be directly darken again so it will almost have 0 effect. You could try to add the css in dev tools under the site `*` and than CSS section.

**Comment by Gusted** [comment] 2020-08-23 16:56
> I have lost the trail at this point: `under the site *`. Could you elaborate?

![](https://i.imgur.com/aI4TnCM.png) It's the first site in devtools

The CSS should be under the CSS section so it won't be affected by dark reader(and be faulty darken again)

**Comment by MPeti1** [comment] 2020-08-23 22:05
Oh, _that_ devtools.

I've now added the attribute `background-color: rgba(226,0,116,0.6)` to be there
![kép](https://user-images.githubusercontent.com/9215491/90989919-5fe9b780-e59d-11ea-8b59-5fca1f901f59.png)

after that I clicked apply and reloaded the router's page, but the login form is still invisible

**Comment by Gusted** [comment] 2020-08-24 11:49
Oh it should be more like 
```CSS
.someSelectorClass {
    background-color: rgba(266,0,116,0.6) !important;
}
```
instead of
* background-color: rgba(266,0,116,0.6) !important;

**Comment by MPeti1** [comment] 2020-08-24 12:49
Ok, so I'm going to use the previous list for which selectors to try: 
1. body
2. div main-ui-view
3. ui-view ng-scope
4. div ng-scope
5. div form-main has-frq
6. div form-div
7. div form-div-login

Below I'll include what selector did I use in the place of `.someSelectorClass`, and it's effect in a screenshot, or writing just no change if there wasn't any.

Without custom modification, but dark reader still on:
(noticed when previewing comment: the background image was just changing when taking the screenshot)
![kép](https://user-images.githubusercontent.com/9215491/91045608-6f0d4b80-e617-11ea-9f5d-013f44a76ad1.png)

With #main-ui-view: no change

With .ng-scope:
![kép](https://user-images.githubusercontent.com/9215491/91046025-096d8f00-e618-11ea-9546-64ad9b8516b5.png)

with .form-main: same as without custom modification

with #form-div: no change

with #form-div-login: no change

with #form-login: no change

**Comment by Gusted** [comment] 2020-08-24 16:07
Hmm, I'm starting to run out of possibilities, By any change you know if any of the element used `z-index`? also instead trying with a `rgba` try `background-color: red` it could be the problem that the original color is also not visible on this

**Comment by MPeti1** [comment] 2020-08-24 21:05
>By any change you know if any of the element used `z-index`?

It seems like. I disabled Dark Reader to be sure that I only see the stylesheets of the site, and there are usages of z-index in these files: [lib.css, login-magyar.css](https://gist.github.com/MPeti1/dbe661753b53cdf363c6ebd22e88960c).


>also instead trying with a `rgba` try `background-color: red` it could be the problem that the original color is also not visible on this

Nothing changed :/

One weird thing though, is that sometimes when I load the page, new inline style sheets are getting created indefinitely for some reason. When this happens, I also see this error message, which reopens quickly after I close it:
![kép](https://user-images.githubusercontent.com/9215491/91094155-b537ce80-e65a-11ea-87fd-6a124aae3f44.png)

This stops when I disable Dark Reader for the current site, and did not occur for now while the page was loaded with it being turned off.

**Comment by Gusted** [comment] 2020-08-24 21:10
> It seems like. I disabled Dark Reader to be sure that I only see the stylesheets of the site, and there are usages of z-index in these files: [lib.css, login-magyar.css](https://gist.github.com/MPeti1/dbe661753b53cdf363c6ebd22e88960c).

Anything with negative z-index won't be displayed due our code base and `html` element and it seems like some of the listed element are negative
```CSS
#form-div-frame {
 background-color:rgba(226,0,116,.6);
 height:310px;
 margin:0;
 position:absolute;
 right:0;
 top:0;
 width:710px;
 z-index:-100
}
.has-frq #form-div-frame {
 background-color:rgba(226,0,116,.6);
 height:470px;
 margin:0;
 position:absolute;
 right:0;
 top:0;
 width:710px;
 z-index:-100
}
```
So I suggest to make fixes for those elements like
```CSS
#form-div-frame {
    z-index: 1 !important;
}
```
Also as it's going to be a permanent fix I recommend [styles](https://github.com/openstyles/stylus/) to use this CSS on as we don't provide any User CSS section what won't be removed next update.

> One weird thing though, is that sometimes when I load the page, new inline style sheets are getting created indefinitely for some reason. When this happens, I also see this error message, which reopens quickly after I close it:

Normal behavior never know why it do this, but it doesn't seem to give any problems so I'm not bother investigating this 🤷🏽‍♀️

**Comment by MPeti1** [comment] 2020-08-24 21:27
The developer tools confirms that the z-index value has been replaced with 1, but the form still does not appear:
![kép](https://user-images.githubusercontent.com/9215491/91098099-25e1e980-e661-11ea-8a34-800b6cef665a.png)


Added the style like this:
![kép](https://user-images.githubusercontent.com/9215491/91097743-8b81a600-e660-11ea-8f1d-5069d77028f2.png)

Enabled here:
![kép](https://user-images.githubusercontent.com/9215491/91097769-99372b80-e660-11ea-8c0d-7e3ff71875eb.png)

**Comment by Gusted** [comment] 2020-08-24 21:28
What if you try a higher value? Higher than the others.

**Comment by MPeti1** [comment] 2020-08-24 21:38
Tried with 10000, but it did not help

**Comment by Gusted** [comment] 2020-08-24 21:43
What if you just copy and paste [this](https://pastebin.com/raw/MN086zRW) stylus?

**Comment by MPeti1** [comment] 2020-08-24 21:46
The site turns dark grey
![kép](https://user-images.githubusercontent.com/9215491/91099579-df41be80-e663-11ea-9840-f66fbc0d6485.png)

**Comment by Gusted** [comment] 2020-08-24 21:47
You can remove the
```CSS
body,
html {
 margin:0;
 padding:0;
 color:#fff;
 background:#111;
 overflow:hidden;
 font-family:Arial,sans-serif;
 font-weight:300;
 font-size:1em
}
```
Part from the code... Might fix it

**Comment by MPeti1** [comment] 2020-08-24 21:48
Same, but maybe a bit lighter grey now

**Comment by Gusted** [comment] 2020-08-24 21:53
Okay, seems to to original work my idea.

Let's try to get a reproduce able.
Could you save the site without dark reader enabled(Hopefully it works this time) and than Export the generated theme trough [this](https://darkreader.org/blog/v4-9-16/) instructions.

**Comment by MPeti1** [comment] 2020-08-25 20:37
Here is the website without Dark Reader enabled: [sagemcom.zip](https://github.com/darkreader/darkreader/files/5126165/sagemcom.zip)
Here is the generated theme css: [generated theme.zip](https://github.com/darkreader/darkreader/files/5126167/generated.theme.zip)

**Comment by Gusted** [comment] 2020-08-25 21:58
Well, I got a reproduce able case. With a little modified .html to ensure to get all styles working
[HomeBox.zip](https://github.com/darkreader/darkreader/files/5126499/HomeBox.zip)
I will poke around a little :)

**Comment by Gusted** [comment] 2020-08-25 22:13
Well, it seems it shows for me either way, but it's not loading the background-images so might it be that?
Anyway could you try
```CSS
.slideshow * {
    background: transparent !important;
}
```
Or
```CSS
.slideshow * {
    background-image: none !important;
}
```

As it's now for me like this ![](https://i.imgur.com/J7lwgrl.png) due to images. Or you could remove the `slideshow` element https://i.imgur.com/4fHZtKe.png *Click on it and press del*

**Comment by MPeti1** [comment] 2020-08-26 11:35
Deleting the slideshow results in this:
![image](https://user-images.githubusercontent.com/9215491/91298293-0b625a00-e7a0-11ea-8d80-dbfbc32bcd07.png)

`.slideshow * {
    background: transparent !important;
}`

Same, but with the text at the bottom left changing

`.slideshow * {
    background-image: none !important;
}`

Same

But for me even the saved HTML does not load correctly, it's like this:
![image](https://user-images.githubusercontent.com/9215491/91298820-f9cd8200-e7a0-11ea-994b-da507b9e98a5.png)

**Comment by Gusted** [comment] 2020-08-27 18:14
I'm bit giving up other than just let you use Filter(+)/Static. As I have 0 ideas what to do.

**Comment by Gusted** [comment] 2020-11-15 18:31
Closing as giving with a fresh mind another try I didn't came up with anything.

**Closed by Gusted** 2020-11-15 18:31 UTC
