### ISSUE TITLE
[Broken Website] https://personal.vanguard.com

### ISSUE THREAD

**Issue by gopipal** [darkreader/darkreader#3593] opened 2020-09-04 17:47 UTC
**Website**
https://personal.vanguard.com/us/faces/com/vanguard/logon/view/LogonLogoff.xhtml

**How to Reproduce**
 1. Go to https://personal.vanguard.com/us/faces/com/vanguard/logon/view/LogonLogoff.xhtml
2. Blank Page. 

**Expected behavior**
There should be content when I go to that page. Makes vanguard.com unusable. When you turn off Dark reader content renders fine.

**Actual behavior**
After login the website should render, but it does not.

**System info:**
 - OS:MacOS
 -  chrome
 - Darkreader Version: latest

**Comment by irvinm** [comment] 2020-09-04 18:17
I saw the same thing today.  It looks like there is a DOM exception being thrown around CSS injection.  I was able to get it to work in private mode (didn't have Dark Reader enabled for private windows) and if Dark Reader was completely disabled (not just disabled for that one site).

**Comment by gopipal** [comment] 2020-09-04 18:36
Same issue as https://github.com/darkreader/darkreader/issues/3576

**Comment by Gusted** [comment] 2020-09-06 16:37
Duplicate of #3576

**Closed by Gusted** 2020-09-06 16:37 UTC
