### ISSUE TITLE
[Feature Request] Adding third mode which will keep a website's default theme

### ISSUE THREAD

**Issue by krasimirkrustev** [darkreader/darkreader#9433] opened 2022-07-29 13:55 UTC
# Feature Request
Adding third mode which will keep a website's default theme, so people will be able to make changes to Brightness, Contrast, Sepia, Grayscale, Font and Text Stroke without making changes to the actual theme

## Is this feature request related to a problem?
No

**Comment by Gusted** [comment] 2022-07-29 18:18
Duplicate of #9276

**Closed by Gusted** 2022-07-29 18:18 UTC
Labels: enhancement
