### ISSUE TITLE
[Broken Website] onedrive

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#3411] opened 2020-08-14 14:50 UTC
**Website**
https://onedrive.live.com/?id=22FB491072D6A964!225&cid=22FB491072D6A964

**How to Reproduce**
An example of this is
> 1. Go to a onedrive file page
> 2. The menubar is blinking

**Screenshots**
![sshot-005](https://user-images.githubusercontent.com/36977733/90261790-fc44e900-de3c-11ea-8d33-3f4246b9e53a.png)
![sshot-006](https://user-images.githubusercontent.com/36977733/90261792-fcdd7f80-de3c-11ea-8bcd-302021ea7644.png)

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.16
 
**Additional context**
Disable and re-enable dark reader, the problem will disappear.

**Comment by Gusted** [comment] 2020-08-14 14:52
Hi @linsui!

Thank you for reporting this issue,
it seems like that #3138 don't work for Microsoft apps yet(Just like online word is 1 big shining).
I will have a look soon to see what it's the cause of this issue!

Regards,
Gusted

**Comment by linsui** [comment] 2020-08-14 14:54
Thanks!

**Comment by Gusted** [comment] 2020-08-14 18:27
I determined kind of the source to the problem. As I'm a lazy person I will copy paste my message to the owner of dark reader(Alexander) and hopefully can help me out with this weird problem

```
Hey @CEO - Alexander Did you remember the flashing online word?
Well it seems like a trace to the problem has found.
As it was flashing in less than 2 seconds it seems to me that there were 
multiple observers on the node or something else that cause to rebuild the style sheet and shine word. 
https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/style-manager.ts#L263 
Removing this line is making the flashy parts just leaving white https://i.imgur.com/mSdyd1j.png
I'm really unsure why this is causing the flashing the force part is just forcing to rebuild the stylesheet.
It shouldn't trigger the watcher for any reason and think it's has a new prev-sibling right?
Other than rebuilding the style so it gets it stylesheet back
```

**Comment by Gusted** [comment] 2020-08-25 14:50
```
alexanderby Today at 16:39
I've submitted an issue to merge-styles package https://github.com/microsoft/fluentui/issues/14735 that is the reason for removing Dark Reader's style.
```
Well it official became the waiting game for Microsoft and than for sites to update it's scripts.

**Comment by Gusted** [comment] 2020-08-27 20:43
https://codepen.io/Gusted/pen/gOrmXeL
Reproduce-able case with vanilla java script and now back to debugging to see what's causing this 😬

**Comment by Gusted** [comment] 2020-09-24 16:54
Merged the fix(#3692) next release will contains those fixes.

**Closed** 2020-09-24 16:53 UTC

**Comment by sunilvaltix** [comment] 2020-10-24 22:45
What is the release schedule? Monthly? Quarterly?

I would very much like to try this fix.

**Comment by Gusted** [comment] 2020-10-24 22:46
> What is the release schedule? Monthly? Quarterly?

Whenever we feel like a new Update can come trough.

> I would very much like to try this fix.

It's already fixed.

**Comment by sunilvaltix** [comment] 2020-10-24 23:02
Which version has this fix?

**Comment by Gusted** [comment] 2020-10-24 23:02
4.9.20+

**Comment by sunilvaltix** [comment] 2020-10-24 23:08
Thank you! This fixes the Atlassian Jira for me. Very happy!

Now, if you could please take on the gmail monster...:-)

**Comment by Gusted** [comment] 2020-10-24 23:09
> Now, if you could please take on the gmail monster...:-)

Definitely working on that alongside some other general performance problems.
