### ISSUE TITLE
[Bug] Cannot delete or add websites to the site list

### ISSUE THREAD

**Issue by AtivJoshi** [darkreader/darkreader#6903] opened 2021-09-25 11:04 UTC
# Bug Report

## Bug Description

Dark Reader is set on 'Enable by default' mode, and the  exceptions are listed in 'site list'. I am unable to edit the site list, i.e. the site list restores when I reload the webpage. 

## Steps To Reproduce

- Go to github.com. (github is in the site-list, so dark mode on github is disabled by default)
- Click on the Dark Reader extension and delete github.com from the site list. This will enable the dark mode on github.com
- Reload github.com
- github.com is automatically added to the site-list and the dark mode gets disabled.

## Expected Behavior
Dark Reader should keep github.com dark after reload (and delete github.com from the site-list)

## Actual Behavior

Dark Reader does not convert github.com to dark after reload (and adds github.com to the site-list)

## System Information

- OS: Manjaro 
- Browser: Firefox 92.0 
- Dark Reader Version: 4.9.37.1 

## Additional Context

Needs to be fixed ASAP. Totally unable to use Dark Reader

**Comment by OmarNamis** [comment] 2021-09-25 11:58
Duplicate of #6848.

**Closed** 2021-09-25 13:16 UTC
Labels: bug
