### ISSUE TITLE
[Feature Request] Apply dark mode only when system theme is set to dark

### ISSUE THREAD

**Issue by ritiek** [darkreader/darkreader#7984] opened 2022-01-18 10:04 UTC
# Feature Request

## Is this feature request related to a problem?
Is it possible to apply dark theme on the basis of current system theme?

I use Brave browser (and suspect this could also be relevant to other browsers) and it has an option to turn on Dark or Light mode in Settings -> Appearance -> Theme, and if I turn on the Dark mode, it would cause websites that support reading the browser's system theme like GitHub, YouTube to show up in Dark mode but other websites like Google Search page that do support this still show up in Light mode.

I tried out Dark Reader but it forces Dark mode on all the websites irrespective of the theme that I have set in my Brave browser. I'm looking for something that would force Dark theme on all the websites only if my Brave theme is set to Dark, otherwise I'd still want a website to show up in its default colors.

Would this be possible to implement or perhaps I am missing out something?

## Additional Context

I use my machine in different lightning conditions through out the day, so having something like this could make things really convenient to me.

**Comment by Gusted** [comment] 2022-01-19 17:31
Duplicate of #7375

**Closed by Gusted** 2022-01-19 17:31 UTC
Labels: enhancement
