### ISSUE TITLE
[Broken Website] www.webupd8.org

### ISSUE THREAD

**Issue by bbhtt** [darkreader/darkreader#9344] opened 2022-07-19 14:58 UTC
# Broken Website Report

## Website Address

http://www.webupd8.org/

## Steps To Reproduce

- Open a blog post http://www.webupd8.org/2016/05/easily-create-your-own-numix-based-gtk.html

## Problematic Observation

Page is not dark themed

Heading is unreadable

## Screenshots

![image](https://user-images.githubusercontent.com/62639087/179782041-9a88f32b-7853-4144-98d7-edf117b1be64.png)

![image](https://user-images.githubusercontent.com/62639087/179782097-5cdf202a-eba9-4ea7-89fe-f01669f1c1c2.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 2022-07-19
- Dark Reader Version: 4.9.52

## Additional Context

None

**Comment by Gusted** [comment] 2022-07-20 19:01
Duplicate of #5937

**Closed by Gusted** 2022-07-20 19:01 UTC
Labels: Broken Website
