### ISSUE TITLE
Video players freeze!

### ISSUE THREAD

**Issue by anoldmaninthesea** [darkreader/darkreader#3598] opened 2020-09-05 18:36 UTC
Description:
When I'm watching videos online, the player either freezes completely, or the lower half freezes, while the upper half continues to work.

Go to https://w4.ffmovies.cc/, or https://yesmovies.ag/ for example, and choose any video. 

I'm using Google Chrome, Filter +, Dark Reader version 4.9.18

Only when I disable the reader, does the player behaviour returns to normal...

**Comment by Gusted** [comment] 2020-09-06 17:03
Hi @anoldmaninthesea!

As you mention Filter(+) It seems it could be more a browser bug due to the CSS we use and only apply some things to the video that is handled by the browser itself. Could have a try at [this site](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video) if you experience the bug as well. 

Do you have hardware acceleration enabled? As seen here ![](https://i.imgur.com/HgKSkvw.png) Maybe it could help if you disabled it.

Regards,
Gusted

**Comment by anoldmaninthesea** [comment] 2020-09-07 09:24
Hi @Gusted  I've tried your link, and I had no problems with the video there...

I tried disabling the hardware acceleration on Chrome, and alleviated the issue, but it did not solved the problem.

I'm sending a picture in attachment to better illustrate my issue.

![Doubt](https://user-images.githubusercontent.com/39698530/92371807-02ed1600-f0f4-11ea-8675-e163646e4961.png)

**Comment by Gusted** [comment] 2020-09-08 14:53
> Only when I disable the reader, does the player behaviour returns to normal...

I'm curious how you are sure of this? As I know it doesn't modify the video just the color of it.

**Comment by anoldmaninthesea** [comment] 2020-09-10 13:04
Because as soon as I disable it, then issues is solved...

**Comment by anoldmaninthesea** [comment] 2020-09-10 16:53
@Gusted hum... I'm not proficient enough in tech to know what you're suggesting... If you elaborate a bit, I may give it a try.

**Comment by anoldmaninthesea** [comment] 2020-09-12 19:23
@Gusted  incidentally, I only have this problem with Filter+. Static, Filter, Dynamic, work just fine.

**Comment by krystian3w** [comment] 2020-10-12 06:44
You recommend bugged CSS @Gusted.

Stylus need:

`filter:  invert(100%) hue-rotate(180deg) !important;`

but you eaten "`filter:`"...

**Comment by Gusted** [comment] 2020-10-12 07:29
> You recommend bugged CSS @Gusted.
Stylus need:
filter: invert(100%) hue-rotate(180deg) !important;
but you eaten "filter:"...

Oh yeah, I see. I've probably forgot to add it to the CSS declaration.

> PS. pages use <iframe src="...">, so need change CSS to:
> ```CSS
>html {
>    invert(100%) hue-rotate(180deg) !important;
>}
>video, iframe {
>    invert(100%) hue-rotate(180deg) !important;
>}
>```

Don't you forget the `filter: ` now as well?

**Comment by krystian3w** [comment] 2020-10-12 07:45
Still you no override `iframe`.

video sitll have wrong colors.

**Comment by Gusted** [comment] 2020-10-12 14:16
The original issue is a issue caused by the rendering of the browser itself. Closing

**Closed by Gusted** 2020-10-12 14:16 UTC
Labels: bug
