### ISSUE TITLE
[Feature Request] Inlcude a shortcut for toggling "Mode" between "Dark" and "Light"

### ISSUE THREAD

**Issue by drkhn1234** [darkreader/darkreader#11336] opened 2023-05-29 15:47 UTC
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

It is helpful for users to be able to quickly switch between "Dark" and "Light" modes of Dark Reader, but as of now there is not a way to achieve this.

There currently exists three shortcut options for Dark Reader:

* "Toggle extension"
* "Toggle current site"
* "Theme generation mode"

I suggest there be added a fourth shortcut named either "Filter mode" or "Toggle between Dark/Light mode".

### Screenshots

<img width="285" alt="image" src="https://github.com/darkreader/darkreader/assets/97989691/860d7d5a-9cac-4d39-a056-41e75f77c7c0">

### Additional Context

I would like to add that prior to opening this issue I have came across to only a single [feature request](https://github.com/darkreader/darkreader/issues/899) with the same goal that which unfortunately hasn't caught attention in 5 years and which also have resulted in change of subject of the requested feature due to irrelevant discussion of the topic in its comment section, thus I have decided to reopen the feature request in a more organized manner.

**Comment by bershanskiy** [comment] 2023-06-23 14:14
I'm not sure we can ship this any time soon since:
 - In the old UI we have "Dark" and "Light" modes while in the new UI we have generic themes. They represent somewhat similar concepts, but there is no straightforward bijection between their UI elements. Would this toggle be limited only to the old UI (noop on the old UI) or would it just advance to the next theme?
 - Every command has to be specified in `manifest.json`, which typically requires longer store reviews so we would like to avoid changing the manifest. Quite literally, we are withholding some features (e.g., stronger and safer CSP) because we are not sure how they would impact store review times.

**Comment by alexanderby** [comment] 2024-01-16 11:01
Duplicate of https://github.com/darkreader/darkreader/issues/899

**Closed by alexanderby** 2024-01-16 11:01 UTC
Labels: enhancement
