### ISSUE TITLE
[Feature Request] Automatically turn DarkReader on between time x and time y

### ISSUE THREAD

**Issue by matievisthekat** [darkreader/darkreader#8400] opened 2022-03-08 19:33 UTC
# Feature Request

## Is this feature request related to a problem?
nope

## Additional Context
Additional settings to automatically turn on DarkReader at a certain time and off at another time. This would be similar to a "bedtime" mode between xx:xx and yy:yy.

im creating this issue to see if this feature would be allowed. If so, i would love to dive into the source code and submit a pr.

**Comment by Gusted** [comment] 2022-03-08 19:53
Duplicate of #6991

**Closed by Gusted** 2022-03-08 19:53 UTC
Labels: enhancement
