### ISSUE TITLE
[Bug] Hotkey "Toggle current site" doesn't work

### ISSUE THREAD

**Issue by azat11** [darkreader/darkreader#6859] opened 2021-09-22 08:39 UTC
# Bug Report

## Bug Description

Hotkey "Toggle current site" doesn't work. Clicking "Toggle current site" doesn't work either. Site toggles only if manually entered into the site list.

## Steps To Reproduce

Just started happening. Trying to toggle any site on/off with hotkey - it's not working.

## Expected Behavior

Should toggle.

## Actual Behavior

Doesn't toggle.

## System Information

- OS:  Win 7
- Browser:  Waterfox G3.2.6 (64-bit)
- Dark Reader Version:  4.9.35

## Additional Context

Didn't notice why it started happening. Can't say how to reproduce.

**Comment by bershanskiy** [comment] 2021-09-22 09:04
Duplicate of #6832. Should be fixed in 4.0.36 which is being reviewed for publication.

**Closed by bershanskiy** 2021-09-22 09:04 UTC
Labels: bug

**Comment by azat11** [comment] 2021-09-23 19:18
> Duplicate of #6832. Should be fixed in 4.0.36 which is being reviewed for publication.

4.9.36 Did fix things, thank you.
