### ISSUE TITLE
[Feature Request] Scheduling

### ISSUE THREAD

**Issue by x4D48** [darkreader/darkreader#10150] opened 2022-10-22 11:42 UTC
# Feature Request

## Is this feature request related to a problem?

Add an option to turn the Dark Reader on/off based on schedule. For example, have it inactive during the day and automatically activate at certain time.

## Screenshots

N/A

**Comment by Gusted** [comment] 2022-10-23 09:42
Duplicate of #6181

**Closed by Gusted** 2022-10-23 09:42 UTC
Labels: enhancement
