### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by meteortears** [darkreader/darkreader#6901] opened 2021-09-25 03:11 UTC
# Bug Report
Console error

## Bug Description
Console error
Unchecked runtime.lastError: The message port closed before a response was received.

## Expected Behavior
The console does not report an error

## Screenshots

<img width="976" alt="iShot2021-09-25 11 17 02" src="https://user-images.githubusercontent.com/4099706/134756101-c37358bb-ed60-4769-a73b-03a01e1fe783.png">

## System Information
- OS: macOS
- Browser:  Chrome 94
- Dark Reader Version: 4.9.37

**Comment by Gusted** [comment] 2021-09-25 06:22
Duplicate of #6892

**Closed by Gusted** 2021-09-25 06:22 UTC
Labels: bug
