### ISSUE TITLE
Light theme website not getting inverted

### ISSUE THREAD

**Issue by marcodiiga** [darkreader/darkreader#1043] opened 2019-01-25 08:17 UTC
It seems some webpages on dev.to like [this one](https://dev.to/awwsmm/101-bash-commands-and-tips-for-beginners-to-experts-30je) aren't being inverted. Just a few labels are being manipulated, the main background remains white.

**Comment by alexanderby** [comment] 2019-01-25 11:41
I think this is a duplicate of #956.

**Closed by alexanderby** 2019-01-25 11:41 UTC
