### ISSUE TITLE
old.reddit.com/r/archlinux/ is not dark

### ISSUE THREAD

**Issue by MR-Diamond** [darkreader/darkreader#12158] opened 2024-01-16 14:21 UTC
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

As the title states, the website [http://old.reddit.com/r/archlinux/](http://old.reddit.com/r/archlinux/) is not affected by DarkReader. Screenshot:
![2024-01-16_15-15](https://github.com/darkreader/darkreader/assets/32249442/2ff6f57f-d174-41bc-9ea6-1af93f8f2caf)

### Website Address

http://old.reddit.com/r/archlinux/)

### Steps To Reproduce

1. Make sure that the extension DarkReader is active
2. Go to http://old.reddit.com/r/archlinux/)
3. The page should be dark, instead it remains white as shown in the screenshot. 

### Operating System

Manjaro Linux

### Web Browser name and version

Firefox 121.0.1

### Dark Reader version

4.9.74

**Comment by alexanderby** [comment] 2024-01-16 14:53
I made a fix earlier today and will publish after Chrome and Firefox review the previous release.

**Comment by alexanderby** [comment] 2024-01-16 14:54
The problem is they use a background sprite with very different colours for some odd reason.

**Comment by MR-Diamond** [comment] 2024-01-18 16:44
I received an update of DarkReader to version 4.9.75 (from 4.9.74), but  http://old.reddit.com/r/archlinux/ is still white.

**Comment by alexanderby** [comment] 2024-01-18 17:37
@MR-Diamond That's because Mozilla has just finished reviewing 4.9.75 yesterday. The fix is in 4.9.76, which is under another review.

**Comment by MR-Diamond** [comment] 2024-01-22 12:04
> The fix is in 4.9.76

I received 4.9.76 but old.reddit.com/r/archlinux/ is still white.

**Comment by MR-Diamond** [comment] 2024-01-22 12:08
In DarkReader I see "Disabled for the current website", but I didn't disabled it and there is no way to force, as shown in the following gif:

![Peek 2024-01-22 13-07](https://github.com/darkreader/darkreader/assets/32249442/0dcf709b-33c0-49e4-908c-b3b17d452ba4)

**Closed** 2024-01-22 12:23 UTC
Labels: Broken Website
