### ISSUE TITLE
[Bug] Auto detection isn't working on ColorOS7

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#8051] opened 2022-01-27 12:52 UTC
## Bug Description
When I use the 'Auto' setting, that is supposed to adjust my Darkreader according to the system setting, it is not working.

## Steps To Reproduce
Can be reproduced on the Oppo Find X2 Neo fully updated.

I use ColorOS 7, Android 10.

## Expected Behavior
It adjusts according with my system settings.

## Actual Behavior
It treats it as on, despite me not using dark mode on the phone. 

## Screenshots
![Screenshot_2022-01-27-13-44-14-82](https://user-images.githubusercontent.com/6344099/151362020-ebfbd29b-b928-40a8-9d09-6f2a649642c3.jpg)
![Screenshot_2022-01-27-13-44-05-01_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/151362027-dc658bd2-37e2-4291-8177-1194266a1262.jpg)

## System Information
Android 10
Firefox 96.2
Darkreader 4.9.43

## Additional Context
I used to stay with Dark Mode on at my phone for the last months, I changed it back to Daylight just today.

This is when I encountered this issue.
I also tried to restart Firefox.

**Comment by Gusted** [comment] 2022-01-27 21:05
I've seen some recent issues with this one on Mobile(seems to be a bug on our side), I'm having a look at this bug in the weekend, due to that Firefox remote debugging is causing some crashes on my phone with a recent update. Closing as a duplicate of #8039 for now.

**Closed by Gusted** 2022-01-27 21:05 UTC
Labels: bug
