### ISSUE TITLE
[Broken Website] virustotal.com - Virustotal Name Not Visible

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8357] opened 2022-03-04 22:02 UTC
# Broken Website Report

## Website Address
https://www.virustotal.com/

## Screenshots

![Screenshot_010006_2022-03-05](https://user-images.githubusercontent.com/15933805/156847877-62ec7aa3-2f8a-43d0-b10e-721ab8c3c6b6.png)

![Screenshot_005952_2022-03-05](https://user-images.githubusercontent.com/15933805/156847904-391fc212-8756-445a-82c2-537866310d41.png)

## System Information

- OS: Windows 10
- Browser: Firefox 97.0.1
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment] 2022-03-04 22:23
Duplicate of #4682

**Closed by Gusted** 2022-03-04 22:23 UTC
Labels: Broken Website
