### ISSUE TITLE
[Bug] Automation resets to use system theme when dark reader is turned off

### ISSUE THREAD

**Issue by dnut** [darkreader/darkreader#9059] opened 2022-06-10 14:58 UTC
Typically, I would assume expect extension configuration to persist until the extension is removed (if not longer). But it appears to be cleared arbitrarily during normal usage.

The way automation is presented in the UI indicates two controls for automation:
- one toggle in the main page that turns automation on or off
- an option in the settings to configure how automation works (clock, sun, or system)

Having these two separate types of automation controls means that the UI implies this message to the user: "Select whether you want automation to be turned on. Separately, whenever automation is turned on, automate based on this persistent configuration." Based on that implication, it's reasonable to expect that the configuration would not suddenly reset just because you briefly toggled dark reader off.

I was initially puzzled by the actual behavior of the extension and spent a while testing all the different behaviors. Finally I came to the conclusion the "system theme" toggle in the settings is the same as the "automation" toggle in the main page, and that configuring the automation configuration within settings can actually switch dark reader out of "off" or "on" mode. I find this behavior to be both surprising and undesirable.

It's annoying to have to dig into settings whenever I want to turn automation back on. I always want clock based automation. I would never use system based automation. It's also ordinary for me to temporarily switch dark reader on during the day or off at night for any number of reasons, only to turn automation back on as the standard operating mode. So I run into this minor annoyance very often.

### Steps
1. Enable automation
2. Enter settings, and configure automation mode to use the clock
3. Turn dark reader off
4. Turn automation back on

**expect:** Automation should use the clock as configured
**actual:** Automation is based on system theme

### Steps
1. Turn dark reader off
2. Enter settings, and configure automation mode to use the clock

**expect:** Dark reader should remain off, but if automation is enabled, it would use the clock
**actual:** Dark reader is set to clock-based automation mode

## System Information
- OS: linux
- Browser: firefox 100.0.2
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment] 2022-06-11 21:26
Duplicate of https://github.com/darkreader/darkreader/issues/3268

**Closed by Gusted** 2022-06-11 21:26 UTC
Labels: bug
