### ISSUE TITLE
[Feature Request] Allow web developers to specify if website is already using a dark theme

### ISSUE THREAD

**Issue by TheStachelfisch** [darkreader/darkreader#7644] opened 2021-12-14 23:09 UTC
# Feature Request

A feature to allow web developers to include some kind of header or other indication to Dark reader, that the website has a dark theme and dark reader shouldn't be enabled on that site.
This would allow websites to not have to deal with broken/weird looking elements when the site already has dark mode.

## Is this feature request related to a problem?

Developers can include an optional indication to Dark reader, that the website is already using a dark theme. Dark reader would then detect that and disable dark mode for that website, but still give the user the option to enable dark mode from dark reader.

## Screenshots

None applicable.

## Additional Context
Often when visiting websites that already have a dark theme colors are messed up or look weird, this can be mitigated by this.

**Comment by Gusted** [comment] 2021-12-16 13:02
Duplicate of #4325

**Closed by Gusted** 2021-12-16 13:02 UTC
Labels: enhancement
