### ISSUE TITLE
Improve UI discoverability of the "Use system color scheme" option

### ISSUE THREAD

**Issue by jasontk19** [darkreader/darkreader#2247] opened 2020-04-08 19:34 UTC
Currently this option is hard to find. The "Automation" menu access, triggered by the vertical ellipses next to the `[ ON  | OFF ]` switch, is not immediately obvious.  This interaction could be improved in order to make the "use system color scheme" option easier to find, since this is likely a highly used and desirable feature.  Numerous users have come to file an issue to suggest introducing this feature yet, discovered it already existed.   Some were only able to determine where to enable it by reading the thread for closed issue #745.  [See comments starting here and below](https://github.com/darkreader/darkreader/issues/745#issuecomment-553686507).

One possible interaction would be to update the main `[ ON | OFF ]` toggle switch in the main menu to simply: `[ ON | OFF | SYSTEM ]`

Another possibility would be to just move everything under the "Automation" menu into the "More" tab where most other options are currently consolidated. This may be less desirable since the "More" menu is disabled when Dark Reader is turned off for a site.

**Comment by anohren** [comment] 2020-04-08 20:05
I think the concept of "disabling" the entire extension as a default action just to switch from dark to light is flawed.  It sounds more reasonable to assume that users want the extension active most of the time, then automate whether it's in light or dark mode, and surface that mode switch instead of the enable/disable switch. 

Either way the automation options need a better home. I think the More tab is the most obvious place for it, after the tab has been made accessible at all times. It's set and forget so it shouldn't need to take up space in a regularly used on/off switch that is also used to override the automated actions. I want to be able to override the state independently of automation settings which [ on | off | system ] would not allow.

**Comment by Gusted** [comment] 2020-04-09 11:30
https://darkreader.org/blog/dr-5-announcement/ Theirs a new UI incoming that will Improve this Option.

**Comment by anohren** [comment] 2020-04-09 11:54
> https://darkreader.org/blog/dr-5-announcement/ Theirs a new UI incoming that will Improve this Option. (The Auto Option)

Thanks for the link. 

Judging by the screenshot the on/auto/off switch makes "auto" mutually exclusive with "on" and "off". It's worth mentioning again that coupling two orthogonal concepts like this is not a good idea; it's now impossible to override an automatic switch without changing one's automation settings.

**Comment by Gusted** [comment] 2020-04-09 11:59
The auto Option will use the System Color Scheme 
![](https://i.imgur.com/g8rvWtL.jpg)

**Comment by anohren** [comment] 2020-04-09 12:03
> The auto Option will use the System Color Scheme

Yes, exactly

**Comment by Gusted** [comment] 2020-04-09 12:05
That I don't really get you? This Issue is to make it more discoverabilty of the Use System color scheme what will be provided with Darkreader V5

**Comment by anohren** [comment] 2020-04-09 15:42
Ok, let's take an example of what I mean from a company with a design budget of a few hundred million dollars:

MacOS Night Shift (changes color temperature at night): 

1. You set a schedule, e.g. 21:00-07:00, for when you want night shift to be enabled (21:00) and disabled (07:00) automatically. These are your _automation preferences_ for Night Shift. 
2. A real life situation occurs where you need to disable night shift. You open Notification Center and flip the switch to disable it. **Your automation preferences are preserved; automation is still enabled**. 

In your design where "auto" is mutually exclusive with "on/off" this scenario is impossible; there's no way of having automation enabled while at the same time overriding the decision that it made. 

Real life situations occur remarkably often, hence the need to override.

**Comment by Gusted** [comment] 2020-04-09 15:49
Hmm I get it, when the new UI will be released I will make this functionality.

**Comment by alexanderby** [comment] 2020-05-04 12:20
I think all the automation options should be placed on a separate page:
![New Project](https://user-images.githubusercontent.com/9638588/80965192-d01bd400-8e1a-11ea-91d5-fd82ce9eb9f3.png)

**Comment by alexanderby** [comment] 2020-05-04 13:07
The label below **Auto** button should have a message in accordance with automation mode.

There should be an icon (same as for current design) over the **Auto** button. Clicking on that icon should open **Automation** page.

**Comment by anohren** [comment] 2020-05-04 14:39
@alexanderby With that last screenshot you're back to the problem I described above.

**Comment by Gusted** [comment] 2020-05-05 14:58
> With that last screenshot you're back to the problem I described above.

A simple extra button to switch between disabling or the color scheme should do the trick.
@anohren

**Comment by anohren** [comment] 2020-05-05 15:01
Not sure I follow, sorry. There are already more buttons than necessary for all of this.

**Comment by alexanderby** [comment] 2020-05-05 15:25
@anohren Here is another issue for this https://github.com/darkreader/darkreader/issues/1713

**Comment by anohren** [comment] 2020-05-05 15:29
@alexanderby Ok I think we misunderstood each other.

> I want to be able to override the state independently of automation settings which [ on | off | system ] would not allow.

> It's worth mentioning again that coupling two orthogonal concepts like this is not a good idea; it's now impossible to override an automatic switch without changing one's automation settings.

> In your design where "auto" is mutually exclusive with "on/off" this scenario is impossible; there's no way of having automation enabled while at the same time overriding the decision that it made regarding the on/off state.

**Comment by anohren** [comment] 2020-05-05 15:36
If anyone needs a fourth explanation, let me know 😉

**Comment by Gusted** [comment] 2020-05-05 15:37
> If anyone needs a fourth explanation, let me know 😉

Describe a scenario were you want to have it overrideable :)

**Comment by anohren** [comment] 2020-05-05 16:02
The short answer is: any time automation is enabled.

One scenario is when the browser doesn't properly propagate system events to the extension. Another is when you're in a bright room even though it's late. Another is that you don't plan on going to bed for a while anyway. Another is that more than one domain render improperly and you can't be bothered with micromanagement at that time. Another is that the page renders incorrectly, but you know a fix will arrive in the next version so there's no point in setting a domain specific setting. Another is that it's the easiest and quickest solution to the problem, regardless of whether there exists a more advanced and less visible feature that would solve it in a more elegant way. There are of course countless scenarios for overriding that are unpredictable, so if you want to instill some sense of control in the user then you have to compensate for that. That means giving them the option to override. 

Since the enable/disable buttons exist you must have imagined that they would be used, and since you don't disable them when automation is enabled it means the design encourages the very use case of overriding, but _you can't override without losing the state of enabled automation_ even though the concepts are orthogonal and independent. It's unexpected behavior, and a defect.

**Comment by Gusted** [comment] 2020-05-05 19:09
> 1. Ensure overrides do not impact the enabled automation state.

We don't have that anymore in the new design.

> 2. The automation enable switch is set-and-forget, and can be hidden away on a preference page instead of taking up valuable real-estate and adding to visual clutter at the top of the main view.

Not every user would appericate that.

> 3. The segmented [ on | off ] control that we have left, which is pretty much equivalent to two buttons next to each other, can be exchanged for a switch with the benefit of relieving the user from having to visually parse the state of the widget before knowing where to click. A switch toggles -- that's all it does. No need to read or decide where to click once you know where to find it.

New design :-)

**Comment by anohren** [comment] 2020-05-05 21:29
> We don't have that anymore in the new design.

I'm commenting on the pictures posted here by @alexanderby yesterday. The widget used in those screenshots clearly conveys mutual exclusivity. If you're right and his screenshots wrong then that's good. That's all I know and all I can say about it.

> Not every user would appericate that.

Luckily I don't care about every user. I care about the majority of users in the majority of cases. If you are convinced that they will enable and disable automation on a daily basis (what's the point then?) then you'll go with that design, naturally. 

That doesn't mean it will be helpful to convey mutual exclusivity where there isn't, though.

> New design :-)

I... don't know? I'm commenting on the screenshots, as shown in this issue. If they're not correct, and you're going with a switch instead, then: 👍

I'm just leaving feedback on the ideas expressed in this thread so far. They might be better suited in another issue, but I continued here since we got started here.

**Comment by Gusted** [comment] 2020-05-05 21:34
> I... don't know? I'm commenting on the screenshots, as shown in this issue. If they're not correct, and you're going with a switch instead, then: 

Yep theirs coming a switch

**Comment by anohren** [comment] 2020-05-05 21:37
Looking forward to it!

**Comment by Gusted** [comment] 2020-05-12 13:09
#2461

**Closed by Gusted** 2020-05-12 13:09 UTC
Labels: enhancement

**Comment by anohren** [comment] 2020-05-27 21:33
> Yep theirs coming a switch

Hey! Any idea when it would be possible to preview this? I had a look in 4.9.9 which appears to be two days old at the time of writing.

**Comment by Gusted** [comment] 2020-05-27 21:37
Devtool -> Preview new design

**Comment by anohren** [comment] 2020-05-27 22:47
> Devtool -> Preview new design

Yes, exactly. No switch in the UI.

**Comment by Gusted** [comment] 2020-05-27 22:49
[ON | AUTO | OFF] that's clearly a switch

**Comment by anohren** [comment] 2020-05-28 00:50
> [ON | AUTO | OFF] that's clearly a switch

Only if you haven't read a word I've written... 🤨🤔

And as though the already existing [ on | off ] were _not_ a switch by that very same logic, in which case I don't see what "there's coming a switch" is supposed to mean?

Switch:

![](https://www.shareicon.net/data/512x512/2016/05/29/772527_multimedia_512x512.png)

Not a switch:

![Skärmavbild 2020-05-28 kl  02 48 24](https://user-images.githubusercontent.com/3519879/83085960-bc683400-a08d-11ea-808e-75a8bb2f40b5.png)

**Comment by Gusted** [comment] 2020-05-28 07:49
That's our new design it won't change. We call it MultiSwitch it's exactly what the OP's issue stated :) making it to another switch will break our current way of enabling and disabling

**Comment by anohren** [comment] 2020-05-28 10:55
Sorry about the needlessly large image there. I was tired and just grabbed something.

> That's our new design it won't change

Okay, the decision is your prerogative of course. I'm just trying to improve upon the design by reasoning about it, but if it simply "won't change" then I understand that an attempt at such a discussion would be futile.

If you don't mind, could you explain just one thing? Why use this kind of "MultiSwitch" that basically tells the user that { on, off, auto } are mutually exclusive, after ensuring that...:

> > 1. Ensure overrides do not impact the enabled automation state.
> 
> We don't have that anymore in the new design.

If automation's enabled/disabled state is not strongly coupled with the extension's on/off state, then why squeeze it into the same "MultiSwitch" widget?

**Comment by Gusted** [comment] 2020-05-28 18:56
> One possible interaction would be to update the main `[ ON | OFF ]` toggle switch in the main menu to simply: `[ ON | OFF | SYSTEM ]`

That's why their is a `MultiSwitch` so you can overwrite on/off at any time you want and switch back to Auto when you feel to.

**Comment by anohren** [comment] 2020-05-28 21:38
> That's why their is a `MultiSwitch` so you can overwrite on/off at any time you want and switch back to Auto when you feel to.

I...see. So you actually haven't read a single word I've written...

Well, I think I've accomplished all I can here 🙄 (nothing)

**Comment by Gusted** [comment] 2020-05-28 21:40
And you don't get the original issue. I'm not going into discussion with this.

**Comment by anohren** [comment] 2020-05-28 21:46
> And you don't get the original issue

I'm the person who originally drew attention to the original issue in the other thread 🤣 This is too funny...



> I'm not going into discussion with this.

Well, I know that now. Though, it would have been nice to have known from the start, because it wasted my time and effort in writing explanations and rationales that you were never prepared to read seriously, in which case you should not have answered me the way you did, or even at all.

**Comment by Gusted** [comment] 2020-05-28 21:53
Okay you don't see why I said `Their's coming a switch`. Yes their was coming one a MultiSwitch I can't explaing everything into detail when their wasn't a concrete plan their was draft.

**Comment by anohren** [comment] 2020-05-28 22:46
Yes, thank you. You explained about the switch/MultiSwitch and it was a simple misunderstanding of terminology. I have written it off as such and it is not a problem. I don't expect you to know or explain every uncertain detail. 

But after I've tried to explain -- not one, not two, but three times -- the problem of having { on, off, auto } be mutually exclusive, and subsequently having received a reply that that we "don't have that anymoe in the new design", only to then discover that...

> [...] and switch back to Auto when you feel to.

...which cannot possibly mean anything other than that "auto" is _still mutually exclusive_ with "on" and "off", since if it weren't then you would never have to "switch back to Auto" at all. 

You might understand why I felt stupid at that point for thinking that I had been unclear in my explanations, and instead had to assume they just hadn't been read. It's completely fine if you aren't interested in the topic though. We'll just end the discussion of it, and I'll wish you luck on your revamped design.
