### ISSUE TITLE
[Bug] dark png characters mixed in dark background

### ISSUE THREAD

**Issue by Banyc** [darkreader/darkreader#8220] opened 2022-02-18 03:09 UTC
# Bug Report

## Website Address

!PAYWALLED
https://medium.com/a-journey-with-go/go-concurrency-scheduler-affinity-3b678f490488

## Bug Description

The descriptions in the images can hardly being seen since the background is so dark.

## Steps To Reproduce

1. go to the web via the provided address
2. scroll down to the png image
3. observer the descriptions in the image

## Expected Behavior

- The background is bright so that I can recognize the words in the image.
- Or, invert the color of the image

## Actual Behavior

Only the transparent background is turned dark, mixed with the descriptions in the image.

## Screenshots

<img width="268" alt="image" src="https://user-images.githubusercontent.com/36535895/154611242-bf2685cb-622f-4331-81bc-f54c7ba6b487.png">

## System Information

- OS:  macOS
- Browser:  Chrome 98
- Dark Reader Version:  4.9.45

**Comment by Gusted** [comment] 2022-02-18 15:48
Duplicate of #356

**Closed by Gusted** 2022-02-18 15:48 UTC
Labels: bug
