### ISSUE TITLE
[Bug] Unchecked runtime.lastError: (occurring on locally developed webservers, possibly on other sites as well)

### ISSUE THREAD

**Issue by ivarcode** [darkreader/darkreader#6934] opened 2021-09-27 15:54 UTC
# Bug Report

## Bug Description
`Unchecked runtime.lastError: The message port closed before a response was received` happening on `localhost` when developing web applications

## Website Address
I cannot provide a site address because the code is property of my company. Nothing especially unusual about the webserver / site you need to know about.

## Steps To Reproduce
Here is an example:
- Run a local webserver on you machine and have DarkReader ON as a browser extension on Chrome (have not tested other browsers)
- Open localhost:3001 (I am running a flask webserver off this port but you could do anything) and see the error

## Expected Behavior
From what I can tell a number of other Chrome extensions have caused this in the past. This should not be happening.

## Actual Behavior
Error gets thrown. I disabled DarkReader on my work machine until this gets fixed.

## Screenshots
Cannot supply.

## System Information
- OS: Windows
- Browser: Chrome 91
- Dark Reader Version: 4.9.38

## Additional Context
None at this time.

**Comment by Gusted** [comment] 2021-09-27 15:56
Duplicate of #6892

**Closed by Gusted** 2021-09-27 15:56 UTC
Labels: bug
