### ISSUE TITLE
Automatic Toggle Dark Reader based on time defined by user.

### ISSUE THREAD

**Issue by anishmittal2020** [darkreader/darkreader#657] opened 2018-08-04 18:19 UTC
Thanks for the awsm work!

Could you please let user define the time to Toggle On Dark Reader, and time to Toggle off Dark Reader?

This is helpful for those who prefer dark reader only at night.

Inspiration: [Nightswitch-lite](https://github.com/gharveymn/nightswitch-lite)

**Comment by risualiser** [comment] 2018-08-05 10:38
Duplicate of #10.
Actually, this feature is already in [https://github.com/darkreader/darkreader/projects/1](roadmap), maybe developer is working on it right now.

**Closed** 2018-11-02 08:42 UTC
Labels: duplicate
