### ISSUE TITLE
Wikimedia Foundation websites bugs - part 2

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13068] opened 2024-08-02 15:57 UTC

**Comment by Myshor** [comment] 2024-08-02 17:20
Told you that it won't be last fix... one fix can break another.
I already made some fixes I catched on some pages after my fixes but not this one. 😁

The fix will be in a minute.

And I tried all URLs from Part I issue to be sure everything will work. 😉 So now only new wikimedia pages with issues. 😝
As I look into the fixes for it it would be easier to use native Dark Mode of wiki than doing fixes. 😂

I bet most of issues are because they inject style into html and I need to force our colors with !important.

Ok... enough of my complains... time to push next fix. 🙂

**Comment by Myshor** [comment] 2024-08-04 15:37
I will push the fix in a minute but I need to think about some alternative for that inverting background in infobox when you find new color 😋

**Comment by Myshor** [comment] 2024-08-04 16:46
we will see... most of signatures will be dark with transparent background... if you find different then I will think about making fix to exact ones.

And more thoughts about infobox colors... I looked how official dark mode of wikipedia is working with this and they just set one background for whole infobox 😝 So... when there will be more issues with colors in infobox I think I will end with the same solution. 😈

**Comment by Myshor** [comment] 2024-08-04 17:01
> Without Dark Reader that line does not exist.

It's not a bug... It's a feature. 😁

It's because of this part in fixes.
![obraz](https://github.com/user-attachments/assets/b76a8e5a-1abd-4a47-82de-0c71fc64bb5f)

I can remove .infobox-image but I am afraid it will break some older fix with setting borded with fixed color. So it's a feature. 😋

**Comment by Myshor** [comment] 2024-08-04 17:18
Ok... found where I used this fix.

I was to fix this page:
https://github.com/darkreader/darkreader/issues/12763#issuecomment-2242502669

I will remove this .infobox-image for now and add the broken color there istead. However if there will be new problematic borders under images it will be easier to revert this and put back whole .infobox-image back.

**Comment by Myshor** [comment] 2024-08-07 08:23
Adding fix for lavender color... 😝
![obraz](https://github.com/user-attachments/assets/a67a76b1-dd49-45ff-aaa1-43c0dc27a6c8)

Still thinking very seriously to set inherit color for all parts with different background so it would look like dark mode from Wikipedia:
![obraz](https://github.com/user-attachments/assets/6a67b655-a37f-4ede-bb41-2b622a7f26a5)

This would remove problems with all next new catched colors. 😋
Now every new color is needed to be fixed because I even not set invert but use the invered version of found color.

So think about 2nd option as you are using wikipedia most and submit most of issues to it. 😉

For now I add next color as I wrote in the first line. 😉

**Comment by Myshor** [comment] 2024-08-09 11:06
Adding fix in a moment...

**Comment by Myshor** [comment] 2024-08-11 14:58
I am starting to think about setting all to inherit. 😋
It's the same color I fixed last time but now someone who made that page used background: instead of background-color: so it didn't match the selector. 🤦‍♂️

I will push fix in a sec.

**Comment by Myshor** [comment] 2024-08-12 12:12
For now I will push still the background color fix + borders fix.

I will try to think if it would be possible to make the background fixes refactored and check if making `inherit` for some general selector won't break infobox even more. 🙄

**Comment by Myshor** [comment] 2024-08-12 12:36
I think I found the solution for the colors in .infobox and it won't be inherit. 😉

Pushing general .infobox background solution in a minute and you will have possibility to check if you find some problem... I checked all pages mentioned in this bug and it works and uses inverted background as it should. 😁

**Comment by Myshor** [comment] 2024-08-12 12:45
![obraz](https://github.com/user-attachments/assets/0e0a3716-2d52-48bd-9c4d-5d204862459d)

**Comment by Myshor** [comment] 2024-08-14 11:56
First invert added.

Second thing - as I can not use variables with `${color}` I used black and white... because putting there var(--darkreader-neutral-text) won't do anything. But I will put manually inverted that color into fixes.

**Comment by Myshor** [comment] 2024-08-17 18:24
> https://en.wikipedia.org/wiki/Voepass_Linhas_A%C3%A9reas_Flight_2283
> 
> Wrong color in infobox.

Color is good... Everything inverted. 😈 Did you check how it looks without dark reader enabled? 😝

I add fix to exclude invert if orginal text color is white.
Same for setting text color it now exclude original white.

For the borders... it catched "border" in html style but as they didn't have 1px so I now check if the setting has 1px too.

**Closed** 2024-08-17 18:27 UTC
Labels: Broken Website
