### ISSUE TITLE
[Broken Website] PDF reader ONLINE PDF

### ISSUE THREAD

**Issue by bdmariobd** [darkreader/darkreader#7212] opened 2021-10-30 17:04 UTC
# Broken Website Report

## Website Address

Not an actual adress. PDF reader WITH ONLINE PDF, NOT DOWLOADED PDF - Chromium Browsers
## Steps To Reproduce

Open a PDF file online, NOT A DOWLOADED ONE (it doesn't work with them). They're not protected by the browser. For example, this scientific article: [https://arxiv.org/pdf/2005.12872.pdf](https://arxiv.org/pdf/2005.12872.pdf)
## Expected Behavior

Dark Background, and not inverted images, as seen in Actual Behavior.
## Actual Behavior

Light background, PDF color inverted (great that is dark background), but inverted image color (i don't like that).
I'm using Vivaldi, but I got the same results at Chrome.
## Screenshots

Vivaldi:
![image](https://user-images.githubusercontent.com/56127361/139542314-cd14f729-9c16-4108-a498-fd81ba65c44b.png)
Chrome:
![image](https://user-images.githubusercontent.com/56127361/139542268-d779a529-d598-4d0c-9d4b-6b687b91b835.png)
Firefox: 
![image](https://user-images.githubusercontent.com/56127361/139542287-a9df24ea-a035-435a-89eb-be1a63fd3b26.png)

## System Information

- OS: Windows 11
- Browser: 
Vivaldi 4.3.2439.63 (Stable channel) (64 bits)
Google Chrome | 95.0.4638.54 (Build oficial) (64 bits) (cohort: Stable)
Firefox 93.0 (64-bit)

- Dark Reader Version:  4.9.39

**Comment by Gusted** [comment] 2021-10-31 08:59
Hi @bdmariobd!

There are several reasons why this behavior cannot be changed.

For Firefox we cannot modify the PDF(and thus disabled as you can see in the pop-up) because they simply don't allow extensions to be injected into PDF's.

For chromium-based browsers like Chrome and Vivaldi, they expose the PDF Viewer as 1 big element(kinda like a interactive image), so If we want to just modify the text and background we have to do it against all elements as there is no method to only target a select few element. So we Invert the whole element(which is the only thing we can do to make it dark) which also includes all images on the PDF.

We've had a few issues on Dark Reader about this behavior and arguing about adding it(while it technically cannot be done), I'm closing this issue as well as this isn't a broken website, as it's expected behavior with the current technical limits.

Regards,
Gusted

**Closed by Gusted** 2021-10-31 08:59 UTC
Labels: Broken Website

**Comment by luo-chuan** [comment] 2024-04-15 18:47
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
