### ISSUE TITLE
[BUG] Error in event handler: TypeError: Cannot read property 'l' of null

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#2966] opened 2020-06-28 11:50 UTC
### **Describe the bug**

No dark theme on some websites

### **Steps to reproduce**

- visit a website

### **Expected behavior**

Dark theme

### **Actual behavior**

There is no dark theme, Dark Reader generates an error when trying to make a dark theme.

```
Error in event handler: TypeError: Cannot read property 'l' of null
    at modifyBgHSL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:1309:60)
    at modifyColorWithCache (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:1244:26)
    at modifyBackgroundColor (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:1332:16)
    at getModifiedFallbackStyle (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:1939:38)
    at createStaticStyleOverrides (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:3569:37)
    at createThemeAndWatchForUpdates (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:3794:9)
    at createOrUpdateDynamicTheme (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:3902:13)
    at onMessage (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:3981:17)
```

The error is here:
![image](https://user-images.githubusercontent.com/4723091/85946669-c8e4e400-b8fa-11ea-9263-effd106f3197.png)

So far it's occurred on YouTube (old theme) and GitHub (this page)

### **Screenshots**

![image](https://user-images.githubusercontent.com/4723091/85946717-4a3c7680-b8fb-11ea-88f2-4fa5121b087d.png)
![image](https://user-images.githubusercontent.com/4723091/85946763-8ec81200-b8fb-11ea-99b8-a43914e9ed5e.png)

### **System Information:**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome 83.0.4103.97 (Official Build) (64-bit)
 - Dark Reader version: 4.9.11

**Comment by Gusted** [comment] 2020-06-28 11:51
Please use proper bug report template to get full details.

**Comment by LoganDark** [comment] 2020-06-28 11:54
The template has tons of fluff and unnecessary sections, but if you wish.

**Comment by Gusted** [comment] 2020-06-28 11:57
I prefer to have all information needed without asking and waiting for a continous research for myself. For this bug I was more intrested in system information as this is occuring in 4.9.11

**Comment by LoganDark** [comment] 2020-06-28 11:59
The only extra information added was version information and 2 screenshots. The rest was a bunch of fluff that I preferred not filling out. You could have simply asked for version info and I wouldn't have had to reformat the entire post, since my report was concise and already included all the info needed to reproduce the issue.

There is always information that the template doesn't catch, and in those cases it is also appropriate to ask specific questions rather than "fill out the template" (which I feel is better suited to beginners than anyone else)

I just wanted to let you know that there are now 3 unnecessary sections separated by headers that I could have simplified into a more concise report.

I filled out the template anyway, no further argument is required.

**Comment by Gusted** [comment] 2020-06-28 12:02
Hmm unable to reproduce, uhm.
I'm running `Version 83.0.4103.116 (Official Build) (64-bit)` and you `Chrome 83.0.4103.97 (Official Build) (64-bit)` Can you check for a update on chrome? Probably not the cause but just want to exclude it.
Do you use any other extensions? 
I only checked for github as youtube has new theme for me. 
Do any other pages e.g. google.com work?

**Comment by LoganDark** [comment] 2020-06-28 12:06
> Can you check for a update on chrome? Probably not the cause but just want to exclude it.

I'm on the exact same version as you! You asked for version information but you didn't even read it?

> Do you use any other extensions?

![image](https://user-images.githubusercontent.com/4723091/85946933-ae136f00-b8fc-11ea-8be1-23952aca89b0.png)

Haven't installed anything recently, these extensions shouldn't interfere with Dark Reader. Dark Reader behaved just fine before

> I only checked for github as youtube has new theme for me.

YouTube has new theme for everyone, you can bypass it by changing your user-agent to googlebot. Even worked in incognito, whoever figured that out was a legend! (I'm almost glad the new theme is SPA trash because that means they will always keep the old one around for bots)

> Do any other pages e.g. google.com work?

Yes, tested that while making the report. It's why I specified 2 specific sites instead of "all websites"

**Comment by LoganDark** [comment] 2020-06-28 12:08
![image](https://user-images.githubusercontent.com/4723091/85947067-5de8dc80-b8fd-11ea-8fd0-03d9305f66a9.png)

Here you go, `pole` is null. Any idea why that happens?

**Comment by LoganDark** [comment] 2020-06-28 12:10
`anotherPoleColor` is `undefined`, that means `modifyColorWithCache` is being called with `undefined`, which means `pole` in `modifyBackgroundColor` is `undefined`, which means `getBgPole` for the `theme` is returning `undefined` (`theme` is set correctly).

What can you do with this info?

**Comment by Gusted** [comment] 2020-06-28 12:12
1. Go to chrome://system -> Expand extensions copy paste them please I will have a look if something interfere with it.
2. Oh lol googlebot.
3. Do you have anything changed to those sites in Dark Reader settings?
4. I don't know anything about color.ts and the algorithm I didn't maked them nor I understand them. 
5. Seems you understand Dev Tools :D Set breakpoint on getBgPole and see if you find anything unusual/where the undefined comes from.

**Comment by LoganDark** [comment] 2020-06-28 12:12
Oh I know what it probably is. If it's a new addition, you didn't add `lightSchemeBackgroundColor` and `darkSchemeBackgroundColor` to my theme when I upgraded. Data fixers! :D

**Comment by LoganDark** [comment] 2020-06-28 12:14
The reason it works on other sites, I think, is because site-specific themes didn't get updated with those new keys but the global themes did. That's also why creating a *new* site-specific theme doesn't reproduce the issue.

**Comment by Gusted** [comment] 2020-06-28 12:14
> The reason it works on other sites, I think, is because site-specific themes didn't get updated with those new keys but the global themes did. That's also why creating a _new_ site-specific theme doesn't reproduce the issue.

Aha that make more sense site-specific themes! I can do something with that perhabs, thank you!

**Comment by LoganDark** [comment] 2020-06-28 12:16
It could be fixed by initializing these keys with their default (or calculated) values whenever you encounter a theme that doesn't have them. That would fix all themes, in present and future, forever. Because any theme encountered that could have possibly triggered this error will have been fixed.

**Comment by Gusted** [comment] 2020-06-28 12:18
Uhm, no as I didn't use any specific themes and don't planned to use them. But it got me when you said it didn't reproduced on other sites.

**Comment by LoganDark** [comment] 2020-06-28 12:19
Well, you know `pole` was null so you probably could have went up the call stack and found out which function call was returning it :P

Just devtools makes it a lot faster and easier

**Comment by Gusted** [comment] 2020-06-28 12:22
Yeah pole was null and came from the first function of staticOverride fallback. So it probably was a more global problem instead of passing a wrong argument in x situation

**Comment by Gusted** [comment] 2020-06-28 12:25
I hope it can be tomorrow merged and perhabs released as hotfix as I know a lot of people use site-specific option and are now all broken...

**Comment by LoganDark** [comment] 2020-06-28 12:31
I hope it happens today because the light theme is burning my eyes

**Comment by Gusted** [comment] 2020-06-28 12:32
1. Can't publish release
2. Owner needs to review manual all code related changes

**Comment by LoganDark** [comment] 2020-06-28 12:33
> 1. Can't publish release
> 2. Owner needs to review manual all code related changes

I'm saying I hope the owner reviews it quick, I'm not saying that you are the problem

**Comment by Gusted** [comment] 2020-06-28 12:35
It's weekend and he is not online on discord and won't be until Monday, I already gave all information when he will read it. Hopefully today else tomorrow.

**Comment by LoganDark** [comment] 2020-06-28 12:36
Okay man, I'm sorry for whatever I did. I just hope this fix gets released ASAP.

**Closed** 2020-06-28 13:20 UTC
Labels: bug

**Comment by Gusted** [comment] 2020-06-28 13:32
```
alexanderbyToday at 15:30
Great, thanks!

I will push another update.
```

Their you go! Now you should wait on google to review it and push the update to users.
Thank you for reporting this quite criticial issue!
