### ISSUE TITLE
[Broken Website] www.virustotal.com

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#9072] opened 2022-06-13 06:41 UTC
# Broken Website Report

## Website Address
https://www.virustotal.com/gui/home/search

## System Information

- OS: Linux
- Browser: Firefox 101
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment] 2022-06-17 19:17
Duplicate of #4682

**Closed by Gusted** 2022-06-17 19:17 UTC
Labels: Broken Website
