### ISSUE TITLE
[BUG] Export settings as JSON file don't work on Vivaldi Browser

### ISSUE THREAD

**Issue by Glaived** [darkreader/darkreader#2999] opened 2020-07-01 22:49 UTC
### **Describe the bug**

Export settings as JSON file don't work on Vivaldi Browser. There is no file launched for downloading. It doesn't seem to me that there's a console error

### **Steps to reproduce**

- Click on Dark Reader button
- Click on Dev tools (in the bottom-right corner)
- Click on Preview new design
- Click on Settings
- Click on Manage settings
- Click on Export Settings

### **Expected behavior**

There should be a JSON file added to the download list.

### **Actual behavior**

Nothing's happening.

### **System Information:**
 - OS: W10 Pro x64 1909 (18363.900)
 - Browser: Vivaldi v3.1.1929.45 (Stable channel) (64 bits)
 - Dark Reader version: v4.9.13

**Comment by Gusted** [comment] 2020-07-01 22:52
Try guest profile or clean profile with dark reader could be your settings

**Comment by Glaived** [comment] 2020-07-02 00:35
Extensions are not available in guest mode.
I tried to reset the Dark Reader settings to resolve the export (After checking the contents of chromium.storage.sync, it seems that the reset was successful), but it didn't solve the problem.

**Comment by Gusted** [comment] 2020-07-02 15:55
Hmm seems I'm going to install yet another browser.

**Comment by Gusted** [comment] 2020-07-02 15:56
Btw can you just normal download a file from other sites?

**Comment by Glaived** [comment] 2020-07-02 16:00
Yep, tested from http://www.ovh.net/files/

**Comment by Gusted** [comment] 2020-07-02 16:51
Browser bug, I can't get it to working. I will add in the back-end to copy the data to your clipboard seems that good to you?

**Comment by Glaived** [comment] 2020-07-02 16:53
> Browser bug, I can't get it to working. I will add in the back-end to copy the data to your clipboard seems that good to you?

Yep, it's always better than nothing

**Comment by Gusted** [comment] 2020-07-02 17:25
I actually would maked it that it won't show for Vivaldi users that it would be saved to a JSON but Vivaldi is taking measurements against fingerprinting and make it for a basic detection impossible to show it's vivaldi.

**Comment by Glaived** [comment] 2020-07-02 17:40
Yeah, some services were abusive and anti-competitive towards Vivaldi, the development team chose to avoid this to make the use more homogeneous.

**Comment by Glaived** [comment] 2020-07-08 05:07
Dark Reader version: v4.9.14

No error, no copy to clipboard

**Comment by Gusted** [comment] 2020-07-08 12:45
The issue is still open and the PR is still not merged. Weird it still doesn't copy 🤦

**Comment by dominic-03** [comment] 2020-07-08 17:25
Can reproduce in Vivaldi Snapshot 3.2.1959.3 on arm64/Debian Linux

**Closed** 2020-07-08 18:17 UTC
Labels: bug
