### ISSUE TITLE
[Broken Website] Lando

### ISSUE THREAD

**Issue by saschanaz** [darkreader/darkreader#5603] opened 2021-04-21 00:19 UTC
# Broken Website

## Website
https://lando.services.mozilla.com/D100000/

## How to Reproduce

1. Click the link
2. See the "Preview Landing" button has no background color in dark mode
3. Switch to light mode
4. Return to dark mode

## Expected behavior

The button should have a gray background color, and after step 4 the page should be same as it looks after step 1.

## Actual behavior

No background color, and after step 4 some elements becomes white.

## Screenshots

![image](https://user-images.githubusercontent.com/3396686/115479034-d089c680-a247-11eb-9e3c-0d206863aa10.png)

![image](https://user-images.githubusercontent.com/3396686/115479039-d5e71100-a247-11eb-89d8-b000c3c1a185.png)

## System Information

- OS:  Windows
- Browser:  Firefox 88
- Dark Reader Version:  4.9.31

## Additional context

I think it regressed some weeks ago.

**Comment by Gusted** [comment] 2021-04-21 15:12
That's new, even after on -> off -> on it won't display correct. Seems like their is some issue in collecting the styles of the site.

**Comment by Gusted** [comment] 2021-04-21 15:23
> I think it regressed some weeks ago.

The regression was within a release ~20 days ago. So very good possible. #5612 fixes this and we just had a new release It's very good possible that the next release is over 4+ weeks. So I hope you won't mind side-loading for a while until v4.9.33 is released.
[build-firefox.zip](https://github.com/darkreader/darkreader/files/6352043/build-firefox.zip)

**Comment by saschanaz** [comment] 2021-04-21 15:27
Confirmed that it works, thanks! ♥

**Comment by alexanderby** [comment] 2021-04-21 16:31
@saschanaz Could you please try version 4.9.32 released today? I see no issue there.

**Comment by alexanderby** [comment] 2021-04-21 16:54
@saschanaz Are you related to Firefox? There is a Firefox bug: when new `HTMLStyleElement` is created by `document.createElement('style')`, it sometimes throws a CORS error, when trying to manipulate its sheet via CSSOM. Assigning empty `textContent = ''` fixes the issue.

**Comment by saschanaz** [comment] 2021-04-21 18:47
I wonder this is again a variation of https://bugzilla.mozilla.org/show_bug.cgi?id=1697829. Do you have a minimal example that reproduces CORS issue?

**Comment by Gusted** [comment] 2021-04-21 19:16
> I wonder this is again a variation of https://bugzilla.mozilla.org/show_bug.cgi?id=1697829.

It's a longer outstanding issue we had, let me see... #2359 Around that time we found that the issue was when the textContent is set it didn't had such CORS issue and the issue itself(#1009) dates from 2019.



> Do you have a minimal example that reproduces CORS issue?

As this is just reproduce-able on websites with hardened CSP Headers, such as archlinux.org privacytools.io and pypi.org. It will need a little server to set such headers. 

Please note while I was working on this little reproduce-able, that I wasn't able to reproduce this with `<script>`on the site-itself. So I might be related that's cross-content injection, so I had to switch to a small Extension to do the injection.

[aaa-site.zip](https://github.com/darkreader/darkreader/files/6353354/aaa-site.zip)
use `node run.js` to run the server on port 3000 and side-load the extension then navigate to 0.0.0.0:3000.
You will observer that the element with textContent will be injected `p { color: red }` and the other one will error out in the console due to the `style-src: 'self';` CSP header. 

Regards,
Gusted

**Comment by saschanaz** [comment] 2021-04-21 21:37
Thanks! I can reproduce it and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1706787 for the relevant people to take a look.

**Comment by Gusted** [comment] 2021-04-21 21:39
> Thanks! I can reproduce it and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1706787 for the relevant people to take a look.

Thank you! Let's see how this packs out.

**Comment by Gusted** [comment] 2021-04-27 20:13
Guess we can close this one 😄 as latest version is pretty much by now installed on every user.

**Closed by Gusted** 2021-04-27 20:13 UTC
Labels: Broken Website
