### ISSUE TITLE
[BUG] GitHub -> New issue -> Broken website: Change to "Broken/slow website"?

### ISSUE THREAD

**Issue by Jonta** [darkreader/darkreader#3971] opened 2020-10-29 13:46 UTC
- 91 [bugs containing the word "slow"](https://github.com/darkreader/darkreader/issues?q=is%3Aissue+slow)
- Unclear to me whether "Broken website" should be used for "broken in the sense that it is significantly slower with DR"
- People are [being pointed away](https://github.com/darkreader/darkreader/issues/535#issuecomment-716626866) from https://github.com/darkreader/darkreader/issues/535 for reports on slow pages

=)

**Comment by Gusted** [comment] 2020-10-30 09:04
> 91 bugs containing the word "slow"

Whereby 75 closed and 16 still open. Not sure what the point is?

> Unclear to me whether "Broken website" should be used for "broken in the sense that it is significantly slower with DR"

... I'm unclear how the reference with Broken website and `significantly slower` is being made as a good example of a broken website issue is #3969. As it's consider it can be fixed by some CSS whereby the performance issue is consider for the bug template and should be looked individually at.

> People are being pointed away from #535 for reports on slow pages

Yes, because it's not generally a performance issue in Firefox. But those site can contain certain scenarios whereby Dark Reader is slow and if this is the case(so far it has been) it's nice to have a clean issue and not have to scroll down 50 comments and having emails to sent to all participant in the issue. 

Regards,
Gusted

**Comment by Jonta** [comment] 2020-10-31 13:51
I stated the number as an indicator that speed is a problem that comes up somewhat often. Perhaps often enough that a change in the "New issue"-page would be warranted

It's clearer to me now that "website X is significantly slower with DR" should be reported as a new issue, and I still think clarifying that in the "New issue"-page would be helpful

To me, "broken site" reads as different enough from "much slower site"

**Comment by Gusted** [comment] 2020-10-31 22:56
> Perhaps often enough that a change in the "New issue"-page would be warranted

Not sure, as performance issue is a very wide spectrum and therefor can't be explained with some pre-defined steps.

> It's clearer to me now that "website X is significantly slower with DR" should be reported as a new issue, and I still think clarifying that in the "New issue"-page would be helpful

Same as above and the only issue was that people kept reporting in #535 which now clarified to not do this and open up a new issue. 

> To me, "broken site" reads as different enough from "much slower site"

The site is broken, because it's slow when dark reader it's on.

**Comment by Jonta** [comment] 2020-11-03 13:47
The clarifications in #535 and here are all well and good for those of us who have happened to read those

How should a newcomer report a slow site? (New issue -> Site broken)

And is it reasonable to expect a large enough portion of them to do so? (imo: No)

**Comment by Gusted** [comment] 2020-11-04 12:52
> How should a newcomer report a slow site? (New issue -> Site broken)

Doensn't matter, You just need a URL to have someone reproduce and the device info. So Site Broken Or Bug Report is fine.

> And is it reasonable to expect a large enough portion of them to do so? (imo: No)

Like I said, I personally don't care if it's a case where a site is slow. I just need the standard info. And a large enough portion can provide those.

**Comment by Jonta** [comment] 2020-11-11 12:52
I thought I had put it differently, so here's a correction:

Is it reasonable to expect a large enough portion of users to realise that "Site broken" is the correct place to report a slow site? (imo: No)

**Comment by Gusted** [comment] 2020-11-11 20:57
#4097

**Closed** 2020-11-12 18:00 UTC
Labels: bug
