### ISSUE TITLE
[Bug] Not work when local PDF file name contain character '['

### ISSUE THREAD

**Issue by AlfredXiaSF** [darkreader/darkreader#8002] opened 2022-01-20 08:07 UTC
# Bug Report

## Bug Description

Not work when local PDF file name contain character '['

## Steps To Reproduce

- open loacal PDF file name contain '['
- rename the file, remove '['
- Observe its color

## Expected Behavior

The background of local PDF should be Black, when select Dark mode in Dark Reader

## Actual Behavior

The background of local PDF is White, when PDF file name contain ‘['

## Screenshots

![image](https://user-images.githubusercontent.com/33239379/150297331-805a5642-bfee-4610-9026-785173769e36.png)

## System Information

- OS: Windows 11- 21H2 - 22000.434
- Browser: Chrome  97.0.4692.99
- Dark Reader Version:  4.9.43

**Comment by Gusted** [comment] 2022-01-20 12:04
Duplicate of #7206

**Closed by Gusted** 2022-01-20 12:04 UTC
Labels: bug
