### ISSUE TITLE
Google Sheets is changing text color

### ISSUE THREAD

**Issue by jeff275** [darkreader/darkreader#490] opened 2018-05-11 13:16 UTC
![screen shot 2018-05-11 at 8 16 23 am](https://user-images.githubusercontent.com/39192561/39926048-a1408d72-54f3-11e8-9b7e-0dc527b2cb9b.png)

**Comment by arthurblake** [comment] 2018-05-14 13:08
What I've noticed happening is when you type text into a new cell in Google Sheets, the color comes out unreadable/invisible. Seems to be something caused by the new dynamic theme. Maybe the dynamic theme is not picking up a dynamic CSS color change. If you copy one cell to another or reset the color (with google sheets) it fixes it. But it's annoying if you are typing in a lot of data into the sheet.

**Comment by jeff275** [comment] 2018-05-14 14:06
Yes, exactly. It's a lot of work on highly used spreadsheets.

**Comment by krupenja** [comment] 2018-07-26 20:08
Quick workaround for this is to select all affected cells and set colour to black from Sheets menu bar. Obviously only works if you only use black colour for text.

**Comment by jeff275** [comment] 2018-07-26 20:30
It's less work to just disable Dark Reader on the Google Sheets.

**Comment by rtman** [comment] 2018-08-17 19:48
Just noticed this too, its super frustrating

**Comment by electricityforprogress** [comment] 2018-10-13 14:17
I believe this is due to the mode which you are using.  Change the settings to Filter+ under DarkReader --> more --> filter+, I only use this setting with docs.google ...  Same thing happens with some Gmail emails and Calendar which you may want to toggle settings for those sites too.

![darkreader_filterplus](https://user-images.githubusercontent.com/22551283/46906382-a0237d80-ced0-11e8-8025-d9ecdcfeadc5.png)

**Comment by Fabian42** [comment] 2018-12-04 12:16
Confirmed, switching to "Filter+" for docs.google.com works around the issue. But it's still a valid bug, isn't it? There's no reason why the "Dynamic" filter should change the text colour, so this issue should be reopened.

**Comment by Fabian42** [comment] 2018-12-06 14:36
Ah, ok. I just saw a red "Closed" label and thought it referred to this one.

**Comment by MavropaliasG** [comment] 2018-12-13 11:35
Can confirm, please fix!

**Comment by ufo2mstar** [comment] 2018-12-17 16:54
The "Filter +" theme engine works perfectly for sites like Google Sheets (and even github, it looks like)..
So would a feature request like defaulting the experimental theme engine to 'known-issue' sites be more apt for the fix? @Fabian42 @darkreaderdev

**Comment by Fabian42** [comment] 2018-12-17 18:34
Can you please reword that? I don't understand what you mean.

**Comment by alexanderby** [comment] 2018-12-17 21:30
It is planned to fix the issue this month.

@Fabian42 The idea was to force Filter mode on Google Sheets by default. The fix will be the probably the same: switching off CSS analysis for editor area and applying CSS filter to it.

**Comment by Fabian42** [comment] 2018-12-17 21:44
That would be one possible fix, yes. But making it default instead of
enforcing it would of course be better.

**Comment by forzentorafe** [comment] 2019-02-08 17:20
Hi! I have another workaround that works for per sheet.
1. hold ctrl and press A. This will select the cells that currently have data in a rectangular box.
2. press A again to select the entire sheet ( includes blank cell )
3. right click
4. go to conditional formatting. by default, they will create a rule for you to use.
5. Click Fill Color ( which is like a bucket spilling a drop of paint ) 
6. Click None.
7. Click Text Color.
8. Choose Black color, which will be inverted to white by darkreader.
9. Test this by typing in a cell and pressing enter.

Ps. This probably won't help as much for those sheets that are already using conditional formatting or have the need for multiple text colors. So... sorry about that :)

**Comment by jeff275** [comment] 2019-02-08 17:41
That's wayyyyyy too much of a workaround.

**Comment by Fabian42** [comment] 2019-02-09 00:13
Btw, this issue is not exclusive to Dark reader. There's an extension made by Google that can invert tabs and it has some weird side effects with Google Docs as well. Once I wasted a lot of ink when printing a mostly white document that I believed to be only visually inverted.

**Comment by mastahcez** [comment] 2019-03-11 11:30
Filter+ is ok for me since I don't work that much in sheets but would be nice to properly fix this. Took me a few weeks of patiently turning DR off and on to fill out forms till I found this issue today.

**Comment by AndroidDeveloperLB** [comment] 2019-04-15 13:39
Is it possible to have the plugin ready for this website, instead of us modifying things for it?

**Comment by Fabian42** [comment] 2019-05-04 21:46
I now switched from "Filter+" to "Filter", because "Filter+" breaks some embedded images in Google Docs.

**Comment by portothree** [comment] 2019-06-12 15:12
> I believe this is due to the mode which you are using. Change the settings to Filter+ under DarkReader --> more --> filter+, I only use this setting with docs.google ... Same thing happens with some Gmail emails and Calendar which you may want to toggle settings for those sites too.
> 
> ![darkreader_filterplus](https://user-images.githubusercontent.com/22551283/46906382-a0237d80-ced0-11e8-8025-d9ecdcfeadc5.png)

you are a lifesaver

**Comment by mountswolmore** [comment] 2019-10-17 20:05
Using filter+ makes it incredibly hard to know what color you're checking as the pallet is all messed up.

The color picker is accurate with Dynamic.

**Comment by NorthIsUp** [comment] 2019-11-20 00:26
filter+ isn't an option on the safari extension. so a real fix would be appreciated :)

**Closed** 2019-11-29 10:13 UTC
Labels: Dynamic Theme, bug

**Comment by NorthIsUp** [comment] 2020-02-21 01:49
This is still happening for me in safari, is that expected?

**Comment by FranklinYu** [comment] 2020-02-21 07:30
@NorthIsUp I don’t think so. I’m currently using the Filter+ mode for this reason.
