### ISSUE TITLE
[Broken Website] IMDb.com new layout

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#6173] opened 2021-07-03 04:42 UTC
# Broken Website
## Website

https://www.imdb.com/title/tt4978420/?ref_=nm_flmg_dr_2

## How to Reproduce

  - Go to Imdb.com
  - Navigate to any title page
  - See that text is hard to read and background is still white

## Expected behavior

It should be easier to read and majority of background should be dark

## Actual behavior

The background is still white and text is hard to read

## Screenshots

DR disabled: 
![image](https://user-images.githubusercontent.com/46114199/124343140-38308c00-db7e-11eb-927c-51d9b455ddc2.png)

DR enabled:
![image](https://user-images.githubusercontent.com/46114199/124343124-1a632700-db7e-11eb-86d8-62ed8cd11353.png)

## System Information

- OS:  Windows
- Browser: Firefox 89
- Dark Reader Version: 4.9.33

**Comment by Mennaruuk** [comment] 2021-07-03 06:15
Hmm. Can't reproduce.
![Screenshot 2021-07-03 at 02-13-54 Borderlands (2022) - IMDb](https://user-images.githubusercontent.com/52135169/124345074-73de4c80-dba4-11eb-8928-104d5f5bc2b9.jpg)

**Comment by Gusted** [comment] 2021-07-03 11:54
Are you sure about the 4.9.33 version? We included a fix for this particular issue a while ago. If you've modified the devtools inside dark reader. Ensure that you restart the Dev tools. Anyway wontfix as this is already fixed.

**Closed** 2021-07-04 12:56 UTC
Labels: Broken Website, wontfix
