### ISSUE TITLE
Can you make the addon scheduled?

### ISSUE THREAD

**Issue by ars4l4n** [darkreader/darkreader#1236] opened 2019-04-10 22:31 UTC
A good thing would be turning dark mode on at sunset or dusk
or eg sunset+2 hours

**Comment by Andrew5569** [comment] 2019-05-12 01:02
This is a duplicate of /issues/72

**Comment by Gusted** [comment] 2020-07-28 14:36
https://darkreader.org/blog/automation

**Closed by Gusted** 2020-07-28 14:36 UTC
