### ISSUE TITLE
Dark Reader not working and perpetually "Loading, please wait"

### ISSUE THREAD

**Issue by timblaktu** [darkreader/darkreader#700] opened 2018-08-29 00:12 UTC
I have updated my OSes, restarted Chrome, and rebootes OSes, and Dark Reader still doesn't work and the toolbar dropdown is always stuck at "Loading please wait".

I'm seeing this issue with Chrome 68.0.3440.106 in Windows 10 Pro and also Chrome 68.0.3440.106 on OSX 10.13.6 (17G65).

**Comment by risualiser** [comment] 2018-08-29 05:13
I'm not a developer, but I think you should check your browser console (`Ctrl+Shift+J` or `F12` -> "Console" tab), while you turn off/on the extension. This information could help to fix it.

**Comment by alexanderby** [comment] 2018-08-29 21:47
Hi. Go to `chrome://extensions` page, enable the Developer Mode, under Dark Reader click `background.html`. Do you see any errors in Console? Also you can look at popup page Console: right-click Dark Reader icon and click "Inspect popup".

**Comment by timblaktu** [comment] 2018-08-30 23:54
I don't see anything in inspect popup - console, but in the
background/index.html Console I see 2 errors:

Uncaught (in promise) TypeError: Cannot read property 'notifyOfNews' of null
    at Newsmaker.Extension.news.Newsmaker [as onUpdate] (index.js:2160)
    at Newsmaker.updateNews (index.js:1139)
index.js:1471 Uncaught (in promise) TypeError: $settings.siteList.filter is
not a function
    at UserStorage.set (index.js:1471)
    at Extension.changeSettings (index.js:2277)
    at Extension.start (index.js:2196)

When I disable the extension and reenable it, and then go look at the
background/index.html Console, I see just the second error from above:

index.js:1471 Uncaught (in promise) TypeError: $settings.siteList.filter is
not a function
    at UserStorage.set (index.js:1471)
    at Extension.changeSettings (index.js:2277)
    at Extension.start (index.js:2196)

and I see nothing change as I click the DarkReader icon multiple times.

**Comment by timblaktu** [comment] 2018-09-05 17:21
Problem went away after removing extension, restarting chrome, and adding extension to chrome.

**Comment by alexanderby** [comment] 2018-09-07 15:01
@timblaktu Do you remember how long are you using Dark Reader? One of possible reasons could be that there was a time when Chrome stored arrays as objects. I've removed this check and conversion from object to array recently, so this could cause your problem. Unfortunately now we will never know what settings you actually had.

**Comment by timblaktu** [comment] 2018-09-09 23:27
I think it's been a little over a year and a half. I can check my browser
history to get more accuracy if you want.

**Comment by MartyMacGyver** [comment] 2018-09-11 02:08
FWIW I'm seeing the same problem in Chrome 69.0.3497.81 (Official Build) (64-bit).

I did the uninstall/reinstall bit to no avail, except now toggling the extension off and on no longer helps either.

I do see this and only this in the `background/index.html` console when I enable the extension:

    Uncaught (in promise) TypeError: Cannot read property 'notifyOfNews' of null
        at Newsmaker.Extension.news.Newsmaker [as onUpdate] (index.js:2171)
        at Newsmaker.updateNews (index.js:1140)

**Comment by MartyMacGyver** [comment] 2018-09-11 03:03
I suspect there's a race condition in the constructor involving `this.user.settings` - it's hard to pin down in the debugger but while you can easily log `this.user` to the console and it appears to have settings correctly within it, if you try to display `this.user.settings` it simple logs as `null`.

**Comment by MartyMacGyver** [comment] 2018-09-11 03:09
If you shift that `this.news = new Newsmaker((news) => {...}` block into the `start()` code block, it all seems to behave better.

**Comment by MartyMacGyver** [comment] 2018-09-12 01:28
Update: FWIW this happened again to me today, with the changes (however, I was able to toggle the extension and restore functionality). This was after the computer was asleep for the day. 

That said, the notable error was `net::ERR_CONNECTION_REFUSED` for the debugger at `http://localhost:8890/`, which is what's currently loaded. So either there's still a race condition or this is a side-effect of debugging (but it's working now despite those errors continuing so I suspect it's still a race condition of some sort).

**Comment by MartyMacGyver** [comment] 2018-09-12 01:40
I was able to reproduce this using a built extension with the News fix (which again may not be part of the problem). I put the computer to sleep, woke it up, clicked the extension button, got the "Loading" problem, and saw an error I've not seen before and which is NOT in the debugger window, only the errors tab in chrome (the one you get to by clicking the "Errors" button):

`Uncaught (in promise) RangeError: Unsupported time zone specified undefined`

it was in `ui/popup/index.js:1571 (anonymous function)`

The specific line:

`const formattedDate = new Date(event.date).toLocaleDateString(locale, { month: 'short', day: 'numeric' });`

I'm not yet sure what to make of it yet.

**Comment by MartyMacGyver** [comment] 2018-09-12 02:59
... but I have a theory.

`toLocaleDateString` is from what seems to be the Typescript library, and ends up using `Intl.DateTimeFormatOptions` . That led me to this issue:

https://github.com/andyearnshaw/Intl.js/issues/293

When you look at Intl, indeed, timezones are apparently not supported, and there's a long-standing enhancement request open for that:

https://github.com/andyearnshaw/Intl.js/issues/19

Perhaps this is a dependency issue that crept in. I'm not sure how to ideally solve this, but commenting out the use of the `formattedDate` seemed to help, and it worked after returning from sleep as well (I'm not sure *why* that factors in, but it may be due to how Chrome manages memory for sleeping processes as this also happens after a period of inactivity).

IMHO, when I click the news button, I'd be happy if it just opened the news page instead of having a tiny popup within the popup. That'd obviate the need for this entirely (the release notes already do this and you end up clicking twice to see the news if you're interested - and if you clicked "News" odds are you wanted to read it anyway).

**Comment by MartyMacGyver** [comment] 2018-09-13 04:09
FYI @alexanderby et al., with that second correction the extension seems to be stable, even after a long sleep cycle.

**Comment by alexanderby** [comment] 2018-09-13 08:35
@MartyBeGood `http://localhost:8890/` is a live-reload server, that triggers extension reloading after the source code change, if you run `npm run debug`. It will not try to connect in release.

What about a time error, I think this is Chromium [issue 811403](https://bugs.chromium.org/p/chromium/issues/detail?id=811403). Try executing `(new Date()).toLocaleDateString();`, maybe you have some manually set up timezone on your machine, or maybe there is some other Chrome bug. But the `toLocaleDateString` is a [part of JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), not some dependency. I've just added a workaround for this.

**Comment by MartyMacGyver** [comment] 2018-09-14 06:28
I think you were replying to me there.

First, The updated version seems to work.

Second, it looks like I was tracing into Visual Studio Code's source so it's apparently not loading the particular library I thought it was from that place.

However, I'm not convinced it's that particular Chrome bug either. Depending on the page I'm on, entering `(new Date()).toLocaleDateString();` either fails or works fine, consistently. The output of `Date()` itself is also interesting:

https://www.google.com/ - Fails if logged in, works in incognito mode (where I'm not logged in):

```
(new Date())
Fri Sep 14 2018 05:45:59 GMT+0000 (GMT)

(new Date()).toLocaleDateString();
VM1520:1 Uncaught RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (/native)
    at Date.toLocaleDateString (/native)
    at <anonymous>:1:14

Date()
"Fri Sep 14 2018 05:43:30 GMT+0000 (GMT)"
```

https://ifconfig.co/ - Works fine in any mode

```
(new Date())
Thu Sep 13 2018 21:43:22 GMT-0800 (GMT-08:00)

(new Date()).toLocaleDateString();
"9/13/2018"
```

FWIW, `(new Date()).toUTCString()` gives the same (GMT) output in any of these and never fails.

I find it very peculiar that the timezone (and/or the way `Date()` works) is slightly different depending on whether I'm authenticated to Google or not in a given window, though that definitely seems to be the problem. I'm not sure what to make of it....

**Comment by MartyMacGyver** [comment] 2018-09-14 06:50
While writing all that, I noticed Chrome wanted to upgrade, so I just did that (now `Version 69.0.3497.92 (Official Build) (64-bit)`).

The weird problem with `Date()` went away. It seems to be consistent on all tabs now.

As I relaunched several times while investigating this the other day, whatever changed, it wasn't simply the act of relaunching the browser.

**Comment by alexanderby** [comment] 2018-11-01 10:12
Hello, does "loading, please wait" still happen to you?

**Comment by MartyMacGyver** [comment] 2018-11-01 20:04
It hasn't been a problem for me since then, so I presume whatever was going on was resolved in the new version of Chrome.

**Comment by alexanderby** [comment] 2018-11-01 20:15
Great, thank you.

**Closed by alexanderby** 2018-11-01 20:15 UTC
Labels: bug
