### ISSUE TITLE
[Broken Website] hs.fi - brown/sepia background color

### ISSUE THREAD

**Issue by 07416** [darkreader/darkreader#9484] opened 2022-08-07 10:36 UTC
# Broken Website Report

## Website Address

https://www.hs.fi/visio/

## Steps To Reproduce

- visit any of the following pages: 

- https://www.hs.fi/visio/
- https://www.hs.fi/talous/
- https://www.hs.fi/teknologia/
- https://www.hs.fi/autot/
- https://www.hs.fi/porssi/

## Problematic Observation

The page background is displayed in brown — this can be alleviated to some degree by changing the default Dark Reader BG color option from `#181a1b` to `#000000` (see the screenshots).

Seems to exclusively affect their recently launched 'HS Visio' platform — not [the frontpage](https://www.hs.fi/) for instance.

## Screenshots

![image](https://user-images.githubusercontent.com/14923168/183286672-7296a0b5-e4cb-4c69-be1e-e9f8f8ee5f60.png)

![image](https://user-images.githubusercontent.com/14923168/183286771-21befb19-d1e1-4305-b907-a347e6ded650.png)

## System Information

- OS: Fedora 36 (Linux)
- Browser: firefox.x86_64                                   103.0-1.fc36                        
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment] 2022-08-09 02:01
More or less as your other report, original site already has this color tint. Closing, working as intended.

**Closed by Gusted** 2022-08-09 02:01 UTC
Labels: Broken Website
