### ISSUE TITLE
[Feature Request] Separate whitelist and blacklist

### ISSUE THREAD

**Issue by Zoooook** [darkreader/darkreader#2413] opened 2020-04-29 01:58 UTC
I've used Dark Reader in disabled mode for a while where I add sites to the list where colors are inverted. I switched to default enabled mode recently to have it invert colors on all sites, and all of a sudden my previous list of dark sites is now bright. The exception list in disabled mode should not become the exception list in enabled mode, the two lists should be separate.

**Comment by Gusted** [comment] 2020-04-29 13:21
Duplicate of #28
And is already on the roadmap for darkreader v5 https://github.com/darkreader/darkreader/projects/1

**Closed by Gusted** 2020-04-29 13:21 UTC
Labels: enhancement
