### ISSUE TITLE
[Bug] Network connections in Thunderbird despite remote content being blocked

### ISSUE THREAD

**Issue by ElhemEnohpi** [darkreader/darkreader#6713] opened 2021-09-08 19:33 UTC
# Bug Report

## Bug Description
When Dark Reader is used with Thunderbird 78 (and possibly later), there are outgoing network connections to remote hosts, when reading some mail messages, even though remote content is blocked in Thunderbird settings. The message "Remote content blocked" is still displayed by Thunderbird, but e.g. a firewall configured to look for outgoing connections will detect them. Denying the connection doesn't seem to impact Dark Reader.

## Steps To Reproduce

- Install in Thunderbird 78.xx (I haven't tested TB 91)
- Use some method to monitor outgoing network connections.
- Uncheck "Allow remote content in messages" in Thunderbird settings.
- Read an e-mail containing remote content (not all messages with remote content trigger a connection, I'm not sure what the pattern is).

## Expected Behavior

No network connections to remote content should be made.

## Actual Behavior

Network connections are made, but only if Dark Reader is enabled.

## System Information

- OS: macOS
- Browser: Thunderbird 78.14.0
- Dark Reader Version: 4.9.34.1

## Additional Context

I had reported this as a Thunderbird bug, but it seems it's caused by Dark Reader. For more information, and a screenshot, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1722292

**Comment by Gusted** [comment] 2021-09-08 21:05
Hi @ElhemEnohpi!

Thank you for this detailed report, but honestly. I don't have a clue what to do with this. This is a Thunderbird feature, they should take care of blocking our network access. Dark Reader don't have a clue about that setting, it only know that the network request might go trough or might not go trough. If we're bypassing that restriction, then it's up to the Mozilla team to either fix it or slap a "Working as intended WONTFIX" onto this, but for as dark reader developer this is not actionable and I have to close this. I'm happy to help with that Bugzilla in anyway, but Thunderbird should restrict the access, we shouldn't go do a extra mile on Thunderbird for every network requests to check some setting(which we can't).

Regards,
Gusted

**Closed by Gusted** 2021-09-08 21:05 UTC
Labels: bug
