### ISSUE TITLE
[Broken Website] Bing Search uses custom white background

### ISSUE THREAD

**Issue by Tech-How** [darkreader/darkreader#8854] opened 2022-05-09 21:17 UTC
# Broken Website Report

## Website Address
https://www.bing.com/search?q=asd+file

## Steps To Reproduce
- Go to bing.com, or the link above
- Search for "asd file" (It's just one of the random searches with the gradient issue)

## Problematic Observation
The background of the website changes to a gradient, destroying the Dark Reader functionality.

## Screenshots
https://i.ibb.co/StQHFhd/Screenshot-2022-05-09-171423.png

## System Information
- OS: Windows
- Browser: Edge 101
- Dark Reader Version: 4.9.48

## Additional Context
I'm not sure how Bing judges their searches, but I also found that "polar bear" and "donald trump" work. Some "popular" searches, people, animals, can have their own background.

**Comment by Gusted** [comment] 2022-05-09 21:18
Duplicate of #8742

**Closed by Gusted** 2022-05-09 21:18 UTC
Labels: Broken Website
