### ISSUE TITLE
`[Feature Request]` Autodetect & autoexclude if website has it's own default dark mode

### ISSUE THREAD

**Issue by pc00per** [darkreader/darkreader#10056] opened 2022-10-10 14:45 UTC
# Feature Request
Autodetect website's default dark mode & leave extension unapplied.
TL;DR: **Respect website's builtin dark mode**

## Is this feature request related to a problem?

The extension even gets applied on dark websites & makes them look ugly (by introducing button borders, too high contrast, etc)

## Screenshots

NA

## Additional Context

I know there's an exception list feature. But on how many websites you gonna apply it? Internet almost has zillions of sites & people visit hundreds of sites per week on average. Isn't there any automatic detection of background ?

**Comment by Gusted** [comment] 2022-10-10 19:31
Duplicate of #8645

**Closed by Gusted** 2022-10-10 19:31 UTC
Labels: enhancement
