### ISSUE TITLE
[Feature Request] If the website has a bulit-in dark mode and is enabled by the user, the extension shouldn't work on the website and should be automatically disabled for that website

### ISSUE THREAD

**Issue by fadihh** [darkreader/darkreader#7750] opened 2021-12-26 15:36 UTC
# Feature Request

## Is this feature request related to a problem?
NO

## Additional Context
title is self-explanatory

**Comment by Gusted** [comment] 2021-12-26 15:41
> title is self-explanatory

The title shouldn't be used as a explanation. Duplicate of #1285

**Closed by Gusted** 2021-12-26 15:41 UTC
Labels: enhancement
