### ISSUE TITLE
Auto Toggle based on Sunrise/Sunset given by Zip Code

### ISSUE THREAD

**Issue by drewhagen** [darkreader/darkreader#72] opened 2017-05-25 20:39 UTC
Similar to how f.lux and iOS's Night Shift operates, it would be great if Dark Reader automatically was on during the day and off at night.
Currently, I do this manually, so this implementation would really save me time. Thanks!

**Comment by c-borgia** [comment] 2017-05-26 02:50
Just wanted to chip in, I prefer it on all the time.
If one doesn't want it on, one just switches it off.

**Comment by FatalMerlin** [comment] 2017-06-14 14:35
@c-borgia I totally agree, but I can see why one would want this.

@alexanderby , you could use https://github.com/mourner/suncalc to accomplish this.

To get the address as longitude and latitude you could use this code https://gist.github.com/BastinRobin/7463602.

Then you just need to provide a field to enter the address (maybe with autocomplete provided my Google Maps) and a checkbox to enable the feature.

**Comment by gsirvine** [comment] 2018-07-11 22:00
I do like white pages during the day and the dark at night.  I find myself switching it all the time so I do see this being a good idea.  To save that switching I end up doing anyways.

However, maybe a simple scheduler would be a better idea rather than zip code.    Less personal information needed.  
My problem with Flux and sunrise.  What if for example I like to wake up before the sunrise?  I want the white to energize and signal wakefulness.  To the basics white seems to be more energizing as it contains more blue on screens than black does.  

I believe a simple scheduler based on computer time be better.  A default time could be in place as long as I can modify it.  

Maybe having both would be best.  General thoughts.

**Comment by thomshouse** [comment] 2018-09-13 20:11
I must :+1: this suggestion.  It should definitely be an optional feature, but I would absolutely use it.  As it is, I manually toggle the app--when I remember to.  But some days I spend a few hours wondering why Facebook looks weird, and some nights I am blinded by a flash of un-inverted web page. :grin:

**Comment by rolagg** [comment] 2018-09-26 19:53
I think it's a duplicate of #10.
It's better for all suggestions to go on that thread.

**Comment by xgdgsc** [comment] 2019-01-19 03:07
This is very useful. I use  https://atom.io/packages/sunset in atom and https://marketplace.visualstudio.com/items?itemName=gharveymn.nightswitch for this. I guess it should be easy to borrow some code to implement this.

**Comment by real-uplink** [comment] 2019-01-23 12:30
+1 to time based rules. I think this could be implemented in a first step. Later on, a sun following scheduler may follow.

**Comment by pavel-r-georgiev** [comment] 2019-01-25 12:04
+ 1. I might look into implementing this and doing a PR when I have a bit more free time.

**Comment by EkilDeew** [comment] 2019-05-02 19:06
+1. There is already the time setting, but getting the exact timing for the sunset without needing to change time setting every few month would be better.

**Comment by ars4l4n** [comment] 2019-05-12 13:44
The thread says that the feature was added in December but how do I activate it?

**Comment by Andrew5569** [comment] 2019-06-27 14:52
@ars4l4n It was added to the features backlog but it's currently not implemented. However, you can currently set a fixed time to enable/disable dark reader. See: https://github.com/darkreader/darkreader/issues/1312#issuecomment-491555723

**Comment by chrisgross** [comment] 2019-07-09 01:28
NightOwl and Flux are increasingly popular apps that allow, for example, MacOS system themes to change and sunrise/sunset. This is the best dark-content extension for firefox, so it would be really awesome to see this implemented here, too. Sunrise and sunset times change every day, so in order to sync up with other apps, you have to keep changing this setting which is a pain.

**Comment by briancalderon** [comment] 2019-07-09 15:18
That menu icon is a bit small and I have never noticed it despite being quite technically adept. :(

Is it possible to detect the status of the browser theme? I use Flux to automatically switch to dark mode on macOS at sunset and this feature is coming natively in the system in Catalina; static time changes for the modes are—well… static.

**Comment by Yoshi2889** [comment] 2019-07-09 15:19
At least on macOS 10.15, the system now includes an Auto setting for the dark/light theme. Along with Dark Reader's Auto setting (which is present in its Safari version!) this provides pretty much what the OP wants.

I realise this may not apply to the extensions for other browsers and other OSes.

**Comment by ars4l4n** [comment] 2019-07-09 16:49
@Yoshi2889
I'm about to switch anyway
windows has no vision, no taste, no love for detail

**Closed** 2019-09-09 20:11 UTC
Labels: enhancement

**Comment by rben01** [comment] 2019-09-10 23:53
> At least on macOS 10.15, the system now includes an Auto setting for the dark/light theme. Along with Dark Reader's Auto setting (which is present in its Safari version!) this provides pretty much what the OP wants.
> 
> I realise this may not apply to the extensions for other browsers and other OSes.

I am not sure if this is a known bug or not, but for me (macOS Catalina beta) Dark Reader does not pick up on the current status of the auto dark/light theme. Regardless of whether Catalina's auto theme is using the light or dark theme, Dark Reader always shows pages in light mode when set to auto. Only if Catalina is explicitly set to (permanent) dark mode does Dark Reader's auto mode change web pages to dark.

**Comment by alexanderby** [comment] 2019-09-11 05:06
Thanks to @Kimbatt, who implemented this feature. It will be released soon after I review other Pull Requests and test a little bit. You will have to specify your location, so that Dark Reader don't have to ask for location permissions.

@rben01 Thanks for the details, I was not aware of Auto setting in Catalina.

**Comment by nickokgo** [comment] 2019-09-11 13:43
@alexalekseyenko yeah, same issue here. (Love the app, though!)

**Comment by TarikMahmudRafee** [comment] 2020-03-11 04:43
Same request here...

**Comment by 0x49D1** [comment] 2020-05-06 05:48
This is not working in Firefox  for Mobile. Probably needs to be implemented: the dark reader is nice when you use it at night, but during the day it just changes the visuals of all the websites and that's not the thing I want to have during normal browsing, not the night one. Thanks!

**Comment by Mac-lucky** [comment] 2021-05-15 22:49
I would like to have this feature too.
