### ISSUE TITLE
YouTube channel thumbnail disappear

### ISSUE THREAD

**Issue by KimiNoNaWaGithub** [darkreader/darkreader#2219] opened 2020-04-02 17:01 UTC
Here is normal thing on YouTube when I see a channel:
![image](https://user-images.githubusercontent.com/62417238/78277169-425c7880-753e-11ea-96a2-c03f0bcb0598.png)

Still that but with Dark Reader:
![image](https://user-images.githubusercontent.com/62417238/78277240-5d2eed00-753e-11ea-9452-ae113b78db1c.png)

Please fix this.

**Comment by Gusted** [comment] 2020-04-02 21:17
#2221 Fixs this 
Duplicate of #1530 But still thank you making this issue and made it aware to me.

**Comment by KimiNoNaWaGithub** [comment] 2020-04-08 01:02
![image](https://user-images.githubusercontent.com/62417238/78733285-2f4b0d80-796f-11ea-8d74-6b86cc8d520b.png)

Hey it's still that even with 4.9.4 update of Dark Reader.

**Comment by Gusted** [comment] 2020-04-08 07:22
Yeah The owner need to merge my Pull Request and than it will be in 4.9.5

**Comment by Gusted** [comment] 2020-04-15 11:55
#2221 It just got merged So I'm gonna close the issue and it will be avaible in 4.9.5 when released

**Closed by Gusted** 2020-04-15 11:55 UTC
