### ISSUE TITLE
[Feature Request] Be able to CLEAR the site lists

### ISSUE THREAD

**Issue by heyvoon** [darkreader/darkreader#5213] opened 2021-03-09 08:47 UTC
# Feature Request

## Is your feature request related to a problem? Please describe
There is no way to clear (reset) the site lists and start from scratch. Very annoying.

## Describe the solution you'd like
Some way of clearing (reset) the site lists.

**Comment by Gusted** [comment] 2021-03-09 13:45
Duplicate of #999

**Closed by Gusted** 2021-03-09 13:45 UTC
Labels: enhancement
