### ISSUE TITLE
[Bug] UI doesn't load and websites are broken after 4.9.40/4.9.41 update

### ISSUE THREAD

**Issue by marlop352** [darkreader/darkreader#7270] opened 2021-11-06 00:53 UTC
# Bug Report

## Bug Description
UI doesn't load and websites are broken on Firefox

## Website Address
Mainly tested on https://arstechnica.com/ , https://www.steamgifts.com/ and https://www.youtube.com/

## Steps To Reproduce
1 - Open website, 
2 - Stare at variable levels of broken

1 - Click on DarkReader icon on toolbar
2 - Pop-up appear with a loading text but the UI never loads

## Expected Behavior
The UI should load and be able to control DarkReader

## Actual Behavior
No UI other than the popup with a loading text on it.

## Screenshots

![2021-11-05 (5)](https://user-images.githubusercontent.com/846592/140591718-ef307fcc-8847-499e-9724-5cb09208b262.png)
![2021-11-05 (6)](https://user-images.githubusercontent.com/846592/140591721-24667a89-2b04-49f9-b2bd-089f3b4e4821.png)
![2021-11-05](https://user-images.githubusercontent.com/846592/140591723-73c3b359-d6a3-40f4-984f-babbee5f36f4.png)
![2021-11-05 (7)](https://user-images.githubusercontent.com/846592/140591803-a3bfc824-221b-410a-8ea2-77e4d294ee2d.png)

## System Information
- OS: Windows 10 21H1 all updates applied
- Browser: Firefox 94.0.1(x64)
- Dark Reader Version: 4.9.41 and 4.9.40 according to the Firefox extensions settings page.

## Additional Context
Manually reverting to 4.9.39 fixes everything for me.
Disabling all other extensions have no impact.
Tested on two different systems(a desktop and a notebook), the profiles are synced using Firefox sync.
Doesn't happen on a clean profile.
One of the systems has https://github.com/black7375/Firefox-UI-Fix the other does not.

**Comment by marlop352** [comment] 2021-11-06 00:55
I can provide any log needed and do debugging of the extension if given instructions.

**Comment by marlop352** [comment] 2021-11-06 01:21
(4.9.40 on Chrome/Vivaldi/Brave works fine)

**Comment by marlop352** [comment] 2021-11-06 01:37
Firefox 94.0 on a x64 Linux system on a profile that was/is also synced with the same Firefox account has the same issue.

**Comment by xcasxcursex** [comment] 2021-11-06 05:20
Nightly 96 on Win 10 same here. I've seen it on a few sites and visiting arstechnica just now made me go look and see what broke.

**Comment by cipitaua** [comment] 2021-11-06 07:14
duplicate of  #7266

**Comment by marlop352** [comment] 2021-11-06 07:27
> 
> 
> duplicate of #7266

I don't have the site freeze and high CPU usage symptoms that are mentioned on that issue, the memory ballooning one also seems to not happen to me.

**Comment by Gusted** [comment] 2021-11-06 08:13
Hi @marlop352!

That's a pretty weird issue, it seems like one of our fallback theme is still being applied(looking at the screenshots). However I'm not able to reproduce them on the mentioned sites. Could you try to re-install dark reader, reset the settings(you can back-up them first) and see if that works.

Regards,
Gusted

**Comment by marlop352** [comment] 2021-11-06 13:05
@Gusted I exported the settings(using 4.9.39 as .40 and .41 won't load the extension's UI), reset them and did a re-install, that fixed it but it won't import the settings back so any pointers on what to do to try and fix whatever is wrong with the settings exported so that they can be imported again?

**Comment by marlop352** [comment] 2021-11-06 13:21
Just tried creating a export with a single setting changed(marking it to not run on github.com) on 4.9.41 resetting the settings and then importing it back and it didn't work the structure of the old and new exported settings booth look like valid JSON to me (other then the old one had a null in it)

**Comment by re64trh5hheterrethg** [comment] 2021-11-06 14:54
Same issue ion Firefox 94.0 and Darkreader 4.9.41. Deleting and reinstalling resulted in same result.

**Comment by Gusted** [comment] 2021-11-06 14:59
> reset them and did a re-install, that fixed it but it won't import the settings back so any pointers on what to do to try and fix whatever is wrong with the settings exported so that they can be imported again?

Ah I forget, #3927

**Comment by alexanderby** [comment] 2021-11-06 16:20
Could anyone open `about:debugging#/runtime/this-firefox` and in Dark Reader section click `Inspect`? Do you see any errors?

**Comment by codecat** [comment] 2021-11-06 17:32
Not sure if it's the same issue, but I am seeing this when opening https://openplanet.nl/ which freezes the tab entirely when Dark Reader is enabled:

![image](https://user-images.githubusercontent.com/136534/140618584-e5f74f1e-5294-4507-95c2-476d07aa1895.png)

**Comment by Gusted** [comment] 2021-11-06 17:35
> Not sure if it's the same issue, but I am seeing this when opening https://openplanet.nl/ which freezes the tab entirely when Dark Reader is enabled:
> 
> ![image](https://user-images.githubusercontent.com/136534/140618584-e5f74f1e-5294-4507-95c2-476d07aa1895.png)
> 

#7266

**Comment by marlop352** [comment] 2021-11-06 18:39
on the computer that I didn't fix by resetting the config of the extension: ![Sem título](https://user-images.githubusercontent.com/846592/140620099-2594d48f-75b6-4545-8aaa-26be94c55088.png)
error on extension startup, the settings seem to have "null" set as the value of the "changeBrowserTheme" option ( "changeBrowserTheme": null, )


on the computer that I did fix by resetting the extension settings:
![2021-11-06 (1)](https://user-images.githubusercontent.com/846592/140620191-01f87f2a-34e8-4297-8f90-dbee8972bbd6.png)
error only when trying to import a config, the null on the export was fixed manually before trying to import it

**Comment by antishok** [comment] 2021-11-06 20:22
I had the same exact issue, and indeed forcing the `changeBrowserTheme` setting in storage to be false instead of null fixes the issue

**Comment by Gusted** [comment] 2021-11-06 20:57
> error on extension startup, the settings seem to have "null" set as the value of the "changeBrowserTheme" option ( "changeBrowserTheme": null, )
> 
> on the computer that I did fix by resetting the extension settings:

That's is very valuable information. The fix is luckily simple: #7283

@alexanderby I think we can go for a hotfix after that PR is merged as we have another regression from #7266 which are both pretty nasty bugs and impact the extension a lot.

**Closed** 2021-11-06 20:59 UTC
Labels: bug

**Comment by alexanderby** [comment] 2021-11-06 21:00
@Gusted You are a super hero 🦸

How could the null appear here? Let me check what it's all about and test so that we would not introduce another bug.

**Comment by marlop352** [comment] 2021-11-06 21:02
@Gusted @alexanderby I'm not sure I understood that commit correctly, but shouldn't the key be set to the default value if a null is detected instead of ignoring it?

**Comment by Gusted** [comment] 2021-11-06 21:08
> I'm not sure I understood that commit correctly, but shouldn't the key be set to the default value if a null is detected instead of ignoring it?

I don't think the key should be set to default, well none of the values should be null. By simply going to set it back to default value, we will be ignoring a bug whereby a value can become null. Also it could be a legitimate value.

To fix the issue of not loading websites and UI, ignoring it for now is the simplest option. As finding out why it was `null` in the first place can take weeks if not months given experience.

**Comment by alexanderby** [comment] 2021-11-06 21:09
Should it be `defaults` instead of `null` [here](https://github.com/darkreader/darkreader/blob/a529519cb2064242ea332d8fd0aaea52a257b632/src/background/utils/extension-api.ts#L45)?

**Comment by Gusted** [comment] 2021-11-06 21:14
> Should it be `defaults` instead of `null` [here](https://github.com/darkreader/darkreader/blob/a529519cb2064242ea332d8fd0aaea52a257b632/src/background/utils/extension-api.ts#L45)?

Oh yeah, that's a interesting one which is to avoid multiple look-ups, see: https://github.com/darkreader/darkreader/pull/7091#discussion_r730019913

But it shouldn't impact anything, as writing to the storage should have something like `{...defaultValues, ...modifiedSettings}`(In terms of javascript). So the `null` was somehow in the `modifiedSettings` bit then, as the defaultValue of `changeBrowserTheme` is `false`.

**Comment by marlop352** [comment] 2021-11-06 21:14
> 
> 
> > I'm not sure I understood that commit correctly, but shouldn't the key be set to the default value if a null is detected instead of ignoring it?
> 
> I don't think the key should be set to default, well none of the values should be null. By simply going to set it back to default value, we will be ignoring a bug whereby a value can become null. Also it could be a legitimate value.
> 
> To fix the issue of not loading websites and UI, ignoring it for now is the simplest option. As finding out why it was `null` in the first place can take weeks if not months given experience.

understood, thanks for the explanation and the fix!

**Comment by alexanderby** [comment] 2021-11-06 21:31
@Gusted Do you understand [this](https://github.com/darkreader/darkreader/blame/a529519cb2064242ea332d8fd0aaea52a257b632/src/background/utils/extension-api.ts#L113) part? It assigns an object but then rewrites it with `undefined`.

**Comment by alexanderby** [comment] 2021-11-06 21:35
Well, it's late night in Netherlands and Ukraine, let's have a look at it with a clear mind.

**Comment by Gusted** [comment] 2021-11-06 21:38
> `chrome.storage.sync.QUOTA_BYTES_PER_ITEM` is `undefined` in Firefox.

Firefox will then not have that functionality, as `anyDigit > undefined` is always false.



> Do you understand [this](https://github.com/darkreader/darkreader/blame/a529519cb2064242ea332d8fd0aaea52a257b632/src/background/utils/extension-api.ts#L113) part? It assigns an object but then rewrites it with `undefined`.

Yes, this is to migate large values when writing to sync storage, the sync storage on chromium only allow a max amount of bytes per item(hence the constant `QUOTA_BYTES_PER_ITEM`), we had a issue that when the `siteList` becomes too large, it will not write anymore to sync server, so to migate that issue, when such value becomes too big. It will be stringified(`JSON.stringify(...)`) and then that string is split into multiple keys to avoid 1 key having a too large amount of value.



> Well, it's late night in Netherlands and Ukraine, let's have a look at it with a clear mind.

👍🏽

**Comment by alexanderby** [comment] 2021-11-06 21:43
> then that string is split into multiple keys to avoid 1 key having a too large amount of value

That's great idea, but the final value written is `undefined` as far as it overwrites `{__meta_split_count: minimalKeysNeeded}`

**Comment by alexanderby** [comment] 2021-11-06 21:44
I can try luck and push an update now :) Anyway the previous one didn't arrive on Chrome.
