### ISSUE TITLE
[Feature Request] detecting and automatic switching to site vendor dark mode

### ISSUE THREAD

**Issue by selfisekai** [darkreader/darkreader#2449] opened 2020-05-06 09:31 UTC
**Is your feature request related to a problem? Please describe.**
some websites provide dark mode for its users but it needs to be enabled by user. I think that darkreader could have some set of rules or JS functions for that.

**Describe the solution you'd like**
I'll take [anilist.co](https://anilist.co) as an example. 
1. darkreader has a predefined rule to check if the website uses dark mode currently (`body.site-theme-dark`).
2. if it exists, don't load standard darkreader
3. if there is no such element, check for `.theme-selector .dark`, the dark mode switch element.
4. if it exists, click on it and disable standard darkreader.
5. if it does not exist, then usual darkreader rules are enabled.

also there should be some generic rules, like for mastodon [dark mode enabled on the most of instances by default (try: [https://mastodon.social/@Gargron](https://mastodon.social/@Gargron) ), but some instances switch it like on [https://framapiaf.org/@Framasoft](https://framapiaf.org/@Framasoft) ] or nextcloud.

**Additional context**

**Comment by Gusted** [comment] 2020-05-06 10:35
Good suggestion but some problems with it...

1. Not every user would like to swtich to vendor's dark mode as it too material or etc.
2. We should make this for every site another rules as take for example reddit.com it doesn't say anywhere it's dark in the DOM structure.

**Comment by HiKE-yt** [comment] 2022-05-15 14:52
Upvote ! I am waiting for this. 
I found that Google have a JS action, when you go to the home page ( [google.com](https://google.com/) ) then settings, you have a "Dark Mode" button, which have a JSaction : `jsaction="ok5gFc;x6BCfb:ggFCce;w3Ukrf:aelxJb"`. This is, yes, site-specific, but this could be added as Google have a good dark theme. 
Another thing is that if someone doesn't like vendor dark theme, a button to  switch the vendor's dark mode off (if supported) and Dark Reader on can be added to the panel's UI.

Also, devs can just add the recognition system and all the data needed can be provided by the community, so the devs can be less than 2yrs late for Dark Reader 5.

Another bunch of ideas, if it helps...

Great work guys ! ❤️

**Comment by Gusted** [comment] 2022-05-21 13:12
> This is, yes, site-specific, but this could be added as Google have a good dark theme.

Where do we draw the line of that? I can make a new site which a simply perfect black theme and also say "good dark theme".



> Also, devs can just add the recognition system and all the data needed can be provided by the community, so the devs can be less than 2yrs late for Dark Reader 5.

Yes, data provided by the community is a no-go especially javascript. Btw we never set a deadline for Dark Reader 5, it's evolving upgrade.

**Comment by yazan1107** [comment] 2022-07-19 18:41
yes for example reddit.com is pain in the ass to switch to dark mode when dark reader dynamic is working(the button for dark mode there does not show correctly) also lots of other websites. It should prefer vendor's dark mode instead of dark reader dark mode.

**Comment by EtzBetz** [comment] 2022-12-21 21:02
there really just should be an easy way for a developer to say "Yeah I'm supporting dark-theme myself", the simplest methods would be defining a header meta value i guess. i would also like the thing of detecting the usage of the prefers-color-scheme and then just switching dark reader off.

these two settings should just be possible to disable and we are done probably. we won't catch every sheep in this story.

**Comment by KaKi87** [comment] 2022-12-22 11:16
Duplicate of #1837

**Comment by alexanderby** [comment] 2024-04-02 13:23
Duplicate of https://github.com/darkreader/darkreader/issues/1327

**Closed by alexanderby** 2024-04-02 13:23 UTC
Labels: enhancement
