### ISSUE TITLE
[Bug] Wrong settings active on proxy site

### ISSUE THREAD

**Issue by neon-dev** [darkreader/darkreader#8856] opened 2022-05-10 00:08 UTC
# Bug Report

## Website Address
https://htmlpreview.github.io/?https://github.com/github/welcome-to-github/blob/master/index.html

## Bug Description
When visiting above website, the settings for github,com are used instead of the ones for github,io.

## Steps To Reproduce
- Disable dark mode for github.com
- Go to https://htmlpreview.github.io/?https://github.com/github/welcome-to-github/blob/master/index.html

## Expected Behavior
Dark mode on github.io should be active

## Actual Behavior
github.io will not use dark mode and you cannot activate it. The button shows ![grafik](https://user-images.githubusercontent.com/1169307/167517231-4c6fb308-cbac-41a5-b4f3-d1c452466f16.png) and does not change when you click on it.

## System Information
- Browser: Firefox 100,0
- Dark Reader Version: 4.9.50

## Additional Context
If it's just due to a URL regex pattern, here's one that should work: `/^(?:https?:\/\/)?([^\/]+)/` (group 1 will contain the host name or ip including the port, if present).

**Comment by Gusted** [comment] 2022-05-10 10:46
Duplicate of https://github.com/darkreader/darkreader/issues/4675

**Closed by Gusted** 2022-05-10 10:46 UTC
Labels: bug
